### ISSUE TITLE
ccp4: wrong rep when moving mouse

### ISSUE THREAD

**Issue by hainm** [arose/ngl#105]
![ccp4](https://cloud.githubusercontent.com/assets/4451957/15005201/37353d0a-118f-11e6-85a8-4ffd423ef3b6.png)

**Comment by arose** [comment]
what is wrong about it?

**Comment by hainm** [comment]
:D is the map supposed to be location-fix.

![ccp4_1](https://cloud.githubusercontent.com/assets/4451957/15005264/55c84bda-1190-11e6-907f-8ea8ffdf4bbf.png)

**Comment by arose** [comment]
It is supposed to move :-) There is a parameter `boxSize`. If you set that to 0, the whole map will be shown. However this can be too slow or leave the display too full to see anything.

**Comment by hainm** [comment]
oh I see. thx.
