### ISSUE TITLE
problems with mdsrv.dev.html and loading of xtc files

### ISSUE THREAD

**Issue by j0kaso** [arose/ngl#106]
since the last 2-3(?) commits, I have now problems to use the mdsrv.dev.html. I fixed it by copying the script part from the ngl.dev.html.

but I still have problems to import .xtc trajectories. the error I receive:

>  trajectory.js:721 Uncaught TypeError: Expecting a function in instanceof check, but got undefined

also the gro_trajectory example (executed on the github.io) gives an error:

> ngl.full.min.js:1929 Uncaught TypeError: a.eachSelectedAtom is not a function

**Comment by arose** [comment]
I will fix that for now, but in the long run I will remove mdsrv.dev.html and just have it in the mdsrv repository.

**Comment by arose** [comment]
> also the gro_trajectory example (executed on the github.io) gives an error:

that was fixed in 7151fa62bc350afbf0043d861df8ac6b70551690

**Comment by arose** [comment]
> I will fix that for now, but in the long run I will remove mdsrv.dev.html and just have it in the mdsrv repository.

The idea being that you take a release from NGL to use with MDsrv instead of trying to keep up with the development versions of NGL. There also will be more frequent releases of NGL.

**Comment by j0kaso** [comment]
jupp, this makes way more sense. I will simply go back to the latest released version. I agree, that mdsrv.dev.html is also not needed. Thanks :-)

**Comment by arose** [comment]
went ahead and removed it (576bc1a2e4176bbc841173161e617e6fcc2c1b94) and added an issue to [mdsrv](https://github.com/arose/mdsrv/issues/4)
