### ISSUE TITLE
wrong licorice rep

### ISSUE THREAD

**Issue by hainm** [arose/ngl#114]
NGLView shows wrong licorice repr after merging NGL 0.7

![wrong_repr](https://cloud.githubusercontent.com/assets/4451957/15121013/5f1cec7c-15e6-11e6-8f74-879af875aca7.png)

**Comment by arose** [comment]
That are a lot of bonds :-) Can you attach the offending structure as a pdb?

**Comment by hainm** [comment]
please check here. https://github.com/hainm/amber_things/tree/master/things/nglview/wrong_repr

**Comment by arose** [comment]
fixed in NGL a0bfa16c4470020a8cd5209f1b9f76c8c1e6a08. The terminal ALH residue was wrongly determined as a coarse grained residue which allowed longer bond distances.

![screenshot 7](https://cloud.githubusercontent.com/assets/272250/15122576/ab392c04-15d4-11e6-815a-604ee835e924.png)

**Comment by hainm** [comment]
:D update to NGLView please.

**Comment by arose** [comment]
I will make a NGL patch release in a couple of days, after that NGLView can be updated

**Comment by hainm** [comment]
so after that, we can release NGLView too.
