### ISSUE TITLE
Set Z-offset for TextBuffer

### ISSUE THREAD

**Issue by sbliven** [arose/ngl#116]
It would be nice to be able to offset a TextBuffer towards the camera. I would like to label some SphereBuffers while making sure that the label always falls in front of the labelled object.

**Comment by arose** [comment]
Added parameters `xOffset`, `yOffset`, `zOffset` for `LabelRepresentation` and `TextBuffer`, see b71040a46bca386e7bf3c0ea14522f1a4649a522. They move the label in screen space.

![screenshot 72](https://cloud.githubusercontent.com/assets/272250/15265407/d774c6fa-1937-11e6-9db3-fd9e6142f68a.png)

**Comment by yqshao** [comment]
It seems that label offsets behave differently in perspective and orthorgonal cameras.
In perspective camera, it moves the labels with respect to camera, 
but in orthorgonal camera, it moves the labels in the real space. (tested in the webapp)

**Comment by arose** [comment]
@yqshao can you try again with the ts2 branch, was fixed in 7a7d030d1512ae9a29032c7b5cec8034f9dd0be0
