### ISSUE TITLE
Remove Hyperball representation?

### ISSUE THREAD

**Issue by arose** [arose/ngl#118]
- not used much (looks fancy but unsure if really useful)
- maintenance overhead

**Comment by harryjubb** [comment]
I've been using it and like it! As you say, because it looks fancy, whether it adds anything other than prettiness is debatable.

Does it result in a large maintenance overhead for you?

**Comment by hainm** [comment]
> prettiness

is a good thing to keep.

But nor sure if it is really fancy. 

![screenshot](https://cloud.githubusercontent.com/assets/4451957/15233077/915a4010-1873-11e6-96e5-2e1408347c9e.png)

**Comment by hainm** [comment]
but if hyper balls make thing harder for you to update in `Orthographic camera`, +1 for stop supporting it.

**Comment by arose** [comment]
> Does it result in a large maintenance overhead for you?

It is a large and complex glsl shader which I have to adjust whenever I add new shader code.

**Comment by arose** [comment]
the hyperball shader seems to be ok with the orthographic camera, however I haven't tested it on many machines.

![screenshot 73](https://cloud.githubusercontent.com/assets/272250/15265754/32bbee26-1942-11e6-8fce-fa6a45f0f5ba.png)

**Comment by arose** [comment]
I will leave the hyperball representation in for now. Thanks for your comments.
