### ISSUE TITLE
unitcell: too thick

### ISSUE THREAD

**Issue by hainm** [arose/ngl#121]
![screenshot 21](https://cloud.githubusercontent.com/assets/4451957/15265454/ea7b2568-1951-11e6-8923-8cae72b2d74c.png)

And the default color seems does not match well to the protein color.

**Comment by arose** [comment]
There is a `radius` and a `color` parameter to change it. The defaults are meant to make the unitcell be clearly visible also in larger assemblies.

**Comment by hainm** [comment]
I see. Can NGL dynamically adjust based on system size?

**Comment by arose** [comment]
> Can NGL dynamically adjust based on system size?

In principle yes, but I think finetuning default parameters should be done on the application level to its needs and likings.

**Comment by hainm** [comment]
Agree. Close now. Thx.
