### ISSUE TITLE
orthographic camera bug

### ISSUE THREAD

**Issue by hainm** [arose/ngl#129]
this happens in NGLView.

The molecule suddenly jump from center to the top left of the screen.

**Comment by arose** [comment]
haven't seen this myself, any suggestion on how to reproduce it?

**Comment by hainm** [comment]
Please check this notebook: https://github.com/arose/nglview/blob/master/nglview/tests/notebooks/test_orthographic_camera_jump.ipynb

**Comment by hainm** [comment]
tested on google chrome (0.0.2661.102 (64-bit)) on mac.

**Comment by arose** [comment]
Just tried, but could not reproduce it. Do you get any error message?

**Comment by hainm** [comment]
did you try with google-chrome and osx? 

>  Do you get any error message?

I will report later, don't have mac here.

**Comment by hainm** [comment]
> Do you get any error message?

I don't get any. This is my screen

<img width="586" alt="screen shot 2016-06-04 at 12 33 47 am" src="https://cloud.githubusercontent.com/assets/4451957/15797599/2ac283f0-29ec-11e6-960f-4b60ae3840cc.png">


And this is the jumping


![test](https://cloud.githubusercontent.com/assets/4451957/15797604/7aa326d6-29ec-11e6-8444-305b6211557f.gif)

**Comment by arose** [comment]
@hainm do you still observe this?

**Comment by hainm** [comment]
nope. thanks. Do  you know why?

**Comment by arose** [comment]
nope
