### ISSUE TITLE
Not being able to load local PDB

### ISSUE THREAD

**Issue by j3mdamas** [arose/ngl#130]
Hi,

I started using NGL not too long ago and I have a basic question, which I'm almost sure it isn't a bug but something that I am doing wrong. I am using https://arose.github.io/ngl/doc/#User_manual/Usage/Embedding. As you can see on the website, the embedding is not working there. I can make it work by using http://files.rcsb.org/download/1CRN.pdb.gz or http://files.rcsb.org/download/1CRN.pdb.

But what I really wanted to do was to load a local PDB file. The following does not work:

``` html
<script src="ngl.embedded.min.js"></script>

<script>

  NGL.mainScriptFilePath = "./ngl.embedded.min.js";

  document.addEventListener( "DOMContentLoaded", function() {
  var stage = new NGL.Stage( "viewport" );
  stage.setTheme( "dark" );
  stage.viewer.setBackground( 0x272822 );
  stage.loadFile( "./pdb/1CRN.pdb" ).then(function (o){o.addRepresentation( "cartoon", { sele: "polymer", color: "sstruc"} ); o.add\
Representation( "ball+stick", { sele: "hetero OR mol"} ); o.centerView()});
                  } );

</script>
<div style="margin-left:30px">
<div id="viewport" style="overflow:auto; width:auto; height:350px;"></div>
</div>
```

Yes, the `./pdb/1CRN.pdb` exists.

Thanks,
João

**Comment by j3mdamas** [comment]
An update: It works on Firefox but not on Chrome (version 49.0.2623.110). Still have to figure out why the local PDB does not load on Chrome.

The https://arose.github.io/ngl/doc/#User_manual/Usage/Embedding does not work on either.

**Comment by j3mdamas** [comment]
From inspect:
>XMLHttpRequest cannot load <file>. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

Apparently it's because I am opening directly my html and not serving it through http:

I get it now, sorry for disturbing.

Anyway, https://arose.github.io/ngl/doc/#User_manual/Usage/Embedding is not working :)

**Comment by cuzzo87** [comment]
I'm having the same issue. I would like to create a html page that should be opened only locally. I am experiencing the same issue of j3mdamas with chrome. 
Is there any solution for this issue?

**Comment by j3mdamas** [comment]
@cuzzo87 is trying to visualize an HTML locally, instead of serving it through HTTP(S), the same problem I could not solve, but it was fine for me because I could serve it.

**Comment by ppillot** [comment]
You can achieve this by copying the content of your PDB file in your HTML code and load the model from this text.
Otherwise you'll run in CORS issues if you try to load a separate PDB file from a local HTML file

**Comment by j3mdamas** [comment]
@ppillot thanks! do you have an example of your suggestion?

**Comment by arose** [comment]
something like this:

```
<html>
<script>
var stringContainingTheWholePdbFile = "...";
var stringBlob = new Blob( [ stringContainingTheWholePdbFile ], { type: 'text/plain'} );
stage.loadFile( stringBlob, { ext: "pdb" } );
</script>
</html>
```

**Comment by ppillot** [comment]
I made a pen https://codepen.io/ppillot/pen/aLepyj?editors=0010#

**Comment by cuzzo87** [comment]
Thank you for the help @arose  and @ppillot . I tried the solution proposed and it worked.
