### ISSUE TITLE
atom selection: noh

### ISSUE THREAD

**Issue by hainm** [arose/ngl#131]
`noh` as an alias of `not hydrogen`? (VMD-like)

**Comment by arose** [comment]
the shortest version currently is `not #h`, but `noh` better

**Comment by arose** [comment]
hmm, not sure, it is also a PDB ligand name: http://www.rcsb.org/pdb/ligand/ligandsummary.do?hetId=NOH

**Comment by hainm** [comment]
it is "NOH", not 'noh'. ha ha.

**Comment by arose** [comment]
closing this as `noh` too easily conflicts with residue names
