### ISSUE TITLE
Carbon-coloring scheme

### ISSUE THREAD

**Issue by fredludlow** [arose/ngl#132]
How would I go about coloring structures by element, but with a different (and changeable) color for carbons in each structure?

If this is a generally useful feature (rather than just for me) I guess a "carbon" color scheme would be handy? (If it's not generally useful then I guess I can hack something in my interface).

Fred

**Comment by fredludlow** [comment]
Oh, just realised this is how the element colour scheme works...
```
representation.setParameters({colorScheme: "element", colorValue: "cyan"});
```

**Comment by arose** [comment]
:-)
