### ISSUE TITLE
Non-standard PDB CONECT records

### ISSUE THREAD

**Issue by fredludlow** [arose/ngl#133]
Hi again! There are various bits of software which record bond orders in PDB format by specifying the same bond multiple times, e.g. 

CONECT 1 2 2 (for a double bond between atom 1 and 2) 

This is definitely not part of the formal PDB spec, but it seems to be a widely used interpretation of it. Would it be possible to allow/detect this? (maybe turned off by default if this sounds like a dirty hack!)

**Comment by arose** [comment]
I can have a look at it. Do you have an example file for this? Currently specifying the same bond multiple times will create the same bond multiple times.

**Comment by josemduarte** [comment]
The [format specification for CONECT records](http://www.wwpdb.org/documentation/file-format-content/format33/sect10.html#CONECT) says that the 2nd, 3rd, 4th and 5th positions are used for atoms connecting to the atom in 1st position (and in fact that is used often in deposited PDB files). How would the parser be able to distinguish the standard files from those using the 3rd position for double bonds?

In general I'm not in favor of accommodating non-standard PDB file formatting. There's too many ways that people have altered the format to their convenience without following the standard. A parser can't possibly do all the different deviations from the standard correctly.

**Comment by arose** [comment]
as far as I know it is used like this:

CONECT 1 2 2 => double bond between 1 and 2
CONECT 1 2 2 2 => triple bond between 1 and 2
CONECT 1 2 6 6 => single bond between 1 and 2, double bond between 1 and 6

**Comment by fredludlow** [comment]
So in answer to the first question, the examples I have look something like this:

```
CONECT    1    2    2    3
```
for 1 double bonded to 2 and single bonded to 3
(I'm away for the weekend now but can get some actual files to you next week).

If you've got something like a sulfoxide that needs more positions they just get continued:
on another line as the standard says for atoms with higher valence. 
```
CONECT    1    2    2    3    3
CONECT    1    4    5
```
Handling this case wouldn't break files that follow the standard exactly (though might cause some other problem in those that deviate in a different way) 

RDKit explicitly handles this: http://www.rdkit.org/Python_Docs/rdkit.Chem.rdmolfiles-module.html#MolToPDBBlock

I'm fairly sure Pymol, Jmol and AstexViewer also support this way of specifying the bond orders, so it's definitely not unprecedented. 

I'd generally be in favour of telling everyone to just get with the standard (especially as I think the  author is now employed by RCSB!) but this is a well known deviation from the standard, and the only practical way of getting the bond orders right in PDB files that I know of - the other option is to interpret the bond lengths in the viewer and deduce bonding, but we spend quite a lot of time (QM calculations etc) to get tautomers and any other ambiguities right so it seems a bit silly to throw away that work and guess them again based on geometry. 

Another option is to use another file format, but certain bits of X-ray software won't support that, or you lose the residue numbering, reset serial numbers or bump into some other source of pain.

**Comment by fredludlow** [comment]
I've attached an example (the ligand from pdb entry 1ajx with double bonds specified). It's attached as a .pdb.txt file as github only likes certain file extensions. 

[1ajx_ligand.pdb.txt](https://github.com/arose/ngl/files/292901/1ajx_ligand.pdb.txt).

**Comment by arose** [comment]
I'll have a look.

I was wondering what you are expecting. Currently NGL can only display single bonds, though the bond order data is parsed and available.

**Comment by fredludlow** [comment]
Ah, I hadn't realised that, sorry! Could I add depiction of double/triple bonds as a feature request then ;)

**Comment by arose** [comment]
> Could I add depiction of double/triple bonds as a feature request then ;)

sure ;-)

**Comment by arose** [comment]
done 66982695219a3b2056878c223beaae1932f27551
