### ISSUE TITLE
Add resname, resid, chain, ..  keywords?

### ISSUE THREAD

**Issue by hainm** [arose/ngl#139]
I found them easier to remember. For example, i always to check if 'CA' or '.CA' is correct. How is about adding 'atom name CA' , 'resname ASP', 'chain B'....

**Comment by hainm** [comment]
To elaborate:

'1-12'

I always need to check manual

How is about

'atom 1-12'

'residue 1-12'

**Comment by arose** [comment]
The selection language is modeled after Jmol's. I was thinking about implementing the VMD language. Generally I want to get together with other viewer developers to create a common "core" selection language.

Presently I don't want to put effort into extending the selection language. Also, parsing the language should be done with http://pegjs.org/.
