### ISSUE TITLE
Put labels at the center of residues (or chains, models, structures)

### ISSUE THREAD

**Issue by arose** [arose/ngl#141]
for TextBuffer & LabelRepresentation

**Comment by harryjubb** [comment]
How about for whole selections?

(Not trying to make your life harder; honestly! 😛 )

**Comment by arose** [comment]
I am thinking of a parameter `labelType` (open to a better name)
- "perAtom" (current behavior)
- "perGroup"
- "perChain"
- "perModel"
- "perStructure" (seems unnecessary)
- "perSelection"

**Comment by arose** [comment]
added labelGrouping param to LabelRepresentation, see c3d7de89358d2104d08c4ed9041e9003227da582

'atom' has the same behavior than before

'residue' will create a single label per residue in the selection, positioned at the center of the residue

![screenshot 71](https://user-images.githubusercontent.com/272250/34855825-a980a4a0-f6f6-11e7-9db1-754961e81823.png)

If someone wants labels at the chain or model level please do a PR.
