### ISSUE TITLE
Problems with sidechain/backbone selection keywords

### ISSUE THREAD

**Issue by sbliven** [arose/ngl#145]
1. The `sidechain`selection should include CA atoms. You pretty much always want sidechains to connect with the backbone visually. In the rare cases where you don't want CA, one can always use `not backbone`.

2. Terminal carboxyl ('OXT') atoms should be included as backbone rather than sidechain.

**Comment by sbliven** [comment]
I checked PyMOL's behavior on this and found it inconsistent. The command `select sidechain` does not include CA atoms. However, showing a representation for sidechains using the GUI menus does apply to CA atoms. I'd still argue that including CA is more natural.

**Comment by hainm** [comment]
How is about

sidechain and CA

considering it (CA) as part of sidechain is not natural to me.

**Comment by josemduarte** [comment]
I agree with @hainm , to me sidechain should be strict about selecting side chain atoms only. If one wants to have the CA as well, then it should be done with an explicit command. Another solution is to have a new keyword that does sidechain+CA

**Comment by arose** [comment]
there is `sidechainAttached` which is the same as `not backbone or .CA or (PRO and .N)`

**Comment by arose** [comment]
> Terminal carboxyl ('OXT') atoms should be included as backbone rather than sidechain.

Added to list of protein backbone atomnames 2bb948ebe16f5a0d88832b985663c8eb60b4b9d2

**Comment by arose** [comment]
> there is sidechainAttached which is the same as not backbone or .CA or (PRO and .N)

I am open to suggestions for a more succinct - but still telling - name

**Comment by arose** [comment]
> I checked PyMOL's behavior on this and found it inconsistent. The command select sidechain does not include CA atoms. However, showing a representation for sidechains using the GUI menus does apply to CA atoms. I'd still argue that including CA is more natural.

I vaguely remember a setting called "sidechain helper" that needs to be enabled
