### ISSUE TITLE
Line representation quirks

### ISSUE THREAD

**Issue by fredludlow** [arose/ngl#147]
Is there a way to set the width of the lines for line representation? (There's a parameter called linewidth, but it doesn't seem to do much, or I'm providing values out of range or something). 

Currently I get quite a noticeable change in appearance a small time after I stop rotating the structure - I guess this is anti-aliasing kicking in after a delay? If I set sampleLevel (stage parameters) to -1 or >2 the effect disappears. 

If I use licorice with very narrow cylinders (0.02) then I get the same thing, but much less so once radius gets above 0.05) so I was thinking if I could have thicker lines the difference would be less noticeable... Or the licorice radius being dynamically set according to current zoom level (probably a nonstarter performance-wise and actually not quite what I'd want anyway as the great thing about line representation is that it looks "flat" - which is handy when you've got 40 overlaid protein structures).

**Comment by fredludlow** [comment]
Oh, I see, [this](https://bugs.chromium.org/p/angleproject/issues/detail?id=334) [is](https://bugs.chromium.org/p/chromium/issues/detail?id=60124) [complicated](https://bugs.chromium.org/p/angleproject/issues/detail?id=119) :) 

Seems the fix is to [force chrome to use OpenGL](https://github.com/mrdoob/three.js/wiki/How-to-use-OpenGL-or-ANGLE-rendering-on-Windows) mode, but alas no IE workaround.

Will stick to sampleLevel -1 for now...

**Comment by arose** [comment]
Yeah, it's an ANGLE issue, only lines of one pixel. At one point I had LineSprite and PointSprite Buffers, which were basically like Cylinder and Sphere, but unshaded (though with perspective "distortion"). SOmething similar could be added again.

**Comment by fredludlow** [comment]
It would be nice but low priority (can just use "slim licorice" for now). On a traditional projector that's not perfectly setup 1-pixel lines can be hard to see.
