### ISSUE TITLE
structure is too dark if zooming in

### ISSUE THREAD

**Issue by hainm** [arose/ngl#154]
Do you know how to make the structure brighter? 

![screenshot 6](https://cloud.githubusercontent.com/assets/4451957/16500623/7a30162c-3ed3-11e6-9d42-e0a78ea9f1ea.png)

**Comment by arose** [comment]
which build are you using?

**Comment by hainm** [comment]
the one in current nglview.

**Comment by arose** [comment]
can you make the structure available?

**Comment by arose** [comment]
Thanks, I looked at it and the effect is much less apparent in the development version. It has to do with how I handle lights, camera and (mouse) controls which I started to refactor. There should be no effect at all.

**Comment by arose** [comment]
fixed, see 6323762d4d4dd9f7f71c040a2b5d58fd2aba3e65
