### ISSUE TITLE
Built-in support for highlighting atoms/representations

### ISSUE THREAD

**Issue by arose** [arose/ngl#158]
For example for helping with measurements #46.

There are two approaches:
1. A single, fixed (though user-defined) atom-based representation for highlighting
2. A highlight version of each representation (buffer)

**Comment by arose** [comment]
Allow a custom mesh for highlighting of atoms (residues, chains, models), see #161.

**Comment by harryjubb** [comment]
Did this ever progress in the end? #381 suggests larger/transluscent ball+stick, but we've found that the blending isn't ideal (#592)

FYI @jamesfoley

**Comment by arose** [comment]
No progress on it. Thinking of it now. I say it is easy enough to do yourself. In Mol* (molstar.org) it is part of the library.
