### ISSUE TITLE
Add lazy/deferred option to RepresentationComponent

### ISSUE THREAD

**Issue by arose** [arose/ngl#160]
create/update representation only when it is also visible

**Comment by fredludlow** [comment]
+1 This would remove a level of complexity from my UI code so I'm all for it :)

(I wrap representations with a lazy-loading wrapper, but would be simpler to just say `visible:false` or similar in the parameters).

**Comment by arose** [comment]
see 72c587359ba1c829cbdc13123eaeb6584300a963

```javascript
var repr = comp.addRepresentation( "cartoon", {  // cartoon geometry NOT created
    lazy: true, visible: false
} );
repr.setVisibility( true );  // cartoon geometry created
repr.setVisibility(false );
repr.setParameters( { scale: 3 } );  // cartoon geometry NOT updated
repr.setVisibility( true );  // cartoon geometry updated
```
