### ISSUE TITLE
Adding custom Three.js objects

### ISSUE THREAD

**Issue by harryjubb** [arose/ngl#161]
Hi,

Is it possible to add custom objects to the stage's `scene`?

I had a go (though I'm still using an older NGL version where the THREE object is global) and managed to add an object, using the coordinates of an atom, but it didn't appear; I assume because of a lighting or coordinates issue?

**Comment by arose** [comment]
> Is it possible to add custom objects to the stage's scene?

There is no api for it and I am reluctant to generally support it.

What are you trying to do? Would something like a a stage.addMeshComponent method help?

**Comment by harryjubb** [comment]
I'd like to add a custom object to highlight particular residues as being important, without interfering with representations of the structure, i.e., as an extra layer of annotation.

`stage.addMeshComponent` would be great :) but I wouldn't want to ask you too support something that would require a lot of maintenance. Would doing it directly via the stage's viewer's Three scene not be desirable? That's what I tried (and failed!) to do in the older NGL version.

Many thanks,

**Comment by arose** [comment]
The highlighting sounds like something as #158. Feel free to add what you need from a highlight method.

I have been "creative" with my use of the THREE.Scene object...

Supporting THREE.Object3D would be much more than allowing adding a mesh, so I would like limit it to meshes and hide the use of THREE behind an API.

**Comment by harryjubb** [comment]
To highlight residues or regions of interest at the moment I'm adding separate representations, prefixing them with `hl_` so I can turn them on and off. This would be to go beyond that and be able to have those highlights on while showing further annotations on top of what the highlight is showing.

Here's what I tried so far:

```typescript

// INSTANTIATE A LOADER
var loader = new THREE.JSONLoader();

// LOAD A RESOURCE
loader.load(
	// RESOURCE URL
	'assets/3d/star.js',
	// FUNCTION WHEN RESOURCE IS LOADED
	function ( geometry, materials ) {
		var material = new THREE.MultiMaterial( materials );
		var star = new THREE.Mesh( geometry, material );

		// NO IDEA IF THIS HELPS ^_^
		star.scale.set(1.5, 1.5, 1.5);

		// KNOWN ATOM POSITION
		star.position.set(36.9, -43.9, 60.6);

		stage.viewer.scene.add( star );
		stage.viewer.requestRender();
	}
);

```

> I have been "creative" with my use of the THREE.Scene object...

😄

**Comment by arose** [comment]
So, you would like to have a star geometry?

**Comment by harryjubb** [comment]
As an example, though it would be nice to customise. A star was requested by my supervisor!

**Comment by arose** [comment]
So, a custom mesh for highlighting of atoms (residues, chains, models).

**Comment by harryjubb** [comment]
That would be perfect, if possible.

**Comment by arose** [comment]
> That would be perfect, if possible.

Will try

**Comment by arose** [comment]
You can now add meshes as components using the new Shape class

```JavaScript
var shape = new NGL.Shape( "shape" );
shape.addMesh(
    [ 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1 ],  // a plane
    [ 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0 ]  // all green
);
var shapeComp = stage.addComponentFromObject( shape );
shapeComp.addRepresentation( "buffer" );
```

or add it to StructureComponent

```JavaScript
var shape = new NGL.Shape( "shape" );
shape.addMesh(
    [ 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1 ],  // a plane
    [ 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0 ]  // all green
);
structureComp.addBufferRepresentation( shape.getBufferList() );
```

**Comment by harryjubb** [comment]
Amazing! I will be away next week, but will test this as soon as possible. Really cool progress, as usual.

**Comment by arose** [comment]
Given that you can add arbitrary meshes with shape.addMesh I close this.
