### ISSUE TITLE
EM structures don't load from CIF

### ISSUE THREAD

**Issue by sbliven** [arose/ngl#162]
When loading a multi-model structure from CIF, only the first structure loads. Oddly, the number of models seems to be set correctly (e.g. selection "/1" contains atoms), but all models seem to have the same coordinates.

```{js}
		stage.loadFile( "1ssu.cif", { defaultRepresentation: false } ).then(function(o) {
			
			console.log("Loaded 1hiv.A");
            o.addRepresentation("cartoon", {});
			o.addRepresentation("ball+stick", {sele:"/2"});

		} ); //add event listener
```

**Comment by arose** [comment]
What version are you using? v0.7.1a seems ok http://arose.github.io/ngl/?load=rcsb://1ssu.cif

**Comment by sbliven** [comment]
I'm using 0.7.1a, but I'm loading BioJava's cif files. So probably it's a biojava bug.

**Comment by josemduarte** [comment]
It could well be a biojava bug, do you have an example file around?

**Comment by arose** [comment]
solved offline, a biojava bug, coordinates of all models are the same
