### ISSUE TITLE
can not make 'surface' with makeRepresentation

### ISSUE THREAD

**Issue by hainm** [arose/ngl#164]
I am able to make `cartoon`, ... with `makeRepresentation` but can not make it work with `surface`.

Got Uncaught TypeError: Cannot read property '__postId' of undefined`. This is typical error I met before but don't know how to fix in this case.

any idea how to fix? thanks.

**Comment by arose** [comment]
what version?

**Comment by hainm** [comment]
sorry, I forgot to mention I worked with the one in `nglview`.

(So if I make an issue here, it relates to `ngl` in `nglview`. Otherwise, I will specify version. :D )

**Comment by arose** [comment]
can you link your code?

**Comment by hainm** [comment]
https://github.com/arose/nglview/blob/master/nglview/js/widget_ngl.js#L367-L380

**Comment by arose** [comment]
Please try to set `params.useWorker = false`.

**Comment by hainm** [comment]
that works. thanks.
