### ISSUE TITLE
Problem with surfaces in IE11 (and webworkers)

### ISSUE THREAD

**Issue by fredludlow** [arose/ngl#167]
If I try to create a surface representation in IE using the current master nothing happens. Turning off webworkers (i.e. useWorker: false in the representation parameters) fixes it (though obviously blocks the UI while it calculates). 

The same code is working perfectly in Chrome. 

I can't figure out how to debug a web worker in IE so don't have any clue what the problem is...

**Comment by arose** [comment]
needed to call `revokeObjectURL` later, the worker code was basically empty... (e593d8ac3198a6e6edd8c500e96935de50affe14)

**Comment by fredludlow** [comment]
All working now, thanks!
