### ISSUE TITLE
how to port current ngl.js to nglview

### ISSUE THREAD

**Issue by hainm** [arose/ngl#168]
Probably I asked before. Ask again since there is only a single distribution `ngl.js` now (https://github.com/arose/ngl/tree/master/dist).

Can you show me **exactly** how to port current  `ngl.js`?

My aim is to try with `ipywidgets5` (again. It's really annoying that I can not make it work).

**Comment by hainm** [comment]
this is what I did 

- copy `ngl.js` from `dist/` folder to replace the one in `nglview`

- update `widget_ngl.js`. Below is a part of it

```javascript
require.config( {
    paths: {
        "NGL": "../nbextensions/nglview/ngl"
    },
    shim: {
        NGL: {
            exports: "NGL"
        }
    },
} );

define( [
    "nbextensions/widgets/widgets/js/widget",
    "nbextensions/widgets/widgets/js/manager",
    "jqueryui",
    "NGL"
], function(
    widget, manager, $,
    NGL
){

    var NGLView = widget.DOMWidgetView.extend( {...
```

**Comment by hainm** [comment]
this is a part of error message in JS console.

<img width="769" alt="screen shot 2016-07-16 at 1 52 24 am" src="https://cloud.githubusercontent.com/assets/4451957/16893048/0d74388e-4af8-11e6-9ab4-20e187a767a9.png">

**Comment by hainm** [comment]
`ngl.js` was copied from current dev branch.

**Comment by arose** [comment]
you shouldn't need `shim`

**Comment by hainm** [comment]
so this is the updated code

```javascript
define( [
    "nbextensions/widgets/widgets/js/widget",
    "nbextensions/widgets/widgets/js/manager",
    "jqueryui",
    "nbextensions/nglview/ngl"
], function(
    widget, manager, $,
    NGL
){...
```

But I still get this error
<img width="780" alt="screen shot 2016-07-16 at 12 13 26 pm" src="https://cloud.githubusercontent.com/assets/4451957/16895827/bba83922-4b4e-11e6-9691-402f7970c42b.png">

**Comment by hainm** [comment]
OMG, I did it. Just need to change 'onPicked' to 'clicked'.
