### ISSUE TITLE
superpose: ReferenceError: NGL is not defined

### ISSUE THREAD

**Issue by hainm** [arose/ngl#170]
(I am using code from ngl dev, just pulled)

```javascript
        superpose: function(cindex0, cindex1, params){
           // superpose two components with given params (not yet)
           var component0 = this.stage.compList[cindex0];
           var component1 = this.stage.compList[cindex1];
           //component0.superpose(component1);
           console.log(component0.superpose);
           //NGL.useWorker = true;
           component0.superpose(component1);
           //NGL.useWorker = false;
        },
```

In console, I can see the function 'superpose' code but keep getting 'ReferenceError: NGL is not defined'.

Any idea how to fix it? thanks.

**Comment by arose** [comment]
can you try again, I made some fixes lately and just updated dist/ngl.js

**Comment by hainm** [comment]
got the same error with the newest commit: eda4864d1688c9d2eef93d16e0d9cb13414b44b1

**Comment by hainm** [comment]
just clean my cache and your commit works for me. I will double-check.

**Comment by hainm** [comment]
uhm, try again and still get the same error. Weird.

**Comment by hainm** [comment]
You can try this branch: https://github.com/arose/nglview/pull/396

**Comment by arose** [comment]
> In console, I can see the function 'superpose' code but keep getting 'ReferenceError: NGL is not defined'.

In the error, can you see the code that throws it originally?

**Comment by hainm** [comment]
> var C = e.getView(new NGL.Selection(r + " and .CA"))

(saw from minimized code)

**Comment by arose** [comment]
Thanks! Fixed a whole bunch of similar bugs 7d6d3c9e32b08c1d684e41eaec718f71ffbcddaf.

**Comment by hainm** [comment]
new error in here

`Exception in Comm callback TypeError: Cannot read property 'getAtomSet' of undefined(…) TypeError: Cannot read property 'getAtomSet' of undefined`

```javascript
        getAtomSet: function(t, i) {
            e.Debug && Cu.time("StructureView.getAtomSet");
            var r = this.structure.getAtomSet(t);
            return !i && this.atomSet && (r = r.new_intersection(this.atomSet)),
            e.Debug && Cu.timeEnd("StructureView.getAtomSet"),
            r
        },
```

**Comment by arose** [comment]
This is odd, it suggests the StructureView has no parent structure?! Can you give some context. How are you calling this. Does the error only occurs with the superpose method?

**Comment by hainm** [comment]
>  Can you give some context. How are you calling this

```javascript
        superpose: function(cindex0, cindex1){
           // superpose two components
           var component0 = this.stage.compList[cindex0];
           var component1 = this.stage.compList[cindex1];
           component0.superpose(component1);
        },
```

```python
view._remote_call('superpose', target='Widget',
                 args=[0, 1])
```

> Does the error only occurs with the superpose method?

Yes

**Comment by hainm** [comment]
This is the output from
```javascript
c = this.stage.compList[0]

for (var i in c){
    console.log(i)
}
```

```bash
name
uuid
visible
signals
stage
viewer
reprList
structure
trajList
selection
structureView
defaultAssembly
constructor
type
initSelection
setSelection
setDefaultAssembly
rebuildRepresentations
rebuildTrajectories
addRepresentation
addTrajectory
removeTrajectory
dispose
centerView
getCenter
superpose
setVisibility
addBufferRepresentation
removeRepresentation
updateRepresentations
clearRepresentations
setStatus
setName
eachRepresentation
__getRepresentationComponent
```

**Comment by hainm** [comment]
very weird

If I wrote straight JS script, I can see the superposition. (Try to remove all cache to make sure
I am using correct ngl.js file)

```python
%%html

<script>
stage.setParameters({backgroundColor: 'white'})

stage.loadFile("./1crn.pdb", {defaultRepresentation: true})
stage.loadFile("./tz2.single.pdb", {defaultRepresentation: true})
</script>
```

```python
%%html
<script>

var c0 = stage.compList[0];
var c1 = stage.compList[1];

</script>
```

```python
%%html
<script>
    console.log(stage.compList)
    console.log(stage.compList[0])
    
    c0.superpose(c1)
</script>
```

**Comment by hainm** [comment]
In JS script mode

```javascript
NGL.superpose(c0, c1)
```
TypeError: Object \#\<Hr\> has no method 'getView'

BUT

```javascript
c0.superpose(c1)
````

OK

**Comment by hainm** [comment]
LOL, weirder

If I specify 

- `c1.superpose(c0)`: work

- `c0.superpose(c1)`: got error

**Comment by arose** [comment]
You must make sure that both molecules actually have finished loading, looking at your code, this could be the problem.

**Comment by hainm** [comment]
I only hit enter to run my code if I saw two structures.

**Comment by arose** [comment]
> NGL.superpose(c0, c1)

that is not supposed to work, NGL.superpose expects Structure or StructureView objects.

**Comment by arose** [comment]
> c0.superpose(c1): got error

this should definitely work

**Comment by arose** [comment]
I just did a new install from this repo and the following works for me:

```javascript
import nglview
view = nglview.show_pdbid("3pqr")  # load "3pqr" from RCSB PDB and display viewer widget
view
```

```javascript
view.add_structure(nglview.PdbIdStructure("1gzm"))
```

```javascript
view._remote_call('superpose', target='Widget', args=[0, 1])
```

**Comment by hainm** [comment]
indeed. cache is evil. thanks.

**Comment by arose** [comment]
I am glad it is resolved, I was out of ideas. :-)
