### ISSUE TITLE
Bundle webapp as AMD for use with require.js

### ISSUE THREAD

**Issue by hainm** [arose/ngl#171]
it's nice. Can you make min file so I can use it in NGLView? I am not familiar with JS packaging (there are so many ways :D) 

https://github.com/arose/ngl/blob/master/examples/webapp.html#L17-L23

**Comment by arose** [comment]
it needs
- examples/js/lib/*
- examples/js/ui/*
- examples/js/gui.js
- examples/css/*
- examples/fonts/*

**Comment by arose** [comment]
> it's nice. Can you make min file so I can use it in NGLView?

Needs to be an AMD bundle as far as I can tell.

**Comment by hainm** [comment]
nglview will be stick with ipywidgets and jupyterlab for now.
