### ISSUE TITLE
Add dashed lines and cylinders

### ISSUE THREAD

**Issue by hainm** [arose/ngl#172]
![pymol-dash-dist-example](https://cloud.githubusercontent.com/assets/4451957/17187562/cb9ba6ae-5407-11e6-9f35-9fe5c43493fe.png)

(source: http://www.stampcollectingproject.org/crystallography/molecular-graphics/pymol/dash-lines-showing-distances-between-atoms)

**Comment by arose** [comment]
done in ts2 branch
