### ISSUE TITLE
CONECT records generate multiple copies of bonds

### ISSUE THREAD

**Issue by fredludlow** [arose/ngl#175]
If I have a PDB ligand file e.g:
[pp_ligand_33892_251397.pdb.txt](https://github.com/arose/ngl/files/388784/pp_ligand_33892_251397.pdb.txt)
which contains my dodgy "multiple serials in the conect records for double bonds" I get some slightly weird behaviour displaying multiple bonds where I get a mixture of double and single bonds (so everything looks like triple bonds). - actually there's a trivial typo that breaks the representation building in current master but that's simple to fix.

I've done some digging and have a fix (~~I'll submit this, then reference the issue number~~, see below), but don't think it's optimal. 

* The pdb-parser adds bonds it encounters in the CONECT records to the structure. Because bonds are specified both ways round there are twice as many bonds from this step (but the bonds orders are currently correct thanks to your fix in #133 )
* For PDB files, dontAutoBond is false, which eventually results in calls to `calculateBondsWithin/Between` 
* The first time this is called on a particular residue it calls `getBonds` which ends up calling `calculateResidueBonds`, which calculates bonds based on interatom distances. I've added code so that if those bonds are already specified the bond order is copied and the ResidueType.bonds.bondOrders property is correct, this might not be the best way of doing this.
* Back in `calculateBondsWithin` - the bonds from ResidueType get copied back onto the actual structure (now with correct bond orders). 
* The structure now has 30 bonds: original parse of conect records is 20 (specified both ways round) plus 10 copied from ResidueType. 
* When it comes to deducing reference atoms, shifts etc, half of those bonds (the ones specified 'backwards' in the CONECT section fail to find a reference atom (fixed in my version)
* My shoddy `getReferenceAtomIndex` implementation adds together `undefined` and an integer to produce a NaN for the reference atom index... (this happens when looking up the reference atom for bonds specified backwards e.g. `CONECT 2 1 `)
  * My change to BondProxy.getReferenceAtomIndex now checks serials both ways round
* THREE.js ends up normalizing a `NaN, NaN, NaN` vector to `0,0,0` as our shift dir, so the two cylinders/lines are drawn on top of each other. 

The upshot of all these changes is that all 3 instances of each double bond now pick equivalent reference atoms and render their cylinders lines in exactly the same place, so it looks fine. 

Question: Would it be better to just make sure there are the correct number of bonds in the structure? This means keeping track of the CONECT that's already been seen and not adding duplicates, plus also not adding duplicate bonds in `calculateBondsWithin`?
Alternatively, leave the parser alone but when applying bonds from ResidueType to structure first clear out all existing bonds for that residue?

**Comment by arose** [comment]
I took the liberty to commit the obvious fixes already, thanks!

I like using bond orders from existing bonds in calculateResidueBonds.

What about adding a function that removes duplicate bonds from the BondStore after bond parsing and calculation is finished? It is a handy function to have. Eventually an index that allows fast queries by atom indices could be added to BondStore and be used to avoid adding duplicates.

**Comment by fredludlow** [comment]
Cool, thanks! 

> What about adding a function that removes duplicate bonds from the BondStore after bond parsing and calculation is finished? 
> Eventually an index that allows fast queries by atom indices could be added to BondStore and be used to avoid adding duplicates.

Doing the first part would implicitly build the index for the second part? This sort of relates to previous discussion regarding a BondGraph type. In terms of implementation, is there a more efficient way of doing this than just plain objects: `{aid : { aid2: bondIndex1, ... }, ...}` - Building and maintaining that structure in BondStore would allow a method like:

`BondStore.prototype.bondIndicesForAtom( a1 )` returns array of bond indices
or
`BondStore.prototype.eachBondForAtom( a1, callback )` (callback takes bondProxy)

which would allow deduplication (as you say either avoiding adding twice or post-processing) and also simplify the code that finds the reference atom for drawing double bonds.

**Comment by fredludlow** [comment]
I made a gist](https://gist.github.com/fredludlow/eae62f1bc9a66e35e6b158010db26d7b) of what I meant, though I'm not sure about having the callback taking function in that file as that means importing bond proxy...

**Comment by arose** [comment]
Thanks for the suggestions. Let me test how it scales.

As to `eachBondForAtom`. I will probably make the bonds accessible from the atom object directly.

**Comment by arose** [comment]
@fredludlow Implemented updating bond orders similarly to your initial code. Also, don't add automatically calculated bonds to the bondStore if they already exist. See 20a4b1219386958d15a8dc13e840b798adc396da. The code builds an atom pair to bond mapping but only for the bonds that are in the file, which should not be too many.

I tried building an atom pair to bond mapping inside of the BondStore (as in your gist) but that is too slow for large structures. For example, for MMTF files building it takes >4x longer than parsing the file. I will test implementing a static adjacency list using Typed Arrays to get efficient access to bonded atoms from an atom.

**Comment by arose** [comment]
Added a BondHash class for efficient access to bonded atoms from an atom, see  9a90d23506b839e444f515e6294a50cb67f990cf.

Compared to an Array-of-Arrays implementation it is ~15 times faster.

**Comment by arose** [comment]
Changed the PDB parser so that bonds are not added multiple times, see 2a847fc693212618babb75ceaa605da5e57c494a. There are not that many bonds in PDB files and the files are not that big (unless you misuse the format). I guess that is a good compromise.

**Comment by fredludlow** [comment]
> Added a BondHash class for efficient access to bonded atoms from an atom, see 9a90d23.
> Compared to an Array-of-Arrays implementation it is ~15 times faster.

:-)

Excellent, thanks once again! I can refactor the existing multiple-bond code to use this if you think it would be cleaner and/or quicker? -(I realise I also said I'd do the off-centred multiple bond representation, which I've not forgotten, will get on with it later in the week).

**Comment by arose** [comment]
> I can refactor the existing multiple-bond code to use this if you think it would be cleaner and/or quicker?

That would be great.

> (I realise I also said I'd do the off-centred multiple bond representation, which I've not forgotten, will get on with it later in the week).

Sure, that would especially nice for rings, right?
