### ISSUE TITLE
nglview embeding does not work

### ISSUE THREAD

**Issue by hainm** [arose/ngl#176]
I am creating a demo for `nglview` so we can have a showcase here (http://jupyter.org/widgets.html).

The demo is here: http://amber-md.github.io/pytraj/test/nglview_demo.html

As you can see there is nothing.

Here is the log:
<img width="891" alt="screen shot 2016-07-29 at 6 44 00 pm" src="https://cloud.githubusercontent.com/assets/4451957/17265405/a8abc0aa-55bc-11e6-8d04-ae9fb38d6559.png">

**Comment by arose** [comment]
The canvas has a size of 0px by 0px which is probably the root of the problem.

**Comment by hainm** [comment]
so how can I fix that? :D

**Comment by arose** [comment]
maybe calling `stage.handleResize()` after the widget is otherwise initialized and has a size helps

**Comment by hainm** [comment]
I give up this.

**Comment by arose** [comment]
If `stage.handleResize()` does not work you can set the size explicitly with `stage.viewer.setSize( 200, 200 )`.

**Comment by hainm** [comment]
no luck. :D

**Comment by hainm** [comment]
http://amber-md.github.io/pytraj/test/nglview_demo.html

**Comment by arose** [comment]
earlier today I added some guards to the Viewer class to never have a canvas smaller than 1px by 1px. Could you try with the current version, maybe it helps.

**Comment by hainm** [comment]
neither. 

I go ahead closing this since it's not something we should do right now.
