### ISSUE TITLE
local file system support

### ISSUE THREAD

**Issue by Burning-Daylight** [arose/ngl#18]
Standalone NGL Viewer does not always work if used from local filesystem (file:///...). The error only shows up in Chromium, in Firefox everything works fine. The problem also disappears if security policies in Chromium are relaxed deliberately with "--allow-file-access-from-files".
![Image of Yaktocat](http://i.imgur.com/Eu6ppRr.png)

**Comment by arose** [comment]
As far is I understand access restrictions to the local file system are a security feature and can only be relaxed in Google Chrome/Chromium with the `--allow-file-access-from-files` flag, as you noted (for a discussion see [1](https://productforums.google.com/forum/#!topic/chrome/v177zA6LCKU), [2](https://code.google.com/p/chromium/issues/detail?id=37586), [3](https://code.google.com/p/chromium/issues/detail?id=47416) and [4](http://blog.chromium.org/2008/12/security-in-depth-local-web-pages.html)).

As an alternative, depending what you want to achieve, serving the files you want to access through a simple web server could be the way to go.
