### ISSUE TITLE
what's the final goal?

### ISSUE THREAD

**Issue by albumns** [arose/ngl#182]
Hello:

I am playing around NGL these days. It is a really amazing tool for online 3D visualization of molecules. I am just wondering what's the ultimate goal for NGL? Have the developers consider to introduce more sophisticated GUI for NGL like what we see in PyMol or UCSF Chimer? 

If yes, that's would be really amazing. 

Thank you very much

**Comment by hainm** [comment]
one of the goal is here: https://github.com/arose/nglview :D

**Comment by albumns** [comment]
Aha. *^_^*

I noticed that before. Actually I first saw the NGLView in Amber, then I 
found NGL.....

That's really fantastic work!!! I enjoy it a lot.

If we can have more menu for the normal operations like that in most 
offline tool, that's would be perfect.....

**Comment by hainm** [comment]
You can also try mdsrv: https://github.com/Amber-MD/mdsrv/

I made a fork from original repo to work with pytraj in amber. 

Also the nglview dev branch does have menu for Jupyter notebook version.

What kind of specific menu feature you are looking for?

(The one in NGL website is quite good:

http://arose.github.io/ngl/)

Hai

**Comment by albumns** [comment]
Hi Hai:

Indeed the NGL has very powerful function and we can do many things by 
the current menu.

However. there are still something one could be expected. For instance: 
there are plenty of good things in the example, and we probably need to 
build a .html file based on related .js file. There are not available in 
the menu operations.

For a specific case: I imported a local pdb into NGL and I would like to 
measure the distance/angle between atoms. I cannot find any menu in NGL 
could do this.

I saw NGL could support reading electron density map and creating 
surface for a ligand or protein. That's very useful function. However, 
all those good stuff cannot be done from the current available menu in a 
web browser.....

Another aspect one could expect is the implement of a command line 
window. That's would be extremely helpful if the menu is missing, but we 
can still obtain what we want from a command line.

I hope this would be helpful for improving NGL....

kind regards

Albert

**Comment by arose** [comment]
> For a specific case: I imported a local pdb into NGL and I would like to
measure the distance/angle between atoms. I cannot find any menu in NGL
could do this.

Yeah, much needed, an open issue, see https://github.com/arose/ngl/issues/46

> I saw NGL could support reading electron density map and creating
surface for a ligand or protein. That's very useful function. However,
all those good stuff cannot be done from the current available menu in a
web browser.....

Reading electron density map can be done through Menu > File > Open or just by drag'n'droping the file onto the canvas.

A molecular surface for a ligand or protein can be created by loading a structure file and then adding "surface" representation to it (using the three-lines-icon) and then changing the selection (text field to the right of the funnel-icon) to "protein" or "hetero and not(water or ion)".

The NGL webapp certainly lacks documentation. Any contributions are most welcome!

> Another aspect one could expect is the implement of a command line
window. That's would be extremely helpful if the menu is missing, but we
can still obtain what we want from a command line.

One way would be is to make the `stage` instance available to the browser console. Not super user-friendly, but a start.

**Comment by albumns** [comment]
I see.

Glad to learn more things about NGL.

Is it also possible to export movie for the MD simulation trajectory? At 
least I found that NGL could support playing the trajectory in a browser.

**Comment by hainm** [comment]
At current moment, I don't think there's an easy way to export a movie for MD (with either `ngl` or `nglview`).

But I wrote a tutorial with `nglview` here (with Jupyter notebook): http://ambermd.org/tutorials/analysis/tutorial_notebooks/nglview_movie/

**Comment by albumns** [comment]
I see. Probably it is even more easier just record the screen of my 
Linux for the movie. ^_^

**Comment by hainm** [comment]
> Probably it is even more easier just record the screen of my Linux for the movie.

absolutely true.

**Comment by hainm** [comment]
The only difference I can think of is that you can generate high quality images from NGL to show on big screen.

**Comment by albumns** [comment]
Another foreseeing good thing is editing structure from NGL. Would it be 
good if we can do something like: mutate the amino acid for a protein or 
add an additional functional group for a small molecule? This would be 
particularly helpful for modellers' daily work.....

regards

**Comment by hainm** [comment]
I think there are many good programs out there for that task (e.g pymol, ...), NGL should focus mainly on visualization.

**Comment by arose** [comment]
> Another foreseeing good thing is editing structure from NGL. Would it be
good if we can do something like: mutate the amino acid for a protein or
add an additional functional group for a small molecule? This would be
particularly helpful for modellers' daily work.....

For the time being I focus on optimising display of static structures, static in the sense that the topology/composition does not change (coordinates can change).

**Comment by hainm** [comment]
FWIW, Autodesk team has very nice progress with 3Dmol
https://github.com/Autodesk/molecular-design-toolkit/pull/95

![](https://cloud.githubusercontent.com/assets/389558/18140116/f6325288-6f68-11e6-83ba-9ea20e7a33dc.gif)
