### ISSUE TITLE
keep residueindx as default color for small structure?

### ISSUE THREAD

**Issue by hainm** [arose/ngl#183]
from you recent build: 8944ded51c45a52e208bad11d57d1bbcdfa8429b
![screenshot 1](https://cloud.githubusercontent.com/assets/4451957/17598506/e6e2ce5c-5fc8-11e6-9851-3991b21a1202.png)

I myself prefer the old color pattern with `residueindex` for small molecule.

**Comment by hainm** [comment]
old one

![screenshot 2](https://cloud.githubusercontent.com/assets/4451957/17598523/f8642054-5fc8-11e6-981f-9c4b648fe2d1.png)

**Comment by hainm** [comment]
1tsu

new
![screenshot 3](https://cloud.githubusercontent.com/assets/4451957/17598606/3d3ba904-5fc9-11e6-9bb1-a4ffe4784055.png)

old
![screenshot 4](https://cloud.githubusercontent.com/assets/4451957/17598611/41967d08-5fc9-11e6-848d-387e46e5a0b5.png)

**Comment by hainm** [comment]
`1l2y`

new 

![screenshot 5](https://cloud.githubusercontent.com/assets/4451957/17598779/1ae21464-5fca-11e6-9a20-9c51dbe19a09.png)

old

![screenshot 6](https://cloud.githubusercontent.com/assets/4451957/17598782/1f4b1474-5fca-11e6-9712-724818875969.png)

**Comment by arose** [comment]
I changed the colorscheme for the defaultRepresentation method from atomindex to chainname. I think this is what you are observing here.

**Comment by hainm** [comment]
yeah, I am aware that. But the default color for small structure is not nicer than the old pattern (IMO).

**Comment by hainm** [comment]
just update the title.

**Comment by arose** [comment]
I'll think about it. As soon as there are multiple polymer chains, I would prefer the chainname colorscheme

**Comment by arose** [comment]
Changed it so that for structures with a single polymer chainname the "residueindex" color scheme is used, see 796bb3b8bcc05d5724b9608e6ae5434448a6b986
