### ISSUE TITLE
no bond connect for terminal base - polyAT

### ISSUE THREAD

**Issue by hainm** [arose/ngl#184]
FYI

Using http://arose.github.io/ngl/ (the most updated ngl.js too)

![screenshot 7](https://cloud.githubusercontent.com/assets/4451957/17601531/a12838b2-5fd6-11e6-893a-aadca17e0c9a.png)

File: http://ambermd.org/tutorials/advanced/tutorial1/files/polyAT.pdb

**Comment by arose** [comment]
This is DNA right? NGL detects it mostly as RNA and only the terminal bases as DNA. The detecting is based on atomnames as they are in official PDB entries. I have to look if I can make it work with the amber ff atomnames (which I presume they are?) as well.

**Comment by hainm** [comment]
the terminal bases are A3, A5, T3, T5. Yes, DNA (it only use A G T C letters :D).

**Comment by arose** [comment]
tweaked rna/dna moleculeType detection, see 90dee08098940f49d66c8e8d10987ce95682a854
![screenshot 23](https://cloud.githubusercontent.com/assets/272250/17990594/19cf85a2-6aec-11e6-84f5-bc5f5c1b8b06.png)

**Comment by hainm** [comment]
thanks.
