### ISSUE TITLE
default orientation makes the molecule small

### ISSUE THREAD

**Issue by hainm** [arose/ngl#189]
I am using ngl dev just pulled one or two days ago.

![screenshot](https://cloud.githubusercontent.com/assets/4451957/17826695/83154a9c-6641-11e6-9493-914f7a4a7912.png)

**Comment by arose** [comment]
what about the current version?

**Comment by hainm** [comment]
same thing
```bash
commit aa8d8e5c7f9f41a35cd710c464a61b16c3de71c5
Author: arose <alexander.rose@weirdbyte.de>
Date:   Thu Aug 18 20:03:53 2016 -0700

    limit travis to current major node version
```

**Comment by arose** [comment]
have you updated the build?

**Comment by hainm** [comment]
tricky question. no, I haved not because you always did that. :D

**Comment by arose** [comment]
Please build it. I recently made some changes on how to do that, see https://github.com/arose/ngl/blob/master/DEVELOPMENT.md

**Comment by hainm** [comment]
> The necessary dependencies can be installed with npm install

is there any way to install all the packages in a single command? I keep getting missing some.

**Comment by hainm** [comment]
for example, getting

> Cannot find module 'rollup-plugin-istanbul'

**Comment by arose** [comment]
did you do `npm install`?

**Comment by hainm** [comment]
I tried

```bash
npm run-script build
```

saw missing rollup,
so keep going
```bash
npm install rollup -g
```
and so on. :D

**Comment by arose** [comment]
inside the ngl repository directory do `npm install` then `npm run-script build`

**Comment by hainm** [comment]
thanks. I clearly that I misunderstood the doc.

btw, I updated ngl.js but still getting small molecule.

**Comment by arose** [comment]
build/ngl.js (npm run-script build) or dist/ngl.js (npm run-script build-min)?

**Comment by hainm** [comment]
The min version from

npm run-script build-min

**Comment by arose** [comment]
still an issue?

**Comment by hainm** [comment]
I am not sure if I got the cache issue, but still see the small molecule.

**Comment by hainm** [comment]
I confirm that the issue is not solved yet.

**Comment by arose** [comment]
I think this is just how it currently works. The zoom is such that however you rotate the structure it won't get clip at the edges (there are some edge cases where this still happens).

Initial view
![screenshot 31](https://cloud.githubusercontent.com/assets/272250/18690308/51cbe742-7f42-11e6-88e9-733d34e93b23.png)

Rotated, alomost touching the edges
![screenshot 32](https://cloud.githubusercontent.com/assets/272250/18690309/51cd8e58-7f42-11e6-98ee-1dc796a4f56e.png)

**Comment by arose** [comment]
A new feature could be a zoom that is optimized for the current orientation.
