### ISSUE TITLE
PDB format: insertion code support

### ISSUE THREAD

**Issue by arose** [arose/ngl#19]
The insertion code is currently not parsed.

See http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM

Adding support has consequences when comparing atoms for identity where at least one has an insertion code set.

**Comment by arose** [comment]
done (dev branch). select residue with number 10 and insertion code A:  `10^A`

**Comment by josemduarte** [comment]
Will insertion codes be supported in selection ranges? That is in general problematic as there's no guaranteed order of the insertion codes... e.g. in 1a2c the first few residues have this ordering: `1H, 1G, 1F, 1E, 1D, 1C, 1B, 1A, 1, 2, 3 ...`
