### ISSUE TITLE
(AA?) bug in chrome on Android 

### ISSUE THREAD

**Issue by fredludlow** [arose/ngl#191]
Possibly related to #103. Structures appear whilst dragging and rotating but dissappear after a small delay. This is on Chrome 52 / Android 6.0.1 using the example webapp at http://arose.github.io/ngl/

**Comment by arose** [comment]
I saw the same thing just yesterday on a Chromebook but I can't reproduce it on any of my devices (and I don't have access to a Chromebook). Can you please test http://arose.github.io/ngldev/ - I put the latest dev version on there. Thanks

**Comment by fredludlow** [comment]
The bug's still there for me in that version (both fine in Chrome on Linux)

**Comment by arose** [comment]
Any messages in the Browser console?

**Comment by fredludlow** [comment]
Never tried debugging on Android, presumably need to install the sdk? will investigate...

**Comment by arose** [comment]
No need to install the sdk, you can use Chrome for remote debugging, see https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging?hl=en

**Comment by fredludlow** [comment]
I've attached the log, let me know if there's any other info I can provide
[arose.github.io-1472483662504.txt](https://github.com/arose/ngl/files/442696/arose.github.io-1472483662504.txt)

**Comment by fredludlow** [comment]
I think the 404 in that log is suprious (didn't happen when I refreshed the page).
The recurring two error messages were generated each time I stopped dragging/rotating

**Comment by arose** [comment]
Thanks, does the log look the same for http://arose.github.io/ngldev/?

**Comment by fredludlow** [comment]
Yup

**Comment by arose** [comment]
Workaround is setting `sampleLevel` to -1.

**Comment by arose** [comment]
@fredludlow can you please test http://arose.github.io/ngldev/ again, I made a change (02628b45ef79884d34e99c5819f3072bd6aa96c2) that might fix it.

**Comment by hainm** [comment]
do you turn off mouse wheel?

**Comment by arose** [comment]
> do you turn off mouse wheel?

can you try again (maybe wait a minute) I hopefully fixed that

**Comment by hainm** [comment]
work for me now.

**Comment by fredludlow** [comment]
Alas, I'm still seeing the same bug on some devices: 

Working: Moto G1 Android 5.1
Not working: Moto G4 (6.0.1), Samsung S4 (4.4.2).

I'll see if I can get console logs for various devices and compare (slightly hampered by Windows group policy on my work box)

**Comment by arose** [comment]
What are the supported webgl extensions on those devices? Visit http://webglreport.com/ to get a list.

**Comment by fredludlow** [comment]
So the Moto G4 (which doesn't work) says this:
ANGLE_instanced_arrays
EXT_blend_minmax
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_compressed_texture_atc
WEBKIT_WEBGL_compressed_texture_atc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBKIT_WEBGL_lose_context

Still trying to get hands back on the other devices (their owners are out of the office...)

**Comment by arose** [comment]
Maybe it is an issue with rendering to a half float texture.

Can use test if

```
type: HalfFloatType
```

 or 

```
type: FloatType
```

 or 

```
type: UnsignedByteType
```

works instead of

```
type: (
    supportsHalfFloat ? HalfFloatType :
        ( SupportsReadPixelsFloat ? FloatType : UnsignedByteType )
)
```

at https://github.com/arose/ngl/blob/master/src/viewer/viewer.js#L292-L295

**Comment by fredludlow** [comment]
So Moto G4, 6.0.1, OES extensions in WebGL report are
OES__element_index_uint
OSE_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object

Working with FloatType and UnsignedByteType (HalfFloatType reproduces the bug)

Moto G1 5.1, WebGL report says:
OES__element_index_uint
OSE_standard_derivatives
OES_texture_float
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object

Works with HalfFloatType or UnsignedBytetype (FloatType reproduces the bug - which I'd not seen before on this device).

That doesn't make it a whole lot clearer to me...

**Comment by arose** [comment]
> That doesn't make it a whole lot clearer to me...

It might be browser or driver bug :-(

I was thinking about using UnsignedBytetype on mobile (which produces some banding artifacts with high sampling rates but that isn't a common use case on mobile)

**Comment by fredludlow** [comment]
I don't know anything about the pros and cons of different types (beyond "it works" or "it doesn't work.."). If you want to avoid the banding another option would be to detect the WebGL errors and turn sampleLevel down to -1 when they appear? (Not sure how feasible that is..)

**Comment by fredludlow** [comment]
I got one more data point- Android 7 on Nexus 6p, all 3 modes work...

**Comment by arose** [comment]
went with the "UnsignedBytetype on mobile" option, see 325cf9bcbe9b4a33ea63f754c414d5663ca6e160
