### ISSUE TITLE
mouse wheel is slow

### ISSUE THREAD

**Issue by hainm** [arose/ngl#194]
I tried the last commit https://github.com/arose/ngl/pull/186.

The mouse wheel behaves weird (speed is slow, not really smooth)

**Comment by arose** [comment]
firefox, right?

**Comment by hainm** [comment]
you catch me.

**Comment by arose** [comment]
better with 80b0ee13161b35fcee4c9e6d444fd924c36ae18a?

**Comment by hainm** [comment]
yeap.
