### ISSUE TITLE
getByGid - off by one error?

### ISSUE THREAD

**Issue by martingraham** [arose/ngl#195]
Bear with me (alex might be used to this by now)

I've a collection of items I'm showing as a DistanceRepresentation and trying to pick and I've found something odd when I whittle the DistanceRepresentation down to just a few items - specifically one of the bonds is not pickable

I have a structure with 9205 atoms and 2 bonds in the distance representation, these two bonds have the gids' 9206 and 9207. The gid pool has a range of [1, 17000+]

By adding some console.logs, I see when I ask getByGid for 9207 it returns a BondProxy, when I ask for 9206 it returns an AtomProxy

The best i can figure out what's happening is:

It appears the code in https://github.com/arose/ngl/blob/95ad73498250c7394fa00f36c286fcd6e663ca22/src/utils/gid-pool.js#L184

first makes an offset var by subtracting the bottom gid range value (1) from 9206 to make 9205

It then does a less than or equal to comparison against the atom count (9205) to decide if it's an atom. Since 9205 <= 9205 is true it returns an AtomProxy. 

I think it should just be a less to comparison (not an equal as well)?

And that would probably apply to the subsequent comparisons for the various bond types?

Sorry if this is a bit long-winded and doesn't have a test case but I'm still trying to get something together for you Alex :-)

**Comment by arose** [comment]
Sadly picking is broken for DistanceRepresentation (just removed picking to avoid confusion, see 1aa939db4436a5274c43b37ff88c986b2e090b09).

**Comment by martingraham** [comment]
Hi Alex, this isn't so much that picking is broken, but that getbygid will return an AtomProxy for the first bond in the gid list, whether it's in a distance representation or not.  I think the comparator in getbygid needs to be a "<" rather than a "<="

**Comment by arose** [comment]
@martingraham you are right, sorry for not looking closely enough. It is hopefully fixed with e072310bf24ec5a826fd4c702581d262593d68fe. Also, added some tests.

**Comment by arose** [comment]
@martingraham Is it good for you?

**Comment by martingraham** [comment]
yes, that seems fixed as far as I can tell, thanks
