### ISSUE TITLE
implement .vol loading?

### ISSUE THREAD

**Issue by pconesa** [arose/ngl#196]
Hi! I have a .vol (density map) and really like to use your viewer instead of a dirty hack we already have rendering the .vol using chimera headless on the server and cherry picking the volume code and embed it into our HTML template.....grrr!!

I really want to use NGL but loading .vol files doesn't seem to be implemented. At this point I can convert .vol to .mrc in the server, and serve the .mrc to the viewer or ...

Implement .vol in the ngl viewer. I'm familiar with javascript but not at all with this project, with some guidance, I'm happy to contribute.

Congratulations for this work!

Pablo.

**Comment by arose** [comment]
You are very welcome to contribute! See [here](https://github.com/arose/ngl/blob/master/DEVELOPMENT.md) for some pointers.

Is [this](http://paulbourke.net/dataformats/vol/) the .vol format you are referring to? If it is, the parser can be similar to the parser for binary .mrc, see [here](https://github.com/arose/ngl/blob/master/src/parser/mrc-parser.js). To use it you need to register it in [ngl.js](https://github.com/arose/ngl/blob/master/src/ngl.js#L527) by importing it there. Also add "vol" [here](https://github.com/arose/ngl/blob/master/src/loader/loader.js#L16) and [here](https://github.com/arose/ngl/blob/master/src/loader/loader-utils.js#L45) and [here](https://github.com/arose/ngl/blob/master/examples/js/gui.js#L474).

Hope that helps

**Comment by pconesa** [comment]
Thanks Alexander, for now it's faster for me to convert to mrc on the 
fly and use the viewer as it it.

But I'll keep this email in my mind for the future. I'm already 
visualizing stuff. Just need to figure out how to change the threshold 
(isolevel).

Any tip? Actually, I'm already setting the value, but don't know how to 
trigger the rendering.

All the best,

**Comment by arose** [comment]
> Any tip? Actually, I'm already setting the value, but don't know how to
trigger the rendering.

Have you tried `component.setParameters({ isolevel: 1.0 })`?

**Comment by pconesa** [comment]
Many thanks, I've found out this on Friday:

             surfaceComponent.clearRepresentations();
             surfaceComponent.addRepresentation("surface", {isolevel: 
threshold});

This works fine, surfaceComponent is a NGL.SurfaceComponent object.

I'm also using the 0.7dev version (same  source at here 
<http://proteinformatics.charite.de/ngl/doc/index.html#User_manual/Usage/Embedding>)

I've also tried to use later versions (0.7 to set an orthographic camera 
but got not success)

If you are interested I can switch to the latest (v0.8) and report back 
what I find.

Now I can't remember the exact problem but it was related with the fact 
that our URL to request our data looks like this:

http://localhost:8000/webtools/get_file/?path=/Runs/000178_XmippProtAlignVolumeForWeb/extra/output_vol000274.vol.mrc&filename=ngloutput.mrc


and the error was about a problem with the extension. If I remember 
right, there was a class that parses the url trying to get an extension, 
and in this case it was null since it was using only "get_file/".

At that point I though my case was a bit out of the scope (that url is 
working in v0.7dev, embedded)  and gave up.

If this case is useful for you, I'll be happy to report exact details.

All the best, Pablo. And congratulations for the viewer.

**Comment by arose** [comment]
> If you are interested I can switch to the latest (v0.8) and report back what I find.

it is in any case a good idea to switch to 0.8

> and the error was about a problem with the extension.

you can force the extension/file type like

```stage.loadFile("url", {ext: "mrc"})```

see also http://arose.github.io/ngl/api/Stage.html#loadFile__anchor

**Comment by pconesa** [comment]
It worked like a charm! And now we have the orthographic camera on.

Many thanks!

**Comment by arose** [comment]
> It worked like a charm! And now we have the orthographic camera on. Many thanks!

You're welcome

**Comment by pconesa** [comment]
I'll let you know where to find it, when deployed.

**Comment by arose** [comment]
that would be great!

**Comment by pconesa** [comment]
Deployed, couldn't wait to see it in action.

It's a bit hidden.

You can see it working here 
<http://scipion.cnb.csic.es/m/showj/?path=Runs/000462_XmippProtAlignVolumeForWeb/volumes.sqlite&s=myfirstmap&p=BpvTestData&visible=id%20enabled%20comment%20_filename%20&mode=table&render=_filename&order=id%20enabled%20comment%20_filename>


Steps to show it in action:

1.- Click on GREEN area of the last box of the work-flow (aligned volume 
web).

2.- Click on the "Analyze results" button

3.- A window should pop up (must allow pop up windows, sorry)

4.- In the popped up window...click in the small cube icon ()  (shortcut 
out of context 
<http://scipion.cnb.csic.es/m/showj/?path=Runs/000462_XmippProtAlignVolumeForWeb/volumes.sqlite&s=myfirstmap&p=BpvTestData&visible=id%20enabled%20comment%20_filename%20&mode=table&render=_filename&order=id%20enabled%20comment%20_filename>)

5.- A surface object should appear.

Any improvement is very welcome.

We are writing a paper, were NGL is cited already.

Thanks again!.

**Comment by arose** [comment]
Very nice! What kind of improvements are you looking for?

**Comment by pconesa** [comment]
Sorry, I think my english confused you. 

I meant feedback. Your viewer does all we need for now.

**Comment by arose** [comment]
> I meant feedback.

I see. Adding a slider for the front clipping plane might be useful.

> Your viewer does all we need for now.

Alright. Good luck with your paper!
