### ISSUE TITLE
Can't see other transparent (opacity < 1.0) representations through transparent cartoon structure

### ISSUE THREAD

**Issue by martingraham** [arose/ngl#199]
Is this a known issue? When I set the structure (cartoon representation) to less than 1 I can see other parts of the same structure through itself. I can also see other representations through it if they're completely opaque.

However if I reduce the opacity of those representations to <1 they aren't seen through the cartoon representation. I've attached a screenshot (residues and distance reps with opacity 0.9) where they're cut out when they go behind the transparent cartoon rep structure. Squinting, I swear I can see the cartoon structure showing correctly as it goes behind the slightly transparent bonds so the reverse isn't true.

I guess a better description of the problem is "transparent cartoon representation acts as opaque when in front of other transparent representations"
![screenshot 9](https://cloud.githubusercontent.com/assets/3490823/18385008/d1f93ea8-7685-11e6-86e2-ea0570d4d822.png)

I ask if it's a known issue as it might well just be my graphics card and work fine for others. Firefox won't show anti-aliased fonts because it's that rubbish.

I'll also list these three warnings I always get when I load NGL in case any of these have a bearing on it:
ngl_verbose.js:20968 THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.
ngl_verbose.js:20968 THREE.WebGLRenderer: OES_texture_float_linear extension not supported.
ngl_verbose.js:20968 THREE.WebGLRenderer: WEBGL_color_buffer_float extension not supported.

**Comment by arose** [comment]
This is a known problem. Transparency is hard for GPUs. You can remove the patterns in the cartoon by setting the parameter side to "front".

**Comment by arose** [comment]
@martingraham does the workaround help you?

**Comment by martingraham** [comment]
yes I can get rid of the striping effect in the helix reps with that parameter setting, thanks, martin

**Comment by arose** [comment]
great
