### ISSUE TITLE
Make a release on npm

### ISSUE THREAD

**Issue by rgbkrk** [arose/ngl#201]
Please package a release on npm, for use via browserify, webpack, or electron. You'll need to do this particularly if you want nice integration in the future with [JupyterLab](https://github.com/jupyter/jupyterlab), [nteract](https://github.com/nteract/nteract), or [Hydrogen](https://github.com/nteract/hydrogen).

**Comment by rgbkrk** [comment]
On the electron note, it looks like `require`ing works just fine. Was simple enough to display:

![screen shot 2016-09-18 at 4 36 20 pm](https://cloud.githubusercontent.com/assets/836375/18619980/0e45cd4c-7dbe-11e6-9d96-d67b16003767.png)

To get that working I uploaded exactly what's on master here to my own namespace. No changes, worked flawlessly. If you make a release, I can make use of it immediately. :smile:

However, some of the implied paths wouldn't load properly though since the scheme in Electron is `file:`:

```
stage.loadFile("rcsb://1crn",  { defaultRepresentation: true } );
```

<img width="954" alt="screen shot 2016-09-18 at 4 32 38 pm" src="https://cloud.githubusercontent.com/assets/836375/18619955/8db69256-7dbd-11e6-8191-41dce8989b3f.png">

**Comment by arose** [comment]
Yeah, good point, now that I do proper bundling it should be easy to release on npm.

**Comment by arose** [comment]
> However, the specialized schemes wouldn't load properly though since the scheme in Electron is file:

I see, would you mind opening another issue?

**Comment by hainm** [comment]
Just FYI: @rgbkrk Per integration with `JupyterLab`, I think `NGL` has https://github.com/arose/nglview that follow [widget-cookiecutter](https://github.com/jupyter/widget-cookiecutter) template.

**Comment by rgbkrk** [comment]
Sure, I'll open another issue. Thanks for the quick responses.

> Just FYI: @rgbkrk Per integration with JupyterLab, I think NGL has https://github.com/arose/nglview that follow widget-cookiecutter template.

That's really awesome.

**Comment by arose** [comment]
Ok, I practiced with the latest release 0.8.0, see https://www.npmjs.com/package/ngl.

- How do people generally handle development snapshots on npm?
- Is there a common way to sync the version number in package.json with a version number in a js source file?
- How can I install electron note? I have electron, but how do I get a notebook inside of it as in you screenshot?

> Just FYI: @rgbkrk Per integration with JupyterLab, I think NGL has https://github.com/arose/nglview that follow widget-cookiecutter template.

When ngl is published on npm I assume you can remove its code from nglview-js and nglview?! And then trigger installation by the user?

**Comment by hainm** [comment]
> And then trigger installation by the user?

No. Python users should not need to use `npm`. All the code will be bundled in https://github.com/arose/nglview/tree/master/nglview/static anyway.

**Comment by hainm** [comment]
but yes, `ngl.js` can be removed from `nglview`.

**Comment by rgbkrk** [comment]
> How do people generally handle development snapshots on npm?

npm lets you do [prerelease tags](https://docs.npmjs.com/misc/semver#prerelease-tags), which means you can push out `0.9.0-dev.1` if you like. I certainly use RxJS 5's beta prerelease tags right now, they work quite well.

**Comment by rgbkrk** [comment]
> Is there a common way to sync the version number in package.json with a version number in a js source file?

Some people will `require('package.json').version`. That works out of the box with browserify and Electron. Webpack needs to have `json-loader` configured.

**Comment by rgbkrk** [comment]
> How can I install electron note? I have electron, but how do I get a notebook inside of it as in you screenshot?

We've been hacking on an [electron based jupyter notebook over in nteract/nteract](https://github.com/nteract/nteract).

My long term hope is that we can do something similar to what we do for geojson and plotly - there's a built in renderer/transform for their mimetypes.

![nteract geojson support](https://cloud.githubusercontent.com/assets/836375/18421299/d95ad398-783b-11e6-8b23-d54cf7caad1e.png)

**Comment by arose** [comment]
> Some people will require('package.json').version. That works out of the box with node, browserify, and Electron. Webpack needs to have json-loader configured.

that seems very reasonable, I just set that up with rollup, see 3daeb9324a52e73ca4bdb1b965a06f31af4b5e4e

**Comment by rgbkrk** [comment]
Rollup made that nice and easy!

**Comment by arose** [comment]
> We've been hacking on an electron based jupyter notebook over in nteract/nteract.

I installed nteract and tried your example but I get an empty canvas and no error message, any tipps?

![screen shot 2016-09-19 at 12 01 03 pm](https://cloud.githubusercontent.com/assets/272250/18645140/e6a45e72-7e60-11e6-8caa-cd29806b823d.png)

**Comment by arose** [comment]
ok got, just do `npm install ngl` in the nteract folder :-)

![screen shot 2016-09-19 at 12 09 20 pm](https://cloud.githubusercontent.com/assets/272250/18645442/0be5ae9c-7e62-11e6-9679-f15b6c19150c.png)

**Comment by arose** [comment]
I made a dev release on npm (https://www.npmjs.com/package/ngl). I guess we can close this issue?

**Comment by arose** [comment]
> My long term hope is that we can do something similar to what we do for geojson and plotly - there's a built in renderer/transform for their mimetypes.

Sounds great. Either ngl directly or the nglview widget which gives you some ui.

**Comment by rgbkrk** [comment]
Great!

/cc @jdetle

**Comment by rgbkrk** [comment]
> ok got, just do npm install ngl in the nteract folder :-)

Whoops, yeah. I also noticed that `ngl` is only about 2.5MB which isn't too much of an increase on our current size. It's tempting to make it available by default if we have a way to make it useful to everyone.

**Comment by arose** [comment]
Did an update, it is now just under 1MB :-)

It would be nice to have a simple widget that does not need any python code. Expanding the example from above it turns out you have access to the stage object from other cells :-) With that you can script NGL in anyway you like.

![screen shot 2016-09-19 at 6 12 18 pm](https://cloud.githubusercontent.com/assets/272250/18654317/ea32b082-7e94-11e6-8d37-a68db708ab82.png)

**Comment by hainm** [comment]
> Expanding the example from above it turns out you have access to the stage object from other cells

also True for Jupyter notebook.

**Comment by arose** [comment]
ha, there is a %%javascript magic

![screen shot 2016-09-19 at 6 23 36 pm](https://cloud.githubusercontent.com/assets/272250/18654491/44f6ae64-7e96-11e6-917f-401716a4c82b.png)

**Comment by arose** [comment]
However it won't be part of the saved notebook :-( http://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/JavaScript%20Notebook%20Extensions.html

**Comment by rgbkrk** [comment]
Awesome!

The troubling thing across the available frontends right now is how they require assets and how it differs across versions. Within Jupyter notebook, requirejs is a given in the notebook since 2.0 or later which puts a tight coupling on html/javascript outputs and the runtime. With JupyterLab, they're building a great way to do extensions that is going to be specific to JupyterLab but paves a really good path for the future.

Within Atom (with Hydrogen) and Electron the environment is similar, but you can't assume commonjs require.

The path nteract and jupyterlab has taken is that you can register custom mimetypes for display + renderers in the frontend.

* [jupyterlab ipywidget](https://github.com/ipython/ipywidgets/blob/6596618389be29ce775c898d99234a3034390f83/widgetslabextension/src/plugin.ts#L57-L75)
* [nteract in geojson](https://github.com/ipython/ipywidgets/blob/6596618389be29ce775c898d99234a3034390f83/widgetslabextension/src/plugin.ts#L57-L75): `application/vnd.geo+json` defers to Leaflet rendering

As for interactive updates, I've been [doing a little bit of thinking on _only_ the aspect of object synchronization from js ➡️ backend](https://github.com/rgbkrk/synchronized-object-diff-spec) so we have some of the core aspects for building ipywidgets (I want a lower level primitive on the jupyter protocol).

**Comment by rgbkrk** [comment]
This does pose concerns about if a notebook can be rendered on nbviewer or github.

For instance - this notebook doesn't show up in github very well:

https://github.com/nteract/nteract/blob/master/example-notebooks/geojson.ipynb

Even if it embedded HTML though, github wouldn't display it (that's their security stance). However, if they wanted to render the `application/vnd.geo+json` they could defer to their leaflet renderer since the raw notebook just embeds the geojson directly:

```json
   "outputs": [
    {
     "metadata": {},
     "data": {
      "application/vnd.geo+json": {
       "type": "FeatureCollection",
       "features": [
        {
         "type": "Feature",
         "geometry": {
          "type": "Point",
          "coordinates": [
           -77.02827,
           38.91427
          ]
         },
         "properties": {
          "place": "The coffee bar",
          "lat": "38.91427",
          "lon": "-77.02827",
          "login": "espresso"
         }
```

For `ngl` (pardon my lack of domain experience here), if we have a defined spec from front to back (preferably via JSON for the message spec) then we can render these and embed just the pieces we need to recreate it with `ngl`.
