### ISSUE TITLE
Some schemes can't be viewed in Electron

### ISSUE THREAD

**Issue by rgbkrk** [arose/ngl#203]
Carried over from #201. The `rcsb` uri doesn't load properly when `ngl` is used in Electron. It seems to replace the scheme with `file:`, which seems like a `//` default being used somewhere or a regular expression that's changing it out.

```js
stage.loadFile("rcsb://1crn",  { defaultRepresentation: true } );
```

<img width="954" alt="screen shot 2016-09-18 at 4 32 38 pm" src="https://cloud.githubusercontent.com/assets/836375/18619955/8db69256-7dbd-11e6-8191-41dce8989b3f.png">

**Comment by arose** [comment]
fixed in c20cfe0bd18a1fd54e547f4307fc6631823ccd27 and published as 0.9.0-dev.2

electron returns "file:" for window.location.protocol (at least in nteract)

**Comment by arose** [comment]
@rgbkrk does it work for you?

**Comment by rgbkrk** [comment]
Oh yes!
