### ISSUE TITLE
Return more info in picking data [feat request]

### ISSUE THREAD

**Issue by martingraham** [arose/ngl#204]
Hi Alex, at the moment I've hacked my version of the picking-controls.js to return a gid for my own nefarious purposes, but also the mouse coordinates so I can use them to position a tooltip. I'm just wondering is there another existing way to get the mouse position info or if not maybe adding it in would be useful for others?

i.e. return more info here -->
https://github.com/arose/ngl/blob/653022a8320b4faf0628b3bc92c925f79fac7b6b/src/stage/picking-controls.js#L108

**Comment by arose** [comment]
You mean return `mouse.canvasPosition.x, mouse.canvasPosition.y`?

**Comment by martingraham** [comment]
Yup, I should have said, that's exactly what I'm doing at the moment.

**Comment by arose** [comment]
added canvasPosition to pickingData, see c93bc303c2069bb19fce20ffc81b7455d9d6ef82

**Comment by martingraham** [comment]
Thanks Alex
