### ISSUE TITLE
AV-style surfaces

### ISSUE THREAD

**Issue by fredludlow** [arose/ngl#205]
So I had a go at porting the aforementioned AstexViewer surface code:

The current method (EDT - the isoquinoline looks a bit weird to me):
![screenshot 12](https://cloud.githubusercontent.com/assets/900535/18719361/02562e88-801f-11e6-82e4-fb7a749649aa.png)

New style (looks a bit more regular):
![screenshot 11](https://cloud.githubusercontent.com/assets/900535/18719407/2f262710-801f-11e6-932c-e6b5ed5beb34.png)

Also works on large surfaces:
![screenshot 13](https://cloud.githubusercontent.com/assets/900535/18719463/5e03a7ec-801f-11e6-934c-e4bd1ea3dfcb.png)

You can play with it [here](http://fredludlow.com/ngldev/examples/webapp.html). Create a surface and turn off useworker (or load the avSurf example) - (basically I set it so that if you generate without using a worker it calls AVSurface and if you use a worker it uses EDTSurface). 

In terms of implementation the `AVSurface` class is a drop-in replacement for the EDTSurface class. 

Code is here:
https://github.com/fredludlow/ngl/tree/av-style-surface

I'll do a bit of tidying etc before making a PR (have to leave the office in like, 2 minutes....)

**Comment by arose** [comment]
This is absolutely amazing!

> New style (looks a bit more regular)

That's a gross understatement ;-)

Let me know if you need help making it work in a Worker.

In terms of integrating it I would suggest to add another type "av" and in `MolecularSurface.getSurface` use `AVSurface` when `params.type` is "av".

If we can make AVSurface a bit faster it should replace EDTSurface.

**Comment by fredludlow** [comment]
Thanks! Though most of the credit should go to Mike for coming up with the method and you for having a such an easy to extend codebase! 

I'll see if I can get it going in a worker and do as you suggest with the "av" type etc. Any worker-specific gotchas I need to look out for? (I was just going to copy the way EDTSuface does it)

I dropped the number of torroidal samples to 20 and I actually get comparable speed between EDT and AV on chrome and IE on my windows box, you can also reduce the scaleFactor to about 1.5-1.6 in AV mode and it still looks okay. However, the difference on Chrome running on Android is still big - EDT seems to win by a factor of 2.5. I don't really understand this.

**Comment by fredludlow** [comment]
Got the web-worker bit working (fredludlow/ngl@bdbe601), though it's a bit of an ugly cludge (I define a method which sets up the prototype object for AVSurface and call it in the worker...).

Some other stuff:

* It currently uses prototype methods rather than one big closure (the way EDTSurface is implemented) - not sure if there's scope for some free performance improvement with a bit of a refactor?

* The profiler shows most of the time is spent in projectTorus - I wonder if there's a more efficient way of doing this (it currently visits all grid points in a small cube around each of 30 torus sample points - a lot of those points will be visited multiple times, there might be a cleverer way to do this - even halving the number of points visited might speed the whole surface generation up by a third or so).

* Haven't quite figured out how to get the atom indexes mapped properly yet so you can colour by element/bfactor etc

**Comment by arose** [comment]
> It currently uses prototype methods rather than one big closure (the way EDTSurface is implemented) - not sure if there's scope for some free performance improvement with a bit of a refactor?

I suggest to put it into one big closure. There won't be many instances and that way you can get rid of a lot of `this` uses.

> The profiler shows most of the time is spent in projectTorus - I wonder if there's a more efficient way of doing this (it currently visits all grid points in a small cube around each of 30 torus sample points - a lot of those points will be visited multiple times, there might be a cleverer way to do this - even halving the number of points visited might speed the whole surface generation up by a third or so).

If there are points visited multiple times, can some (intermediary) results be cached?

> Haven't quite figured out how to get the atom indexes mapped properly yet so you can colour by element/bfactor etc

You are setting it here https://github.com/fredludlow/ngl/blob/bdbe601d7780375ac8225b591c29a6c0a95b2af5/src/surface/av-surface.js#L283 and here https://github.com/fredludlow/ngl/blob/bdbe601d7780375ac8225b591c29a6c0a95b2af5/src/surface/av-surface.js#L402. Any idea why this does not work?

Other ideas
- make torus sample points resolution dependent, more samples for finer grids (or are you doing this already?)
- reuse Float32Array https://github.com/fredludlow/ngl/blob/bdbe601d7780375ac8225b591c29a6c0a95b2af5/src/surface/av-surface.js#L330 and https://github.com/fredludlow/ngl/blob/bdbe601d7780375ac8225b591c29a6c0a95b2af5/src/surface/av-surface.js#L338

**Comment by fredludlow** [comment]
> I suggest to put it into one big closure. There won't be many instances and that way you can get rid of a lot of this uses.

Yup - I'd been reading lots of conflicting views on relative performance of attribute lookups vs scope-chain lookups and figured I'd just go with what was easiest to translate from Java first. I'll refactor into a closure (with no other changes initially) and see if/how performance changes (it'll certainly make setting up the worker a bit cleaner)

> * make torus sample points resolution dependent, more samples for finer grids (or are you doing this already?)

Not doing it at the moment but it's a good idea

> * reuse Float32Array

Yes, looks like an easy win

> If there are points visited multiple times, can some (intermediary) results be cached?

I don't think so in the current method (iterating over atoms -> torii -> grid points around each torus point)
However, I think the algorithm is equivalent to: For each point on the grid:
- If it's inside a single expanded atom radius, calculate distance to surface
- If it's inside exactly 2 atom radii - calculate distance to relevant intersection of those two atoms
- If it's inside more than 2 atom radii, give it some big positive value (it's not going to have any effect on the final surface)

Might be worth trying to do it in a single pass of the grid... but will refactor as a closure first and see how that performs before messing around too much with the logic.
