### ISSUE TITLE
Add ball representation similar to VMD's 'VDW' 

### ISSUE THREAD

**Issue by kain88-de** [arose/ngl#208]
I'm currently work with code that models proteins as spheres with a fixed radius.  I can visualize these models in VMD using the *VDW* drawing method. I haven't found anything similar in for nglview. I thought ball+stick could be used but that doesn't allow me to set a defined radius of the balls. Only a value for some *spectRatio*.

**Comment by fredludlow** [comment]
Is the `spacefill` representation with `radiusType: "vdw"` what you're after?

**Comment by kain88-de** [comment]
Spacefil already looks promising. How can I set the radius? There isn't anything in the [docs](https://arose.github.io/ngl/api/tutorial-molecular-representations.html)

As a reference for 1E8L I get the following in VMD with selecting 'name CA', as a drawing method VWD and as spherescale 4.2 (thats the bead radius in Angström).

![vmdscene](https://cloud.githubusercontent.com/assets/4302678/18880020/c548ae8c-84d6-11e6-98b9-b9b41fe53b7d.jpg)

**Comment by kain88-de** [comment]
OK I found that I can do 'radiustype=size' and then set the radius to the value I like.

**Comment by arose** [comment]
There are a scale and a radius parameter that work for most structure representations, see https://arose.github.io/ngl/api/global.html#StructureRepresentationParameters

The doc on `radiusTyoe` is a bit unclear, possible values are `size`, `vdw`, `sstruc`, `covalent`, and `bfactor`.

```
comp.addRepresentation( "spacefill", { radius: 4.6 } )  // will set radiusType to "size"
```

**Comment by arose** [comment]
You beat me :-)

**Comment by hainm** [comment]
@kain88-de  you meant using `radiustype=size` in nglview? This is weird. (should be `radius_type` or `radiusType`)

**Comment by kain88-de** [comment]
I meant radius**T**ype. I just missed the capital letter when writing

**Comment by kain88-de** [comment]
@arose the size parameter has Angström as units?

**Comment by arose** [comment]
> the radius parameter has Angström as units?

yes
