### ISSUE TITLE
v0.9.0-dev.3 vs v0.9.0-dev.4 and later version?

### ISSUE THREAD

**Issue by hainm** [arose/ngl#215]
Hi,

I can not make >= v0.9.0-dev.4 to work with nglview (got known (and non-useful) message "Widget Javascript not detected").
Console did not show any useful message either:  `promiseRejection`

works fine with `v0.9.0-dev.3`

Any idea why?

**Comment by arose** [comment]
does v0.9.1 also not work?

**Comment by hainm** [comment]
Nope

**Comment by arose** [comment]
hmm, I guess require.js doesn't like to prepended polyfills :-( give me a moment

**Comment by arose** [comment]
can you try 0.9.2-dev.1

**Comment by hainm** [comment]
work for me now. thanks.

**Comment by arose** [comment]
cool, thanks for the quick testing

**Comment by hainm** [comment]
FYI: I add more info about updating `ngl.js` for `nglview`  https://github.com/arose/nglview/blob/master/DEVELOPMENT.md#update-javascript-build

**Comment by arose** [comment]
> FYI: I add more info about updating ngl.js for nglview

great!

**Comment by arose** [comment]
released v0.9.2
