### ISSUE TITLE
non deterministic orientation

### ISSUE THREAD

**Issue by hainm** [arose/ngl#216]
Hi

I always got different `orientation` array between different `ngl` versions. Is it intention? if yes, then why? I ask because I have to update `nglview` notebooks several times for setting `orientation`.

**Comment by arose** [comment]
I suppose you get the orientation with `defaultRepresentation: true`. There are multiple ways the `orientation` array can change:

- the way the tight zoom is calculated
- the exact extend of the rendered geometries
- the default representation composition

How much does it change?

**Comment by hainm** [comment]
> I suppose you get the orientation with defaultRepresentation: true

yeah.

> How much does it change?

I only tested this 1-2 month ago: a lot, sometimes the render disappears (out of current view), but this significantly change might due to #189 

I close this issue since it's not fixable (right? ).
