### ISSUE TITLE
Doc issue: signals example is incorrect

### ISSUE THREAD

**Issue by iangilman** [arose/ngl#218]
On http://arose.github.io/ngl/api/Stage.html#event:clicked it gives this example:

```
stage.signals.clicked( function( pickingData ){ ... } );
```

...which doesn't work. It should be:

```
stage.signals.clicked.add( function( pickingData ){ ... } );
```

...instead. Applies to all of the event examples, it looks like.

**Comment by arose** [comment]
good find, fixed in d8e9720e154d09eed1f79aaa8921c09cc66d6f58

**Comment by iangilman** [comment]
Awesome. Thank you for the quick response, and the great library! :-)

**Comment by arose** [comment]
you're welcome
