### ISSUE TITLE
[question] How to color specific atoms?

### ISSUE THREAD

**Issue by iangilman** [arose/ngl#220]
I hope this is an okay place to ask questions... if not, please point me in the right direction!

I want to use one of the built in color schemes, but for a couple of special atoms I want them to be white (or whatever). I'm wondering what the best way to do this is. So far this is what I've come up with:

```
schemeId = NGL.ColorMakerRegistry.addScheme(function(params) {
  params.scheme = 'residueindex';
  var residueindexScheme = NGL.ColorMakerRegistry.getScheme(params);

  this.atomColor = function(atom){
    if (isSpecial(atom)) {
      return 0xffffff;
    }

    return residueindexScheme.atomColor(atom);
  };
});
```

It seems to work, but I just want to make sure this is the preferred technique. Thank you!

**Comment by arose** [comment]
Ha, that is very clever, to reuse the existing schemes! I haven't thought of doing it in such a way but it is perfectly fine.

PS: Questions are fine here.

**Comment by iangilman** [comment]
Awesome, thanks! I may be back with more... :)
