### ISSUE TITLE
regex problem for search of name including a "+" in scripting

### ISSUE THREAD

**Issue by j0kaso** [arose/ngl#226]
For this script.ngl example, the file can not be found because of the "+" (renaming of the file solve the problem).
```
Promise.all( [
    stage.loadFile( "data://1crn+1.gro", {
        firstModelOnly: true
    } ).then( function( o ){
        o.addRepresentation( "cartoon" );
        o.centerView();
        o.setName("1crn+1");
    } )
] ).then( function(){
    console.log(stage.getComponentsByName("1crn+1").list[0])
} );
```

**Comment by arose** [comment]
thanks for reporting!

now accept regexp or string in stage.get*ByName methods, don't assume it is a regex string, see 22d548ef65e4e1e7b10de0408417817973f9a4d7

**Comment by arose** [comment]
@j0kaso ok for you?

**Comment by arose** [comment]
ping @j0kaso

**Comment by j0kaso** [comment]
works perfectly fine! thx @arose
