### ISSUE TITLE
Cube volume shifted?

### ISSUE THREAD

**Issue by AJK-dev** [arose/ngl#227]
When loading a benzene SDF and the corresponding cube file, the resulting surfaces/fields are shifted with respect to the benzene ring. To test this I used example files from the 3Dmol website ([SDF](http://3dmol.csb.pitt.edu/tests/test_structs/benzene.sdf) and [Cube](http://3dmol.csb.pitt.edu/tests/test_structs/benzene-homo.cube)).

Viewed in e.g. Chimera:
<img width="600" alt="chimera_orbitals_benzene" src="https://cloud.githubusercontent.com/assets/15200114/19887981/1c643388-a02c-11e6-8888-c30f96c95140.png">

Viewed in NGL (surface based on value cutoffs -0.01 and 0.01):
<img width="600" alt="ngl_orbitals_benzene png" src="https://cloud.githubusercontent.com/assets/15200114/19887987/2514ef5e-a02c-11e6-8681-412b1994cadf.png">

In the NGL viewer the atoms are shifted downwards (from this perspective) into the bottom fields, where the centre of the atoms should be aligned in the middel between the top and bottom fields.

PS Thank you for your great efforts in developing the NGL viewer!

**Comment by arose** [comment]
Thanks for reporting. There was an error in the cube parser when a line with orbital data is included. Fixed in 52da06247efb15f99d467479df44a700f9336b92

![screenshot 36](https://cloud.githubusercontent.com/assets/272250/19909187/b32f38d2-a043-11e6-9b4b-08a250cca61c.png)

**Comment by AJK-dev** [comment]
Thanks for the quick fix, it works like a charm.
This will definitely help during lectures: making orbitals a bit more insightful/fun in 3D!

**Comment by arose** [comment]
Great to hear it works for you!
