### ISSUE TITLE
missing note for autoLoad of dcd file

### ISSUE THREAD

**Issue by j0kaso** [arose/ngl#228]
no error message in the panel for .dcd files when loaded by stage.autoLoad as for others, e.g. .xtc --> "autoLoad: ext 'xtc' unknown"

**Comment by arose** [comment]
done, see 7063ec947b5c72a7629a510904ef3997badaa33a

**Comment by arose** [comment]
@j0kaso please test

**Comment by j0kaso** [comment]
still no error in the panel but running symbol and error: "ngl.js:25
Uncaught (in promise) TypeError: Cannot read property 'type' of undefined "
for dev10.4 build/ngl.js, dev10.4 dist/ngl.js, master build/ngl.js, master
dist/ngl.js

2016-11-23 0:51 GMT+01:00 Alexander Rose <notifications@github.com>:

**Comment by j0kaso** [comment]
shows now Error (thx) but maybe better if it shows that autoLoad is not possible (generally, the dcd format is know and loadable)

**Comment by arose** [comment]
You mean a GUI warning when trying `stage.loadFile("some.dcd")`? That is not easily doable and I would argue that a user that scripts like this should know what he/she is doing.

**Comment by j0kaso** [comment]
No, I just mean a renaming of the error. right now it says "loadFile: ext 'dcd' can't be loaded" but in general it is loadable but not via autoLoad, therefore an error like "autoLoad: ext 'xtc' unknown" (like for xtc) or similar would be more suitable

**Comment by arose** [comment]
what about "loadFile: ext 'dcd' must be loaded into a structure component"

**Comment by j0kaso** [comment]
even better! would also be great for the others (xtc...)

**Comment by arose** [comment]
no, there is no xtc support in core ngl and the above is already a poor workaround

**Comment by j0kaso** [comment]
of course - you're right!

**Comment by arose** [comment]
done d6081a628728c1c7d9344ee3eab312edea2e354c
