### ISSUE TITLE
Mouse wheel zoom issue in IE

### ISSUE THREAD

**Issue by harryjubb** [arose/ngl#233]
Using NGL 0.10.0-dev.3 on IE 11.0.96

Zooming with the scroll wheel zooms out far, and prevents zooming back in with the scroll wheel.

Zooming in and out by holding down the middle mouse button and dragging up/down still works.

Works correctly in Chrome on Mac.

**Comment by arose** [comment]
@harryjubb can you confirm that #233 fixes it?

**Comment by harryjubb** [comment]
@arose I haven't checked yet as I've been using the NPM build and not pulling in the latest dev builds, but @fredludlow demonstrated his fix in IE. I'll update and confirm
