### ISSUE TITLE
change standard step size and play timeout for scripting of trajectories

### ISSUE THREAD

**Issue by j0kaso** [arose/ngl#238]
not possible to change the "step size" or "play timeout" as e.g. centerPbc, selection or starting step.

e.g.: (not working)
var trajComp2b = comp.addTrajectory( "protein.xtc", trajSele, 0, 150, 50 );
trajComp2b.setParameters( { centerPbc: false, removePbc: false, superpose: false } );
with starting step = 0 (working), step size = 150 (not working) and play timeout = 50 (not working)

**Comment by arose** [comment]
Hi @j0kaso please have a look at 37ccc13c76422c6809e2be3bb1c60fdeac4332a6, also release as ngl@0.10.0-dev.5

It breaks a few things, so watch out, but adds new params and streamlines how trajectory params are handled. Mainly, `.addTrajectory` now takes a param object as second argument.

```javascript
NGL.autoLoad( "data://md_1u19.dcd.gz" ).then( function( frames ){
    var trajComp = o.addTrajectory( frames, {
        initialFrame: 100,
        defaultTimeout: 500,
        defaultStep: undefined,
        centerPbc: false,
        removePbc: false,
        superpose: true,
        sele: "backbone and not hydrogen"
    } );
    trajComp.trajectory.player.play();  // player from gui can be accessed that way
} );
```

**Comment by j0kaso** [comment]
Great work! I like that it is similar to the representation parameters. So far I did not run into any problems. Are there also options for the "interpolation type", "interpolation steps", "play direction" and "play mode"?

**Comment by arose** [comment]
added more default parameters to TrajectoryComponent, added parameter object to TrajectoryPlayer (breaks code that uses the trajectory player directly), see 6221ae11c4987ea28e0a563956f11cda24ecd6a3

```
 * @property {String} defaultInterpolateType - one of "" (empty string), "linear" or "spline"
 * @property {Integer} defaultInterpolateStep - window size used for interpolation
 * @property {String} defaultMode - either "loop" or "once"
 * @property {String} defaultDirection - either "forward" or "backward"
```

**Comment by j0kaso** [comment]
Thx great!!! Is the renaming of the trajectory also possible?

**Comment by arose** [comment]
> Is the renaming of the trajectory also possible?

fixed some things, see 3666ac4fb199d16cfb03cf737a9db82e9710da8e

you can use `component.setName()` or via `name` in the initial parameter object

**Comment by j0kaso** [comment]
Cool I'll test it and will give you feedback!

**Comment by arose** [comment]
ping @j0kaso

**Comment by j0kaso** [comment]
everything works except for 
`defaultInterpolateType: "linear/spline"`
it seems that it has to visit all frames with "none" before one of the others can be used. If the "defaultInterpolateType" is set in a script to "linear" or "spline", an error occurs:
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at Is.La.interpolate (ngl.js:22)
    at Is.<anonymous> (ngl.js:22)
    at Is.<anonymous> (ngl.js:22)
    at i (ngl.js:7)
    at ngl.js:7
La.interpolate @ ngl.js:22
(anonymous) @ ngl.js:22
(anonymous) @ ngl.js:22
i @ ngl.js:7
(anonymous) @ ngl.js:7
ngl.js:6 rendered still frame
```

**Comment by arose** [comment]
@j0kaso can you please make a new issue for the error regarding interpolation, thanks
