### ISSUE TITLE
Atom serial number set to 1 for very large files

### ISSUE THREAD

**Issue by j0kaso** [arose/ngl#241]
For very large files, the atom serial number is set to 1 if the number is greater than 99999 +1 = 186a0 +1 = 186a1. Would it be possible to have in this case just the string? Example from MD simulation attached.

[A2A_C.pdb.zip](https://github.com/arose/ngl/files/630619/A2A_C.pdb.zip)

**Comment by arose** [comment]
lol, those are hexadecimal atom ids, very non standard. A new feature for the PDB parser.

```
ATOM  1a97b  O   LEU P  93       1.850  11.633  -6.758  0.00  0.00      P1    
```

**Comment by arose** [comment]
Added a `hex` parameter to the PdbParser, see e12d64bfa72afd9db4ee69937330a1eab915d419

```
     * @param  {Boolean} params.hex - hexadecimal parsing of
     *                                atom numbers >99.999 and
     *                                residue numbers >9.999
```

There is no reliable way to detect this automatically, so specify when loading a file `stage.loadFIle( "hex.pdb", { hex: true } )`.

**Comment by arose** [comment]
@j0kaso does the new parameter work for you? Do you need something else?

**Comment by j0kaso** [comment]
thanks! could you also add this to the GroParser?

**Comment by arose** [comment]
which software dow output gro files like that?

**Comment by j0kaso** [comment]
right, standard output doesn't do it. writing would be different but not an issue in ngl - sry and thx!
