### ISSUE TITLE
structure clone method to get duplicates

### ISSUE THREAD

**Issue by j0kaso** [arose/ngl#243]
Could a Structure.clone() method to get duplicates of loaded structures be added again like it was in a previous ngl version?

**Comment by arose** [comment]
Your use case is displaying multiple coordinate frames at the same time, right?

**Comment by arose** [comment]
see #231

**Comment by j0kaso** [comment]
I intended to just make a copy of a loaded structure file (no frame, still it's a nice idea) like the duplicate function in a previous version.

**Comment by arose** [comment]
What about just loading the file again? Should be cached by the browser.

**Comment by j0kaso** [comment]
I run into this case when I was working with a ngl "session" on another pc. Of cause I could download and then upload the file again - it's just very unhandy and I was wondering why this function had been removed.

**Comment by arose** [comment]
But this only makes sense in the context of a trajectory, otherwise it can be handled by extra representations.

Adding a `Structure.clone()` is not trivial, especially when considering maintainability.

My idea to avoid it would be to have a (optional) representation parameter setting the frame to display. But that is not trivial either...

**Comment by j0kaso** [comment]
I was using it to manipulate the superposition function  - I wanted to superpose only a certain part but when I remove this from the structure selection, the superpositioning is undone, therefore I cutted this into parts and then superposed the single parts to get a complete more suitable superposition. Maybe an issue with a more selective superpositioning would be more suitable?

**Comment by arose** [comment]
> Maybe an issue with a more selective superpositioning would be more suitable?

yes, it is mainly a problem with lacking GUI, the underlaying code probably supports what you want

**Comment by arose** [comment]
Helper method `NGL.concatStructures` available, see https://codepen.io/arose/pen/VQjBGq?&editors=001
