### ISSUE TITLE
comp.removeRepresentation(repr) not working

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#244]
The **removeRepresentation()** method doesn't seem to work as expected : it removes representations from the component representation list but the representation is still displayed on the stage. The **clearRepresentations()** method on the contrary does remove the representations from the display.

Test in NGL v 0.10.0 dev5:
`repr = stage.compList[0].addRepresentation('ribbon')
stage.compList[0].clearRepresentations() //everything is cleared as expected

repr = stage.compList[0].addRepresentation('ribbon')
stage.compList[0].removeRepresentation(repr) //the representation is still on screen
stage.compList[0].eachRepresentation(i=>{ console.log(i) }) //no representation logged`

**Comment by arose** [comment]
Thanks, that was unclear indeed. Previously `removeRepresentation()` would not dispose the representation but with b85a46f265d69cd2539949fd9449aa6e191f2839 it does.

**Comment by ppillot** [comment]
Thanks Alex, it now works beautifully!
