### ISSUE TITLE
Add defined shapes like an arrow.

### ISSUE THREAD

**Issue by kain88-de** [arose/ngl#245]
I want to visualize different principal axes of a protein, I calculated them using two different methods and now want to show the difference between them. My idea for this was to directly draw two arrows (one for each main principal axes for both methods) on to the protein. The effect should be similar to centering the reference xyz axes (as eg in VMD). 

How could I do that with ngl, or better nglview? I haven't found any primitive shapes in the docs.

**Comment by arose** [comment]
Have a look at the `Shape` class http://arose.github.io/ngl/api/Shape.html

Also, there is basic support to show principal axes for any selection with the `axes` representation. Still undocumented but see http://arose.github.io/ngl/?example=axes.

**Comment by hainm** [comment]
per `nglview`, you can use

```bash
view.shape.add_arrow([NGL parameters])
```

![shape](https://cloud.githubusercontent.com/assets/4451957/21770394/1038d1e4-d651-11e6-9864-1a48bd34e69f.png)

**Comment by kain88-de** [comment]
Nice this works really well. Is there also a way to specify the color using HEX strings?

**Comment by khoroshyy** [comment]
Nice. How do I remove arrow?
