### ISSUE TITLE
Export key event state on pick/select

### ISSUE THREAD

**Issue by martingraham** [arose/ngl#246]
Hi Alex, another edge case here for you :-) Basically when I select something on screen, I'd like to also receive the key press state in the associated signals.js event pickingData parameter

At the moment I've done a hack on my own version to get the ctrlKey state:

At https://github.com/arose/ngl/blob/master/src/stage/picking-controls.js#L160

I stick in the line 
`pd.ctrlKey = e.ctrlKey;`
just before pd is dispatched to the signals.clicked event

I'm wondering if there's a better or more general way to do it?

**Comment by arose** [comment]
What about listening to keypresses globally and put the currently pressed key into you application state?

**Comment by martingraham** [comment]
That could work yeah. A key down and up listener on my view that stores the current keystate for the view, and then I/we don't need to change ngl code.

**Comment by arose** [comment]
Hey, decided to add alt/ctrl/meta/shiftKey to pickingData object, see ceede4ca4dd2d3dfc51ea9eb330aac6db421ca4f

**Comment by martingraham** [comment]
Thanks Alex
