### ISSUE TITLE
Getting chain colours 

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#247]
Is there a way to get the colours used by NGL in a representation, for example when the colour scheme is based upon the chain name.
I guess it's possible to access it by creating a new NGL.ColorMakerRegistry and passing the structure as a parameter ? How can it be done ?

**Comment by ppillot** [comment]
Nevermind, I've found out how to do it : 
provided *structure* is the structure object,
```javascript
var colorMap = new Map()
var chainNameScheme = NGL.ColorMakerRegistry.gestScheme( {scheme: 'chainname', structure: structure})

structure.eachChain( chain => {
  colorMap.set( chain.chainname,
    chainNameScheme(structure.getAtomProxy(chain.atomOffset)).toString(16)
})

console.log(colorMap)
```

**Comment by arose** [comment]
looks good :-)

**Comment by arose** [comment]
I will also take this as a feature request. It should not be that hard.
