### ISSUE TITLE
any trick to add more atoms without rerendering?

### ISSUE THREAD

**Issue by hainm** [arose/ngl#248]
hey man,

I am working on [pdb4amber](https://github.com/Amber-MD/pdb4amber), a program doing a bunch of stuff (e.g: add missing atoms).

I added `nglview` support for `pdb4amber` and want to see atoms added in the same view.
Any trick for doing this without re-rendering? (which I try to avoid screen flashing).

example
```python
fixer = AmberPDBFixer(...)
view = fixer.visualize()
# display view in notebook
view
```

then
```python
fixer.add_missing_atoms(...)
# I would like to see the `view` updated.
```

**Comment by arose** [comment]
If you want to the atoms to an existing structure then I am afraid, no. The structure class is immutable with respect to the topology, only the atom positions can be changed.

**Comment by hainm** [comment]
I just add `replaceStructure` for `nglview` to do the trick while waiting for NGL's feature :D (if happens).

Not very eye pleasing but I think it's good to play with (for now)

![add_h](https://cloud.githubusercontent.com/assets/4451957/22360891/61e7b238-e422-11e6-95b0-e3df7f2a0a2b.gif)

**Comment by arose** [comment]
@hainm one workaround would be to draw the second structure before removing the first one

**Comment by hainm** [comment]
Can you make cod example?

**Comment by hainm** [comment]
Do you mean add 2nd structure first and then remove the 1st?

**Comment by arose** [comment]
> Do you mean add 2nd structure first and then remove the 1st?

yes, so they are drawn on top of each other and if the 2nd structure only adds atoms it should look good :)

**Comment by hainm** [comment]
Great trick. Thx.

**Comment by hainm** [comment]
work fantastic. I knew you were the right person to ask. :D
