### ISSUE TITLE
zoom in/out

### ISSUE THREAD

**Issue by hainm** [arose/ngl#25]
Hi

Does ngl support zoom?

**Comment by hainm** [comment]
I think you just accidentally turned off?

**Comment by arose** [comment]
You mean a method to call? There is

```javascript
stage.viewer.centerView( zoom, position )
```

where `zoom` can be `true` for automatic zooming (tries to fill the screen) or a number and `position` is a `THREE.Vector3` object in "model space".

**Comment by arose** [comment]
> I think you just accidentally turned off?

With the latest commits? Hmm, works for me.

**Comment by hainm** [comment]
sorry not to be clear. I can not use mouse wheel to zoom in http://arose.github.io/ngl/

(and with jupyter notebook too)

**Comment by arose** [comment]
Strange, it works for me on Ubuntu with Chrome 46 and Firefox 42 and 43.

**Comment by hainm** [comment]
I can zoom in/out with 'pv': https://biasmv.github.io/pv/demo.html with my chrome (Version 27.0.1453.110).

**Comment by arose** [comment]
Are there any messages in the browser console? I assume it did it work before, or not?

**Comment by hainm** [comment]
> Are there any messages in the browser console?

Nope

> I assume it did it work before, or not?

**Comment by hainm** [comment]
I am not sure what happens (or what you did), but I am able too use zoom in/out now.

**Comment by hainm** [comment]
@arose can you double-check the difference between ngl and nglview for ngl.js file? 

I can zoom in/out by mouse wheel in http://arose.github.io/ngl/

but can not do that in jupyter notebook: I need to press middle button and move mouse forward/backward to zoom.

**Comment by hainm** [comment]
never mind, perhaps because of my old Chrome in linux. Works fine when tunneling from linux to be used in my windows.
