### ISSUE TITLE
File load error is not reported

### ISSUE THREAD

**Issue by vvv444** [arose/ngl#254]
**Reproduction scenario**
Name some wrong formatted file with ".mmtf.gz" extension and try to load it.

**Expected behaviour**
NGL.Stage.loadFile() shall raise as exception.

**Actual behaviour**
No exception is thrown. Moreover, there is a non-decremented task left.

**Details**
An exception is raised from MmtfParser._parse(), but this function is called in context originating from 'load' event of XMLHttpRequest() in NetworkStreamer._read() which lacks exception handling.

**Comment by arose** [comment]
thanks!
