### ISSUE TITLE
CSV autoLoad shows error on Firefox

### ISSUE THREAD

**Issue by vvv444** [arose/ngl#255]
**Reproduction**
Use autoLoad for some CSV file: `NGL.autoLoad(myCsvUrl, { ext: 'csv' })`

**Problem**
On Firefox the log in developer console shows the following error:
> XML Parsing Error: syntax error Location: ...

Although this does not present any actual problem, it is still annoying.
This happens because if no responseType is specified for the XMLHttpRequest object, Firefox automatically assumes it is XML and attempts to parse it internally.

**Comment by vvv444** [comment]
Related info: http://stackoverflow.com/questions/14399648/reading-text-file-trough-xmlhttprequest-produces-syntax-error-in-text-file-work

**Comment by arose** [comment]
thanks, great find!
