### ISSUE TITLE
hydrophobicity colour scheme not visible in ColormakerRegistry

### ISSUE THREAD

**Issue by martingraham** [arose/ngl#258]
Looks like its scheme type has been set to "modelindex" by mistake, so its entry then gets overridden by the proper modelindex scheme?

https://github.com/arose/ngl/blob/master/src/color/hydrophobicity-colormaker.js#L63

**Comment by arose** [comment]
yeah, my bad

**Comment by arose** [comment]
fixed, see 15f939bad46f6cafe64f5ba484a5a37af88e8f0a

**Comment by arose** [comment]
thanks @martingraham
