### ISSUE TITLE
wishlist: option for zoom, speed, ...

### ISSUE THREAD

**Issue by hainm** [arose/ngl#26]
I am myself using VMD for visualization and there are few things I want to customize in in `ngl`

- camera: orthographic or perspective (I normally use orthographic camera)

- zoom and rotation speed: Most of viewing packages make me feel the molecule is very heavy when rotating. It's great if `ngl` allows user to config (right now I need to change js file)

**Comment by arose** [comment]
I am working on exposing zoom and rotation speed. Would you mind creating a separate issue for the orthographic camera as it requires some more work?

**Comment by hainm** [comment]
okie.

**Comment by arose** [comment]
41afbe21175fc891251f3a0456b1fc9eacec10ec exposes zoom/rotation/pan speed in the GUI via `Help > Preferences`. I am still streamlining parameter handling for the `stage` object to allow programmatic access.

Note that preferences are saved locally.

**Comment by arose** [comment]
Reworked `stage` parameter handling some more. The clip/fog parameters are now also exposed. See http://arose.github.io/ngl/ `Help > Preferences`. There is some documenting work to be done... very shortly:

The `NGL.Stage` constructor now accepts a parameter object

```JavaScript
var stage = new NGL.Stage( "someElementId", {
  rotateSpeed: 4.0,
  fogNear: 100,
  overwritePreferences: true  // otherwise the user preferences take precedence
} );
```

The `stage.preferences` object holds user preferences which are stored via `localStorage`. Call `stage.setParameters( { rotateSpeed: 2.0 } )` to change them after object construction.

**Comment by hainm** [comment]
just tried. Cool.
