### ISSUE TITLE
Is it possible to mix color schemes on the same representation ?

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#260]
I would like to colour part of a representation (say for example 'cartoon') with a given plain colour and an other part with a color scheme (for example chainname).
I have tried with NGL.ColormakerRegistry.addSelectionScheme(), but the color scheme names are ignored.
Is this feasible ?
If not, should I then create a separate representation for each colour scheme ?

**Comment by arose** [comment]
Would you be interested to implement it yourself?

**Comment by ppillot** [comment]
I could give it a try ! Any idea about where I should start from ?

**Comment by arose** [comment]
I just refactored it a bit and moved all the code for the selection colormaker into its own file, `src/color/selection-colormaker.js`, see 5ee7492f969d17721762bb8d3895b4ecf633a845.

You can extend the constructor in there to create instances of all the sub-colormakers you need as provided in the pairlIst. You also need to `import { ColormakerRegistry } from "./globals.js";` to get the sub-colormakers.

HTH can give more pointers later

**Comment by ppillot** [comment]
I've made some progress! I've changed the selection-colormaker.js so that it could detect when schemes are set in the pairlist. The color makers that simply rely on atom proxy properties behave as expected (element, resname, hydophobicity). I get errors when the color makers rely on the structure property to set a scale beforehand (eg: chainname, atomindex,...). They throw an error stating that the expected property/method (e.g. `eachModel()`) from this.structure could not be find in `undefined`
My concern is that NGL.ColormakerRegistry.addSelectionScheme() is called independently from a structure, that is the scheme doesn't contain any reference to a given structure. Do you think that some other code should be refactored such as the `setColor()` method from representation ?

```javascript
class SelectionColormaker extends Colormaker{

    constructor( params ){

        super( params );

        this.pairList = params.pairList || [];

        this.colorList = [];
        this.selectionList = [];
        
        this.schemesList = ColormakerRegistry.getSchemes();

        this.pairList.forEach( pair => {
            if ( this.schemesList.hasOwnProperty( pair[ 0 ] ) ) {
                this.colorList.push( ColormakerRegistry.getScheme( { scheme: this.schemesList[ pair[ 0 ] ], value: 0x909090 } ) );
            } else {
                this.colorList.push( ColormakerRegistry.getScheme( { scheme: 'uniform', value: new Color( pair[ 0 ] ).getHex() } ) );
            }
            
            this.selectionList.push( new Selection( pair[ 1 ] ) );
        } );

    }

    atomColor( a ){
        
        this.structure = a.structure;

        for( var i = 0, n = this.pairList.length; i < n; ++i ){
            if( this.selectionList[ i ].test( a ) ){
                return this.colorList[ i ].atomColor( a );
            }
        }
        return 0xFFFFFF;
    }

}```

**Comment by arose** [comment]
Cool, looking good. There is a `this.structure` available, you should pass that when getting the sub-schemes

```javascript
var subSchemeParams = {
    structure: this.structure,
    scheme: this.schemesList[ pair[ 0 ] ],
    value: 0x909090
};
ColormakerRegistry.getScheme( subSchemeParams );
```

Also, it would be good to have a parameter object to pass in each `pairList` entry that creates a sub-scheme.

**Comment by ppillot** [comment]
Thanks! It now works as expected. I've added the ability to pass a parameter object as well ans made a pull request #268

**Comment by arose** [comment]
PR accepted :) thanks @ppillot
