### ISSUE TITLE
Orthographic zoom broken

### ISSUE THREAD

**Issue by fredludlow** [arose/ngl#261]
Zooming in orthographic mode seems to be broken by 0afba24. The previous zooming code detected orthographic mode by checking `camera.fov === undefined`
https://github.com/arose/ngl/blob/ad550c7abdfda7da9a37b223512d976cf8dd7b6a/src/controls/trackball-controls.js#L237

I've got a patch with a simple fix, though there may be a cleaner way, will send a PR

**Comment by fredludlow** [comment]
Relatedly, and not so much a bug as a personal preference: In orthographic mode, translation moves the view a different amount depending on the zoom level. Would it be possible for translation to move 1:n (preferably 1:1!) with the mouse pointer at any zoom level in orthographic mode? (i.e. if my pointer is over a carbon and I right-click and drag the carbon should stay under the pointer).

**Comment by fredludlow** [comment]
Sorry, engage brain - I guess the sums work the other way round actually: in my ideal world, screen pixels are scaled to Angstroms and the camera moved the appropriate number of pixels. I had a quick play but couldn't figure out how to go from screen units to viewer units

**Comment by arose** [comment]
> if my pointer is over a carbon and I right-click and drag the carbon should stay under the pointer

that would be nice indeed

**Comment by arose** [comment]
The orthographic zooming should be fine now. Could you please make a new issue for the sync of scene translation and mouse movement
