### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#263]
Hi Alexander,
I am trying to deploy my website using NGL on netlify and the build process fails as my package.json refers to NGL's version from NPM, which predates the Colormaker breaking change name.
Thanks for your help,
Paul

**Comment by ppillot** [comment]
Well, I've found a way to solve this issue by linking directly to git://github.com/arose/ngl.git in package.json

**Comment by arose** [comment]
There are more recent version published on npm under the tag `next`.
