### ISSUE TITLE
Switch between models

### ISSUE THREAD

**Issue by gbayarri** [arose/ngl#266]
Hi, is it possible to switch models when you load a multimodel pdb? For example, if I load 1GRM it loads all the models overlapped, and I can load it as a trajectory, but in static mode I can't show / hide the different models. I mean, is there a select input with all the possible models to switch between them? Like 'firstModelOnly' parameter, but for all the models.

Thanks.

**Comment by arose** [comment]
You can set a selection on the structure component which will affect all added representations `structureComponent.setSelection("/0")`, or "/1" for model 1 and so on. The same selection can also be given when loading the file `stage.loadFile("structure.cif", {sele: "/0"})`.

**Comment by gbayarri** [comment]
Thank's, that's exactly what I needed.
