### ISSUE TITLE
Drag rotation not working in firefox ( latest git version ) 

### ISSUE THREAD

**Issue by yqshao** [arose/ngl#267]
As said in the title.
The test are done in firefox 51.0.1 on archlinux and firefox 52.0 on windows10.
Server runs python 2.7.12
Steps:
- Clone the latest code and complile by `npm run-script build-min`
- open `python -m SimpleHTTPServer`
- open one of the examples and load a molecule, can do drag rotation in Microsoft Edge, Chromium, but not in firefox

**Comment by arose** [comment]
thanks, fixed in 5cdbed2824e3cdecfd8e1e3306932cac04118222

strange that it worked in Chrome though, there must be a global event object or something?!
