### ISSUE TITLE
wishlist: shortcut key for "Translate" (T) and "Rotate" (R)

### ISSUE THREAD

**Issue by hainm** [arose/ngl#27]
currently ngl uses right mouse button for translating molecule. But using ring finger to push seems requiring more press. What's about adding shorcut key T (same as VMD) to switch to translate mode to be used with index finger? add adding 'R' to go back to Rotation mode.

PS: since I am using VMD and find it very convenient, I will suggest some nice features (I think).

**Comment by arose** [comment]
Sounds useful. I have actually all sorts of request (IRL) to adjust the controls (to mirror all the different viewers).

Currently, NGL uses the standard trackball controls from three.js and I haven't figured out how to bind  actions differently.

> PS: since I am using VMD and find it very convenient, I will suggest some nice features (I think).

Sure, keep them coming. It is good to have a list!

**Comment by hainm** [comment]
@arose do you want me to create an issue with a VMD list so I can keep updating? Or just separate issue for each feauture.

**Comment by arose** [comment]
@hainm Separate issues for each feature please.

**Comment by hainm** [comment]
I prefer to NGL usage now. close.
