### ISSUE TITLE
cartoon representation selection problem with atom list as sele string

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#270]
How to reproduce the bug:
```javascript
stage.loadFile('rcsb://1GZX')
stage.compList[0].addRepresentation('cartoon',
{
   sele: '@0,1,2,4383'
})
```
Expected result: only the atoms provided should be represented (this test case is extreme, nothing should be represented withs as few atoms).
Actual result: the 4 chains extending from the first to the last atom are represented.

When a list of atom is provided for a sele string, cartoon (and other secondary structure displays such as tube) is displayed starting from the first atom of the list and extending to the last.
This is not the case with representations such as spacefill, licorice or ball+stick

**Comment by arose** [comment]
thanks, see it too

**Comment by arose** [comment]
fixed in 726b7ed6efe7fee788e42d1cc53e02815415e7af, please have a look

**Comment by ppillot** [comment]
It works! 
Thank-you Alexander!

I suspect there is another unexpected behaviour related with selections. I am noticing a kind of caching problem where a selection of protein minus chain B comes back when the whole protein is selected (ie : structure.getAtomSet('protein') gives the wrong result, same result as structure.getAtomSet('protein and not :B)). It may be linked to attempt at representing an empty selection previously. I'll try to make a reproducible test case scenario.

**Comment by arose** [comment]
> I suspect there is another unexpected behaviour related with selections. [...] I'll try to make a reproducible test case scenario.

ok, best make another issue when you do. thanks!
