### ISSUE TITLE
Play trajectory without gui

### ISSUE THREAD

**Issue by gbayarri** [arose/ngl#271]
Hi, I'm embedding the NGL viewer in a Bootstrap modal window. When I have a PDB with models as trajectories, I would like to autoplay this PDB. I know how to do that with the gui, but I don't want to load all the libraries needed for the gui in my website because I have some incompatibilities. Besides, I just need this player, not all the features of the gui, because it's just a previsualization. Is there any way to play trajectories without the gui? The code I have:

stage = new NGL.Stage( "viewport" );
stage.loadFile( "structure.pdb", { defaultRepresentation: true, asTrajectory: true } )
    .then( function( o ){
      // here I would need to launch a player (just that)
      // something similar to that, but I could not create just a player: traj.player.play();
    } );

**Comment by arose** [comment]
Hi, please try this:

```javascript
stage.loadFile( "structure.pdb", {
    defaultRepresentation: true, asTrajectory: true
} ).then( function( o ){
    var trajComp = o.addTrajectory();
    trajComp.trajectory.player.play();
} );
```

**Comment by gbayarri** [comment]
Hi, this returns the next error:

`Uncaught (in promise) TypeError: Cannot read property 'play' of undefined`

Finally it seems that creating a player inside the promise resolves it:

```
stage.loadFile( "structure.2.jsmol.pdb", { defaultRepresentation: true, asTrajectory: true } )
    .then( function( o ){
      var traj = o.trajList[0].trajectory;
      var player = new NGL.TrajectoryPlayer( traj, { } );
      traj.setPlayer( player );
      traj.player.play();
      stage.centerView();
    } );
```

Thanks!
