### ISSUE TITLE
Bug with selections and what might be a caching issue with atomsets generated selestrings

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#274]
I've noticed a strange bug related to successive selection operations and maybe the use of seleStrings.
Here is the test case procedure to replicate the bug:
- open page embedded.html in example folder
- paste in the console the following script
```javascript
stage.removeAllComponents()
stage.loadFile('rcsb://1GZX').then((comp) => {

comp = stage.compList[0]
    comp.addRepresentation('ball+stick',
          {
            sele: 'all'
          })
    repr0AS = comp.structure.getAtomSet() //all atoms
    console.log('Whole set size:', repr0AS.size())
    
    as = comp.structure.getAtomSet(new NGL.Selection('protein')) //protein atoms only
    console.log('Protein set size:', as.size())

    sel = comp.structure.getAtomSet(new NGL.Selection(':B')) //chain B atoms only
    
    as.difference(sel) //protein and not chain B
    console.log('Protein and not chain B set size:', as.size())
    
    repr0AS.difference(as) //chain B or not protein

    comp.reprList[0].setSelection(repr0AS.toString())
    console.log('Chain B or not protein set size:', repr0AS.size())
    
    comp.reprList[0].setSelection('protein') //should be protein but is protein and not chain B
    console.log('Protein set size:', comp.structure.getAtomSet(new NGL.Selection('protein')).size())

})
```

The output from the script is : 
```
Whole set size: 4769
Protein set size: 4384 <--
Protein and not chain B set size: 3261
Chain B or not protein set size: 1508
Protein set size: 3261 <--
```
After the script has performed, each command using the `protein` set returns a wrong set (eg: setSelection('protein'), structure.getAtomSet(new NGL.Selection('protein')) )

**Comment by ppillot** [comment]
A further insight: when the string in the line `comp.reprList[0].setSelection(repr0AS.toString())` is replaced by a string such as `:B and not protein`, the correct behaviour is observed.
I've checked also with a reduced selestring such as `@0,1,2,4383` in case it is related to the previous bug with cartoon/tube representations and extrapolation. I've noticed that the expected atomSet size is returned (4), but the representation displays the whole protein...
```
stage.removeAllComponents()
stage.loadFile('rcsb://1GZX').then((comp) => {

comp = stage.compList[0]
    comp.addRepresentation('ball+stick',
          {
            sele: 'all'
          })
    repr0AS = comp.structure.getAtomSet() //all atoms
    console.log('Whole set size:', repr0AS.size())
    
    as = comp.structure.getAtomSet(new NGL.Selection('protein')) //protein atoms only
    console.log('Protein set size:', as.size())

    sel = comp.structure.getAtomSet(new NGL.Selection(':B')) //chain B atoms only
    
    /*as.difference(sel) //protein and not chain B
    console.log('Protein and not chain B set size:', as.size())
    
    repr0AS.difference(as) //chain B or not protein
*/
    sel = comp.structure.getAtomSet(new NGL.Selection('@0,1,2,4383'))
    comp.reprList[0].setSelection(sel.toSeleString())
    console.log('Four atoms encompassing chains A and D:', sel.size())
    
    comp.reprList[0].setSelection('protein') //should be protein but is protein and not chain B
    console.log('Protein set size:', comp.structure.getAtomSet(new NGL.Selection('protein')).size())

})
```

**Comment by ppillot** [comment]
the "bug" is in fact an artifact of the caching mechanism in structure.js

when a selection such as `structure.getAtomSet('protein')` is performed, the atom set returned is also cached in the structure.atomSetCache object under the key "protein".
In my code, I made changes to the returned atomSet `as.difference(sel)` so it also made changes to the "protein" cached atomSet (as javascript transfers objects by reference). When the protein set is queried at the end of the request, it's the altered cached atomSet that is returned.

I can prevent this artifact in my code by using the "clone()" method on atom sets.

To prevent this for future users, I suggest that either the atomSetCache contains only clone() atomSets and queries from it return a clone() or that the structure.getAtomSet() returns a cloned() as object.

**Comment by arose** [comment]
> To prevent this for future users, I suggest that either the atomSetCache contains only clone() atomSets and queries from it return a clone() or that the structure.getAtomSet() returns a cloned() as object.

I see, that is what you did in #279. There are other place where the user is responsible to clone an object when needed for performance reasons. Most of the time when getAtomSet is called, no copy is needed, so providing a clone all the time seems overkill. Maybe documenting is sufficient?

**Comment by ppillot** [comment]
I understand that cloning partly defeats the performance gained in caching. 
From the user perspective as the caching mechanism is transparent and probably unexpected, it introduces a really hard to debug feature.
Documenting might be sufficient. In this case, the question is how this information could be made accessible? The current documentation provides usefull insights into NGL, but for example the Structure.getAtomSet() method is not yet documented. Do you have plans for this? (I understand that you'd rather spend time on NGL features than on documenting them)
Anyway, feel free to remove the aforementioned commit from #279

**Comment by arose** [comment]
> Structure.getAtomSet() method is not yet documented. Do you have plans for this?

I try to document methods that are more user facing and where I think to API is stable enough

**Comment by arose** [comment]
close this, but will keep it in mind for documenting when I consider this as a public API method
