### ISSUE TITLE
wishlist: camera: orthographic or perspective

### ISSUE THREAD

**Issue by hainm** [arose/ngl#28]
option to change the camera type (and can be changed in notebook)

**Comment by arose** [comment]
started working on this in the [orthographic](https://github.com/arose/ngl/tree/orthographic) branch

- [ ] integrate CombinedCamera (perspective & orthographic) including methods to switch
- [ ] fix hyperball impostor (just noise)
- [ ] fix sphere impostor (bounding box too small)
- [ ] integrate OrthographicTrackballControls (also, make feel more similar to TrackballControls)
- [ ] fix multi-sample antialiasing (needs offset for OrthographicCamera)
- [ ] add camera switch to preferences

**Comment by hainm** [comment]
![happy-dance-e1315079523499](https://cloud.githubusercontent.com/assets/4451957/15155982/f2db210a-16b2-11e6-8397-579a4c30710a.jpg)

**Comment by arose** [comment]
ongoing work in PR https://github.com/arose/ngl/pull/115

**Comment by arose** [comment]
merged the PR, testing appreciated

![screenshot 74](https://cloud.githubusercontent.com/assets/272250/15265764/9b95d34e-1942-11e6-93e9-3f5d587b5562.png)

**Comment by hainm** [comment]
can you create a branch in NGLView with updated NGL code for camera? And how to change camera type? I can test it but prefer to use notebook. :D

**Comment by arose** [comment]
`stage.setParameters({cameraType: "orthographic"})`

**Comment by hainm** [comment]
so I did

`cd ngl/build`
`sh make.sh

then copy `js/build/{ngl.js, three.custom.min.js}` to NGLView. Nothing shows up. Open JS console and saw

```bash
[.CommandBufferContext]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
```

**Comment by hainm** [comment]
done. work nicely.
