### ISSUE TITLE
Problem with sphere impostors in the latest build

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#288]
After updating to latest source version, I encountered errors with representations involving sphere impostors
Here is the console log I got from loading the examples/embedded.html page

![capture d ecran 2017-04-01 a 17 30 13](https://cloud.githubusercontent.com/assets/3930632/24582600/44ca26ba-1701-11e7-9668-3e9e92d74273.png)

**Comment by arose** [comment]
yeah, sorry, refactoring a lot and pushed some unstable version. looking to fix later today.

**Comment by ppillot** [comment]
Cool! It's working now
