### ISSUE TITLE
PSF file parsing

### ISSUE THREAD

**Issue by arose** [arose/ngl#29]
See http://www.ks.uiuc.edu/Training/Tutorials/namd/namd-tutorial-unix-html/node23.html for a format description.

Only atom and bond sections.

There is an example file [ala.psf](../tree/dev/data/ala3.psf) in the repository.

**Comment by arose** [comment]
@j0kaso feel free to implement this

**Comment by arose** [comment]
pending PR, see #200

**Comment by j0kaso** [comment]
example attached

[ala3.tar.gz](https://github.com/arose/ngl/files/564091/ala3.tar.gz)

**Comment by arose** [comment]
done
