### ISSUE TITLE
Label issue - v. probably chrome update related

### ISSUE THREAD

**Issue by martingraham** [arose/ngl#290]
This isn't probably even an ngl issue, put might as well add f.y.i.

recently updated my chrome / opera browsers on windows 7 (64-bit) and my labels have started misbehaving. They're ok at the front of the view, but move them slightly out the way and the glyphs start thinning out and then partially disappearing in 'blocks'.

![goodlabel](https://cloud.githubusercontent.com/assets/3490823/24957283/1cb3f8e2-1f83-11e7-934a-8d7d891ec559.png)

![borkedlabel](https://cloud.githubusercontent.com/assets/3490823/24957272/163eb01a-1f83-11e7-813e-15ec7208d02d.png)

I tried searching google chromium issues but there's dozens of labels / webgl/ canvas issues and I dunno which one mine fits into

Graphics card is old - intel q45/q43 express with latest drivers (2011!)

**Comment by martingraham** [comment]
Ah, it seems to go away if I disable "accelerated 2d canvas" in chrome://flags

Not sure whether the new chrome version turned that on by default when it was previously off, or whether it's a genuine new issue they've introduced - but works for me now

**Comment by arose** [comment]
Hmm, haven't seen this myself. Might indeed be some old graphics card issue.

**Comment by arose** [comment]
Thanks for reporting!

**Comment by martingraham** [comment]
I tried it at home with the latest chrome release and it was fine, so looks like it is just a prehistoric graphics card issue. I'll close it but at least the fix is above if anyone else has the same issue.
