### ISSUE TITLE
Feature request/suggestion: Putty/sausage representation

### ISSUE THREAD

**Issue by harryjubb** [arose/ngl#291]
This is a nice rep in PyMOL, where you can vary the radius of a cartoon/tube rep depending on e.g. B-factor: https://pymolwiki.org/index.php/Cartoon#Sausage_Representation

![Putty example](https://pymolwiki.org/images/thumb/4/40/B_factor_putty.png/500px-B_factor_putty.png)

**Comment by arose** [comment]
Like this :)

http://arose.github.io/ngldev/?example=bfactor

```javascript
stage.loadFile( "rcsb://1u19" ).then( function( o ){
    o.addRepresentation( "tube", {
        sele: ":A", radius: "bfactor", scale: 0.010,
        color: "bfactor", colorScale: "RdYlBu"
    } );
} );
```

![screenshot 43](https://cloud.githubusercontent.com/assets/272250/24970292/a3655446-1f68-11e7-9210-bd1ad242e67e.png)

**Comment by harryjubb** [comment]
Amazing!!
