### ISSUE TITLE
Legacy PDB files

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#292]
Hi, I have a database that includes some old pdb files that can't be properly processed to display by NGL (no ribbon representations, in b+s all atoms appear as white and are unknown.
It appears that these files date probably back prior to pdb v2, when lines relevant length was 70 and that there was no disambiguation atom identifier in columns 77-78
For example here is a comparison
```txt
legacy 1TSR
ATOM    561  O   GLN A 167      65.605  25.182  75.287  1.00 21.54      1TSR 778

present 1TSR
ATOM   1418  O   GLN A 167      65.605  25.182  75.287  1.00 21.54           O   
```
(See the attached zip file for complete examples)

Unfortunately, changing the files in my database (which is much needed!), would not prevent my users from loading their own legacy pdb files, which given my user base is very likely to happen.
Would it be possible to support this file format? If so, I don't mind tweaking the pdb parser but would appreciate some directions on how you'd rather have it done
[Archive.zip](https://github.com/arose/ngl/files/923672/Archive.zip)

**Comment by ppillot** [comment]
I have another weird pdb file that shows only atoms and no bonds between them in NGL (it is displayed correctly in Jsmol). This file does not have CONECT records which might be the cause of this behaviour?
[starch.pdb.txt](https://github.com/arose/ngl/files/924526/starch.pdb.txt)

**Comment by arose** [comment]
```
legacy 1TSR
ATOM    561  O   GLN A 167      65.605  25.182  75.287  1.00 21.54      1TSR 778
```

what does 778 in `1TSR 778` stand for? do you have a link that describes this format variant?

**Comment by arose** [comment]
>  This file does not have CONECT records

there are a lot of other fields missing too, but there is enough to calculate bonds, will fix it

**Comment by ppillot** [comment]
778 is a line number.
I have found a clue in the 1996 v2.2 description document (p9): http://cdn.rcsb.org/rcsb-pdb//file_formats/pdb/pdbguide2.2/pdb_contents_guide2.2.pdf
Under **What's new in pdb format v2.0** : 

> Columns 71 - 80 now contain data. They previously contained the PDB ID code and
record serial number.

**Comment by ppillot** [comment]
I've made a quick fix in my code, checking for digits as element names. In that case I suggest users an automatic download of the corresponding PDB file from the PDB.

**Comment by ppillot** [comment]
Is there a way to know if something is wrong from the file being processed by NGL? For example if a pdb file displaying heteroatoms has no CONECT record?
I was thinking about a second parameter (after component) returned by the stage.loadFile() Promise

**Comment by arose** [comment]
- see 8a158f1f6d0a6d2d2004396b3b6422bdeeeeb991 for better support for very sparse pdb files
- see 7d0e16ea136f11a26498b030a7c8de01d2b38457 for better support for legacy pdb files

**Comment by arose** [comment]
> Is there a way to know if something is wrong from the file being processed by NGL

the parser would need to throw an exception

> I was thinking about a second parameter (after component) returned by the stage.loadFile() Promise

Promises only ever return on value. Either throw an exception in the parser or inspect the Structure object.

**Comment by ppillot** [comment]
I've just updated to the latest release and made some tests with culprit files. It's working great! Thanks for your dedication to improving NGL!

**Comment by arose** [comment]
Great :)
