### ISSUE TITLE
Load PDB from external URL without extension

### ISSUE THREAD

**Issue by gbayarri** [arose/ngl#293]
Hi, 

I need to load different assemblies from URLs like that:

https://files.rcsb.org/download/1QVT.pdb2.gz

But NGL returns the next error message:

`1QVT:1 Uncaught (in promise) autoLoad: ext 'pdb2' unknown`

It happens the same when I try lo load a PDB from external URL but without extension:

http://mmb.irbbarcelona.org/api/pdb/1qvt

The error in this case is:

`1QVT:1 Uncaught (in promise) autoLoad: ext '' unknown`

Is it possible to load these kind of files? And referring to the assemblies, if is not possible to load them separately, how can I load a specific assembly from a PDB file?

Thanks.

**Comment by ppillot** [comment]
You might try to specify the file extension in the loadFile parameters. See documentation here : http://arose.github.io/ngl/api/Stage.html
`stage.loadFile( 'https://files.rcsb.org/download/1QVT.pdb2.gz' , { ext: 'pdb' } )`

**Comment by gbayarri** [comment]
Hi Paul, that was exactly what I needed.

Thanks a lot for your fast answer!

**Comment by josemduarte** [comment]
@gbayarri I believe NGL has native support for biological assemblies. You only need to load the standard mmcif/pdb/mmtf file and then choose the biological assembly you want. I couldn't find the docs to do it, but this is a good pointer: https://github.com/arose/ngl/issues/78

**Comment by arose** [comment]
```
stage.loadFile( "data://3dqb.pdb", {
    assembly: "BU1"  // AU for asymmetric unit; BU1, BU2, ... for biological unit
} ).then( function( o ){
    o.addRepresentation( "cartoon" );
    o.autoView();
    return o;
} );
```
