### ISSUE TITLE
bug? rotate without mouse click?

### ISSUE THREAD

**Issue by hainm** [arose/ngl#294]
Hi, `nglview` uses recent published ngl version. 

Hovering mouse to the protein will make it rotate. This is not really expected (e.g: I chose very "nice" angle and when moving the mouse out, the protein rotated).

**Comment by arose** [comment]
I suspect that is due to handling the hover callback in nglview. It can now return `undefined` to signify that there is nothing picked/at the mouse cursor.

**Comment by hainm** [comment]
there is no 'hover' keyword in this file: https://github.com/arose/nglview/blob/master/js/src/widget_ngl.js

**Comment by arose** [comment]
hmm, any errors in the console?

**Comment by hainm** [comment]
I have not checked yet.

**Comment by hainm** [comment]
uhm, it happens if I clicked in the region not having any atom.

```python
widget_ngl.js:126 Uncaught TypeError: Cannot read property 'atom' of undefined
    at child.<anonymous> (widget_ngl.js:126)
    at Wn.execute (ngl.js:21)
    at qn.dispatch (ngl.js:21)
    at qn.dispatch (ngl.js:5)
    at Cm.onClick (ngl.js:22)
    at Wn.execute (ngl.js:21)
    at qn.dispatch (ngl.js:21)
    at qn.dispatch (ngl.js:5)
    at rm.onMouseup (ngl.js:22)
```

code
```python
        this.stage.signals.clicked.add(function(pd) {
            var pd2 = {};
            if (pd.atom) pd2.atom = pd.atom.toObject();
            if (pd.bond) pd2.bond = pd.bond.toObject();
            if (pd.instance) pd2.instance = pd.instance;
            this.model.set("picked", pd2);
            this.touch();
            var pickingText = "";
            if (pd.atom) {
                pickingText = "Atom: " + pd.atom.qualifiedName();
            } else if (pd.bond) {
                pickingText = "Bond: " + pd.bond.atom1.qualifiedName() + " - " + pd.bond.atom2.qualifiedName();
            }
            this.$pickingInfo.text(pickingText);
        }, this);
```

**Comment by ppillot** [comment]
The same happened to me when hovering the background. In that case, there is no object returned by the callback : it is `undefined` and can't have an `atom` nor a `bond` property.
