### ISSUE TITLE
Unresponsive right-click-drag (Safari)

### ISSUE THREAD

**Issue by nk53** [arose/ngl#295]
On Safari, a loaded PDB structure will occasionally (and seemingly randomly) be unresponsive to translation attempts (via right-click-and-drag). The issue occurs about 50% of the time a stage is loaded (for me, anyway).

Specifically, what _appears_ to happen is that the structure first translates in the desired direction for one or more frames, then returns to its original position. This makes the structure appear as though it is wobbling without really going anywhere.

The attached file shows a minimalistic way to reproduce the issue. It contains a button that, when pressed, causes the creation of a new stage, and calls its `loadFile()` method with the url `"rcsb://2hac"` (the specific PDB ID doesn't matter). The issue will occur regardless of whether the page is refreshed between button-presses.

I am using Safari 10.1 on a macOS 10.12.4, and I am using the most recent version of `dist/ngl.js`.

This issue does not occur on Firefox or Chrome.

[ngl_test.tar.gz](https://github.com/arose/ngl/files/972122/ngl_test.tar.gz)

**Comment by ppillot** [comment]
I can confirm the bug in the test file. But If I discard the line 
```javascript
viewport.innerHTML = '';
```
then everything is functional. 
See the attached file.
[ngl_test.zip](https://github.com/arose/ngl/files/972175/ngl_test.zip)

**Comment by ppillot** [comment]
Well, I have to slightly amend my previous report : if I click at the button again, then an other stage is appended to the div and this stage may or may not exhibit the unresponsive translation behaviour.

I've had an other look at your code and I have wondered at why you chose to empty the div and then fill it with the stage and load the file.
I would suggest you to create the stage after the page and all its script have been loaded, with a 'load' event listener attached to the window object.
You can then have your button triggering the file loading (would you prefer have a button to load the file: you can instead load the file in the load event listener).

Here is the updated  code from your ngl_test.js file:
```js
// this is the function called by the event listener
function createStage (){
    window.stage = new NGL.Stage("viewport"); //stage object is stored as a global for future use 
}


function load_rcsb() {
    // ensure blank viewport
    // var viewport = document.getElementById("viewport");
    // viewport.innerHTML = '';
    // Load the stage
    stage.loadFile("rcsb://2hac", {defaultRepresentation: true});
}

// this is the setting of the event listener
window.addEventListener('load', createStage)
```
[ngl_test.zip](https://github.com/arose/ngl/files/972200/ngl_test.zip)

**Comment by nk53** [comment]
Thanks Paul,

Actually, the reason I was emptying the div was to allow loading of different PDB structures without reloading the entire page (my actual code gets the PDB ID from a text field). I assumed the proper way to reload a stage was to completely scrap it, then make a new one.

Running `stage.loadFile()` multiple times without having some way to clear the structures already loaded causes multiple structures to be loaded at the same time, which is not the intended effect.

I managed to get what I wanted by doing something similar to what you suggested, with a slight modification:
```javascript
function load_rcsb(url, settings) {
    if (already_loaded) {
        stage.compList.each(function (comp) {
            stage.removeComponent(comp);
        });
    }
    stage.loadFile(url, settings);
}
```

**Comment by ppillot** [comment]
You can use `stage.removeAllComponents()` instead of the each loop, prior loading your file.

**Comment by nk53** [comment]
Ah, I didn't see that method there. Thanks!
