### ISSUE TITLE
General method for creating position-coloured surfaces

### ISSUE THREAD

**Issue by fredludlow** [arose/ngl#297]
This is a bit related to #249. I'd like to have a general way to colour the vertices of a surface by some arbitrary function. The immediate use-case is to generate (rather approximate) electrostatic surfaces from atomic partial charges. 

I've put together a quick example in this branch 
https://github.com/fredludlow/ngl/tree/electrostatic-surface
Demo here (updated the avSurf example)
http://fredludlow.com/ngl/estatic/examples/webapp.html

![estatic-surface](https://cloud.githubusercontent.com/assets/900535/25677960/f935e0c4-303f-11e7-9b43-48d291a7905e.png)

The current surfaces aren't great as the charges are atom-based and it makes no attempt to guess where the hydrogens might be, so H-bond donors (particularly backbone NH) should appear as nice blue positively charged patches but don't - I can make a PR as it is if you want, though I think the surfaces are a bit misleading in their current form.

To get this to work I added a new `ElectrostaticColormaker` - the colormaker already has a reference to a structure so that was straightforward, but in order to get the surface to call `Colormaker.positionColor( ... )` as opposed to `atomColor` I had to alter `surface.js`. 

I'd like to implement some other potential types, but they're all based on external (server-based) code and at the moment I'd have to bake the names of their corresponding Colormaker subclasses into `surface.js`, which means maintaining a fork or some other fragile monkey-patching, which isn't ideal.

Could we have a way for a Colormaker to specify whether it expects to have its `atomColor` or `positionColor` method called?

The simplest way I could think of would be for Colormaker derived classes to set a `colorMode` flag which is either `atom` or `position` and then `Surface.getColor()` can check that flag?

**Comment by arose** [comment]
This cool, never seen such an approximation for the electrostatic potential! Definitely like to see a PR eventually!

I am leaning towards one of the following (favoring No 2)
- having different `Colormaker` base classes: `AtomColormaker`, `PositionColormaker` and `VolumeColormaker`
- removing `atomColor`, `positionColor` and `volumeColor` from `Colormaker` and do duck-typing based on the existence of those methods

**Comment by fredludlow** [comment]
There are various similar approaches, I took the partial charges and method for this from AstexViewer,
 though AstexViewer also generates hydrogen positions for amides, which I intend to implement as well. (The partial charges are CHARMM with hydrogens added to heavy atoms, according to the source code)

Chimera's documentation describes a more sophisticated version ([Coulombic surface](https://www.cgl.ucsf.edu/chimera/docs/ContributedSoftware/coulombic/coulombic.html)), though I don't have access to Chimera to compare. 

PyMOL has something called [Protein Contact Potential](https://pymolwiki.org/index.php/Protein_contact_potential).

As the pymol wiki says, it's probably best to regard these as all very qualitative, but they're quite handy for getting a feel for "big blob of negative charge here" and suchlike. 

I'll try to get H-bond donors working for simple cases, but for the changes to Colormaker can I leave it with you? (`atomColorToArray` is called in quite a few places)

**Comment by arose** [comment]
Thanks Fred!

> As the pymol wiki says, it's probably best to regard these as all very qualitative, but they're quite handy for getting a feel for "big blob of negative charge here" and suchlike.

Indeed 👍 

> but for the changes to Colormaker can I leave it with you? (atomColorToArray is called in quite a few places)

Just changed it so that `colormaker.positionColor` is called when it exists (and `colormaker.volumeColor` does not exist).

**Comment by arose** [comment]
@fredludlow does it work for you?

**Comment by fredludlow** [comment]
Yes, thanks very much! I'll close this for now and open a PR once I'm happy with the H-position stuff (got sidetracked...)
