### ISSUE TITLE
'nucleic' or 'rna' selestrings fail for RNA in 1QLN

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#298]
Hi, weird bug here.
1QLN displays RNA polymerase (:A) with DNA (:N and :T) and RNA (:R)
NGL Selection fails to include chain R in '`nucleic`' or in '`rna`' selected sets: a selection with "`nucleic`" as selestring returns only the DNA atoms ; a selection with '`rna`' as selestring is empty.
Nonetheless, atoms from chain R are correctly set to moleculeType 4, and coloring by moleculetype gives the expected result.

I've made a test case here: https://jsfiddle.net/ppillot/L4n90fvb/ 
(chains N, T and R are colored by chains and displayed as licorice; balls are displayed on '`nucleic`' but only appear over chains N and T)

I noticed also that similar model 1MSW which has the same 4 types chains doesn't exhibit this bug.
Maybe important to notice, chain R first residue is a GTP identified as an hetero atom.

**Comment by arose** [comment]
This is related to the mmtf version of the entry, cif works fine, see https://jsfiddle.net/28qbc1ao/.

In NGL, selection tests try to be clever. So I assume that a chain is of the same moleculeType. 1QLN:R starts with a GTP, which is of moleculeType "NON-POLYMER". However it is also part of the entity chain, which I could use to decide if it is `nucleic`. Anyway, in general it looks like it is not sufficient to look at the first group to test for `nucleic`, I can change that.

**Comment by ppillot** [comment]
Hi, related to that bug, I've found that in 1U19 (rhodopsin), the `protein` sele string returns an empty atomset. In that case, the first residue of each chain is an heteroatom (ACE) that comes before the aminoacids.

**Comment by arose** [comment]
fixed it, see 22d62dbdc74f2f1547561a994324f0a0a0d5e1ee - basically not using the first residue of a chain to guess if it is protein, nucleic, … anymore

**Comment by ppillot** [comment]
Great! Thank-you once again Alex!
