### ISSUE TITLE
selection language #element selector and compatibility with Jmol syntax _element

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#299]
NGL offers a selection language similar to RasMol's. It introduces also a `#` selector for elements such as in `#C` for selecting all carbon atoms.
Jmol has such a capability (see [Jmol reference](https://chemapps.stolaf.edu/jmol/docs/#atomexpressions) under chemical element) but uses the underscore instead (`_C`), the `#`symbol being used for comments in rasmol scripts.
Would it seemed desirable to accept Jmol's syntax for elements?

**Comment by arose** [comment]
Yes and it should have been `_` from the beginning. Added `_` and going to remove `#` after a grace period. See commit ba871f569794019bac938984325af2b635e636fc.
