### ISSUE TITLE
Best guess for representation 

### ISSUE THREAD

**Issue by hainm** [arose/ngl#30]
This is my wish list but might be very low priority. 

Supposed I have a molecule and load to ngl. I do not have artistic eye but wanting to have nice rendering. I just want to have an option, such as 'I am lucky' to have ngl to o make best guess to make nice representation for me. (So I can make good figure for publication)

**Comment by arose** [comment]
Interesting idea. This would involve deciding which representations to show and and at what orientation. It would be nice to have good initial representation and orientation when loading a file. Some ideas. 

### Representations
- have a decision tree that depends on what types of molecules in what quantity are present
- just a default set of representations/selections

### Orientation
- you could orient it with respect to the principal axes, e.g. looking down the smallest one
- you could look down a symmetry axis
- maximize surface visibility

**Comment by arose** [comment]
the dev branch has now a much better default representation defined in stage.defaultRepresentation( component )` and used via `stage.loadFile( url, { defaultRepresentation: true } )`


Also see: https://github.com/arose/ngl/blob/dev/js/ngl/stage.js#L184

**Comment by hainm** [comment]
cool. would love to see in nglview.

**Comment by hainm** [comment]
```python
nv.show_pytraj(traj, guess_repr=True)
```
