### ISSUE TITLE
chainname color scheme: color values not clamped to int

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#300]
I don't know if it's a bug or a feature...
In the code I put together few month ago to get the colors for each chain (see #247), I now get some strange hex values such as fdbf6c.773dfa6
You can have a look at a working example [here](https://jsfiddle.net/ppillot/xtwcu45w/)

Clamping the values to int using |0 gives the expected result (same color as on display)

**Comment by arose** [comment]
I tweaked the example a bit and it works for me now, see https://jsfiddle.net/xvgoap8t/

**Comment by ppillot** [comment]
Thanks.
I was wondering at why the colors values have changed to float ? (they used to be int)

**Comment by arose** [comment]
Don't quite know. However, I updated Chroma.js, which is doing the coloring stuff, recently.

**Comment by ppillot** [comment]
I've found this in the chroma issue list: [precision problem of Lab and CMYK color space](https://github.com/gka/chroma.js/issues/126) 
It appears at the end of the discussion that it was decided to go internally for high precision color values internally in order to make "retro-processing" values feasible.
