### ISSUE TITLE
Selection language discrepancies with Rasmol/Jmol predefined sets 

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#304]
I have noticed the following differences between NGL and Rasmol/Jmol

|keyword | NGL| Rasmol/Jmol*|
|---------|-----|---------------|
|small|Gly, Ala|Ala, Gly, Ser|
|hydrophobic|Val, Leu, Ile, Met, Pro|Ala, Gly*, Ile, Leu, Met, Phe, Pro, Trp, Tyr*, Val|
|nonpolar|Ala, Cys, Gly, Ile, Leu, Met, Phe, Pro,Val, Trp| - |
|polar|Arg, Asn, Asp, Gln, Glu, His, Lys, Ser, Thr, Tyr|Arg, Asn, Asp, Cys, Gln, Glu, His, Lys, Ser, Thr|
|aromatic|Phe, Trp, Tyr|His, Phe, Trp, Tyr|

Classification is a matter a taste... question is: shall we enforce consistency between libraries?

**Comment by arose** [comment]
Hmm, how is it in other libraries? I don't quite remember how I decided on the classification :(

**Comment by ppillot** [comment]
[Here](http://www.cgl.ucsf.edu/chimera/current/docs/ContributedSoftware/resprop/resprop.html#aacat) is Chimera's with the paper ref categories are taken from.

[Here](http://www.ks.uiuc.edu/Research/vmd/vmd-1.2/ug/vmdug_node138.html#SECTION001010000000000000000) is VMD's

**Comment by arose** [comment]
thanks @ppillot - that needs some sorting out

**Comment by ppillot** [comment]
So, what's the plan ?
I can make more detailed (and readable) comparisons to base suggestions on if you're Ok with changing the predefined sets.

**Comment by arose** [comment]
a better comparison would be awesome

**Comment by ppillot** [comment]
| _Hydrophobic_ | NGL | JMOL | RASMOL | VMD            | CHIMERA | Jalview | 
|-------------|-----|------|--------|----------------|---------|---------| 
| ALA         |     | ALA  | ALA    |                | ALA     | ALA     | 
| ARG         |     |      |        |                |         |         | 
| ASN         |     |      |        |                |         |         | 
| ASP         |     |      |        |                |         |         | 
| CYS         |     |      |        |                | CYS     | CYS     | 
| GLN         |     |      |        |                |         |         | 
| GLU         |     |      |        |                |         |         | 
| GLY         |     | GLY  |        |                | GLY     | GLY     | 
| HIS         |     |      |        |                | HIS     | HIS     | 
| ILE         | ILE | ILE  | ILE    |                | ILE     | ILE     | 
| LEU         | LEU | LEU  | LEU    |                | LEU     | LEU     | 
| LYS         |     |      |        |                | LYS     | LYS     | 
| MET         | MET | MET  | MET    |                | MET     | MET     | 
| PHE         |     | PHE  | PHE    |                | PHE     | PHE     | 
| PRO         | PRO | PRO  | PRO    |                |         |         | 
| SER         |     |      |        |                |         |         | 
| THR         |     |      |        |                | THR     | THR     | 
| TRP         |     | TRP  | TRP    |                | TRP     | TRP     | 
| TYR         |     | TYR  |        |                | TYR     | TYR     | 
| VAL         | VAL | VAL  | VAL    |                | VAL     | VAL     | 
|             |     |      |        | Not documented |         |         | 

| _Polar_ | NGL | JMOL | RASMOL | VMD             | CHIMERA | JALVIEW | 
|-------|-----|------|--------|-----------------|---------|---------| 
| ALA   |     |      |        |                 |         |         | 
| ARG   | ARG | ARG  | ARG    |                 | ARG     | ARG     | 
| ASN   | ASN | ASN  | ASN    |                 | ASN     | ASN     | 
| ASP   | ASP | ASP  | ASP    |                 | ASP     | ASP     | 
| CYS   |     | CYS  | CYS    |                 |         |         | 
| GLN   | GLN | GLN  | GLN    |                 | GLN     | GLN     | 
| GLU   | GLU | GLU  | GLU    |                 | GLU     | GLU     | 
| GLY   |     |      | GLY    |                 |         |         | 
| HIS   | HIS | HIS  | HIS    |                 | HIS     | HIS     | 
| ILE   |     |      |        |                 |         |         | 
| LEU   |     |      |        |                 |         |         | 
| LYS   | LYS | LYS  | LYS    |                 | LYS     | LYS     | 
| MET   |     |      |        |                 |         |         | 
| PHE   |     |      |        |                 |         |         | 
| PRO   |     |      |        |                 |         |         | 
| SER   | SER | SER  | SER    |                 | SER     | SER     | 
| THR   | THR | THR  | THR    |                 | THR     | THR     | 
| TRP   |     |      |        |                 | TRP     | TRP     | 
| TYR   | TYR |      | TYR    |                 | TYR     | TYR     | 
| VAL   |     |      |        |                 |         |         | 
|       |     |      |        | Not hydrophobic |         |         | 


| _Aliphatic_ | NGL | JMOL | RASMOL | VMD | CHIMERA | JALVIEW | 
|---------------|-----|------|--------|-----|---------|---------| 
| ALA           |     | ALA  | ALA    | ALA |         |         | 
| ARG           |     |      |        |     |         |         | 
| ASN           |     |      |        |     |         |         | 
| ASP           |     |      |        |     |         |         | 
| CYS           |     |      |        |     |         |         | 
| GLN           |     |      |        |     |         |         | 
| GLU           |     |      |        |     |         |         | 
| GLY           |     | GLY  | GLY    | GLY |         |         | 
| HIS           |     |      |        |     |         |         | 
| ILE           |     | ILE  | ILE    | ILE | ILE     | ILE     | 
| LEU           |     | LEU  | LEU    | LEU | LEU     | LEU     | 
| LYS           |     |      |        |     |         |         | 
| MET           |     |      |        |     |         |         | 
| PHE           |     |      |        |     |         |         | 
| PRO           |     |      |        |     |         |         | 
| SER           |     |      |        |     |         |         | 
| THR           |     |      |        |     |         |         | 
| TRP           |     |      |        |     |         |         | 
| TYR           |     |      |        |     |         |         | 
| VAL           |     | VAL  | VAL    | VAL | VAL     | VAL     | 


| _Small_ | NGL | JMOL | RASMOL | VMD | CHIMERA (tiny) | JALVIEW (tiny) | 
|-------|-----|------|--------|-----|----------------|----------------| 
| ALA   | ALA | ALA  | ALA    | ALA | ALA            | ALA            | 
| ARG   |     |      |        |     |                |                | 
| ASN   |     |      |        |     |                |                | 
| ASP   |     |      |        |     |                |                | 
| CYS   |     |      |        |     |                |                | 
| GLN   |     |      |        |     |                |                | 
| GLU   |     |      |        |     |                |                | 
| GLY   | GLY | GLY  | GLY    | GLY | GLY            | GLY            | 
| HIS   |     |      |        |     |                |                | 
| ILE   |     |      |        |     |                |                | 
| LEU   |     |      |        |     |                |                | 
| LYS   |     |      |        |     |                |                | 
| MET   |     |      |        |     |                |                | 
| PHE   |     |      |        |     |                |                | 
| PRO   |     |      |        |     |                |                | 
| SER   |     | SER  | SER    | SER | SER            | SER            | 
| THR   |     |      |        |     |                |                | 
| TRP   |     |      |        |     |                |                | 
| TYR   |     |      |        |     |                |                | 
| VAL   |     |      |        |     |                |                | 


| _Aromatic_ | NGL | JMOL | RASMOL | VMD | CHIMERA | JALVIEW | 
|----------|-----|------|--------|-----|---------|---------| 
| ALA      |     |      |        |     |         |         | 
| ARG      |     |      |        |     |         |         | 
| ASN      |     |      |        |     |         |         | 
| ASP      |     |      |        |     |         |         | 
| CYS      |     |      |        |     |         |         | 
| GLN      |     |      |        |     |         |         | 
| GLU      |     |      |        |     |         |         | 
| GLY      |     |      |        |     |         |         | 
| HIS      |     | HIS  | HIS    | HIS | HIS     | HIS     | 
| ILE      |     |      |        |     |         |         | 
| LEU      |     |      |        |     |         |         | 
| LYS      |     |      |        |     |         |         | 
| MET      |     |      |        |     |         |         | 
| PHE      | PHE | PHE  | PHE    | PHE | PHE     | PHE     | 
| PRO      |     |      |        |     |         |         | 
| SER      |     |      |        |     |         |         | 
| THR      |     |      |        |     |         |         | 
| TRP      | TRP | TRP  | TRP    | TRP | TRP     | TRP     | 
| TYR      | TYR | TYR  | TYR    | TYR | TYR     | TYR     | 
| VAL      |     |      |        |     |         |         |

**Comment by ppillot** [comment]
[aminoacids classifications.xlsx](https://github.com/arose/ngl/files/1009637/aminoacids.classifications.xlsx)
Same tables as a spread sheet

Basically Chimera follows the same classification as Jalview (and I never thought lysine could be hydrophobic!)
VMD is probably close to RasMol, but the documentation lacks the definition for hydrophobic, even if polar is defined as "protein and not hydrophobic"

**Comment by arose** [comment]
My plan is to follow Rasmol/VMD

changing:
- add HIS to aromatic
- add SER to small
- add CYS and GLY to polar
- add ALA, PHE and TRP to hydrophobic

adding:
- cyclic	HIS PHE PRO TRP TYR
- aliphatic	ALA GLY ILE LEU VAL

**Comment by arose** [comment]
lists of residue names are now allowed: `[ALA,GLU,LYS]`

**Comment by arose** [comment]
done, see 33fb086f02a545e0e52aeb4fc408df1feccadcfe

**Comment by ppillot** [comment]
Sounds great to me!
