### ISSUE TITLE
Upper limit on number of atoms?

### ISSUE THREAD

**Issue by nmih** [arose/ngl#305]
Just a curious question -- as presented in this talk: https://arose.github.io/talks/ngl-3dsig/, NGL can handle up to 40M atoms in a browser relatively well. 

What's the upper limit on that number of atoms? Or is it simply limited by hardware specs? Or is there a cap to the number of polygons drawn with WebGL?

**Comment by arose** [comment]
I would say for practical purposes it is mostly limited by hardware specs. The example with 40M atoms is not individual atoms but multiple implicit copies. The largest example I tried is about 1.2M individual atoms (the hiv capsid). The `Structure` class can certainly handle structures with many million atoms as the data is stored in `TypedArray`s. Do you have a use-case in mind?

**Comment by nmih** [comment]
Not specifically, I was just brainstorming a potential project similar to cellPACK (http://www.cellpack.org/) and was thinking NGL view could be utilized for a whole cell visualization.

**Comment by arose** [comment]
I see. NGL supports geometry instancing, so visualizations akin to cellPACK which contain a large number of identical (but differently rotated and translated) geometry (surfaces) are feasible.

**Comment by nmih** [comment]
That definitely sounds suitable -- I may be contacting you by email in the near future about that once things start ramping up!

**Comment by arose** [comment]
Sure, looking forward to talk to you. Also, we seem to be both at UCSD :)

**Comment by hainm** [comment]
> Also, we seem to be both at UCSD :)
lol

**Comment by nmih** [comment]
Hi Alex -- looking to revisit this, I have some undergrads working with the cellPACK guys for an E. coli and they would like to implement a viewer as part of a web app. Would you be able to meet up anytime to discuss with us? Thanks!
