### ISSUE TITLE
Error when attempting to change DistanceRepresentation colorScheme through setParameters

### ISSUE THREAD

**Issue by martingraham** [arose/ngl#306]
I've managed to find out it's a one-character thing (if I'm right)

https://github.com/arose/ngl/blob/master/src/representation/distance-representation.js#L314

`cylinderData.color = bondData.color1;`

should be

`cylinderData.color = bondData.color;`

as the bondData object doesn't have the property color1, it's color

**Comment by arose** [comment]
Thanks, good find. Fixed, see 8ad97223d07340096ad9d77c57b7ec0eda9d2b5e
