### ISSUE TITLE
new bitarray class missing functions from fastbitset

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#309]
I rely heavily on several functions from atomset objects based on the previous fastbitset implementation. For example, it allows me to keep track of each representation for each atom, to hide a portion of the molecule, etc... With the [replacement by the newer bitarray class](https://github.com/arose/ngl/commit/ea400a722367f9fa4e0178550db7acc8f6ecc762) my program is broken (methods as intersects, intersectionSize, union are absent).
I am about to replicate the previous functionalities, but I am wondering at what is the best: a PR to NGL or separate utils for my own needs?

**Comment by arose** [comment]
Sorry about that. A PR is most welcome :) Unittests would be great!

**Comment by arose** [comment]
Please see if 8250a08a54fd1e4c3da729cbc476fd1e73c02887 solves it for you, thanks!

**Comment by ppillot** [comment]
Yes! I've checked and it's perfect!
Thanks @arose
