### ISSUE TITLE
Wishlist: option change movie speed

### ISSUE THREAD

**Issue by hainm** [arose/ngl#31]
http://www.ks.uiuc.edu/Training/Tutorials/vmd/tutorial-html/node3.html

**Comment by arose** [comment]
There is an option to change the timeout between frames and an option to skip frames.

When you load a trajectory in the web app (http://arose.github.io/ngl/?example=dcd2) there are a number of parameters in the menu of the loaded trajectory:

* center (does a pbc aware centering with respect to the selection given)
* remove PBC (very simple method, from GROMACS, to make molecules whole again that cross the periodic boundary)
* superpose (superpose the given selection onto the initial coordinates)
* step size (how many frames are skipped on play back)
* interpolation type (linear or spline)
* interpolation steps (how many extra frames are calculated)
* play timeout (time in milliseconds between two frames on play back)
* play direction (forward or backward)
* play mode (once or loop)

**Comment by hainm** [comment]
@arose oh man, just check the link. Awesome.
