### ISSUE TITLE
Adding representation outside of loadFile callback

### ISSUE THREAD

**Issue by RasmusFonseca** [arose/ngl#311]
Ive been struggling to do essentially this: https://github.com/arose/ngl/blob/master/examples/scripts/representation/distance.js but outside the loadFile callback (need to add lines between atoms in response to a button press). Ive tried creating a Component object
```
var contacts = NGL.Component(stage);
contacts.addRepresentation("distance", {
    atomPair: [["100.CA", "200.CA"]],
        color: "skyblue",
        labelUnit: "nm"
    }
);
stage.addComponent(contacts);
```
but it says "NGL.Component is not a function". Sorry for the simple question, but I've been banging my head on this for hours now.

**Comment by ppillot** [comment]
I suppose you have to use `new` to create your component object. But it's probably not the way to di it.
You should not add a new component as a Distance is a representation, which implies it is part of a component.
What you should do is declaring an empty component global variable outside your loadFile promise, set it in your promise and access to it later to add your representations.
You can also access your component from your stage.

1st strategy
```javascript
let comp = {} // global

stage.loadFile('filename')
.then( (component) => {
  comp = component
  comp.addRepresentation('cartoon', {....})
})

// later you can
comp.addRepresentation('distance', {
        atomPair: [["100.CA", "200.CA"]],
        color: "skyblue",
        labelUnit: "nm"
})
```

2nd strategy
```javascript
let stage = new NGL.Stage(...)
stage.loadFile(....).then(....)

// later in your code, assuming you've only loaded one file to your stage, you can
stage.compList[0].addRepresentation('distance', {
        atomPair: [["100.CA", "200.CA"]],
        color: "skyblue",
        labelUnit: "nm"
})
```

**Comment by arose** [comment]
You can also name your loaded components and access them via `stage.getComponentsByName`

```JavaScript
stage.loadFile( "rcsb://1crn", { name: "myProtein" } ).then( function( o ){

    o.autoView();
    o.addRepresentation( "cartoon" );

} ).then( function(){

    stage.getComponentsByName( "myProtein" ).addRepresentation( "distance", {
        atomPair: [ [ "10.CA", "25.CA" ] ],
        color: "skyblue"
    } );

} );
```

**Comment by RasmusFonseca** [comment]
That works perfectly, thank you. Now I just have to figure out how to remove the distance again =)

**Comment by ppillot** [comment]
> Now I just have to figure out how to remove the distance again =)
If you have set your representation in a variable, you can remove it later from your component using
```javascript
myDistance = myComponent.addRepresentation(...)

// later
myComponent.removeRepresentation(myDistance)
```
You can also get your distance representation using `myDistance = stage.getRepresentationsByName('distance')`
