### ISSUE TITLE
Pass external variable to new coloring scheme

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#312]
Hi, I am using NGL.ColormakerRegistry.addScheme() to make a new coloring scheme. Is it possible to pass an external variable (like a color palette, or a range list) to this.atomColor?

**Comment by arose** [comment]
If you use `this.getScale` within the scheme you are adding with `.addScheme`, then the normal color parameters for representations (see http://arose.github.io/ngl/api/typedef/index.html#static-typedef-RepresentationParameters) should also work. How does the code you currently have look like and what are you trying to achieve exactly?

**Comment by giagitom** [comment]
Thank you! Passing data with colorScale works well, I wanted to find the way to make a color by element scheme fully customizable (every element's color can be choosen). This code works: 

```js
var byElementScheme = NGL.ColormakerRegistry.addScheme( function( params ){
    this.atomColor = function( atom ){
    	var color = this.scale[atom.element]
    	if (color === undefined){
    		return 0xFFFFFF
    		}
    	return color
    	}
} )
```
the color palette is an object like this:
```js
var palette = {
		H : "0xFFFFFF",
		C : "0xA6A6A6",
		N : "0x1C03FF",
		O : "0xF20000",
		S : "0xF2EC33",
		P : "0xF29811"
		}
```
and I changed the representation coloring scheme in this fashon:
```js
rep.setParameters({colorScheme:byElementScheme,colorScale:palette})
```

**Comment by giagitom** [comment]
Something strange happen when i set multiple times the same (user-defined) coloring scheme 
```js
rep.setParameters({colorScheme:byElementScheme,colorScale:palette})
```
It works only the first time. Then the other times it seems to rebuild itself without changes of color.. But the ```palette``` object is every time different.

In order to make it work, i have to make an other coloring scheme equal to ```byElementScheme``` and switch between this two coloring schemes each time i want to fire ```rep.setParameters```.

Is there something I am missing?

**Comment by arose** [comment]
would you mind making an example on [CodePen](https://codepen.io/pen?template=JNLMXb)?

**Comment by giagitom** [comment]
Ok, I tried to make one (I never used codePen before): [codePen](https://codepen.io/giagitom/pen/aWePPe)

Uncomment `//rep.setParameters({colorScheme:"uniform"})` to make it work properly. If it works the carbon atoms should become blue (like nitrogen)

**Comment by arose** [comment]
Thanks, the problem is that the `palette` object is still the same, just its contents are changed. The `.setParameters` just does a shallow equality test (not a deep one) so this change is not detected. Solution is to create a new object.

**Comment by arose** [comment]
The bigger problem with your code is that you re-/misuse the `colorScale` parameter to inject custom data. I would suggest to do it differently. Keep a reference to your custom color data if you want to change it and if you change it force an update of the coloring of the representation, see https://codepen.io/arose/pen/NgKvBv?editors=0010

**Comment by giagitom** [comment]
Oh.. thank you, before I was trying to update the representation with `rep.signals.parametersChanged.dispatch()` without luck. This solution works well!
