### ISSUE TITLE
Atom picking on licorice representation not working

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#313]
Hi, I have set a signal for picking atoms in the viewer. I only need to retrieve atom.qualifiedName().. It works for surface, spacefill and cartoon, but not for licorices representation (it returns undefined for the .atom property.

**Comment by ppillot** [comment]
In licorice representation, it is very hard to pick right on the atom (and sometimes even impossible), but you can pick a bond and use the `closestBondAtom` property instead.
Here is the code I use in libmol.org
```javascript
if (pickingProxy === undefined || pickingProxy.type !== 'atom' && pickingProxy.type !== 'bond') {
      // no atom picked... do stuff
} else {
    let atomClicked = pickingProxy.atom || pickingProxy.closestBondAtom
    // atom clicked... do other stuff
}
```

where `pickingProxy` is the parameter returned by signal.clicked

**Comment by ppillot** [comment]
Is related to #284

**Comment by giagitom** [comment]
Thank you! It works perfectly.
