### ISSUE TITLE
Other writer formats / additional attributes

### ISSUE THREAD

**Issue by fredludlow** [arose/ngl#314]
At the moment you can save files in PDB format, but not anything else. It looks like I could write a `SDFWriter` based on `PdbWriter`, but there are other attributes like atomic charges which aren't currently stored (I think). 

The use-case is: user sketches a molecule in 2D sketcher possible with charges, server generates 3D conformation with charges in .mol or .sdf format, user tweaks 3D conformation in NGL (haven't implemented this but it sounds from #296 like it's doable) and sends mol/sdf back to server for some calculation.

SDF/Molfile/CTAB specifies a whole load of atomic attributes and creating new arrays in `AtomStore` would be really inefficient in the vast majority of cases where you don't care about them. Could we have some kind of way of storing additional optional atomic properties in a flexible way - maybe `structure.atomProperties` is an array (which can be empty) and an `SDFWriter` class could check:

```javascript
if (structure.atomProperties[ i ] != null){
    var charge = structure.atomProperties[ i ].charge || 0;
}
```

**Comment by arose** [comment]
> could write a SDFWriter based on PdbWriter

you are very welcome to do so :) probably a good idea to make a `writer` directory for them

> atomic charges which aren't currently stored

I want to add a partialCharge property to the atomStore; also want to make (some) store properties optional

> user tweaks 3D conformation

can be done, not a problem

> some kind of way of storing additional optional atomic properties in a flexible way

indeed, there should be a way to do so, maybe two, one "inefficient" using a (json) object (could also be set in the sdf parser) and one "efficient" using typed arrays

**Comment by arose** [comment]
Hi,

I recently added support to add additional fields to stores (see https://github.com/arose/ngl/blob/master/src/parser/mol2-parser.js#L38) and used it for partial charges (mol2, pqr, top, prmtop, psf) and radii (pqr, prmtop). Alos added a partialcharge colormaker. I am not a 100% sure about ho to handle optional fields but for now I added getter/setter to atomProxy which check for the existence of the the partialCharge field. It would be cool if the electrostatic colormaker could use the partial charges when they are available.

Regarding other additional data I added an `extraData` property to the structure class and would suggest to store file type specific data in there under a key that is the file extension. See the sdf parser for an example (https://github.com/arose/ngl/blob/master/src/parser/sdf-parser.js#L53). I am very open to suggestions and comments!

**Comment by fredludlow** [comment]
I've got a basic working version of an SdfWriter class in this branch
https://github.com/fredludlow/ngl/tree/sdf-writer

Changes include:
* Switched from adrenalin.sdf example under test/data to one I found with some charges
* Added a 'formalCharge' to atomProxy in a similar way to the 'partialCharge' field. Would you do it this way or store it under extraData

To-do:
* Guard against going over max atoms limit, other inappropriate molecule types?
* Test it on some real files

**Comment by fredludlow** [comment]
Closing for now, see #360
