### ISSUE TITLE
Assembly not shown correctly in pdb file format

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#315]
Hi, something strange happen when I try to load some files in pdb format. After adding a representation and setting assembly: "BU1" it seems that the parameter is ignored and in the viewer it's shown the default assembly instead. When I load the same structure in cif format the assembly is shown correctly. This structure (2E4A) has 2 BU smaller than the default assembly and both of them don't work correctly. Supercell and unitcell assemblies work correctly instead. It seems that the problem rise up only when some chain has to be hided. This code sholud reproduce the problem.

```javascript
stage.loadFile('rcsb://2E4A.cif').then(function(comp) {
    	    comp.addRepresentation("cartoon", {assembly:"BU1"})		
	    stage.autoView()
	    })
stage.loadFile('rcsb://2E4A.pdb').then(function(comp) {
    	    comp.addRepresentation("licorice", {assembly:"BU1"})
	    stage.autoView()
	    })
```

also 2E48 seems to have the same problem.

**Comment by arose** [comment]
thanks, fixed it recently in a big cleanup commit, see b427d621e8f5ba3a955e963df1feec4aecf2e624

works with the v0.10.2-0 release, see https://codepen.io/arose/pen/qmzvoQ?editors=0010

**Comment by giagitom** [comment]
Thank you, now it works.

Beautiful project!
