### ISSUE TITLE
Can't build examples in current master

### ISSUE THREAD

**Issue by fredludlow** [arose/ngl#317]
Sorry you're probably in the middle of redoing this - but at the moment I can't open any examples in webapp.html using the current master. I think this is because I can't run the slimerjs gallery script (which builds `..build/gallery/scripts.json`) due to my dev server being a VM without WebGL support.

**Comment by fredludlow** [comment]
Oh, I can open `examples/test.html?script=x/y` :)

**Comment by arose** [comment]
yes indeed :) or `examples/webapp.html?script=x/y`

`..build/gallery/scripts.json` is just used to populate the menu in `examples/webapp.html`

we could add a non slimerjs script to make `..build/gallery/scripts.json`

**Comment by arose** [comment]
list with examples script now build automatically, see a40e1ffa0fc35eb76027d0dfa310cdb462fd3b3f
