### ISSUE TITLE
Wishlist: smoothing traj

### ISSUE THREAD

**Issue by hainm** [arose/ngl#32]
Just like vmd.

In python we can use scipy (same as mdtraj) for traj smoothing. Not sure about what u want for js side.

**Comment by arose** [comment]
There is support for linear or spline-based interpolation. For nglview, I agree that it's best to leave that in the hands of an analysis library.

When you load a trajectory in the web app (http://arose.github.io/ngl/?example=dcd2) there are a number of parameters in the menu of the loaded trajectory:

* center (does a pbc aware centering with respect to the selection given)
* remove PBC (very simple method, from GROMACS, to make molecules whole again that cross the periodic boundary)
* superpose (superpose the given selection onto the initial coordinates)
* step size (how many frames are skipped on play back)
* interpolation type (linear or spline)
* interpolation steps (how many extra frames are calculated)
* play timeout (time in milliseconds between two frames on play back)
* play direction (forward or backward)
* play mode (once or loop)

**Comment by hainm** [comment]
:+1:
