### ISSUE TITLE
issue in 1BBB

### ISSUE THREAD

**Issue by wojdyr** [arose/ngl#321]
When I select Assembly: Unitcell in 1BBB:
http://www.rcsb.org/pdb/ngl/ngl.do?pdbid=1BBB
two molecules seem to overlap.
![1bbb_screenshot](https://cloud.githubusercontent.com/assets/491873/26808857/d733baa0-4a57-11e7-9a06-43dbf7267ea5.png)

which would suggest a problem with handling of symmetry transformations.

**Comment by josemduarte** [comment]
1bbb is in a non-standard coordinate frame. The scale matrix calculated by NGL assumes the standard frame and thus gives a wrong scale matrix for this entry. There's only about ~ 200 entries with this problem in the PDB. See https://github.com/eppic-team/owl/issues/4 for more details.

**Comment by arose** [comment]
Thanks @wojdyr. NGL uses the provided scale matrix in PDB and mmCIF files (both blue), so those look ok compared to MMTF (green).

![screenshot 53](https://cloud.githubusercontent.com/assets/272250/26809578/d0ca858c-4a1a-11e7-8507-c4f1c0681ffd.png)
