### ISSUE TITLE
Add distance representation between two different structures

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#323]
Hi, is it possible to add a distance representation between two different structures (2 different files)?

**Comment by fredludlow** [comment]
You can now! The example test/concat in the ts2 branch shows how to concatenate two structures to achieve this

**Comment by giagitom** [comment]
Thanks @fredludlow ! I didn't see this. One question: What does structure.getView exactly do ?

**Comment by fredludlow** [comment]
It gets a `StructureView` which is a subclass of `Structure`, but with some selection applied, so methods like `eachAtom` only iterate over atoms in the selection.

**Comment by giagitom** [comment]
Thanks!
