### ISSUE TITLE
Structures loaded from pdb or cif file formats not showing multipleBonds

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#325]
Hi, It seems that structures loaded form pdb or cif fie formats are unable to reproduce multiple bonds in ball+stick or line representation. Instead mmtf files show them correctly. This [code](https://codepen.io/giagitom/pen/aWePPe?editors=0010) should reproduce the problem. Am I missing some necessary parameter?

**Comment by ppillot** [comment]
This [article](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005575) describes the peculiarities of the mmtf file format and explains that the bond order information is indeed hardcoded into the file.

> MMTF includes the full chemical description of all molecules in a PDB entry. Bonds and bond orders for both standard and non-standard residues, e.g., ligands, are included from the Chemical Component Dictionary [17] and additional covalent bonds (struct_conn category in the PDBx/mmCIF files), such as disulfide bonds or covalent bonds between ligands and polymers are also included in MMTF.

**Comment by giagitom** [comment]
Thank you

**Comment by giagitom** [comment]
An other thing.. In PDB files there are CONNECT fields, does NGL is able to read this informations? For I I tried to load a ligand file like [HEM](https://files.rcsb.org/ligands/download/hem_model.sdf) with connect information but when I set multipleBond : "symmetric" nothing changes.

**Comment by fredludlow** [comment]
The PDB CONECT records don't officially have any mechanism for indicating bond order, but many bits of software that write PDB files fudge it by specifying the connection multiple times, e.g. below atom 1 and 2 have a double bond, atoms 1 and 3 have a single bond:

    CONECT 1     2     2     3
    CONECT 2     1     1     
    CONECT 3     1

(NB: My spaces probably don't line up with correct columns, but that's the general idea..)

NGL does read the CONECT records and will handle this non-standard representation for multiple bonds, but if your input file is coming straight from the PDB (or from software which doesn't use this workaround) then NGL has no way of determining the bond order and so assumes they're all single.

**Comment by giagitom** [comment]
Thank you. So the problem is that the CONECT information is written in an other way.
