### ISSUE TITLE
Load blob containing mmtf data

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#326]
Hi, I am trying to load a Blob containing mmtf data. Which is the better way to do it? I tried in this way but it returns me an error during the file parsing (```TypeError: Cannot read property 'subarray' of undefined```)

```js
var blob = new Blob([mmtfData], {type:"text/plain"})
file = new File([blob], pdbId+".mmtf")
var opt = {ext:"mmtf"}
viewer.loadFile(file, opt).then(function(s){ .... //not working
```

with pdb and cif file format it works instead. Could be something related to the MIME type?

**Comment by arose** [comment]
How about
```javascript
// load binary data in MMTF format via a Blob
var binaryBlob = new Blob( [ mmtfData ], { type: 'application/octet-binary'} );
stage.loadFile( binaryBlob, { ext: "mmtf" } );
```
?

Also, how do you get the mmtf data?

**Comment by giagitom** [comment]
I finded a way to load blob data using normal new XMLHttpRequest(). Before I was using jQuery.ajax() . Maybe I was missing some parameter in the ajax call.. Thanks
