### ISSUE TITLE
Updating protein after a click button

### ISSUE THREAD

**Issue by apaillarse** [arose/ngl#330]
Hello,
the goal of my site is to have a ngl representation of a molecule (loaded with rcsb) and to update it through jquery resquets when events happen.
For example, I have a form and a button to select the protein you want to show. The problem is as ngl stage is already loaded when page is shown, ngl won't show the protein the user just selected.
I worked it around by reloading the whole page when the user cliks on the button but it's not very dynamic.
Do you have a way to do this without reloading the whole page ?
I will also want to update the molecule on which the frame is zoomed/centered.
Thanks in advance!

**Comment by ppillot** [comment]
Yes, you can achieve this by declaring a global variable for your stage.
```javascript
stage = new NGL.Stage("viewerHTMLid")
```
and a function linked to your button with
```javascript
stage.removeAllComponents() // to remove previously loaded molecules
stage.loadFile('rcsb://1crn').then( (component) => { // where the 1crn part is changed accordingly with your form 
  component.addRepresentation('ball+stick')
})
```

**Comment by apaillarse** [comment]
Thanks for your quick response !
