### ISSUE TITLE
no dcd loading into ngl via gui

### ISSUE THREAD

**Issue by j0kaso** [arose/ngl#331]
when I try to load a dcd trajectory via the gui (trajectory open), it doesn't respond. 
I tested the Issue within mdsrv (+ ngl v.0.10.3) and http://arose.github.io/ngl/ / ngldev

**Comment by arose** [comment]
resolved two issues, see b7d0206d6bc10884451f6931ac2fa164c9adba85 and 2c545b607a8a030aa6ce0ec371d9252b6062cab7

**Comment by j0kaso** [comment]
works! thanks!!!
