### ISSUE TITLE
Trajectory interpolation options only work for previously "loaded" trajectory

### ISSUE THREAD

**Issue by j0kaso** [arose/ngl#332]
reference from mdsrv: arose/mdsrv#17

> Interpolation Type "spline" and "linear" only work for frames previously run with no interpolation type. If the trajectory is not run completely and those frames are run again with an interpolation, they stop at the last loaded frame.

> with version 0.10.3

Issue does not occur for .gro trajectories.

I was not able to reconstruct the issue within http://arose.github.io/ngl/ as I did not found an xtc/dcd script example and couldn't load a trajectory as mentioned in #331

**Comment by arose** [comment]
are there any errors in the console?

**Comment by j0kaso** [comment]
yes:
```
ngl.js:1 Uncaught TypeError: Cannot read property 'length' of undefined
    at e.Cv.interpolate (ngl.js:1)
    at e.<anonymous> (ngl.js:1)
    at e.<anonymous> (ngl.js:1)
    at i (ngl.js:1)
    at ngl.js:1
```

**Comment by j0kaso** [comment]
with the recent update, it works like a charm for uploaded trajectories but not for scripted/remote trajectories. Still the same error.

**Comment by arose** [comment]
since v0.10.5-6 it won't throw an error but can still be jerky

**Comment by arose** [comment]
Fixed some more issues with interpolation in 0.10.5-10, please have a look.

**Comment by arose** [comment]
@j0kaso does it work for you now?

**Comment by j0kaso** [comment]
works perfectly - just another idea: interpolation step size 1 doesn't make any sense (and gives of cause no nice results (breaking of bonds etc)). Maybe if interpolation step size is 1, interpolation type should be set to none (or at least handled like it)? Would rather be a thing to prevent the user to run into this issue.

**Comment by arose** [comment]
I see, I have a look

**Comment by arose** [comment]
fixed, was a calculation error, will make a release later

**Comment by j0kaso** [comment]
cool! thx!
