### ISSUE TITLE
Listen for key events on canvas only?

### ISSUE THREAD

**Issue by fredludlow** [arose/ngl#335]
The `KeyBehaviour` class adds document event listeners, which means if I type a 'k' anywhere in the page (e.g. typing "backbone" into the selection input) the view starts rocking, which is, urm, surprising! 

In the interface I'm working on I added listeners to the canvas element, plus the following snippet to make the canvas focusable:

```javascript
canvas.setAttribute( "tabIndex", "1" );
canvas.addEventListener( 'mousedown', function() { canvas.focus(); } )
```

With this you have to click on the canvas to acquire focus before you use keyboard shortcuts, which I see as an advantage, but can see that views may differ on the subject... What do you think? 

(At the very least I should probably replace `mousedown` with a more generic touch-enabled event in my own code).

**Comment by ppillot** [comment]
Indeed, I have a text-box in my interface for writing selections and it reacts as you described ('i' triggers a rotation) which is an unexpected behaviour. I'd rather have keystrokes restricted to the canvas element as you suggest it.

**Comment by arose** [comment]
I agree, those key strokes should be restricted to the canvas element and thus requiring to focus on it.

**Comment by arose** [comment]
fixed this annoying behavior, please see 74237d0f0daed9168cbb98ad444e7b9fb6ada52e and let me know if it is good for you

- tried to ensure the focus is initially on the canvas but if the canvas is not part of the document when the stage is initialized you have focus yourself
- set `canvas.style.outline = 'none'`, hope no one wants that

**Comment by ppillot** [comment]
It works for me!

**Comment by fredludlow** [comment]
Working for me too - many thanks!
