### ISSUE TITLE
Load PDB mutimodel as trajectory

### ISSUE THREAD

**Issue by gbayarri** [arose/ngl#336]
Hi, I'm having problems loading a multimodel PDB as a trajectory. You can see the result below:

http://mmb.irbbarcelona.org/webdev/ngl/

The animation is wrong, it souldn't do this "jumps". But if I upload the same PDB file to your website as a trajectory:

https://arose.github.io/ngl/

And I change the trajectory parameters at the same value in the code it works perfectly. These are the parameters:

```
step: 1,
timeout: 500,
interpolateStep: 100,
interpolateType: "linear"
```
I'm using the same NGL library you use in your website (0.10.4) and I don't know what I'm doing wrong.

Thanks in advance!

**Comment by arose** [comment]
There are probably some problems with the interpolation feature, I will have a look. Does works ok for you with `interpolateType: 'none'`?

**Comment by gbayarri** [comment]
Hi, Alexander, 

It works without interpolateType, but what is strange is that it works with interpolateType = "linear" if I upload the PDB file to your web application example. 

With this PDB file:

http://mmb.irbbarcelona.org/webdev/ngl/lig0FG.anim1.mod2.pdb

Uploaded in your website applications as a trajectory, and putting manually the trajectory values that you can find below in my code it works. So probably it's something wrong in my code:

```
stage = new NGL.Stage( "viewport" , { backgroundColor:"#ddd" });
stage.removeAllComponents();

stage.loadFile( "lig0FG.anim1.mod2.pdb", { defaultRepresentation: true, asTrajectory: true } )
.then( function( o ){

      o.setSelection('/0');

      var traj = o.trajList[0].trajectory;
      var player = new NGL.TrajectoryPlayer( traj, {
          step: 1,
          timeout: 500,
          interpolateStep: 100,
          start: 0,
          end: traj.numframes,
          interpolateType: "linear"
      } );

      player.play();

      o.removeAllRepresentations();
      o.addRepresentation( "licorice" );
      o.autoView();
} );
```
Maybe I'm missing something? The player? the way to load the trajectory?

Thanks.

**Comment by gbayarri** [comment]
Adding a mode: "once" it works. So it seems that the problem is with the loop. But when I put loop there are problems even in the first iteration.

Is there any way to do an animation that does the first iteration in forward direction, the second in backward, the third in forward, etc? Maybe detecting the end of the first iteration I can launch a second one, and whet it finishes a third and so on.

Thanks.

**Comment by arose** [comment]
see also #332, there is something wrong with the interpolation handling. I will have to have a closer look. Thanks for reporting this @gbayarri!

**Comment by arose** [comment]
Fixed some issues with interpolation in 0.10.5-10 and also added a new direction option `bounce`.

**Comment by arose** [comment]
@gbayarri does it work for you now?

**Comment by gbayarri** [comment]
Hi @arose, sorry for the late reply.

I've tested and now it's not jerky, but still something happen with one of the two interpolations. 

Here is the example:

http://mmb.irbbarcelona.org/webdev/ngl/

As you can see, it jumps from the frame 1 to the frame 2 without doing any interpolation, whilst the interpolation from 2 to 1 is perfect.

Here is the PDB I'm using (just 2 models, what I want is an interpolation between them): 

http://mmb.irbbarcelona.org/webdev/ngl/lig0FG.2models.pdb

And here the code I put:

```
stage = new NGL.Stage( "viewport" , { backgroundColor:"#ddd" });

    stage.loadFile( "lig0FG.2models.pdb", { defaultRepresentation: true, asTrajectory: true } )
    .then( function( o ){

      traj = o.trajList[0].trajectory;
      var player = new NGL.TrajectoryPlayer( traj, {
          step: 1,
          timeout: 700,
          interpolateStep: 100,
          start: 0,
          end: traj.numframes,
          interpolateType: "linear",
          mode: "loop",
          direction: "bounce"
      } );

      player.play();

      o.removeAllRepresentations();
      o.addRepresentation( "licorice" );
      o.autoView();

      $("#loading-viewport").hide();
      
    } );
```

The bounce direction sounds great! But maybe there is some problem with the short interpolations? In this case I just have 2 frames.

Thanks for your help!

**Comment by arose** [comment]
Hey, should be fixed by c3ce3b6714183b5babc9a3b1ed8f29b29218c7f8 had to handle to boundaries differently when doing interpolation.

**Comment by gbayarri** [comment]
@arose it works perfect!

Those changes will be integrated in the next build?

Thanks!

**Comment by arose** [comment]
> Those changes will be integrated in the next build?

yes :)
