### ISSUE TITLE
Issue with partially transparent surface

### ISSUE THREAD

**Issue by mkhorton** [arose/ngl#338]
Artefacts are being observed when rotating partially-transparent 3D surfaces, leading to the only the outer surface being viewable at certain angles.

At a guess, maybe it's a bug in the depth-ordering of vertices, since it looks like vertices 'pop-in' when viewed from some angles, but are then not drawn when viewed from other angles. I've seen your open 'order independent transparency' issue in three.js, I imagine that would be one fix for this?

Seen with example `parser/dxbin` with NGL Viewer 0.10.4 in both Chrome 58.0 and Safari 10.10.1.

Steps to repeat:

1. Load example
2. Hide 3pqr.pqr (and, optionally, one of the two 3pqr-pot.dxbin surfaces)
3. Rotate slowly

<img width="1227" alt="artefact" src="https://user-images.githubusercontent.com/2976580/27809297-30e5b128-6003-11e7-86fb-b2ad14eecead.png">

**Comment by arose** [comment]
Hi @mkhorton, you are right this has to do with depth-ordering of vertices and it is not easily fixed. The GPU does everything in parallel and does not care about the order. Doing the order independent transparency approach will hopefully solve it. For now, you can try `depthWrite: false` (see https://codepen.io/arose/pen/vZjWQj?editors=0010) which still produces some artifact but maybe it works better for your use case.

**Comment by mkhorton** [comment]
Thanks for the comment -- we'll probably stick with just a single isosurface for the moment, which should mostly avoid these difficulties. Mostly interested in this functionality to approximate a volumetric rendering, by drawing multiple isosurfaces at different iso-values.
