### ISSUE TITLE
Disabling Ctrl + Move coordinate translation

### ISSUE THREAD

**Issue by DAlvGar** [arose/ngl#340]
Hello,

first of all congratulate you for the excellent work on this package, i really love it :)

I am currently integrating NGL in one project and found this behavior that when you right or left mouse drag holding the control key pressed the actual structure coordinates are translated or rotated. I am doing some structure superimpositions and I would like to disable this behavior as the change of one of the components coordinates will destroy the superimposition. 

I was wondering if it is possible to easily disable this? I had a look at trackball control and also the exposed signals but I found nothing about it. If you could kindly point me to the right code or right functions to use? I would really appreciate it. 

To reproduce: open 'test/alignment' and with the CTRL key pressed, drag some of the two structures around. 

Thanks a lot!

Sincerely,

Daniel

**Comment by arose** [comment]
Hi Daniel,

glad you find NGL useful :)

regarding your problem, have a look at the `MouseControls` http://arose.github.io/ngldev/api/class/src/controls/mouse-controls.js~MouseControls.html#remove

```
stage.mouseControls.remove( "drag-ctrl-right" );
stage.mouseControls.remove( "drag-ctrl-left" );
```

or more specific if you have some actions of your own bound and want to remove only the component pan/rotate actions

```
stage.mouseControls.remove( "drag-ctrl-right", NGL.MouseActions.panComponentDrag );
stage.mouseControls.remove( "drag-ctrl-left", NGL.MouseActions.rotateComponentDrag );
```

**Comment by DAlvGar** [comment]
Awesome! Sorry I missed this TriggerString part when I had a look at the API.
Thank you Alexander!
