### ISSUE TITLE
change colorDomain with setParameters

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#341]
Hi, I was playing a bit with [http://arose.github.io/ngl/](http://arose.github.io/ngl/) and find that if i load the first example (i tried with this) and in the console I try to change the colorScheme and the domainColor parameter of a representation like this:
```js
stage.compList[1].reprList[0].setParameters({colorScheme:"bfactor"}) //works
stage.compList[1].reprList[0].setParameters({colorDomain:[1,100]}) //throw error
```
Setting the colorDomain parameter returns an error:
```
ngl.0.10.5-2.js:1 Uncaught TypeError: Cannot read property 'set' of undefined
```

**Comment by arose** [comment]
thanks, fixed in the latest dev release, try here http://arose.github.io/ngldev/

**Comment by giagitom** [comment]
Great! tank you.
