### ISSUE TITLE
pdb-parser breaks chain at modified residue

### ISSUE THREAD

**Issue by hshany** [arose/ngl#346]
Loading 2src.pdb resulted in a chain break at the modified residue PTR, and the entire protein molecule is shown as ligand in the web app. The same doesn't happen when loading mmtf for the same molecule. 

While the problem may be fixed by modifying the pdb-parser of NGL, it makes one wonder more about how and where this chain identification logic is specified for the mmtf format, because it's not implemented in mmtf-parser, but instead already exists in the mmtf file. It seems like ligands and solvent molecules with the same chain id in PDB are represented as separate chains in mmtf. Does it mean mmtf carries this extra piece of info compared to PDB?

**Comment by arose** [comment]
It is a bug in the pdb parser, I will look into that, thanks for reporting it!

Our MMTF files are generated from the mmCIF files which contain an easier to parse data model for what is an actual polymeric chain. There is no additional data with regards to chains in MMTF compared to mmCIF.

**Comment by arose** [comment]
Hi, I added a (somewhat temporary) ix by parsing the MODRES record in PDB files to determine if a HETATM record belongs to a polymer. See here that 2SRC.pdb is now working https://codepen.io/arose/pen/mwvZKv?&editors=001

**Comment by arose** [comment]
see also #56

**Comment by arose** [comment]
@hshany does it work for you now?
