### ISSUE TITLE
Trajectory from SDF file with multiple frames messes up the molecules

### ISSUE THREAD

**Issue by DAlvGar** [arose/ngl#347]
Hello,

I am loading a SDF file with several small molecules in it. I correctly get the Trajectory component and can access the player to play, stop etc and set particular frames. However any molecule but the first one seem to be messed up and the original coordinates within the file are ok (see attached pic).

Code example:
stage.loadFile(path, {ext: 'sdf', asTrajectory:true}).then(function(o){ 
   o.addRepresentation("licorice");
   o.autoView()
    var traj = o.addTrajectory();
    traj.setFrame(1);
});

NGL second frame:
![image](https://user-images.githubusercontent.com/15227264/28112699-56867d24-66fa-11e7-8564-b188221e6e14.png)

Pymol second frame:
![image](https://user-images.githubusercontent.com/15227264/28112782-99bc7dc8-66fa-11e7-9e33-78b2f0c85d66.png)

SD file used within this ZIP file:
[ligands.zip](https://github.com/arose/ngl/files/1141620/ligands.zip)

Is this a bug? Else could you point me to the potential source of error?

**Comment by arose** [comment]
Hi @DAlvGar 

when you set `asTrajectory: true` it is assumed that the topology of all models is identical. If that is not the case you have to load the file normally and access the different models by setting `component.setStructure('/0')`. Made an example with a slider to change the models, see https://codepen.io/arose/pen/zzeVad?&editors=001

**Comment by arose** [comment]
@DAlvGar does this answer your question?

**Comment by DAlvGar** [comment]
Yes this is great with the example. Thank you Alexander!
