### ISSUE TITLE
Label representation with fixed size

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#349]
Hi, is it possible to show labels with the same size? I mean without shrinking by depth

**Comment by arose** [comment]
no, not currently but I can add a parameter `sizeAttenuation`

**Comment by giagitom** [comment]
Great!

**Comment by arose** [comment]
hmm, more complicated than I thought initially. Can you have a look at the annotation feature. They are not as performant (don't show a hundred) but can display rich html content and don't scale. See https://codepen.io/arose/pen/YQgvRV?&editors=001

**Comment by giagitom** [comment]
I think this should be a good starting point! Thanks !

**Comment by arose** [comment]
@giagitom added a fixedSize param to LabelRepresentation which will keep the size at a fixed pixel count during zooming

**Comment by giagitom** [comment]
Hi @arose, thank you very much! Does the minified version has been updated? I'm not seeing any 'fixedSize' parameter inside it.

**Comment by arose** [comment]
not yet
