### ISSUE TITLE
"import" results in SyntaxError on FireFox

### ISSUE THREAD

**Issue by LenzB** [arose/ngl#353]
Hi there, I'm trying to set up a small protein-viewing website using ngl. 
I've come across the problem that following the documentation and using the "import" function always results in an error in Firefox:
>  SyntaxError: import declarations may only appear at top level

apparently, "import" is only supported by the edge browser, according to [this](https://stackoverflow.com/questions/37624819/es2015-import-doesnt-work-even-at-top-level-in-firefox). 
I'm confused since the web application on this very site works flawlessly. 
Thanks for any tips!

**Comment by arose** [comment]
The files in the src/ folder that contain the import statements are not meant to be consumed by browsers directly. Instead there are files build for distribution in the dist/ folder. Also, have you seen the pages on embedding NGL (here http://nglviewer.org/ngl/api/manual/usage/embedding.html)?

**Comment by LenzB** [comment]
Thanks, that explains why I couldn't get it to work. I'll have to experiment a little though. I also got errors stating that "ColormakerRegistry" isn't defined, that's why I tried importing it. The error isn't gone yet, but I'll keep looking. 
Thanks for the fast response!

**Comment by arose** [comment]
When you use the distribution you have to prefix the classes with NGL like `NGL.ColormakerRegistry`
