### ISSUE TITLE
structure auto spinning in notebook

### ISSUE THREAD

**Issue by hainm** [arose/ngl#356]
hi,

nglview is using NGL 0.10.4. The loaded structure stand for while and then auto-spinning. 
I guess I hit some unknown keys that triggered that. Is it your intention or a bug? cheers.

**Comment by arose** [comment]
There are two key commands `i` to toggle spinning and `k` to toggle rock. In 0.10.4 they would be always triggered but in recent version you have to be focused on the canvas, i.e. click on the canvas, before they are triggered.

**Comment by hainm** [comment]
This mode can be turn off, right?

**Comment by arose** [comment]
currently not, but I will expand that feature to be configurable like the mouse bindings

**Comment by hainm** [comment]
yeah, please.

Jupyter notebook has its own shortcut too. Ideally, it should only be turned on if in full screen mode in notebook.

**Comment by hainm** [comment]
`k` is for moving up.

**Comment by arose** [comment]
Added `stage.keyControls` which can be disabled or you can remove individual key actions (and add your own). See https://github.com/arose/ngl/commit/db08101f2930fc389a36c85464b890ed9a243524 and http://nglviewer.org/ngldev/api/class/src/controls/key-controls.js~KeyControls.html

**Comment by hainm** [comment]
thanks. Can you please publish that in npm so I don't need to use local build.

**Comment by arose** [comment]
should be published as ngl@0.10.5-13 (under the tag next)

**Comment by hainm** [comment]
thanks.
