### ISSUE TITLE
selection not possible for residue naming starting with a number (e.g. for some ligands)

### ISSUE THREAD

**Issue by j0kaso** [arose/ngl#357]
If the naming of a residue/ligand (e.g. HetATM) is starting with a number (5FW), selection is not possible (instead it shows the ones with the residue number - here 5).

Example file attached.
[tmp_dyn_0_15.pdb.zip](https://github.com/arose/ngl/files/1175828/tmp_dyn_0_15.pdb.zip)

**Comment by arose** [comment]
yes, you have to use `[5FW]`, should be documented

**Comment by j0kaso** [comment]
oh, great thanks (overlooked it)!
