### ISSUE TITLE
Picking latency

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#358]
Hi, when I pick an atom i experience a latency of some milliseconds. During this time if I accidentally move the mouse the scene rotates. It seems that the picked atom is taken at the end of this latency period because, if the rotation occurs, the atom picked its not the same I clicked on. I don't know if this latency is necessary, but can it be decreased? I am using version 10.5-14 at the moment.

**Comment by arose** [comment]
fixed with 8eaeeda1e01c435ff6478972c68c1745ef6f6a64, was waiting with firing a single click until the max time for double click has passed, hence the delay. However that is not a good idea in general as you have experienced.

**Comment by giagitom** [comment]
Great! Thankyou
