### ISSUE TITLE
API consistency for color=?

### ISSUE THREAD

**Issue by hainm** [arose/ngl#368]
hi,

If I recall correctly, there is no option for {color: ...} in set representation.
But we do have {color: ...} in addRepresentation
```javascript
stage.loadFile("rcsb://3dqb.pdb").then(function (o) {
  o.addRepresentation("cartoon", {color: schemeId });  // pass schemeId here
  o.autoView();
});
```

**Comment by arose** [comment]
should be possible with b7b57ac54215d1f8de01f2a0a94b77c6bfb95be6 please test

**Comment by hainm** [comment]
yep

<img width="1174" alt="screen shot 2017-08-22 at 9 42 17 pm" src="https://user-images.githubusercontent.com/4451957/29595023-db86c5ee-8782-11e7-84f2-98509bb14618.png">
