### ISSUE TITLE
v0.10.5-18: [Violation] 'requestAnimationFrame' handler took 96ms

### ISSUE THREAD

**Issue by hainm** [arose/ngl#369]
I am not sure if this is an issue.

<img width="425" alt="screen shot 2017-08-20 at 10 57 31 pm" src="https://user-images.githubusercontent.com/4451957/29502055-2d61f6d8-85fb-11e7-86d1-97aebea859b5.png">

(got this with
```python
nglview.demo()
```

**Comment by arose** [comment]
not too much, I should probably use setTimeout in some instances instead of requestAnimationFrame

**Comment by hainm** [comment]
seems like there's a bit lagging in displaying.

**Comment by arose** [comment]
well, things have to be created... the 'Violation' are about the user experience, about how laggy or interactive it feels, how responsive the page is/can be.

**Comment by arose** [comment]
Hey @hainm, would you say 0.10.5-21 lags less?

**Comment by hainm** [comment]
I can't tell if it's less. Seems similar.

**Comment by hainm** [comment]
But I do see

NEW
> 'requestAnimationFrame' handler took 77ms

OLD
> 'requestAnimationFrame' handler took 130ms

**Comment by arose** [comment]
handled some of the violation, see fa0b59536badb3282765338876852f9c4c457c78

as long as the `'requestAnimationFrame' handler took ...` does not occur regularly when rendering it is fine
