### ISSUE TITLE
File not shown starting animations automatically

### ISSUE THREAD

**Issue by gbayarri** [arose/ngl#371]
After changing from 0.10.5-13 to 0.10.5-19 I've detected that there is a small delay charging PDB files, and if I start an animation automatically after loading the file (it doesn't matter if it's a setSpin or a representation as a trajectory), the file is not shown until I pass the mouse over the viewport. I've fixed that temporally putting the call to animation inside a setTimeOut of 1 second. 

Probably related with #369

**Comment by arose** [comment]
Thanks, can you please try 0.10.5-21, I hope to have fixed it there.

**Comment by j0kaso** [comment]
Is fixed for me (tested several trajectories) - thanks!

**Comment by gbayarri** [comment]
It's fixed for me too.
Thanks!!
