### ISSUE TITLE
set camera orientation?

### ISSUE THREAD

**Issue by hainm** [arose/ngl#373]
Hi,

I've asked about this before but got lost.

In very old NGL, we have something to get and set orientation but I don't see that anymore.

http://nglviewer.org/ngl/api/file/src/controls/viewer-controls.js.html

What's exact code to do that? Example: I want to store camera information for embedding NGLView.
Prefer to get data structures Python can understand.

**Comment by arose** [comment]
```javascript
var m = stage.viewerControls.getOrientation()
stage.viewerControls.orient(m)
```

`m` is a Matrix4 so `m.elements` is the array of numbers you want, which stage.viewerControls.orient(m) will also understand

**Comment by hainm** [comment]
thanks. I will try.

**Comment by hainm** [comment]
Your code work. But the zoom does not work. (In the notebook, I zoom it but the embeded html does not have that). I guess I need to update the zoom too?

**Comment by hainm** [comment]
### notebook
<img width="1001" alt="screen shot 2017-08-24 at 11 59 17 pm" src="https://user-images.githubusercontent.com/4451957/29699128-4f432d96-8928-11e7-9e53-82ba2f78e3f5.png">

### HTML
<img width="1009" alt="screen shot 2017-08-24 at 11 59 13 pm" src="https://user-images.githubusercontent.com/4451957/29699132-569a8c42-8928-11e7-8921-76bd9991bf67.png">

**Comment by arose** [comment]
hmm, zoom is supposed to be included in that matrix, could you check if you are doing a autoView() somewhere after applying the orientationMatrix, thanks

**Comment by hainm** [comment]
No I don't think so.

Please see `handle_embed` here:
https://github.com/arose/nglview/blob/set_camera/js/src/widget_ngl.js#L213-L286

**Comment by arose** [comment]
hmm, no, I can't find anything obvious

**Comment by arose** [comment]
looking at https://github.com/arose/nglview/blob/master/js/src/widget_ngl.js#L215-L288, I can't find where the camera setting is handled. Is there some current code?

**Comment by hainm** [comment]
I don't think we have any working code yet. I will push my local branch and ask you to debug later.

**Comment by hainm** [comment]
@arose so I just push code to `set_camera_2` branch. Please see the code there:

https://github.com/arose/nglview/blob/set_camera_2/js/src/widget_ngl.js#L255

frontend and backend here: https://github.com/arose/nglview/blob/set_camera_2/js/src/widget_ngl.js#L215-L225

Issue is reproduced like below:

- Notebook

<img width="1088" alt="screen shot 2017-09-22 at 10 57 57 pm" src="https://user-images.githubusercontent.com/4451957/30769576-f15b7c82-9fe9-11e7-9102-352ea35ba3b2.png">

- embed
<img width="1168" alt="screen shot 2017-09-22 at 10 58 06 pm" src="https://user-images.githubusercontent.com/4451957/30769577-f6d6e4a8-9fe9-11e7-927a-ef529f69e11f.png">

**Comment by arose** [comment]
was related to `defaultRepresentation: true`, please try https://github.com/arose/nglview/commit/3839fe2ad688537a3ceb27073bd1435ab68202d2

**Comment by hainm** [comment]
I've tried with your change but below won't show anything

```
import nglview as nv

view = nv.demo()
view
```

and change to `true` would help.

**Comment by hainm** [comment]
but your change does fix the original issue with camera.

**Comment by arose** [comment]
my bad, moved the code to the `handle_embed` method so it does not effect other parts, see https://github.com/arose/nglview/commit/2779e377c2784d4286a23d4b301c3e504d91c1e4

**Comment by hainm** [comment]
thanks. that works both.
