### ISSUE TITLE
Is there a way to build structures programmatically, not from a structure file?

### ISSUE THREAD

**Issue by scienceviz** [arose/ngl#374]
I apologize if this is obvious to some, but I couldn't figure it out from the documentation of codepen examples.

I have an array of structured data that more or less represents PDB-style data - atoms, elements, X,Y,Z, residue numbers, etc.  I want to build a protein (and possibly ligand, ion, etc) structure from that.  But all of the examples read files rather than build things from scratch.  I tried digging into the file parsing code but I figured I should see if there is an officially-sanctioned method before I started down that path.

Is there any example code for looping over an array of structured data, creating atoms, residues, etc, and then loading them into the stage?

Thank you!
Denny

**Comment by arose** [comment]
you could create a PDB file as string from the data you have and load that or you can look at the StructureBuilder (https://github.com/arose/ngl/blob/master/src/structure/structure-builder.js) and how it is used in one of the simpler parsers (eg mol2, https://github.com/arose/ngl/blob/master/src/parser/mol2-parser.js#L152-L161). The StructureBuilder creates the hierarchy (atoms, residues, chains, ...) for you but you have to fill the "store" with the atom data yourself. This is not part of the API so there are no examples.

**Comment by scienceviz** [comment]
Thank you!  I'll look into it.
