### ISSUE TITLE
Get real xyz of an assembly 

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#375]
Hi, I need to get the real x,y,z coordinates when I pick an atom. For real atoms there is no problem, but when I pick on structures with assemblies I get only the asymmetric unit coordinates. Is it possible to know the real atomic position in this situation?

**Comment by arose** [comment]
I assume you are getting a `PickingProxy` instance. Apart from an `.atom` property it has a `.position` property which contains the transformed coordinates used to render the picked atom in the scene.

**Comment by giagitom** [comment]
Exactly what I needed. Thank you!
