### ISSUE TITLE
How to correctly dispose components?

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#377]
Hi, I am trying to dispose components using ```stage.compList[0].dispose()```
It removes everything from the viewer, but if i check stage.compList[0],the components is still present. How can I completely remove components?

**Comment by hainm** [comment]
may be
```
stage.removeComponent
```

**Comment by arose** [comment]
yes, as @hainm said, `stage.removeComponent(component)`

**Comment by giagitom** [comment]
Oh, I missed that command. Thanks!
