### ISSUE TITLE
Open file type .pdb1/2/3...  

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#378]
Hi, I am trying to open file types pdb1/2/3... like [this](ftp://ftp.wwpdb.org/pub/pdb/data/biounit/PDB/all/2xpg.pdb1.gz) But NGL return this error ```TypeError: Cannot read property 'matrixList' of undefined```

**Comment by arose** [comment]
how are you doing it? do you have an example file to reproduce?

**Comment by giagitom** [comment]
ftp://ftp.wwpdb.org/pub/pdb/data/biounit/PDB/all/2buk.pdb1.gz
This. I uncompressed it before

**Comment by arose** [comment]
Hi, this was a bug in the pdb parser. It was not parsing the MTRIX records (which are related to non-crystallographic symmetry) correctly. Fixed in v0.10.5-22, see 824acd7c2f24d654a0ed96a863913bf1e8bfe7dd.

**Comment by giagitom** [comment]
Thanks!
