### ISSUE TITLE
Wishlist: Autorotate

### ISSUE THREAD

**Issue by gaitat** [arose/ngl#38]
Good for demos would be an auto-rotate option that just continuously rotates model until mouse takes over.

**Comment by arose** [comment]
Yes, certainly, this is great to show the user it isn't just an image but in fact allows user interactivity. I'll bump this up on my todo list.

**Comment by arose** [comment]
available in the dev branch, hope that helps @gaitat 

```JavaScript
function setSpin( spin ) {
  if( spin===true ){
    // first arg can be any vector, 2nd arg is degrees rotated per rendered frame
    stage.setSpin([0, 1, 0], 0.01);
  }else if(spin===false){
    stage.setSpin(null, null);
  }
  currentSpin = spin;
}
```

**Comment by newzhongdan** [comment]
Hello, the function "setSpin" only accept a boolean in the new version, the old arg is deprecated?

**Comment by arose** [comment]
Yes, stage.setSpin only accepts a boolean. If you want more complex things, have a look at the animation support https://github.com/arose/ngl/blob/master/src/animation/animation.ts

**Comment by newzhongdan** [comment]
y solved with 

` stage3.spinAnimation.axis.set(0, 1, 0)`

rotation without spinAnimation

<img width="194" alt="captura de pantalla 2018-08-28 a la s 13 42 25" src="https://user-images.githubusercontent.com/801562/44737629-ec556280-aac8-11e8-9885-20fb6026bd20.png">


with spinAnimation 

<img width="184" alt="captura de pantalla 2018-08-28 a la s 13 42 14" src="https://user-images.githubusercontent.com/801562/44737639-f11a1680-aac8-11e8-8e77-652c6aa55295.png">

thanks you!
