### ISSUE TITLE
Surface rendering performances in Edge browser

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#382]
Hi, I noticed that on microsoft Edge surface rendering is considerably slower than other browsers like chrome and firefox. Is it something known?

**Comment by fredludlow** [comment]
IE11 is certainly slower than Chrome and Firefox. One odd thing is IE11 is MUCH slower with the developer tools open - presumably there' are various optimizations that can't be done while debugging is active? Not sure if that's true in Edge too? 

It's not enormously helpful but a short term fix is to reduce the quality of the surface (reduce scaleFactor) to the lowest you can get away with.

**Comment by arose** [comment]
do you mean surface calculation of drawing (i.e. after it is created)?

**Comment by giagitom** [comment]
Seems that the behavior observed in IE11 can be observed with Edge too. With debugger open It keeps more than 60 seconds to build and render the Surface of 1C0k. Instead, without debugger 8.5 seconds are enaught. Whith Chrome instead the Surface is build and rendered in 4.5 seconds.  Finally, Firefox is the best with 3.4 seconds.

**Comment by arose** [comment]
The IE11/Edge debugger slows things down consierably for me too, I don't know what to do about it (other than using Chrome/FF for development). How are the timeings using Edge with`useWorker: false`?

**Comment by giagitom** [comment]
With useWorker it gains a second compared to before (7.3 seconds).

**Comment by fredludlow** [comment]
The 'av' style surface renders quicker for me, and I think you can get away with a slightly lower scaleFactor for it (maybe as low as 1.5 depending on zoom level). 

Beyond that, some of the code that does the number crunching to build the surface could be parallelized in multiple workers? Or ported to something like wasm - neither of those sound like small tasks!

**Comment by giagitom** [comment]
"av" style halves the times for me. Although keeping the gap between chrome and Edge similar. Thanks for the hint!

**Comment by arose** [comment]
Don't see anything we can do about this currently, so closing for now
