### ISSUE TITLE
api to hide portions of the pdb model?

### ISSUE THREAD

**Issue by paul-shannon** [arose/ngl#383]
Sorry if this is documented; I was unable to find any mention of "hiding". 

Is there a function in the javascript api by which one can hide or show portions of the currently displayed model?   

For instance, when viewing 1IZL, Crystal Structure of Photosystem II, I'd like to zoom in on, and see the unaccompanied structure, of (for example) pheophytin, or the oxygen-evolving complex.

Thank you!

**Comment by arose** [comment]
I made an example codepen, see here https://codepen.io/arose/pen/XebPwK, it load PDB entry 1IZL, shows a ball and stick representation of pheophytin (PHE) in chain A (:A) and focuses on it (.autoView)

**Comment by paul-shannon** [comment]
Beautiful - thank you!

**Comment by paul-shannon** [comment]
Could you point me to a list of the functions the comp object provides?   I see `addRepresentation` with a `select` option; `autoView` with a view target.   

I can only imagine that many more functions and parameters are provided.  (I feel rather silly for not being able to find them from my own search of the repo...)

**Comment by ppillot** [comment]
You can check the corresponding API [here](http://nglviewer.org/ngl/api/class/src/component/component.js~Component.html)

**Comment by paul-shannon** [comment]
Following up...
I pulled, built and ran the ngl webapp, and spent some time searching through the source code for the functions called out of the selection/representation UI, so I can learn how to offer similar capabilities for my own more narrowly focused webapp.   Alas, I have not yet found the right source files and function calls.  Nor do I really understand the basic data structure, as you will see from my example below.

A one-liner should probably set me straight. When running the NGL webapp, openingto the javascript console, with the stage global variable defined: what function do I call on which variable in order to  render residue 1 as ball+stick?   Something perhaps like (I am naively making this up):

    stage.model.setRenderingRule("residue 1", "ball+stick")

where the first arg is any combination of terms from the selection language, and the second arg is the style.

Thank you!

**Comment by arose** [comment]
assuming your structure is named '1crn.pdb' you can do `stage.getComponentsByName('1crn.pdb').addRepresentation('ball+stick', { sele: '1' })`
