### ISSUE TITLE
fixed color backface in spacefill (and other) rep

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#387]
Hi, Is it possible to obtain a spacefill representation with transparent backface like this?
![image](https://user-images.githubusercontent.com/20627977/30585762-26ca60b8-9d2e-11e7-9739-be8417e0dc4f.png)

**Comment by arose** [comment]
No, that is not available. MIght be mostly a task of adding options to what is already in the code. Never thought someone would like to have it displayed like this. What is it used for?

**Comment by giagitom** [comment]
Nothing special in reality.. I am tryng to reproduce the standard output of pymol. Pymol does not support an interior coloring like the one in NGL, it gives transparent backface or fixed color backface (like the one in figure). An other related question: Is it possible in NGL to give a fixed color for interior?  
![coloredbackface](https://user-images.githubusercontent.com/20627977/30616994-75e5516a-9d94-11e7-9fa1-632776c5d2fa.png)

**Comment by arose** [comment]
>  Is it possible in NGL to give a fixed color for interior?

No, but that seems more useful to me and should be easier to add.

**Comment by giagitom** [comment]
It would be better for me as well.

**Comment by giagitom** [comment]
hi, is there some news about this?

**Comment by giagitom** [comment]
Hi @arose, I don't know if what I am going to propose could be easier but:
Why don't expose a "interiorDarkening" parameter in the representations parameters able to handle the darkening intensity instead of keeping it fixed?

**Comment by arose** [comment]
Added a number of additional options and made use of a dark interior color the default
 * @property {Color} [diffuseInterior] - diffuse interior, i.e. ignore normal
 * @property {Color} [useInteriorColor] - use interior color
 * @property {Color} [interiorColor] - interior color
 * @property {Color} [interiorDarkening] - interior darkening: 0 no darkeing, 1 fully darkened

**Comment by arose** [comment]
Would be good if you could test the various options, thanks!

**Comment by giagitom** [comment]
Hi @arose ! Thank you very much! I tested the new features and I did not find any problems. If I find something, i'll let you know.
