### ISSUE TITLE
Use label background / border abilities in DistanceRepresentation?

### ISSUE THREAD

**Issue by martingraham** [arose/ngl#388]
Hi Alex, is it possible to use the text embellishments in #125 for the labels in a DistanceRepresentation? 

Quick glance says no, but I don't want to start hacking away at the code if it is possible with a one-liner or two.

**Comment by arose** [comment]
You are right, currently no. It is certainly a good feature. We should tackle this as part of @fredludlow's effort with a MeasurementRepresentation, see #46

**Comment by fredludlow** [comment]
I've exposed the various parameters in Measurement Representation in my angle-repr branch. You can load the [distance demo](http://fredludlow.com/ngldev/examples/webapp.html?script=representation/distance) and set background/border etc.

Alex - there's a bit that feels a bit "magic", I've defined parameters like this:
```javascript
labelXOffset: {
  type: 'number', precision: 1, max: 20, min: -20, buffer: 'xOffset'
},
```

When you change the value of labelXOffset it passes through xOffset to the buffer, which saves a lot of boilerplate code, is this okay? (couldn't figure out if it passes them through to all buffers or just the first one)

Also, not sure if my naming is ideal - I've prefixed param names with `label` to indicate they apply to the label (as opposed to arcs/lines etc), but that means they're inconsistent with the LabelRepresentation parameters. It's a trade off between a consistent API and more informative names, what do you prefer?

**Comment by arose** [comment]
> When you change the value of labelXOffset it passes through xOffset to the buffer, which saves a lot of boilerplate code, is this okay?

yes, that is ok, `buffer` can be a string for exactly that reason :)

> It's a trade off between a consistent API and more informative names, what do you prefer?

 It is fine with the prefix!

**Comment by arose** [comment]
available in ts2 branch
