### ISSUE TITLE
How to insert a Box in a surface protein representation?

### ISSUE THREAD

**Issue by wandreveloso** [arose/ngl#389]
@arose 
I'm trying to **insert a box** in the surface molecular representation of a protein but I can't do.
This is my code of insert the protein viewer (**this works!**)
`var stage = new NGL.Stage( "viewport", {backgroundColor: "white"});
                stage.viewer.container.appendChild(tooltip);
                stage.loadFile("{{ url_for('static', filename=pdb_filename) }}").then( function(
                  comp )
                  {
                    comp.addRepresentation( "surface", { multipleBond: true, sele: "not hetero", opacity: 0.6} );
                    comp.addRepresentation( "cartoon", { sele: "not hetero" } );
                    comp.centerView();
                    comp.addRepresentation( "ball+stick", { sele: "hetero", multipleBond: true} );
                  }
                );`
Now this is my code to insert the box in the specific X,Y,Z position (**does not work**):
`var shape = new NGL.Shape("shape")
                var boxBuffer = new NGL.BoxBuffer({
                  position: new Float32Array([ 25.518, 64.421, 55.616 ]),
                  color: new Float32Array([ 1, 0, 1 ]),
                  size: new Float32Array([ 40 ]),
                  heightAxis: new Float32Array([ 20, 20, 20 ]),
                  depthAxis: new Float32Array([ 20, 20, 20 ])
                });
                shape.addBuffer(boxBuffer)
                var shapeComp = stage.addComponentFromObject(shape)
                shapeComp.addRepresentation("buffer");
                shapeComp.autoView();`
The position X, Y and Z of the box are absolute and the position of PDB protein file area absolute too (there is no align)? I put the box in the specific position using the atoms of PDB file.

**Comment by arose** [comment]
Hi, can you please make a codepen (https://codepen.io/pen?template=JNLMXb) with your example? Thank you!

**Comment by wandreveloso** [comment]
Hi,
There is my code: https://codepen.io/anon/pen/zEZWGy
@arose

**Comment by wandreveloso** [comment]
@arose , can you help me?

**Comment by arose** [comment]
Hi, the version you were using (v0.10.3) did not support BoxBuffer. It works with the current beta (v1.0.0-beta.1) https://codepen.io/arose/pen/EwXOMr?editors=1010

**Comment by wandreveloso** [comment]
Thanks! Now I got it!
I'm trying to insert a empty or very transparent box but I can't do this...
Can you help me?

**Comment by arose** [comment]
You  can change the opacity with a parameter: `shapeComp.addRepresentation("buffer", {opacity: 0.5})`. I also updated the pen: https://codepen.io/arose/pen/EwXOMr?editors=1010

**Comment by wandreveloso** [comment]
Great!
Now, in my case, I always want to create a cubic (symmetric) box. With values I have to put in variable "size"? If the box is 20x20x20, 13x13x13, 6x6x6...

**Comment by arose** [comment]
like this:

```
 size: new Float32Array([ 6 ]),
 heightAxis: new Float32Array([ 0, 6, 0 ]),
 depthAxis: new Float32Array([ 0, 0, 6 ])
```

```
 size: new Float32Array([ 13 ]),
 heightAxis: new Float32Array([ 0, 13, 0 ]),
 depthAxis: new Float32Array([ 0, 0, 13 ])
```

**Comment by wandreveloso** [comment]
Thanks a lot!
