### ISSUE TITLE
Improper bonding between long distant residues in a theoretical PDB model

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#390]
Hi, I've tried to load an old (but very common in text books) theoretical PDB model of an IGG, coming from Eric Martz website.
[igg1-all.pdb.zip](https://github.com/arose/ngl/files/1335522/igg1-all.pdb.zip)
<img width="743" alt="igg-all" src="https://user-images.githubusercontent.com/3930632/30892302-d69c611c-a305-11e7-8b8a-30ed839aa3ad.png">
Improper bonds are created between atom ND2 of ASN306 in both chain H and I, and unrelated atoms (GLU1 and PHE135 of chain H). I can't see the pattern in this misrepresentation...

**Comment by arose** [comment]
the connect records don't adhere to the fixed column format of the pdb spec but are simply white space separated... that leads to reading of wrong index numbers by the parser. How common are such files?

```
CONECT 5801 10293
CONECT 2317 10183
```

It should be

```
CONECT 580110293
CONECT 231710183
```

**Comment by ppillot** [comment]
It is probably unique : [https://www.umass.edu/microbio/rasmol/padlan.htm](https://www.umass.edu/microbio/rasmol/padlan.htm)

**Comment by arose** [comment]
ok, thanks, not going to spend time on this, but happy to accept PRs

**Comment by ppillot** [comment]
Thanks for your answer. I've made a quick check on other molvis softwares and they all behave along the same way as NGL. I suppose that this incoherent bonding was only invisible back in RasMol time...
I'm closing the issue.

**Comment by arose** [comment]
agreed, thanks for checking
