### ISSUE TITLE
Custom labels

### ISSUE THREAD

**Issue by fredludlow** [arose/ngl#391]
Not urgent, but while I think of it - there might be some use for a mechanism for constructing custom label text e.g.:

e.g. handlebars.js / jinja2 syntax:
`{{ chain }}:{{ resno }} {{ bfactor }}`

Or more compact/cryptic printf style, with precision
`%c:%r %.1b`

**Comment by arose** [comment]
would be nice indeed! there is already sprintf (https://github.com/arose/ngl/blob/master/lib/sprintf.es6.js) in ngl which includes named arguments and can be used for number formating :)

**Comment by arose** [comment]
I suppose once a new sprintf version is released (https://github.com/alexei/sprintf.js/pull/161), we can have this goodness https://github.com/fredludlow/ngl/tree/sprintf-labels, right?

**Comment by fredludlow** [comment]
Yup, that's the idea, or we can just reference a specific git commit in the sprintf.js repo?

**Comment by arose** [comment]
> or we can just reference a specific git commit in the sprintf.js repo?

fine by me too
