### ISSUE TITLE
Could not instantiate widget

### ISSUE THREAD

**Issue by lenhsherr** [arose/ngl#392]
Hi, I'm testing a script on two Macs, and despite apparently identical setup, the widget does not show up on only one of them.

Javascript control panel shows this.
`[Error] Could not instantiate widget
[Error] Error: Could not create a model. — utils.js:109
[Error] Couldn't process kernel message – "Class NGLModel not found in module nglview-js-widgets"
[Error] Unhandled Promise Rejection: Class NGLModel not found in module nglview-js-widgets'

What does this mean?

Thank you.

**Comment by hainm** [comment]
This should be opened in https://github.com/arose/nglview

**Comment by lenhsherr** [comment]
My apologies.

I will close this and reopen it in nglview

**Comment by arose** [comment]
thanks!
