### ISSUE TITLE
Bug in superposing

### ISSUE THREAD

**Issue by rdecapomaranca** [arose/ngl#395]
Whenever a mol2 file is used in superposing (either as the one being superposed, or the one being superposed to) the structure that is being superposed disappears from viewer (without errors) and I can't seem to get it back. I tried show/hide structure and adding different types of representation but nothing is working. This was tested on official ngl web application and in personal application (using code) with latest updates.

I would really appreciate if you would fix this. Thank you.

**Comment by arose** [comment]
Hi, can you please provide two mol2 files with which I can reproduce the error, thanks.

**Comment by rdecapomaranca** [comment]
Here you go. Both files are the same molecule only the positions are different so they should completely overlap when superposed.
[test-files.zip](https://github.com/arose/ngl/files/1351302/test-files.zip)

**Comment by arose** [comment]
The 'Superpose' option in the GUI only supports protein. To superpose any coordinates you need to use the `Superpose` class. However that was not exposed and did not support input coordinates arrays of different length. See 1e9a9260f168f313616ade99a64eb919711d00e3. You can now superpose the two molecules but be aware that the function assumes that the first coordinate in the one structure corresponds to the first coordinate in the other structure.

![screenshot 62](https://user-images.githubusercontent.com/272250/31138744-5afcb9fc-a824-11e7-90d4-732032568067.png)

**Comment by rdecapomaranca** [comment]
Thank you very much for the quick fix.

**Comment by arose** [comment]
you are welcome
