### ISSUE TITLE
selecting a list of residues separated by a comma broken

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#400]
Hi, if a list of comma separated index residue number is given (e.g. `1,2,3,4`), only the first one is considered for a selection command. It used to work some time ago...
This can be tested in the nglviewer with the selection example (basic)

**Comment by arose** [comment]
If it ever worked it was by accident :) You need to connect them by `OR`

**Comment by ppillot** [comment]
Sorry about that... Some time ago might have been in another reality...
I might have confused with Jmol select language.
