### ISSUE TITLE
Trying to integrate with ReactJS

### ISSUE THREAD

**Issue by orion110217** [arose/ngl#404]
Hi, I'm wondering if it is possible to integrate this into a react component?

**Comment by orion110217** [comment]
Nvm, I got it working. Just have to set the height of the canvas. Here is my code for future reference of someone who might use it in React 15.X

`import React, { Component } from 'react'
import * as NGL from 'ngl'

class pv extends Component {

	componentDidMount() {
		const stage = new NGL.Stage(this.viewport)
		stage.setParameters({backgroundColor: 'white'})
		stage.loadFile('https://files.rcsb.org/download/1crn.pdb').then((component) => { 
			component.addRepresentation("cartoon");
			component.autoView();
		})
	}

	render(){
		return(
			<div>
				<div ref={el => this.viewport = el} style={{height: '500px'}}/>
			</div>
		)
	}
}

export default pv`

**Comment by arose** [comment]
@orion110217 thanks for sharing your example code!

**Comment by moritzschaefer** [comment]
@orion110217 The code doesn't work for me. Instantiating NGL.Stage raises an error inside the constructor. Did you face this issue before?

TypeError: this.setParameters is not a function
`
  73706 |     }
  73707 |   };
  73708 | 
> 73709 |   this.setParameters(p);// must come after the viewer has been instantiated
  73710 | 
  73711 |   this.viewer.animate();
  73712 | };
`

**Comment by orion110217** [comment]
What's your 'viewport'? I think it don't exist.

**Comment by moritzschaefer** [comment]
I tried 3 different viewports: 
- Your approach using a state-variable and setState
- Your approach using a file-scope variable
- Hardcode a <div> element into index.html with id "viewport" and providing string "viewport" instead of variable viewport

**Comment by orion110217** [comment]
Can you show me the code and what have you tried so far?

**Comment by orion110217** [comment]
@moritzschaefer It may be that React is not mounting you viewport, you can try and read more about it [here](https://reactjs.org/docs/integrating-with-other-libraries.html).

**Comment by moritzschaefer** [comment]
@orion110217 Here is a failing codepen:
I followed the guide you provided. What do you think?
https://codepen.io/moritzschaefer/pen/boJxmP?editors=1111

**Comment by orion110217** [comment]
@moritzschaefer You're just forgetting to create an instance of stage.
` const stage = new NGL.stage(this.el)`
or set stage in the class, so you can access it later
` this.stage = new NGL.stage(this.el)`

**Comment by moritzschaefer** [comment]
@orion110217 Thanks so much. 
So much time lost for the new keyword.. :/

**Comment by orion110217** [comment]
@moritzschaefer You are welcome my brother, tell me about it, I almost always forgot about 'this' :/
