### ISSUE TITLE
avoid shaking (dizzy) if zoom in and rotate

### ISSUE THREAD

**Issue by hainm** [arose/ngl#406]
hi,

I feel shaking and dizzy if zoom in the atoms in full screen mode while rotating the molecule. Any idea how to reduce it? 

<img width="791" alt="screen shot 2017-10-26 at 11 43 07 pm" src="https://user-images.githubusercontent.com/4451957/32087104-99a14070-baa7-11e7-8aec-57c230317281.png">

PS: With that orientation above, go to full screen mode and rotate.

**Comment by hainm** [comment]
try to open the same file with VMD you won't feel that.

**Comment by arose** [comment]
hmm, do you get the same effect in the NGL webapp?

**Comment by hainm** [comment]
yeap, tried to zoom in like this, then rotate

<img width="1280" alt="screen shot 2017-11-04 at 1 02 09 am" src="https://user-images.githubusercontent.com/4451957/32402501-e07540c8-c0fb-11e7-94ce-df279d7a1c3a.png">

**Comment by hainm** [comment]
the transition seems not smooth, reminding me about 

![image](https://user-images.githubusercontent.com/4451957/32402513-2e529c64-c0fc-11e7-8d09-e90474ff49ed.png)

**Comment by fredludlow** [comment]
Does orthographic mode help? (or is that not an option?)

**Comment by hainm** [comment]
> Does orthographic mode help

hi, no.

**Comment by arose** [comment]
Does it feel more smooth if you reduce the `rotateSpeed` stage parameter?

**Comment by hainm** [comment]
it does with rotateSpeed=0.3 and orthographic camera.

**Comment by arose** [comment]
Ok, so it is mainly the speed of the camera rotation and the shakiness comes from your hand :)
