### ISSUE TITLE
cartoon representation for single residue

### ISSUE THREAD

**Issue by cuzzo87** [arose/ngl#407]
I was trying to use the multiple `cartoon` representation with different residue selection like:

```
o.addRepresentation("cartoon", {color:'blue', sele:'33-56 OR 63-81 OR 83-92 OR 100-133 OR 135-141 OR 148-164 OR 166-169 OR 186-215 OR 322-350 OR 362-386 OR 388-397' });
o.addRepresentation("cartoon", {color:'green', sele:'58-60 OR 165 OR 351 OR 398' });
o.addRepresentation("cartoon", {color:'cyan', sele:'82' });
```

Maybe I am doing it wrong, but the last representation does not work and event the residues 58-60 of the second representation are not shown.
For both, the `line` representation worked and the `cartoon` representation works if I extended the selection 58-60 to 58-61

**Comment by ppillot** [comment]
Yes, it's a current known limitation: at least 3 residues are required to display a cartoon. See #223
