### ISSUE TITLE
ts2 branch: contacts representation

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#410]
I've tried @fredludlow latest PR in ts2 branch. Congratulation Fred for your awesome work! I can assess that interactions depiction is one of the most awaited features from my users! And you implemented such a variety that every need looks fulfilled.

I have one suggestion though: if the representation is simplified (such as in backbone, ribbon, rope,...), dashed lines are not connected to the actual representation and seem to hang in mid-air.
<img width="432" alt="cartoon and hbonds" src="https://user-images.githubusercontent.com/3930632/32473243-a1517d72-c334-11e7-85cd-00166defd2b2.png">
Some software offer the ability to connect bonds to atoms that are part of the sidechain (the actual bonds donor and acceptor) or to the backbone (Jmol for example has `set hbondsBackbone true`). Would it be feasible?
I would favour an option, instead of a general switch for the whole contact representation, where an AtomBitset would be passed as a parameter describing which atoms should be represented as "backboned".
(and I have no idea about what could be done with base representation which is an intermediate case)

**Comment by arose** [comment]
Thanks @ppillot!

I am not entirely sure what want so let me try to describe it in my own words.
1) show the residues as licorice (or some other atom/bond representation) that have at least one atom involved in an interaction
2) option to connect trace atoms (e.g. CA or P) whenever there is an interaction between residues instead of connecting the actual atoms involved in the interaction

**Comment by ppillot** [comment]
I would favour n°2 !
I want to keep control over which atoms are displayed and whether they are represented as licorice or hidden from the view because the user has chosen a representation such as ribbon (so n°1 is not an option).

Presently, hbonds are displayed as if it were assumed the representation is licorice. This is not always the case (as shown in the image in my previous comment).
Sometimes the whole model is shown as ribbon and I suppose that connecting to trace atoms makes sense.
Sometimes one of the atoms actually involved in the interaction could be represented as licorice, and the other would not be shown because it is represented as ribbon. In that case, the connection should be made between the atom in licorice and the trace atom from the same sesidue as the hidden connected atom.
To be able to deal with all these combinations (atom-atom, trace atom-trace atom, atom-trace atom), we could provide as a parameter to the contact representation, a Bitset describing for each atom in the component wether the connection should be made to the actual atom or to the trace atom.
(Does it make sense?)

**Comment by fredludlow** [comment]
Thanks @ppillot, though it's Alex who is due most of the credit :)

Just an idea, but it would be nice if interactions (and distance measurements) updated as atoms are displayed and hidden, maybe StructureComponent.visibleAtoms -> Bitset representing which atoms are currently displayed (basically union of all atomic representations selection bitsets). Then you'd need a Signal on StructureComponent `atomicVisibilityChanged` or something?

**Comment by ppillot** [comment]
Sorry @arose for not giving credit where it is due! I suppose I was misled by Fred's PR length.

@fredludlow that's a good option too. We'd need to take into consideration the way the atom is represented (atomic representation or schematic representation) and wether this atom is displayed at all or not (because in one case the connection can be extended to the trace atom, and in the other case the connection should be deleted).

I have a related request: is it possible to get access to the list of all the computed contacts with their types and related atoms?

**Comment by fredludlow** [comment]
Further along those lines, I just made this which tracks which atoms are visible in an atomic representation
https://gist.github.com/fredludlow/ec6b9edd5e37a1769b21a41da3b764bf
You could look for other representation types as well/instead.

This is part of trying  to get inter-structure distances/interactions (see #323 and others) in a quick way without messing around in NGL internals, but I'm wondering whether it would be easier to do it properly (that would require Alex's help I think ;) )

Getting the data out would need something that can digest the intermediate results, I'd start by looking at the output from `calculateContacts` (unless @arose can think of an easier way I'm missing)
https://github.com/arose/ngl/blob/ts2/src/chemistry/interactions/contact.ts#L129

**Comment by ppillot** [comment]
I think I've found out a way to extract that data: the contact representation object includes a `contactStore` object with `index1` and `index2` arrays containing atom indices for each pair and `type` array storing at the same index the contact type.
For the record, contact types are defined in contact.ts such as:
```javascript
export const enum ContactType {
  Unknown = 0,
  SaltBridge = 1,
  CationPi = 2,
  PiStacking = 3,
  HydrogenBond = 4,
  HalogenBond = 5,
  Hydrophobic = 6,
  MetalComplex = 7,
  WeakHydrogenBond = 8
}
```

**Comment by ppillot** [comment]
I can't find this contactStore object anywhere, so I suppose that it has been removed from the repr object.
I would like to get the list of all residues pairs involved in a contact representation so that they could be highlighted individually.
Would it be possible to make this data available ?

**Comment by ppillot** [comment]
I've found it back, burried in `repr.bufferList.picking.contacts.contactStore` !
