### ISSUE TITLE
Representation-selection needs at least 3 residues to show up

### ISSUE THREAD

**Issue by moritzschaefer** [arose/ngl#414]
Using the template codepen (from the README), and adding custom representations for residue
1-4 (in red) 
and 
4-6 (in blue)
will only show the red part:
![image](https://user-images.githubusercontent.com/2714540/32954264-e58c989c-cbb2-11e7-8cfc-4e4745a690af.png)
Changing 4-6 -> 4-7, shows the blue part as well. It turns out that at least 3 residues are needed in any selection to render the selection. 
Here is a codepen to play around:

https://codepen.io/moritzschaefer/pen/vWWVma

is this a known issue?

**Comment by ppillot** [comment]
Yes, it's a current known limitation: at least 3 residues are required to display a cartoon. See #223
