### ISSUE TITLE
Distance representation not displayed on some configs, but Angle representation displayed as exepcted

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#415]
Hi, one of my user reported that he is not able to display lines in distance representations, but he can display angle representations just fine.
![mesure](https://user-images.githubusercontent.com/3930632/32955743-d8d905fa-cb84-11e7-982f-a391523c0089.jpg)
He tried the codepen for distance representation and aknowledged the same problem.
I had a look at the code for both distance representation and angle representation and saw that the former relies on a cylinder buffer when the later relies on wideline buffer.
Would it be preferable to base both measurements representations on the same wideline buffer? (I'd be happy to make a PR)

**Comment by arose** [comment]
In the ts2 branch I changed all measurements to use wide lines for a consistent look. See below for how the integrated measurements are displayed.

![screenshot 66](https://user-images.githubusercontent.com/272250/32963120-ccbbb78c-cb83-11e7-88e6-f515cc4f7e3c.png)

**Comment by ppillot** [comment]
Looks great! Do you think it should also go into v1.0 master branch?

**Comment by arose** [comment]
Thanks. I prefer not to, want to do only bug fixes in the v1 branch.

**Comment by ppillot** [comment]
I understand your choice. I can use ts2 branch in my application to circumvent this.

**Comment by arose** [comment]
thanks
