### ISSUE TITLE
ts2 branch: distance, angle, ... comments

### ISSUE THREAD

**Issue by hainm** [arose/ngl#417]
Hey,

super nice job to get these things done. It's very helpful for interactive. 

There are several things I think NGL can be enhanced:

- distance reps are only displayed if there are more than 1 distance.
- Disable changing size of stage container.
e.g: choose distance by "click -- click - click" (right now must be "click -- click -- click"). The former will exit the full screen mode.
- the end point of the angle does not point to correct atom center (intention?)

<img width="1254" alt="screen shot 2017-11-21 at 10 07 30 pm" src="https://user-images.githubusercontent.com/4451957/33108137-af3821b8-cf08-11e7-88bb-ee9b33801f19.png">

**Comment by arose** [comment]
> distance reps are only displayed if there are more than 1 distance.

I think I fixed that recently (https://github.com/arose/ngl/commit/0776154f21ee999de6a530ff1354cf11764e35d6)

> Disable changing size of stage container.
e.g: choose distance by "click -- click - click" (right now must be "click -- click -- click"). The former will exit the full screen mode.

The fullscreen on double-click option is something applications add, as far as i can remember it is not part of ngl itself.

> the end point of the angle does not point to correct atom center (intention?)

Hmm, the dihedral measurement might need some more tweaks, @fredludlow, maybe two additional helper lines to the first and last atom?

**Comment by fredludlow** [comment]
> > the end point of the angle does not point to correct atom center (intention?)

>Hmm, the dihedral measurement might need some more tweaks, @fredludlow, maybe two additional helper lines to the first and last atom?

Like this?
http://fredludlow.com/ngldev/examples/webapp.html?script=representation/dihedral
fredludlow/ngl@5f3a9c0

That makes it much more obvious when you pick unusual dihedral measurements but will for the most part be hidden by other representations when you pick a "standard" bond torsion or improper torsion.

**Comment by arose** [comment]
Yes, helpful and looks nice

![screenshot 67](https://user-images.githubusercontent.com/272250/33146677-066285fc-cf7a-11e7-8a97-e26d9bdbb084.png)

**Comment by hainm** [comment]
> I think I fixed that recently (0776154

indeed.

> The fullscreen on double-click option is something applications add, as far as i can remember it is not part of ngl itself.

yeah, updated https://github.com/arose/nglview/blob/master/js/src/widget_ngl.js#L105.

**Comment by hainm** [comment]
Few other things:

- distance should be recalculated if coordinates is changed. [figure below]
- how can nglview get the data? (saying I want to create a widget to hold all info (atom selection, distance)
- how can I clear all distance or angle reprs? (tried with `view.clear_distance` but does not work (view.remove_cartoon does))

<img width="1267" alt="screen shot 2017-11-23 at 2 09 22 am" src="https://user-images.githubusercontent.com/4451957/33161750-9413e67e-cff3-11e7-981b-f8308143b5b8.png">

**Comment by hainm** [comment]
> distance should be recalculated if coordinates is changed. 

may be nglview should handle this? (if so, which code I should use?)

**Comment by hainm** [comment]
- 2nd click to 1st atom should unselect it. e.g: user click it by mistake or just undo the click.

**Comment by arose** [comment]
> distance should be recalculated if coordinates is changed.

fixed, was a bug

> how can nglview get the data? (saying I want to create a widget to hold all info (atom selection, distance)

there is currently no clear api, please make another ticket

> how can I clear all distance or angle reprs?

added `structureComponent.removeAllMeasurements(bitFlag)`, 1 for distance, 2 for angle, 4 dihedral, not given for all

> 2nd click to 1st atom should unselect it

added that behavior

**Comment by hainm** [comment]
kool. Works nicely (except the `removeAllMeasurements`, still need to figure how to call that in nglview properly).

- The label is a bit small (compare to the distance line) if zooming out.

<img width="1160" alt="screen shot 2017-11-27 at 9 56 17 pm" src="https://user-images.githubusercontent.com/4451957/33300523-d5ccbcf2-d3be-11e7-9291-01568f9d6913.png">

**Comment by hainm** [comment]
It seems that distance selection does not work on my machine with centos 7.
How can I check if I am using correct NGL version? (I am sure the nglview js code is correct (saw my changes)).

**Comment by arose** [comment]
What is not working? Can you try here: http://nglviewer.org/ts2/test.html?script=interactive/ligand-viewer.

**Comment by hainm** [comment]
that example does not work for me (Alt-click).

**Comment by hainm** [comment]
Alt-click does not highlight the atom.

**Comment by arose** [comment]
Changed the key modifier to do measurements from alt to ctrl (see 56490d8eb45db3ee50566b502c921af4dbb8e04e) as alt drags the window on some linux distros and is not emitted in the browser.

**Comment by hainm** [comment]
thanks, saving one key stroke for "fn" on mac.
