### ISSUE TITLE
ts2 branch: scale parameter not applied to spacefill representation

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#418]
To highlight atoms I add a spacefill representation over them, using a scale parameter. Switching to the ts2 branch, I've noticed that the spacefill representation doesn't take in account the scale parameter and that atoms appear  with their VdW radii.
`stage.compList[0].addRepresentation('spacefill', {scale: 0.3})`

**Comment by arose** [comment]
I renamed them: radiusScale, radiusSize, radiusType

**Comment by ppillot** [comment]
Thanks, it now works!
