### ISSUE TITLE
Browser jumps automatically to the viewer position

### ISSUE THREAD

**Issue by gbayarri** [arose/ngl#420]
When I put an NGL Viewer in the bottom part of a page, the browser jumps automatically to the viewer as if there were an anchor link in the viewport div.

Here you can find an example: 

http://mmb.irbbarcelona.org/webdev/test/

Is there any way to disable this feature? I want to load the top of the pages, not the part where the NGL Viewer is.

**Comment by arose** [comment]
That is because the canvas was 'focused' on be default. Changed it here 25bd7e21361eeaf614764b17b592748f2bf34350. Will release in a bit.

**Comment by arose** [comment]
released as ngl@1.0.0-beta.7

**Comment by hainm** [comment]
include distance selection too, right?

**Comment by arose** [comment]
no, that is in the ts2 branch

**Comment by gbayarri** [comment]
Thanks, Alexander!
