### ISSUE TITLE
Disabling the default tooltip?

### ISSUE THREAD

**Issue by fcharih** [arose/ngl#421]
Great visualization engine! I implemented my own tooltip whose content lives in a React component's state and I am looking for a way to disable the default tooltip that is triggered when an atom is hovered. Is there an easy way to do that?

Thank you!

**Comment by gbayarri** [comment]
Hi, you can enable / disable the flag when creating the stage:

stage = new NGL.Stage( "viewport", { tooltip:false } );

**Comment by hainm** [comment]
@arose  I think it's better to have application to turn it on rather make ON as default. In current nglview version, the tooltip is on in non-full screen mode and off in full screen (nglview does not change anything).

**Comment by arose** [comment]
It is a bug that it is off when in fullscreen but I am not sure why it is in nglview. It works in the example webapp.
