### ISSUE TITLE
Limit zoom-in and zoom-out 

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#426]
I have encountered users who zoom into the scene as much as they can (even if the scene doesn't change anymore) and assess that they are then unable to zoom out (I know: they deserved it !)
I have nonetheless tried to reproduce the behaviour and realized that zooming out is always possible but requires more scrolls than zooming in.
Another test, just doing repetitive scrolls forward and backward by the same amount have the actual effect of zooming in the structure.

I had a look at the code and found the following lines in viewer-controls.js which might be the culprit for this inconsistency between zooming in and out
`zoom (delta) {
    this.distance(this.viewer.camera.position.z * (1 - delta))
  }`

I had never noticed it before, so the math approximation (1 - delta ≈ 1 / (1 + delta) )is probably good enough.
The improvement I think would be beneficial, is to limit the zoom to the maximum value reached when the view stops being changed.

**Comment by arose** [comment]
good point, should be fixed with f56da5b8e3a96de12a60dac0e7d9e82348132b7c

**Comment by ppillot** [comment]
Indeed!
Thanks @arose
