### ISSUE TITLE
support viewgrid?

### ISSUE THREAD

**Issue by hainm** [arose/ngl#430]
hi,

the use case here: suppose user have 8 ligands and want to view them in the same screen and the camera orientation is linked.

3Dmol has pretty nice feature here:

<img width="1006" alt="screen shot 2017-12-02 at 1 44 57 am" src="https://user-images.githubusercontent.com/4451957/33512670-a166b732-d702-11e7-8eae-279271a3970a.png">

**Comment by arose** [comment]
I started something similar a while ago but haven't made it into a class yet. See https://github.com/arose/ngl/blob/master/examples/grid.html

**Comment by hainm** [comment]
do you have online version? I am sure I did something wrong in my computer.

<img width="1275" alt="screen shot 2017-12-04 at 7 55 43 pm" src="https://user-images.githubusercontent.com/4451957/33584413-3c7ab832-d92d-11e7-8d23-eed6ebd83db0.png">

**Comment by arose** [comment]
fixed here 2463b8fc91e1830b5595a783e3e507b70f2730ed

**Comment by hainm** [comment]
nice, thanks.

<img width="1227" alt="screen shot 2017-12-04 at 8 35 25 pm" src="https://user-images.githubusercontent.com/4451957/33585507-a61237a2-d932-11e7-9651-457f606d68d7.png">
