### ISSUE TITLE
ts2 branch: bug with unusual PDB files

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#431]
Hi, I have files in "PDB" format inherited from a former version of the virtual macromolecular museum.
These files use to load fine with NGL v1, but in TS2 they make the browser crash.
I have notices that the "loading" debugging message is logged in the console, but the "loaded" message never appears. The screen stays blank, the browser freezes and the computer fans roar until I force quit the browser.

[quartz.pdb.zip](https://github.com/arose/ngl/files/1525688/quartz.pdb.zip)

**Comment by arose** [comment]
thanks, fixed here 1d3204cb22c324d69323c43b404694017f83665b

**Comment by ppillot** [comment]
Thanks for the fix !
