### ISSUE TITLE
Wrong atom count (x2) with cif files

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#432]
Hi, I loaded a [cif file for glucose](http://files.rcsb.org/ligands/view/GLC.cif) from PDB ligand (id GLC) in NGL and got a weird atom count: 48 atoms total. If I select only carbon atoms, I get 12 of those
The structure.atomStore appears to have this double count.
<img width="1101" alt="capture d ecran 2017-12-04 a 17 13 41" src="https://user-images.githubusercontent.com/3930632/33579262-2ce8cb72-d917-11e7-9a24-0afbcf4d3243.png">
I had a look to the coordinates of these supplementary ghost atoms and noticed that they are not the same as the others... (I expected these to be a simple duplication) 
This behaviour only appears with this kind of files (not with SDF files from PDB ligand), both in master branch and in ts2

**Comment by arose** [comment]
That looks ok to me. The ligand cif files contain two sets of coordinates (from a structure model and computationally optimal). I handle it in NGL by creating two models, one for each set of coordinates.

**Comment by ppillot** [comment]
Thanks that explains a lot! I forgot that I had a component.setSelection('/0') hidden somewhere...
