### ISSUE TITLE
How load multiple files in different scripts on the same page

### ISSUE THREAD

**Issue by wandreveloso** [arose/ngl#437]
Hi,
I'm trying to do this:
When the page Loads, then I load an Protein file (PDB) without ligands and, when the user push buttons on the HTML page, every ligand will be appear.

After this, when the user click on the same button again, the ligand have to be removed. I know that I have to write something like this: `stage.removeComponent(component)`

I try to do this, but cannot works:
When the page loads:
` <script>
      document.addEventListener( "DOMContentLoaded", function() {
      var stage = new NGL.Stage( "viewport", {backgroundColor: "white"});
        stage.viewer.container.appendChild(tooltip);
        stage.loadFile("{{ url_for('static', filename=pdb_filename+'.pdb') }}").then( function(
          comp )
          {
            comp.addRepresentation( "surface", { multipleBond: true, sele: "not hetero", opacity: 0.6} );
            comp.addRepresentation( "cartoon", { sele: "not hetero" } );
            comp.autoView();
          }
        );
    } );
    </script>`
When click the button:
`<script language="Javascript">
            function load_ligand(lig_id)
            {
              stage.loadFile("{{ url_for('static', filename=lig_id+'.sdf') }}").then( function(
                comp )
                {
                  comp.addRepresentation( "ball+stick", { multipleBond: true} );
                  comp.autoView();
                }
              );
            }
          </script>`

**Comment by wandreveloso** [comment]
@arose

**Comment by arose** [comment]
Could you make a CodePen (https://codepen.io/pen?template=JNLMXb) with what you have tried? Thanks.

**Comment by wandreveloso** [comment]
It is here: https://codepen.io/anon/pen/bYPopB?#

**Comment by arose** [comment]
there are no ligands

**Comment by wandreveloso** [comment]
In my case, all the molecules are local... In this case I try to adapt my problem.
I create a button that will be load a new protein in the same viewport, but does not work.

**Comment by fredludlow** [comment]
Your script at the top (in the HTML script tag) references the stage but the stage is declared inside your DOMContentLoaded callback. Quick fix is to make stage a property of window:

`var stage = ...`
becomes
`window.stage = ...`

https://codepen.io/fludlow/pen/RjzEJv

**Comment by wandreveloso** [comment]
@fredludlow Now I see this.
So, now I understand how to insert a new molecule to the same stage. How to remove? I'm trying to transform the button in my interface into a checkbox, that, when checked, the molecule appears and, not checked, the component are removed.
In `stage.removeComponent(component)`, I don't know what is this parameter...

**Comment by fredludlow** [comment]
The `component` is returned asynchronously from `stage.loadFile`

More correctly: `stage.loadFile(...)` returns a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) object that resolves to the component. It's the `comp` variable in this bit:


```javascript
stage.loadFile("rcsb://1crn").then( function(comp) {
            comp.addRepresentation(...)
})
```

So you need to either store those components somewhere, or get them using
[stage.getComponentsByName](http://nglviewer.org/ngl/api/class/src/stage/stage.js~Stage.html#instance-method-getComponentsByName)

I've updated the pen with a toy example
https://codepen.io/fludlow/pen/RjzEJv

There's a lot that could be improved in that example, but hopefully it gets you a bit further!

**Comment by wandreveloso** [comment]
Thanks @fredludlow and @arose ! This works for me perfectly!
