### ISSUE TITLE
MMTF loading

### ISSUE THREAD

**Issue by BernierCR** [arose/ngl#438]
I can't get NGL to load MMTF files anymore. Neither my version nor your demo site can load my MMTF files. I get "TypeError: Cannot read property 'atomNameList' of undefined".  

I think this was just working. Something wrong with my computer today?

**Comment by arose** [comment]
Which sites are not working for you? Both http://nglviewer.org/ngl/ and http://nglviewer.org/ngldev/ work for me.

**Comment by BernierCR** [comment]
OK. It turns out there are bugs with the encoder in mmtf-python. Original MMTF files work fine. I will use those. Thanks.

**Comment by arose** [comment]
ok, please create issues in the mmtf-python project if you can, thanks
