### ISSUE TITLE
Questions about contacts in NGL v2 dev branch

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#439]
Hi, I've played a bit with contacts trying to understand how they work and I have several questions regarding what I might have guessed

1- When are contacts computed? are they computed when the structure is loaded or only after a contact representation has been added?

2- Are all contacts types computed at the same time? I am under the impression that the contactStore object contains all contact types even if the representation has been restricted to only a subset of them. If this is the case, I could rely on this contact store to get a meaningful list of all contacts as soon as they have been computed.

3- Regarding the different types of hydrogen bonds, 4 categories are made available
- hydrogen bonds
- water hydrogen bonds
- backbone hydrogen bonds
- weak hydrogen bonds
Water hydrogen bonds are bonds between 2 water molecules
Backbone hydrogen bonds are bonds between 2 atoms belonging to the protein backbone. All hbonds involved in the secondary structure fall in this category, which may make these not so relevant depending on user's purposes
Categorization as a weak hydrogen bond is based upon donors and acceptors atom types.
Lastly, whichever bond doesn't fall into any of the previous categories would be part of the hydrogen bonds category.
I suppose that these categories have been established assuming that hbonds falling in the "hydrogen bonds" set are generally the most relevant to most users when studying interactions in a molecular model?

4- I've tried to display metal coordination with Zn in carboxypeptidase (5CPA) and could not get any interaction displayed. Should I submit an issue for that one?

**Comment by arose** [comment]
1) when the contact representation is added
2) all are created at the same time (needed to do refine which ones to display/are possible in case there are multiple)
3) all assumptions correct
4) works for me (maybe because I use a more recent version)

![screenshot 69](https://user-images.githubusercontent.com/272250/33792122-21d82262-dc4d-11e7-92fa-b16460d5fb41.png)

**Comment by arose** [comment]
2) all type but only for the given selection

**Comment by ppillot** [comment]
Thanks!
2. does it mean that the contactstore is updated when the representation selection is set to a new value?

**Comment by arose** [comment]
yes it is. However the features (e.g. hbond acceptor, ...) are not recalculated so it should be faster

**Comment by ppillot** [comment]
Ok. Thanks
