### ISSUE TITLE
parameters to filter or improve selection for contacts

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#440]
I am currently playing with contacts and I am trying to display interactions pertaining to a specific residue.
To achieve this, I have created a selection around the residue using structure.getAtomSetWithinSelection(new NGL.Selection('6:B and sidechain'), 4.1)
When I display the representation of the contacts using this selection as a value for the sele parameter, I get also neighbouring contacts involving pairs of atoms that are not part of the residue I am interested in.
Here is the result with PDB 2HBS and the iconic Val6 from chain H involved in an hydrophobic contact (other contacts such as HBonds are visible but undesirable)
<img width="719" alt="capture d ecran 2017-12-11 a 22 01 32" src="https://user-images.githubusercontent.com/3930632/33865260-ea6898a6-debe-11e7-84d4-19f7ea8dc6e1.png">

So, here is my question (or request): is it possible to display only a subset of the contacts from a contact representation? 
I can think of 2 sele parameters, representing the 2 subsets between which the user would like to display interactions (here it would be '6:B' and the other subset 'not 6:B', but in other cases it could be used to spot the interactions between two chains)

**Comment by arose** [comment]
just added a parameter 'filterSele' to the contact repr, see c73b95a238db6524c6035a61a4469a1e1100082b

**Comment by ppillot** [comment]
It works beautifully!
<img width="719" alt="capture d ecran 2017-12-12 a 13 38 29" src="https://user-images.githubusercontent.com/3930632/33902076-e2d3c326-df41-11e7-9842-5c1e21ca0763.png">
Thank-you @arose
