### ISSUE TITLE
too big unit cell in 1waq

### ISSUE THREAD

**Issue by wojdyr** [arose/ngl#448]
I opened 1waq and added unit cell:

![screenshot](https://user-images.githubusercontent.com/491873/34987868-8f28e132-fab4-11e7-9724-0c3c96489b80.png)

I didn't look into details, but the cell looks too big. In Coot it's much smaller.

**Comment by arose** [comment]
5O3W has issues too

**Comment by arose** [comment]
both examples good now

![screenshot 74](https://user-images.githubusercontent.com/272250/35952822-af9f6204-0c36-11e8-9ba3-c5c19bfeb698.png)

![screenshot 73](https://user-images.githubusercontent.com/272250/35952825-b54e67b8-0c36-11e8-9154-5df671cabbb1.png)

**Comment by arose** [comment]
thanks @wojdyr and @josemduarte for finding this

**Comment by josemduarte** [comment]
Nice, thank you!

**Comment by ppillot** [comment]
@arose, how did you make the green outline around the ribbons in your pictures?

**Comment by arose** [comment]
just a ribbon representation
