### ISSUE TITLE
Non-real bonds in multimodel PDB structure

### ISSUE THREAD

**Issue by gbayarri** [arose/ngl#449]
Hi, after updating to the last version (1.0.0-beta.7), I've realized that the multimodel PDBs have bonds between the different models. It doesn't happen with the 0.10.5-21 version.

1.0.0-beta.7 (note the bonds between C and H of different models):

![screenshot-2](https://user-images.githubusercontent.com/19928100/35042077-663e9248-fb87-11e7-8aea-3f93090c6335.png)

code: [http://mmb.irbbarcelona.org/webdev/test/](http://mmb.irbbarcelona.org/webdev/test/)

0.10.5-21 (correct visualization):

![screenshot-1](https://user-images.githubusercontent.com/19928100/35042104-7d232a46-fb87-11e7-818f-a48614520eb7.png)

code: [http://mmb.irbbarcelona.org/webdev/test/index2.html](http://mmb.irbbarcelona.org/webdev/test/index2.html)

Both codes and PDB files are exactly the same, I've just changed the NGL version.

**Comment by arose** [comment]
fixed ngl@2.0.0-dev.16, see http://nglviewer.org/ts2/?script=parser/pdbqt

issue also described in #460

**Comment by gbayarri** [comment]
Thanks @arose !
