### ISSUE TITLE
Tube representation parameter size "bfactor"  isn't working in ts2

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#453]
Is it something known?

**Comment by arose** [comment]
the radius parameters has been renamed to be more consistent: radiusSize, radiusScale, radiusType, radiusData

**Comment by giagitom** [comment]
It seems that the parameter radiusType isn't updated when I use setParameters.

**Comment by arose** [comment]
> It seems that the parameter radiusType isn't updated when I use setParameters.

fixed in ngl@2.0.0-dev.17, try here http://nglviewer.org/ts2/?load=rcsb://1crn

**Comment by giagitom** [comment]
Thanks!
