### ISSUE TITLE
Custom XHR backend while loading .dcd file from remote

### ISSUE THREAD

**Issue by esanzy87** [arose/ngl#454]
I have experienced some difficulties loading .dcd file from remote because of some security issue, XHR backend need to pass api token to server. Although NGL.autoLoad not supports this, I found how it could work and I want to share my code.

First, this is wrong code that I tried first

```
axios.get('some url...')
  .then(resp => {
      const traj = new Blob([resp.data], {type: 'application/octet-stream'})
      return NGL.autoLoad(traj, {ext: 'dcd'})
  })
```

And below is code that works.

```
axios.get('some url...', {responseType: 'arraybuffer'})
  .then(resp => {
      const traj = new Blob([resp.data], {type: 'application/octet-stream'})
      return NGL.autoLoad(traj, {ext: 'dcd'})
  })
```

So I think adding this example to user manual or reference could be helpful to someone like me.
Thank you!

**Comment by arose** [comment]
Thanks @esanzy87
