### ISSUE TITLE
stage.tasks.signals.countChanged error after updating a surface representation

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#455]
Hi, this [pen](https://codepen.io/giagitom/pen/XVwEoY?editors=0010) should clarify what i mean. In the console is thrown an error: Maximum call stack size exceeded at e.setParameters

**Comment by arose** [comment]
don't see that in the latest version anymore, see https://codepen.io/arose/pen/QQyVKr?editors=0010

**Comment by giagitom** [comment]
Thank you!
