### ISSUE TITLE
Is it possible to load an unstructured grid file?

### ISSUE THREAD

**Issue by lyl472324464** [arose/ngl#456]
Or easier is it possible to slice a volume component from any directions?
Can I write something like removeRepresentation("cartoon") ?By now I just know removeRepresentation(reprList[0]).But this is not easy to use.Thank you. @arose

**Comment by lyl472324464** [comment]
I want to load three .pdb.How can I make sure that the order of this three .pdb in the compList is the same as the one when I loaded them?

**Comment by ppillot** [comment]
You can use `r = stage.getRepresentationsByName(´cartoon’).first` Assuming you only have one representation named cartoon to retrieve it. You can add a `name` parameter to your representation (default is the type of representation used) if it makes it easier to track it for further editing.

**Comment by arose** [comment]
> I want to load three .pdb.How can I make sure that the order of this three .pdb in the compList is the same as the one when I loaded them?

I suggest to use `stage.getComponentsByName('file.pdb')` and not rely on the order in compList.

> Can I write something like removeRepresentation("cartoon")

@ppillot's suggestion is good. I also just added (3b993917b9c75f5a74227b4facc5b9298e98f7fa, still need to build a release) a `.dispose()` method to the collection object returned by `stage.getRepresentationsByName()` so you will be able to do `stage.getRepresentationsByName(´cartoon’).dispose()`.

**Comment by arose** [comment]
> Or easier is it possible to slice a volume component from any directions?

no, not possible, slicing only works in x, y, z direction

**Comment by lyl472324464** [comment]
Thank you. @ppillot @arose
