### ISSUE TITLE
Possible bug with selections in ts2

### ISSUE THREAD

**Issue by DAlvGar** [arose/ngl#457]
Hi all,

I am migrating from NGL 1 to current version of NGL 2 (branch ts2) and I have some unexpected behavior with the selections that were perfectly working before. Either something has changed that I am not aware of or I might have found a bug. 

Here are the steps to reproduce the behavior :

```javascsript 
stage.loadFile("rcsb://1atp").then(function(o){
	o.addRepresentation("cartoon"); 
	o.addRepresentation("licorice",{sele:":I and 21"}); // Works OK and residue 21 in chain I is represented in licorice
	o.addRepresentation("licorice", {sele:":I and 18"}); // This selects all the chain I :(
	o.addRepresentation("licorice", {sele:":I and (21 or 18)"}); // Same error as before
        o.addRepresentation("licorice", {sele:"18"}) // Will select all the protein both chains whereas selecting the 21 will work ok
})
```

Thanks for your help and for the excellent work :)

**Comment by ppillot** [comment]
This behaviour is expected if `18` is not defined in the file. Which PDB are you referring to?

**Comment by ppillot** [comment]
Ok I see, it's 1atp ;-)

**Comment by ppillot** [comment]
Well you're right, I can reproduce this problems. Nonetheless `18:I` would work

**Comment by DAlvGar** [comment]
Thanks Paul! I will use your tip.

**Comment by arose** [comment]
I consider this a bug, `18` should only select residue 18 from chain I

**Comment by arose** [comment]
should be fixed now, try here http://nglviewer.org/ts2/?load=rcsb://1atp

**Comment by DAlvGar** [comment]
Thank you Alexander, it works nicely.
