### ISSUE TITLE
A question about angle and dihedral repr

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#458]
Hi, is it currently possible to draw dihedral and angle repr in a pymol like fashon? Like this I mean:

![image](https://user-images.githubusercontent.com/20627977/35581400-f505e4f4-05eb-11e8-987e-a3bc6f532e20.png)

**Comment by arose** [comment]
the angle yes (http://nglviewer.org/ts2/?script=representation/angle), but the dihedral looks a bit differently (http://nglviewer.org/ts2/?script=representation/dihedral)

**Comment by fredludlow** [comment]
The dihedral with `{planeVisible: false, sectorVisible: false}` won't look quite the same but is closer. (Also just noticed that changing planeVisible doesn't trigger a rebuild, I'll fix that)

**Comment by giagitom** [comment]
Thanks. Is it something hard to implement a parameter to hide the connectors and a parameter to draw the two lines making the sector perimeter?
