### ISSUE TITLE
Extend picking to measurements (distance, angle, dihedral)

### ISSUE THREAD

**Issue by arose** [arose/ngl#46]
The picking code is sufficient but some representations/helpers are needed to display the measurements.

**Comment by fredludlow** [comment]
I've just been looking at how I might go about adding distance measurements (particularly between atoms in different structures) and remembered this issue. 

I was thinking I'd just write a helper that for my interface that watched what had been picked and added some appropriate `Shape` objects - but if you've got any plans or good ideas about how to do it (either in NGL or externally) it would be good to know..

**Comment by fredludlow** [comment]
Bumping this issue: I know we discussed this briefly, but what needs to be done to enable this within NGL? I've got some time to work on this if there's something useful I can do...? Or is it something that fits better at a higher level (outside of NGL)

If it were going to be part of NGL itself:
* Who owns the representations? (if they're measuring distances between atoms in different structures)
* Should the user specify "distance picking mode" then pick some atoms? Or have a concept of selected atoms (and order they were selected) so user selects first and then invokes 'addDistance' which looks at which atoms are selected.

Sorry that's a load of questions and no concrete suggestions ;)

**Comment by ppillot** [comment]
I like the way it is handled in Jmol: double clicking an atom starts picking and a dashed line is displayed between this atom center and the cursor. When the cursor hovers another atom, the dashed line is magnetized and attach to this atom while a distance is displayed. The representation is definitely added when the user validates by double clicking on the target atom.
Measures are canceled by clicking outside the representation.
Angles are measured by making a single click on the "angle" atom.

**Comment by arose** [comment]
A first step would be adding AngleRepresentation and DihedralRepresentation, those could be used to efficiently bring a lot of measurements on the screen, limited to be within a structure.

For more interactive, user driven measurements a separate Measurements class seems better. It would not work as a StructureRepresentation but create spheres and cylinders to show measurements the user wants to see. That way there no limitation from which structure (or volume) the position comes at which some measurement object is drawn.

**Comment by fredludlow** [comment]
Makes sense: I'll start with `AngleRepresentation extends StructureRepresentation` as that should fit nicely into the existing types. 

There's a couple of places to avoid duplication: 
* Distance|Angle|DihedralRepresentation will share a lot of parameters (labelSize, offset etc) so having an intermediary `MeasurementRepresentation` type might be good?
* The Measurements class will need to directly or indirectly own some `Buffer` instances for its own spheres/cylinders/lines etc. The code that builds these from a set of coordinates will be the same. Not quite sure what the best way to arrange this is, but maybe a `DistanceFactory` or `DistanceHelper` which turns coords to `Buffer` isntances? 
Anyway - I'll keep the atoms->coords and coords+parmas->buffers parts separate for now and we can worry about the rest later..

**Comment by arose** [comment]
Having an "intermediary MeasurementRepresentation" sounds good. 

> I'll keep the atoms->coords and coords+parmas->buffers parts separate for now and we can worry about the rest later

Good

**Comment by fredludlow** [comment]
Working draft for dihedrals/angles:
http://fredludlow.com/ngldev/examples/webapp.html?script=representation/dihedral
http://fredludlow.com/ngldev/examples/webapp.html?script=representation/angle

The odd looking dihedral is an improper (_cf_. forcefield planarity constraints)
Code here:
https://github.com/fredludlow/ngl/tree/angle-repr

I've tried to pull as much common code into a MeasurementRepresentation class as well as keep the various steps separate (with the intention of having a structure-agnostic measurement class in due course). 

Feedback on any aspect gratefully received! (the functions that build position arrays are quite verbose as I'm trying to avoid re-calculating the same thing multiple times, but there might be a better way)

**Comment by ppillot** [comment]
They look nice. Is there a parameter to display a unit (°) after the measure ?

**Comment by hainm** [comment]
@fredludlow  really cool.

**Comment by arose** [comment]
Haven't looked at the code yet but to rendering looks great!!!

**Comment by ppillot** [comment]
Hi Fred, I've successfully tried your branch (one of my users asked about an angle measurement feature) and noticed a discrepancy regarding how the opacity parameter is handled between the distance representation and the angle representation: opacity affects only the vertices in the distance representation, whereas it affects both vertices and labels in the angle representation
![capture d ecran 2017-10-07 a 12 40 03](https://user-images.githubusercontent.com/3930632/31309936-af951762-ab5c-11e7-85aa-b866ed8a2156.png)
Here is a screenshot presenting both representations with `{ labelColor: 0x000000, opacity: 0.5 }`

**Comment by fredludlow** [comment]
Yup, that's not quite intended behaviour!  Will fix that and add unit option

**Comment by arose** [comment]
It looks good! Can you do a PR? We can include it in the 1.0 release.

I like @ppillot's suggestions about the angle unit and the opacity param.

One thing that would be nice is planes (enclosed by the respective three atoms and the sector stem line) for the dihedral representation.

I am thinking about making the distance representation a (dashed) wide line as well so that there is a consist style for measurements.

**Comment by fredludlow** [comment]
Will fix outstanding issues, add planes and create a PR. 

@ppillot - Have gone with labels at fixed 100% opacity but can introduce (another) parameter if desired!

@arose - Dashed wide lines/consistency sounds good to me! (dashed lines on angle/dihedral would be good too)

**Comment by ppillot** [comment]
Opaque labels looks good to me! (I fear they'd be too hard to read otherwise)

A quick question about your code: why have you decided to go with low level functions for your angles calculation instead of Threejs' Vecto3D built-in methods ?

**Comment by fredludlow** [comment]
Hmm, I guess I'd seen the vector-utils functions used in surface/hash code and assumed that was the preferred way to do it (based on a lot of untested assumptions of mine about performance which are probably wrong), but searching the codebase now it looks like they're not used as much as I thought

I imagine in this particular case the real-world performance difference will be tiny, and Vector3 methods are probably easier to read, what do you think @arose?

**Comment by arose** [comment]
Has been done, default mouse controls are as follows

Right-mouse click (or Ctrl left-mouse click). Pick to select/deselect 1 to 4 atoms to start a measurement. Finish a measurement by picking an atom twice in a row. Picking no atom deselects all atoms.

**Comment by arose** [comment]
Thanks again @fredludlow, this turned out to be very nice!!!!
