### ISSUE TITLE
Open a pdbqt file format

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#460]
Hi, I am trying to open a pdbqt file format that contains the solutions of a docking with AutoDock Vina. This is the [link](https://www.dropbox.com/s/p301c5exiyrlvj7/sol.pdbqt?dl=0) to the file. It is like a multi model pdb file i think, but unnecessary inter-model connections are made. Is there something missing in the file to keep models separated?
![connectionsbetweenmodels](https://user-images.githubusercontent.com/20627977/35727028-1e213f38-0807-11e8-82ef-7e811c50608b.png)

**Comment by ppillot** [comment]
There is no CONNECT record in your file, thus NGL relies on autobonding

**Comment by arose** [comment]
There should be no bonds between models from autobonding, I will look into this.

**Comment by arose** [comment]
fixed in ngl@2.0.0-dev.16, see http://nglviewer.org/ts2/?script=parser/pdbqt

also added a pdbqt format to handle it a bit better (though it does not read the charge and type yet)

**Comment by giagitom** [comment]
Thanks. The pdbqt file I provided has been filtered to remove non wanted records such as (ROOT, ENDROOT, BRANCH, ENDBRANCH, TORSDOF). This is the original [file](https://www.dropbox.com/s/p301c5exiyrlvj7/sol.pdbqt?dl=0). 
Leaving this records, the models break.

**Comment by arose** [comment]
Improved the parser to ignore the extra records and also parse the partial charge (9630d9cf6efb96e15cbcb83e4b8260f656761cbf).

**Comment by giagitom** [comment]
It seems that columns 77 - 78 containing the atom's element symbol could be misleading in some pdbqt files.
Also I noticed something strange with this [file](https://www.dropbox.com/s/66frjw0rzq3nw5u/hem.pdbqt?dl=0). The ATOM record with atom name "NA" is interpreted by NGL as a sodium atom, but instead it should be a nitrogen atom. Does NGL takes into account that atom names are composed of an atomic (element) symbol in columns 13-14, and trailing identifying characters in columns 15-16?

**Comment by arose** [comment]
Thanks, improved the pdbqt parser to look for the element in columns 13-14 (ae3f2067f535d27a4a9bd662ef514f5346b64f55)

**Comment by giagitom** [comment]
Thank you! Only one thing.. I noticed  from dev.18 that the default representation has changed when you load a PDB file format. Sticks are drawn for the whole protein instead of the non-protein residues only.

**Comment by arose** [comment]
yeah I see that too, unintended side effect of ignoring some pdbqt records...

**Comment by arose** [comment]
Should be goo now, see http://nglviewer.org/ts2/?load=rcsb://1atp

**Comment by giagitom** [comment]
Perfect! Thank you!
