### ISSUE TITLE
Annotations outside the stage

### ISSUE THREAD

**Issue by gbayarri** [arose/ngl#461]
Hi,

I'm trying to add annotations to the proteins of a PDB file following the NGL gallery example named _interactive/annotation_.

The problem is that the annotations are shown outside the stage and in an absolute position respect to the browser. They interact with the viewport (i.e. if we rotate the object, they rotate, if we zoom, they zoom) and the positions seem to be correct between them, but they have an offset. Here you have a screenshot:

![screenshot](https://user-images.githubusercontent.com/19928100/35739216-38d32cc2-0831-11e8-8aab-0041c19e9310.png)

And here an interactive example:

http://mmb.irbbarcelona.org/webdev/test/annotations.html

The code is practically the same of the gallery example.

Tested with ngl.1.0.0-beta.7 and ngl.0.10.5-21.

Anybody knows how to fix that?

Thanks!

**Comment by ppillot** [comment]
It seems related to css positioning. Theses annotations have a fixed position setting and depends on the bottom coordinates for their vertical positioning. By shrinking vertically your window, you can move them back in place (just for testing).
I manually fixed it by setting the viewport container and each annotation block, `position` as `relative`.
I've checked the code source, and the `fixed` position setting is hardcoded there.
 I couldn't find back where the example is in the gallery. Can you give the link so that I could check what the css are ?
I guess this problem doesn't arise as long as the bottom part of your viewport is at the bottom of your web page.

**Comment by arose** [comment]
@ppillot the example is here http://nglviewer.org/ts2/?script=interactive/annotation

@gbayarri does it work with ts2 branch?

**Comment by gbayarri** [comment]
@arose It doesn't work. Actually, I shrunk the browser in the example you provided and the annotations are out of the viewport:

![screenshot](https://user-images.githubusercontent.com/19928100/35797956-a17712ac-0a61-11e8-9daf-4c7f0d0a3e16.png)

@ppillot I'm sorry, but I'm not able to find the css in order to change them. I've checked them via browser inspector and changing the position to relative, the annotations appear at the correct position, but they are still outside the viewport when zooming.

**Comment by ppillot** [comment]
The behaviour you are referring to in that test may have a different cause as it happens after resizing. Positions are correct but the boundaries to make the annotations visible (or not) are not updated after resizing of the viewport. Am I correct?

**Comment by ppillot** [comment]
I have made a codepen to replicate the problem with a centered viewport that does not extend to the bottom of the page: https://codepen.io/ppillot/pen/EQyVwQ 
<img width="907" alt="capture d ecran 2018-02-05 a 08 40 55" src="https://user-images.githubusercontent.com/3930632/35807332-6e47d99a-0a50-11e8-9333-30e6256cf0e2.png">
@arose : I can make a PR with changes in the css to address these concerns

**Comment by gbayarri** [comment]
@ppillot Exactly, it seems there are two bugs: position of annotations (can be solved changing position from fixed to relative) and visibility of annotations outside the viewport as you are showing in the example above.

**Comment by arose** [comment]
> I can make a PR with changes in the css to address these concerns

that would be great!

**Comment by gbayarri** [comment]
Fixed in the ts2 2.0.0-dev.24 version
