### ISSUE TITLE
Default parameters for MeasureRepresentation

### ISSUE THREAD

**Issue by jaimergp** [arose/ngl#463]
Hi,

is there any way to specify the default parameters for any `MeasureRepresentation` (distance, angle, dihedral) instance? The default `labelSize` is too small for my needs and I would like to increase the value for all instances created by picking atoms. I am using latest build from the new `ts2` branch. 

Thanks,
Jaime.

**Comment by arose** [comment]
Hi, added setMeasurementDefaultParams (e40635ccbbd33a643ca8f86954695ee5f636ba9d). Note that it will only affect structures loaded after changing the defaults.

```javascript
NGL.setMeasurementDefaultParams({
  color: 'green',
  labelColor: 'grey',
  labelAttachment: 'bottom-center',
  labelSize: 0.7,
  labelZOffset: 0.5,
  labelYOffset: 0.1,
  labelBorder: true,
  labelBorderColor: 'lightgrey',
  labelBorderWidth: 0.25,
  lineOpacity: 0.8,
  linewidth: 5.0,
  opacity: 0.6,

  labelUnit: 'angstrom',
  arcVisible: true,
  planeVisible: false
})
```

**Comment by jaimergp** [comment]
That's excellent. Thanks!
