### ISSUE TITLE
Centering on atom using viewer.animationControls.zoomMove cause clipping and fog planes to move

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#464]
Hi, if it is something wanted, is there a way to keep fixed fog and clipping planes?

**Comment by arose** [comment]
That is not possible with moving the camera around. However a workaround can be to move the models around using http://nglviewer.org/ts2/api/classes/component.html#setposition (and setRotation).

**Comment by giagitom** [comment]
Does this behavior has changed from master branch? Because If you try to middle-click over an atom [hear](http://nglviewer.org/ts2/?script=parser/pdbqt), the clipping planes cut almost totally the object

**Comment by arose** [comment]
I see, there seems to be a bug when using Orthographic camera

**Comment by arose** [comment]
try again here http://nglviewer.org/ts2/?script=parser/pdbqt

a related stage parameter is `clipDist`, which is the distance between camera and model at which near clipping should occur. If near clipping occurs to early for you set `clipDist` lower or switch it off by setting it to zero.

**Comment by giagitom** [comment]
Hmm.. it seems that the behavior persists for me, but i discovered that removing the middleclick drag action (zoom in out)  with 
```js 
stage.mouseControls.actionList[8]={}
``` 
the problem disappears

**Comment by arose** [comment]
The drag-middle mouse action is a combined zoom and focus. You should better remove it with `stage.mouseControls.remove('drag-middle')`.

I also see that the combined zoom and focus is not well tuned for looking at small molecules. I will try to tweak it.

**Comment by giagitom** [comment]
Thanks!
