### ISSUE TITLE
Drawing custom dashed lines for interactions without contacts

### ISSUE THREAD

**Issue by DAlvGar** [arose/ngl#465]
Hi all! 

I would like to draw the interactions between the ligand and the protein but using a set of pairs and types that we have precalculated. At the end, what i need is to add the dashed lines between the pairs, with a specific color and some pickup details. Is this already possible or is this something i could easily implement? I already had a look into the contacts representation in ts2. There you finally use geometry/dash. Can I use this object directly without going through the contacts? If so, how? I would appreciate some guide/tips!

Thank you!

**Comment by arose** [comment]
add option, use like `var shape = new NGL.Shape('shape', { dashedCylinder: true })`, will release later

**Comment by DAlvGar** [comment]
Thank you Alexander for the quick fixes! 

I could not manage to make the picker work though. It seems the data is lost in getFixedLEngthDashData. In examples/scripts/component/shape.js the picker is not working when dashedCylinder is true, and working otherwise. 

Also i would appreciate if you could point me where i could modify the picker hover text: to remove cylinder: and (shape) from it and keep only the label/name i am providing.

Thank you a lot!

**Comment by arose** [comment]
> I could not manage to make the picker work though. It seems the data is lost in getFixedLEngthDashData. In examples/scripts/component/shape.js the picker is not working when dashedCylinder is true, and working otherwise.

fixed

> Also i would appreciate if you could point me where i could modify the picker hover text: to remove cylinder: and (shape) from it and keep only the label/name i am providing.

fixed too, no more text is added to custom labels

**Comment by DAlvGar** [comment]
This is great! 👍 Thank you! :) 

By the way, i have some local modifications of ts2 in a private github repository: I added an atom serial based selection syntax and stored the PDB header lines when reading to be able to write them back (we were losing them when downloading the files from NGL and the crystallographers quickly complained :P). If you are interested, I can share these changes with you guys. Probably the coding for the PDB parser/writer enhancement is not so nice as yours though...

**Comment by arose** [comment]
Sounds great, feel free to make PRs!
