### ISSUE TITLE
Weird behavior with multiple dashed cylinders

### ISSUE THREAD

**Issue by DAlvGar** [arose/ngl#468]
Hi all,

I am using the recently implemented dashedCylinder shapes by @arose in ts2 and I am having some weird results:

![image](https://user-images.githubusercontent.com/15227264/35920366-f4bc3a8e-0c17-11e8-9839-8bc6f7a413a0.png)

I am adding 5 cylinders with the same origin and they should be displayed in a "star" like manner between the phosphate oxygen and several protein atoms around. What i finally observe are 4 cylinders with weird start and end points that do not correspond to the coordinates i provide or the number of cylinders i add.  

I get a correct display when i set dashedCylinder: false:

![image](https://user-images.githubusercontent.com/15227264/35920758-0c9172d6-0c19-11e8-9554-54604b131046.png)

Minimum working example using 1ATP as PDB already loaded in a stage only for reference:

```
var pos1=[17.549999237060547, 8.53600025177002, -0.5149999856948853];

var pos2=[[19.740999221801758,6.551000118255615,-0.546999990940094],
[19.969999313354492,5.958000183105469,-1.8380000591278076],
[18.88599967956543,6.414999961853027,-2.821000099182129],
[14.675999641418457,8.154000282287598,-3.7300000190734863],
[13.555000305175781,6.9029998779296875,-0.13099999725818634]];

var shape = new NGL.Shape('shape', { dashedCylinder: true, radialSegments:60});

for (var i=0; i<pos2.length; i++){
	shape.addCylinder(pos1, pos2[i], [ 1, 1, 0.4 ], 0.05, "My test "+i);
}
var shapeComp = stage.addComponentFromObject(shape)
shapeComp.addRepresentation('buffer')
shapeComp.autoView()
```

Do you have any idea what is going on? I guess the asynchronous execution of addCylinder is messing something up?

Thank you guys.

Daniel

**Comment by arose** [comment]
there are half of the segments missing for two dashed cylinders, I will have a look

**Comment by arose** [comment]
fixed, see http://nglviewer.org/ts2/?script=test/dashedCylinders

**Comment by DAlvGar** [comment]
Great thank you :)
