### ISSUE TITLE
Canvas does not resize with containing div

### ISSUE THREAD

**Issue by moritzschaefer** [arose/ngl#473]
When resizing the viewport-div that contains the ngl canvas, NGL doesn't detect the change and resize with it. Is there a way to make this happen? Click the button in the codepen to see the issue.

https://codepen.io/anon/pen/qxPzvg?page=1&

Expected behaviour (when resizing):
![image](https://user-images.githubusercontent.com/2714540/36264057-0267edc2-126c-11e8-91c9-6155950e6778.png)

Actual behaviour: 
![image](https://user-images.githubusercontent.com/2714540/36264043-f6073cf4-126b-11e8-8adf-00ad591f5bf7.png)

**Comment by ppillot** [comment]
The webpage only detects resize events triggered by the browser and resizing as you do doesn't trigger a resize event. You need to manually handle the resize. I modified your example by adding a stage.handleResize() command just after the style change. You can see it in action in this codepen fork: https://codepen.io/ppillot/pen/bLoXpW

**Comment by moritzschaefer** [comment]
awesome. thank you!
