### ISSUE TITLE
coloring by molecule

### ISSUE THREAD

**Issue by wojdyr** [arose/ngl#477]
I cannot find option to color cartoon by molecule (asymmetric unit). If it's not there please take it as a feature request.

To elaborate: Assembly AU colored by atomindex looks like this (it's 5CVZ):
![screenshot 4](https://user-images.githubusercontent.com/491873/36552017-d24f66d0-17f0-11e8-8625-f40c5b1e08a1.png)

Then I switch to Assembly BU1:
![screenshot 3](https://user-images.githubusercontent.com/491873/36552120-069d15e0-17f1-11e8-814f-fb381ac068e8.png)

I'd like to show BU1 with each molecule (AU) in a different color. Is it possible?

**Comment by arose** [comment]
Not with standard files from the archive. For efficiency reasons, the chains are transformed on the GPU and currently providing a separate color is not possible.

However you can load the files containing the full assembly and color by model index, see https://codepen.io/arose/pen/QQxPre?editors=0010.

![screenshot 76](https://user-images.githubusercontent.com/272250/36556497-3a493e78-17ba-11e8-9443-b5d66255d5c0.png)
