### ISSUE TITLE
alpha value?

### ISSUE THREAD

**Issue by hainm** [arose/ngl#48]
@arose 

does ngl support `alpha` option?

(http://3dmol.csb.pitt.edu/ check lower section)

**Comment by arose** [comment]
Yes, most representations have an `opacity` parameter. Related parameters are `side` (0: front, 1: back, 2: both) and `opaqueBack` to help mitigate artifacts arising from transparency.

**Comment by hainm** [comment]
cool. thx.

**Comment by hainm** [comment]
@arose 
is this the syntax? I don't see the difference

```python
view.add_representation('surface', color='blue', opacity=0.2)
```

**Comment by arose** [comment]
Yes, that should work. Looks ok for me, see below. Does it work for you in the ngl webapp?

![screenshot from 2016-01-27 21 32 36](https://cloud.githubusercontent.com/assets/272250/12635964/a4aee384-c53d-11e5-8a7b-508b201140c6.png)

**Comment by hainm** [comment]
look fantastic. will try again.

**Comment by hainm** [comment]
I can reproduce yours. close and thanks.
