### ISSUE TITLE
first residue number of the chain

### ISSUE THREAD

**Issue by demetturan** [arose/ngl#482]
Hi,
I am able to find the first residue number by using residueStore. However it gives the first chain's residue number. 
firstResidueNo = o.structure.residueStore.resno[0]

I would like to get residue number for each chain by using chain index or name. I suppose that I should use  chainStore.  But residueOffset of chainStore is not giving the first residue number of the given chain.

Is there any other way to get the first residue number of each chain?

Thanks

**Comment by ppillot** [comment]
to get the specific residue object from the id stores in residueOffset[], you can use the `structure.getResidueProxy()` method. It will give you a ResidueProxy object with the `resno` property.
Beware that in the residueOffset array, each chain can appear several times if several biological entities are present in the file (e.g. protein, ligand, water...), so you might want to add an extra step to your code to ensure that it's only the first residue per chain that you get.

**Comment by fredludlow** [comment]
There's one  instance of each `Store`, (`ChainStore`, `ResidueStore` etc) per structure. The residueOffset for a chain is the index of the first residue for that chain in the residue store, so if you want to access this stuff directly I'd do:
```javascript
var cp = structure.getChainProxy();
cp.index = 1;
console.log(cp.chainname) // "B"
var rp = structure.getResidueProxy();
rp.index = cp.residueOffset // Just an integer offset
console.log(rp.resno) // First residue number of chain B
```
Relatedly, and a bit to do with @ppillot's point about the "first in the file" vs "minimum number": 

You can use the `eachChain`, `eachResidue` functions to iterate without having to create proxies, set indices etc. Snippet below finds lowest numbered residue in each chain by iterating over all chains and each residue in each chain. (There are many ways to do this, but just wanted to flag up the iterators as they're quite handy)
```javascript
stage.loadFile( "rcsb://1bcc", { defaultRepresentation: true } ).then( 
    function(component) {
        var firstResidues = {};
        component.structure.eachChain(function (c) {
            c.eachResidue(function(r)  {
                var prev = firstResidues[c.chainname];
                if (prev == undefined || prev > r.resno) {
                    firstResidues[c.chainname] = r.resno;
               }
        
            })
        })
        
        console.log(firstResidues);
 });
```

**Comment by demetturan** [comment]
Chain and Residue relation is very clear now. I've realized that each chain can appear several times. Already took that into account.  Thanks!
