### ISSUE TITLE
Question about the 2D position from the mouse observer into an output of 3D position 

### ISSUE THREAD

**Issue by ilyiaZhao** [arose/ngl#485]
Hey! I am planning to get the 3D position of a specific sphere when I click on it. However, I notice that the mouse observer only return the 2D position vector of the page instead of the 3D position in the space. So how can I convert the 2D position vector into the 3D position vector? Or is there any function or method that can directly get the 3D position while the mouse clicking on a certain sphere?
Thank you so much

**Comment by arose** [comment]
You should use the 'clickPick' event: `stage.mouseControls.add("clickPick-left", function (stage, pickingProxy) { console.log(pickingProxy.position) });`
