### ISSUE TITLE
label fixedSize and x-yCutoff together make strange behavior

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#486]
This should explain the behavior (related to #484 ). It seems that, when fixedSize : true, the cutoff extent in x and y direction is influenced by camera zoom.
xCutoff : 10
fixedSize : true
![true](https://user-images.githubusercontent.com/20627977/36868357-637fae56-1d98-11e8-82fb-24dc676940ce.png)

xCutoff : 10
fixedSize : false
![false](https://user-images.githubusercontent.com/20627977/36868342-5a6a0f96-1d98-11e8-9576-0bfb7e403a47.png)

**Comment by arose** [comment]
should be good with above commit

**Comment by giagitom** [comment]
Thanks!
