### ISSUE TITLE
Adding PointBuffer to a shape

### ISSUE THREAD

**Issue by nmih** [arose/ngl#487]
Hi Alex - is it possible to currently add PointBuffers to a shape? See: https://codepen.io/nathanmih/pen/rJyGap/

Getting "Uncaught TypeError: NGL.PointBuffer is not a constructor" in the console.

As a side note here is a cellpack recipe as a bunch of spheres: https://codepen.io/nathanmih/pen/gvywmq

**Comment by arose** [comment]
PointBuffer is available now as `NGL.PointBuffer` with above commit

**Comment by nmih** [comment]
Great, thanks!
