### ISSUE TITLE
clear the current stage

### ISSUE THREAD

**Issue by corredD** [arose/ngl#488]
Hi, 

I am trying to clear the stage before loading a second protein, I used stage.removeAllComponents();. It seems to work for most representation but not for the cylinder used in DNA cartoon representation. Is that normal, should I use another function to reset/clear the current state of the viewer ?

Thanks in advance

**Comment by arose** [comment]
sounds like a bug, I will have a look

**Comment by arose** [comment]
Can you provide an example?

I tried http://nglviewer.org/ts2/?load=rcsb://1d66 and issued `stage.removeAllComponents()` in the console which remoes everything.

**Comment by corredD** [comment]
I was able to reproduce it in code pen, with two buttons. the first one clear and load a file with dna, the second one clear and load a protein. You should see that the cylinder are still there.
https://codepen.io/coredA/pen/XZQoqR
thanks !

**Comment by arose** [comment]
You are using an old version of ngl, use e.g. https://cdn.rawgit.com/arose/ngl/v2.0.0-dev.25/dist/ngl.js

it works with the latest https://codepen.io/arose/pen/xYemQY

**Comment by corredD** [comment]
Thanks for pointing this to me ! it easily fixed the problem !
I used the code-pen template you provided and it was pointing to the old version! I will try to be more careful next time.
thanks again

**Comment by arose** [comment]
And I should update the master branch and the template link...
