### ISSUE TITLE
StaticDatasource and OPM

### ISSUE THREAD

**Issue by corredD** [arose/ngl#489]
Hello, 

I am trying to load structure from the Orientation of Proteins in Membrane webserver directly from their website without any success. I tried using the StaticDatasource and then the loader directly.

NGL.DatasourceRegistry.add(
  "opm", new NGL.StaticDatasource("http://opm.phar.umich.edu/pdb/")
);

stage.loadFile( "opm://4b2q.pdb", { defaultRepresentation: true } );

stage.loadFile( "http://opm.phar.umich.edu/pdb/4b2q.pdb", { defaultRepresentation: true } );

Can you help me understand why this doesn't work ? 
Thanks in advance

**Comment by arose** [comment]
It does not work because the OPM server don't allow it, i.e. they don't have a 'Access-Control-Allow-Origin' header set. You can ask them to add one.

![screen shot 2018-03-05 at 2 11 58 pm](https://user-images.githubusercontent.com/272250/37002667-4f75b5a6-207f-11e8-8a9e-a1bf2c07e7e4.png)
