### ISSUE TITLE
Superimpose sub-selection

### ISSUE THREAD

**Issue by sbliven** [arose/ngl#49]
It is often useful to superimpose structures based on a single chain or selection. The most natural (for me) way to do this in NGL would be to filter two structures to the desired selections, superimpose them, and then remove the filters to show the unaligned portions as well. However, the superposition gets updated automatically after changing the filter. Should this behavior be changed to only update the superposition after manually selecting the Superpose option, or is there another way to superimpose based on a selection?

**Comment by arose** [comment]
Hi Spencer, I assume you are describing the GUI. There is currently no support for what you want. I created a gist that how you can script it though: https://gist.github.com/arose/60882b5e5a4f2275c565. A `.ngl` file is just a JavaScript file with access to the `stage` object. You can just drag`n`drop into the application. Hope that helps. It would still be nice to have a GUI that exposes this functionality.

**Comment by sbliven** [comment]
Thanks @arose
