### ISSUE TITLE
spin around one axis?

### ISSUE THREAD

**Issue by csulok** [arose/ngl#497]
Is it possible to create e.g. ctrl+drag event such that you can spin the stage around z axis or whatever is perpendicular to the viewport? that should make it easier to examine biological units with some sort of rotational symmetric or pocket through the middle.

**Comment by arose** [comment]
you can change the axis of the stage spin animation to rotate around the z axis `stage.spinAnimation.axis.set(0, 0, 1)` which is bound the 'i' char. You can also create your own animation and bind it to a mouse action.

**Comment by csulok** [comment]
With ctrl+drag I meant mouse control, not animation. Is that possible?

**Comment by arose** [comment]
Added a mouse action, see above commit

**Comment by csulok** [comment]
this is actually perfect, thank you :)
