### ISSUE TITLE
Picking opaque residues

### ISSUE THREAD

**Issue by RasmusFonseca** [arose/ngl#498]
I'm trying to detect mouse hover and click on a highly transparent cartoon (it will respond by adding a non-transparent ball-and-stick representation). I noticed that events over objects with opacity below 0.7 aren't picked up by `stage.signals` listeners, probably because of these lines:

https://github.com/arose/ngl/blob/8acee6989d61b1f0027bc57c8d90589b44d28f95/src/shader/Mesh.frag#L45-L46

Is there a way to change this behavior without recompiling?

**Comment by arose** [comment]
No, you will need to recompile. What opacity threshold would be acceptable for you?

**Comment by RasmusFonseca** [comment]
Playing around with it just now I was hoping to aim for 0.3 for my application. What's the use-case for having it there at all? Is it the same Mesh that's used for surfaces?

**Comment by arose** [comment]
changed the threshold to 0.3, seems better in general, thanks

**Comment by RasmusFonseca** [comment]
Great! Thanks a lot.
