### ISSUE TITLE
disabling zooming picked atom

### ISSUE THREAD

**Issue by sunhwan** [arose/ngl#499]
I'm using 2.0.0-dev.28 and when I click an atom, it zooms the atom and animate the zooming. How can I turn this off?

**Comment by ppillot** [comment]
You can use `stage.mouseControls.remove('clickPick-left')`

**Comment by sunhwan** [comment]
Worked! Thanks, @ppillot

**Comment by sunhwan** [comment]
removing 'clickPick-left' also removes click signals. Is it possible to only remove the centering of the picked atom?

**Comment by ppillot** [comment]
if the NGL object is available in the scope of your call to this function, you can use `stage.mouseControls.remove('clickPick-left', NGL.MouseActions.movePick)`
