### ISSUE TITLE
keycontrols in Firefox

### ISSUE THREAD

**Issue by csulok** [arose/ngl#500]
At least in Firefox 59, the default keyboard shortcuts, like k for rock animation doesn't work. I've traced it to https://github.com/arose/ngl/blob/master/src/stage/key-behavior.ts#L68 where in FF, keyCode is always 0. The fix could be actually quite simple: 

```
_onKeypress (event: KeyboardEvent) {
   // console.log( "press", event.keyCode, String.fromCharCode( event.keyCode ) );
   this.controls.run(event.which || event.keyCode)
}
```

But according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode), both `keyCode` and `which` are removed from web standards and developers should transition to event attributes like `key` or `code`, however those aren't numeric anymore, so that could require a bit more change in the KeyBehavior class.

Can you comment on this? Happy to send a pull request either way.

**Comment by arose** [comment]
thanks, merged it!
