### ISSUE TITLE
Density ideas

### ISSUE THREAD

**Issue by danpf** [arose/ngl#508]
Hello,
I just had a few requests for density viewing.
1. A density view where you just view each voxel as a simple square/polygon, no shape smoothing or anything.
2. A way to center on density surfaces. Right now it's really hard to center on distal regions of maps. (maybe there is a way to do this?)
3. A way to get the actual coordinates and index coordinates of the map (this is probably the least useful, but I often find it helpful to have, would be best in the bottom left bar i think)
Cheers,
~Dan

**Comment by arose** [comment]
1) there is a dot representation to do it, see https://codepen.io/arose/pen/vRzLPw?editors=0010
2) works with dots
3) the pickingProxy should provide that for the dots but you would need to create your own tooltip for that (see https://codepen.io/arose/pen/OvoNJM?&editors=001 on how to create tooltips)

**Comment by danpf** [comment]
Awesome thanks! I think full voxel cubes would be nicer but this will work!
