### ISSUE TITLE
Contacts between 2 entities only

### ISSUE THREAD

**Issue by LivC182** [arose/ngl#517]
Is there anyway to calculate contacts just between polymer and ligand, without showing polymer to polymer interactions or ligand to ligand interactions? 
I tried: sele:"polymer and ligand" and it dosent work.
sele: "polymer or ligand" works but I get all the interactions within the protein which hinders the visibility for the important contacts.

**Comment by arose** [comment]
There is a 'filterSele' parameter in the contact representation you can use, try setting it to 'ligand'

**Comment by LivC182** [comment]
Works pretty well: filterSele: ligand, gives the interactions between the ligand and all other entities(polymer, ligand, water, ion) so a combination between filterSele and sele should give only the interactions between ligand and polymer


One more thing: I am trying to change the color coding for contacts but I couldn't find any contact-colormaker.ts or a contacts.ts to see where they you init them. Is there color a parameter for each contact ?  

Thank you for your help

**Comment by arose** [comment]
not yet, tracked in #435

**Comment by ppillot** [comment]
I have a concern with the `filterSele` parameter in one case: it works very well for a simple ligand, but I wanted to apply it to antibodies and antigenes. if I use the "antigene" as `filterSele`, then I also get contacts that are internal to the antigene and not only contacts relevant to the epitope binding.
I was wondering if a second filter could be a good option for this scenario?

**Comment by LivC182** [comment]
I had know idea 'antigene' was a recognized value for filterSele. Do you know where I can find all the values this param can take ?

**Comment by ppillot** [comment]
antigene is not a proper selector, that was a (poor) way of describing the invocation of a selector. The list of all the selector accepted by NGL is in the manual at http://nglviewer.org/ngl/api/manual/usage/selection-language.html

**Comment by csulok** [comment]
`filterSele` keeps contacts where at least 1 end is in the selection and I think @LivC182 would need the extra check for both ends.

See here: https://github.com/arose/ngl/blob/master/src/chemistry/interactions/contact.ts#L271
