### ISSUE TITLE
Proximity of a point to spatialHash 

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#522]
Hi, I am wondering which is the fastest way to achieve this:
Given a point, find the spatialHash grid index closer to it.

**Comment by fredludlow** [comment]
I'd look at:
https://github.com/arose/ngl/blob/master/src/geometry/spatial-hash.ts#L123

The grid size is 8 (`2**exp` where exp is 3 unless you've overridden it).

This line from the class finds lowest possible x index for a point x +/- r:
```javascript
    const loX = Math.max(0, (x - r - this.minX) >> this.exp)
```
If you set `r=0` you'd get the x-index of the grid point before your point of interest (i.e. the one that contains your point). 

To get the grid point *closest* to your point of interest you need to add half a grid step:
```javascript
    const ix = Math.max(0, (x + 4 - this.minX) >> this.exp)
    // Likewise for y and z
    const iy = Math.max(0, (y + 4 - this.minY) >> this.exp)
    const iz = Math.max(0, (z + 4 - this.minZ) >> this.exp)
```

Then the grid index would be given by
```javascript
 const idx = (((ix * this.boundY) + iy) * this.boundZ) + iz
```
NB:
* Replace `this` by the hash instance if not implementing it as a class method
* That magic 4 is more generally `2**(exp-1)`, in case the grid size/exp is changed

**Comment by giagitom** [comment]
Hi @fredludlow , thank you for the response!
I noticed that there are boundaries only for the lower limit. When i tried with an external point (like [1000,1000,1000]) it gave to me an index out of range. Whereby I introduced the upper limit like this:

```js
var gr = stage.compList[0].structure.spatialHash; 
ix = Math.max(0, Math.min (gr.boundX -1,(p.x + 4 - gr.minX) >> gr.exp )  ) ; 
iy = Math.max(0, Math.min (gr.boundY -1,(p.y + 4 - gr.minY) >> gr.exp )  ) ;
iz = Math.max(0, Math.min (gr.boundZ -1,(p.z + 4 - gr.minZ) >> gr.exp )  ) ;
idx = (((ix * gr.boundY) + iy) * gr.boundZ) + iz;
```
Is this correct?

One more question:
1) If the grid point has no atoms in it I need to go to the second closer grid point and so on until i find an atom. How to find the second closer point of the grid, the third etc..?

**Comment by giagitom** [comment]
Yes, I tested it :)
Since I have not a maximum relevant distance and even don't know  a priori if atoms might be sparse i think I'll work on the first strategy. Thanks for the moment!
