### ISSUE TITLE
Little bug in TiledRenderer

### ISSUE THREAD

**Issue by martingraham** [arose/ngl#523]
Basically when the view is divided into tiles for saving to png, sometimes tiles will include the last row / column of pixels of the tile to the left or above it, and produce an overplotting artefact, almost like a grid. Here's a close-up of a horizontal line that appears in one of my images:

![nglartefact](https://user-images.githubusercontent.com/3490823/39057704-cf41dd7c-44b1-11e8-9040-05c5294be81f.png)

The trouble only seems to occur when anti-aliasing and when the height or width is odd (non-even). Say a tile was 1001 pixels wide and antialias = true, then the values for drawImage would be offset = floor(0/2) = 0, and width = ceil(1001/2) = 501. Then for the next tile, the offset = floor(1001/2) = 500 and thus the last column of pixels from the last tile would be picked up again in this tile

I've 'fixed' (i.e. works for me, no guarantees) it like so in TiledRenderer _renderTile, basically if the offset for a tile is odd and the width/height is odd, then add 1 to the offset and take 1 off the width/height for that tile:

```
if (this._antialias) {
	  const rx = (offsetX % 2) * (width % 2)
	  const ry = (offsetY % 2) * (height % 2)
      this._ctx.drawImage(
        viewer.renderer.domElement,
        Math.floor(offsetX / 2) + rx,
        Math.floor(offsetY / 2) + ry,
        Math.ceil(width / 2) - rx,
        Math.ceil(height / 2) - ry
      )
    } else {
```

I've got this in my fork at https://github.com/martingraham/ngl and it should be the only change if you want to pull, or ask me to make a pull request (or just cut'n'paste the above code, because that's all there is to it)

**Comment by arose** [comment]
Thanks!
