### ISSUE TITLE
Loading trajectory from float array

### ISSUE THREAD

**Issue by stefdoerr** [arose/ngl#527]
So I am trying to send a ~~binary~~ trajectory over GRPC to NGL to visualize.

I have managed to load the structure of the molecule from a string blob also sent over GRPC but then I want to load the trajectory in that component but the `loadTrajectory` method of `StructureComponent` only accepts a file name or `Frames`. No binary blob. I thought of using the `Frames` class but the problem is that the documentation of `Frames` is pretty empty so I don't know how I would load ~~binary~~ trajectory data into a `StructureComponent`.

I hit a similar wall when trying to use `TrajectoryComponent` to load the blob and link it to the `Stage` and `StructureComponent`.

**Comment by stefdoerr** [comment]
Actually I managed to send a float array over grpc. So I will try instead to create `Frames` from the float array and try to add that to the `StructureComponent`

**Comment by stefdoerr** [comment]
This is definitely my lack of JS knowledge but I am trying to instantiate a `Frames` object like this:
`var frames = NGL.Frames('bla', 'blu');` and I get an error that `NGL.Frames` is not a function. But if I check the source code it is defined as a function!
`NGL.Frames=function(a,b){this.name=a;this.path=b;this.coordinates=[];this.boxes=[]};`

**Comment by ppillot** [comment]
I haven't used trajectories, but regarding Frames, this class is not exported in the NGL default object. That explains why you can't use NGL.Frames to create a new frame object.
As an easy way to  access to NGL object and properties, I suggest using your browser's developper console. At the prompt, you can type `NGL` + enter and explore the object properties that are returned.
If you type `NGL.`, then your browser will suggest properties and methods you can have access to.

**Comment by stefdoerr** [comment]
So, there is no way to load a trajectory into a `StructureComponent` from a list of floats / float array?
I looked up the source code and I really cannot see how I would do it without modifying the source-code of NGL (which I would be horrible at considering my 0 js knowledge).

**Comment by arose** [comment]
I added the Frames class to the export, so it is available via NGL.Frames, see 21f07c9fcf75d43d8bd8c8551cf504ec6fdb1945

**Comment by arose** [comment]
Also, if you just want to update the positions of a Structure you can do StructureComponent.structure.updatePosition(float32array); StructureComponent.updateRepresentations({ 'position': true })

**Comment by stefdoerr** [comment]
Great! Works nicely :)
