### ISSUE TITLE
Question about radiusType parameter in dot representation

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#528]
This question relates with typescript conversion
https://github.com/arose/ngl/blob/2d84a993507fd59bf1d3041c851e8bd93b5db99b/src/representation/dot-representation.js#L297
radiusType is supposed to be a string amongst value, abs-value, value-min, deviation, size
In the linked lines of code, if radiusType is not 'radius' (which is not one of the aforementioned values) then radius which is an integer should take radiusType value?!
What is the desired behaviour here?

**Comment by arose** [comment]
Not a very clear type but radius can be either one of the string values of a number. It is eventually used here https://github.com/arose/ngl/blob/master/src/surface/volume.js#L381.
