### ISSUE TITLE
Adding new color scheme

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#529]
Hi, I am trying to make a new coloring scheme and i have found that the funciton used to color atoms

```this.atomColor = function( atom ){...}``` 

inside ```NGL.ColormakerRegistry.addScheme( function( params ){...}```

may iterate the same atom multiple times. Is this normal?

**Comment by arose** [comment]
It will iterate the same atom for each representation where the scheme is used.

**Comment by giagitom** [comment]
Ok but if I have one representation and change his color using rep.setParameters(...), this.atomColor should iterate each atom one time correct? In this [pen](https://codepen.io/giagitom/pen/XYgZGB?editors=0010) i made a coloring scheme and log atom index in console it seems that some atom is targeted multiple times
My console initial output is this
![image](https://user-images.githubusercontent.com/20627977/41360681-9d38f558-6f2d-11e8-9019-95a1991a84c3.png)

**Comment by arose** [comment]
It gets the color for the atom spheres and bonds separately. If you use a spacefill repr it is only called once per atom.

**Comment by giagitom** [comment]
Now I understand. Thanks
