### ISSUE TITLE
Get the Authors of the structure from structure

### ISSUE THREAD

**Issue by LivC182** [arose/ngl#531]
Hi is there anyway to get the authors of the PDB from the structure object ? I can find title, deposition. method, r-free etc. but not the Authors. They are in the journal section of the pdb file. 

Thanks.

**Comment by ppillot** [comment]
It's not being taken care of by the [parser](https://github.com/arose/ngl/blob/master/src/parser/pdb-parser.js). I suppose that you could use other means to achieve this goal, such as querying rcsb through their [REST API](https://www.rcsb.org/pdb/software/rest.do) if you are working in an environment where you can make online requests.

**Comment by arose** [comment]
Good suggestion to use the rest api, @ppillot. Happy to look at a PR if someone wants to add it.
