### ISSUE TITLE
Proper way to remove stage?

### ISSUE THREAD

**Issue by ehb54** [arose/ngl#532]
I'm using stage to create viewers dynamically, but eventually I get a console error (just testing in Firefox for now).
Error: WebGL warning: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.
I believe I am .dispose()'ing the stage each time and deleting all references to it...
Reusing a pool of fixed stage is not really a trivial option in this case, since multiple "modules" can
each have an arbitrary number of distinct viewers.
Is there any guidance for properly removing a stage?

Thanks,
Emre

**Comment by 1auralynn** [comment]
I had the same issue and I resolved it by calling stage.removeAllComponents() and then stage.dispose()...

**Comment by arose** [comment]
Using stage.dispose() should be sufficient, can you make sure it is called?

**Comment by ehb54** [comment]
Yes, stage.dispose() was called.  console.log()'d it, but I'll verify again and report back.

**Comment by 1auralynn** [comment]
Hmm strange, I was able to call stage.removeAllComponents without a string
variable...

*Laura Lynn Gonzalez*
Owner, Dynamoid <http://dynamoid.com>
Oakland, CA

**Comment by ehb54** [comment]
After some digging, and testing with chromium-browser --js-flags='--expose_gc' to expose the window.gc() command to force garbage collection, our conclusion (cjeong73 & myself) is that this is not an NGL issue but a javascript garbage collection issue.  Once garbage collection is forced, the error goes away.  Unfortunately, there seems no way to force javascript garbage collection.  So I push this issue to the browsers and their javascript engines.  Note: we did not have to call .removeAllComponents(), just simply .dispose().
