### ISSUE TITLE
sele parameter cannot be changed  by using setParameters

### ISSUE THREAD

**Issue by LivC182** [arose/ngl#533]
I am trying to change sele from polymer to ligand by using this:

stage.getRepresentationsByName('representationl').setParameters({sele: 'ligand'})

however it doesn't work.
Codepen:
https://codepen.io/liv182/pen/XqZqwa?editors=0010

**Comment by arose** [comment]
it is stage.getRepresentationsByName('representationl').setSelection('ligand')
