### ISSUE TITLE
How do you get NGL to respond to touch gestures on mobile devices?

### ISSUE THREAD

**Issue by samirelanduk** [arose/ngl#538]
NGL works superbly on desktop machines, but on touch devices you cannot pinch zoom in and out or rotate the structure with touch gestures as a user might expect to - instead it just moves the structure around a little.

I have deployed an exact copy of [the NGL mobile example](https://github.com/arose/ngl/blob/master/examples/mobile.html) to a server to test this, and using the exact settings of that page has no effect. That page is temporarily viewable [here](https://atomium.samireland.com/ngl.html) to show what I mean.

It's clearly possible because the RCSB has a beautifully responsive NGL display - but their code is obfuscated. As is sadly often the case, the documentation offers no guide here. Is there a setting I need to alter?

**Comment by ppillot** [comment]
The only difference I can see is in the meta viewport tag (that's in the header part of the HTML file) where it is stated user-scalable=no.
You may try to discard this setting as it is supposed to prevent zooming events (I can't test this, so thanks for reporting back wether it has worked or not)

**Comment by arose** [comment]
Hi @samirelanduk, the NGL version you have at https://atomium.samireland.com/ngl.html is "0.10.4", whereas the current master branch is "2.0.0-dev.32". Could you try with the current master?

**Comment by samirelanduk** [comment]
Thank you, that works! The new version allows you to rotate the structure with touch gestures and, when the viewport has `width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0`, lets you zoom in and out with touch gestures.
