### ISSUE TITLE
Get the real atom number when assembly is not default

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#539]
Hi, is there an easy way to do this?

**Comment by arose** [comment]
what do you mean by "real" atom number? The serial number from pdb and mmcif file? That is available as atomProxy.serial

**Comment by giagitom** [comment]
Sorry, Actually I would like to be able to know the total atoms number starting from an atomSet and taking into account the repetitions (or deletions) made by the current assembly parameter (when it is different from DEFAULT).

**Comment by arose** [comment]
The assembly class has some helpers, see http://nglviewer.org/ngldev/api/classes/assembly.html, including getting the selection associated with an assembly.

**Comment by giagitom** [comment]
Good, with this code i can find the right atom number for the whole structure:
```js
BU1.getAtomCount(structure)
```
But if i have a subset of the structure? I tried this without luck:
```js
var subStructure = structure.getView(new NGL.Selection(myAtomSet.toSeleString()))
BU1.getAtomCount(subStructure)
```

**Comment by giagitom** [comment]
Solved, thanks
