### ISSUE TITLE
User-friendly API for geometric primitives

### ISSUE THREAD

**Issue by sbliven** [arose/ngl#54]
The current methods for building geometric primitives (buffer.js) do not appear to be designed for use by end users. Adding some documentation would be a great first step, as the arguments are often hard to guess and there are many similarly-named functions (e.g. should I use a SphereBuffer, a SphereGeometryBuffer, or the nefarious SphereImposterBuffer?). It would also be nice to have some higher-level structures, such as a method for arrows.

**Comment by arose** [comment]
Yes, proper documentation is in order. I am also thinking of a more high-level API but the current methods will remain to be available.

> should I use a SphereBuffer, a SphereGeometryBuffer, or the nefarious SphereImposterBuffer?

Only use `SphereBuffer`, it decides which of the special classes to use.

**Comment by arose** [comment]
Drafting a MeshBuilder API

```JavaScript
MeshBuilder.prototype = {

    constructor: MeshBuilder,

    addMesh: function( position, color, index, normal ){

    },

    addSphere: function( position, color, radius ){

    },

    addEllipsoid: function( position, color, radius, majorAxis, minorAxis ){

    },

    addCylinder: function( from, to, color, radius ){

    },

    addCone: function( from, to, color, radius ){

    },

    addArrow: function( from, to, color, radius, coneRadius, coneLength ){

    }

};
```

**Comment by arose** [comment]
Current version of the API:

```JavaScript
var geometry = new NGL.Geometry( "sphere" );
// add as many sphere or other primitives as you want
geometry.addSphere( [ 0, 0, 9 ], [ 1, 0, 0 ], 1.5 );  // position, color, radius
var geoComp = stage.addComponentFromObject( geometry );
geoComp.addRepresentation( "buffer" );
```

**Comment by arose** [comment]
pushed with support for sphere, ellipsoid, cylinder, cone 90095be4b17d97ad86df5443db26f1ff129598cb

**Comment by arose** [comment]
renamed Geometry to Shape

**Comment by arose** [comment]
full example

```JavaScript
var shape = new NGL.Shape( "shape" );
shape.addMesh(
    [ 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1 ],
    [ 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0 ]
);
shape.addSphere( [ 0, 0, 9 ], [ 1, 0, 0 ], 1.5 );
shape.addEllipsoid( [ 6, 0, 0 ], [ 1, 0, 0 ], 1.5, [ 3, 0, 0 ], [ 0, 2, 0 ] );
shape.addCylinder( [ 0, 2, 7 ], [ 0, 0, 9 ], [ 1, 1, 0 ], 0.5 );
shape.addCone( [ 0, 2, 7 ], [ 0, 3, 3 ], [ 1, 1, 0 ], 1.5 );
shape.addArrow( [ 1, 2, 7 ], [ 30, 3, 3 ], [ 1, 0, 1 ], 1.0 );
var shapeComp = stage.addComponentFromObject( shape );
shapeComp.addRepresentation( "buffer" );
```

**Comment by sbliven** [comment]
Nice. Are there significant performance considerations to creating a single shape vs. adding a separate shape for each object?

**Comment by arose** [comment]
> Are there significant performance considerations to creating a single shape vs. adding a separate shape for each object?

For each separate shape you add extra calls to the WebGL API to draw it. You shouldn't have hundreds of shapes, but a couple of dozens is okay.
