### ISSUE TITLE
Is it possible to extract the distance between residues?

### ISSUE THREAD

**Issue by MercifulCode** [arose/ngl#541]
Hi! I know I am able to graphically get the distance between two residues in angstroms with the following stanza:

```
structureComponent.addRepresentation('distance', {
          atomPair: '13.CA,14.CA',
          color: 'skyblue',
          labelUnit: 'angstrom',
        }),
```

However, am I able to extract this distance? Is there a method I am not seeing on one of the proxy classes that would allow this? I would not be surprised if there is a method I'm not familiar with due to my current lack of experience with molecular biology.

Ideally, I'm looking for something that can be done programmatically like:

```
nglData.eachResidue(outerResidue => {
      nglData.eachResidue(innerResidue => {
        if (outerResidue.resno !== innerResidue.resno) {
          const dist = outerResidue.distanceToInAngstrom(innerResidue); 
          console.log(`Distance between ${innerResidue.resno} and ${outerResidue.resno} is ${dist}`);
        }
      });
    });
```

Thanks!

**Comment by npgauth** [comment]
I'd also be interested in this "feature" -- did you ever get this to work?

**Comment by ppillot** [comment]
You can use NGL internal methods on vectors to achieve this.
with your code it could be:
```javascript
const outer = new NGL.Vector3(outerResidue.x, outerResidue. y, outerResidue.z)
const inner = new NGL.Vector3(innerResidue.x, innerResidue. y, innerResidue.z)
const dist = outer.distanceTo(inner)
```

**Comment by npgauth** [comment]
Great -- I will try that. Thanks!

**Comment by MercifulCode** [comment]
Thanks for the hint, @ppillot - Would you happen to know how exactly to get the x,y,z coordinates from the residue? Using that stanza verbatim resulted in only 0 values since those 3 fields didn't exist on the residue object.

Right now the only keys that appear on the residue objects are `structure, index, chainStore, residueStore, atomStore, residueMap, atomMap`.

I do see there is a x, y, and z, array field on the atomStore. So perhaps I need to do some funky residue/atom indexing to go from residue -> atom -> coordinate and go from there?

**Comment by ppillot** [comment]
These x, y and z properties are also available from a ResidueProxy object as returned by `structure.getResidueProxy(residueIndex)`

**Comment by MercifulCode** [comment]
Hm, I'm still seeing the same issue where the residue proxy object returned does not have x, y, or z, fields.

Using my hunch about the atoms, I came up with this loop:

```
data.eachResidue(outerResidue => {
        const outerIndex = outerResidue.direction1AtomIndex;
        const outer = new Vector3(
          structureComponent.structure.atomStore.x[outerIndex],
          structureComponent.structure.atomStore.y[outerIndex],
          structureComponent.structure.atomStore.z[outerIndex],
        );
        data.eachResidue(innerResidue => {
          if (outerResidue.resno !== innerResidue.resno) {
            const innerIndex = innerResidue.direction1AtomIndex;
            const inner = new Vector3(
              structureComponent.structure.atomStore.x[innerIndex],
              structureComponent.structure.atomStore.y[innerIndex],
              structureComponent.structure.atomStore.z[innerIndex],
            );

            const dist = outer.distanceTo(inner);
            console.log(`Distance between resno ${outerResidue.resno} and ${innerResidue.resno} is ${dist}`);
          }
        });
      });
```

Which, at least, is returning various distances.
I'll be looking at it myself through the source code, but I still want to pose 2 questions:

* Is this atom the correct atom to be considered the "center" of the residue?
* How do I convert the distance from (I presume) world coordinates to Angstroms/nanometers/etc?

**Comment by martingraham** [comment]
FWIW, I've been doing it using atom proxies and their distanceTo function

```
        var struc = structureComponent.structure;
        var ap1 = struc.getAtomProxy();
        var ap2 = struc.getAtomProxy();
        var selection = new NGL.Selection ();

        selection.setString ("14.CA 15.CA", true);
        var atomIndices = struc.getAtomIndices (selection);

       // simple example, can make more complex by loop through all combinations of atom pairs in a bigger selection etc
       ap1.index = atomIndices[0];
       ap2.index = atomIndices[1];

        var distances = ap1.distanceTo(ap2);
```
