### ISSUE TITLE
Removing Loaded Structures from Stage

### ISSUE THREAD

**Issue by bassdude44** [arose/ngl#542]
Currently, I am trying to make a web page with an embedded NGL viewer, where the user can check or uncheck an HTML input element to control which structures they want to view. So far, it seems I can only get the structure loaded, but browsing through the documentation, it is not readily apparent to me how to 'unload' a structure. Any assistance would be greatly appreciated. Thanks.

**Comment by ozcan** [comment]
Components and Representations have `dispose()` functions that unload them from the stage.

So you can do something like below:
```
stage.getComponentsByName("1blu.mmtf").list[0].dispose();
```

also you can access and dispose components using `stage.compList` if you do not want to use `getComponentsByName` function.

**Comment by arose** [comment]
Thanks @ozcan good suggestion, just one note, `stage.getComponentsByName("1blu.mmtf").dispose()` should be sufficient.

**Comment by bassdude44** [comment]
Many thanks for the help, ozcan and arose! This did the trick.
