### ISSUE TITLE
Rotate a shape to face the camera

### ISSUE THREAD

**Issue by ozcan** [arose/ngl#543]
Hello, 

I have created a stage with two components, one is a cartoon and second one is a shape (arrow). I want to keep the arrow facing the camera when I rotate the stage. I realized that text labels already have this behavior of facing the camera and I would like to replicate this behavior for arrow, sphere and mesh.

**Comment by arose** [comment]
What you are after is implemented for the labels inside the text shader but it is not supported for meshes. You would need to change the mesh vertex shader but I am not sure how feasible that is.
