### ISSUE TITLE
Loading validation into Stage

### ISSUE THREAD

**Issue by LivC182** [arose/ngl#544]
Is there any way to load the validation report straight from the ftp.wwPDB site, or do I must have a local copy ?

**Comment by LivC182** [comment]
Got it, in case anyone has the same problem. Example for PDB 3pqr
NGL.autoLoad("//ftp.rcsb.org/pub/pdb/validation_reports/pq/3pqr/3pqr_validation.xml.gz", { ext: "validation" })

**Comment by arose** [comment]
Great that you solved it and thanks for posting your solution here!
