### ISSUE TITLE
Hydrogen Bonds detection/add?

### ISSUE THREAD

**Issue by newzhongdan** [arose/ngl#546]
Hi everyone, i see the docs and not find the properties, its possible add bond of hydrogen in the pdbs? like a Chimera hbonds function  (http://www.cgl.ucsf.edu/chimera/docs/UsersGuide/midas/hbonds.html)? any help? or the possible solution is add a shape? mm

thanks for the support and thanks arose for nlgview

**Comment by RasmusFonseca** [comment]
I'm playing around with something similar. Is this what you're after:
```javascript
    this.stage.loadFile(file)
      .then(function (component) {
        component.addRepresentation("cartoon", { color: "sstruc" });
        component.addRepresentation("ball+stick", { color: "element" });
        component.autoView();
        component.addRepresentation("contact", {hydrogenBond: true});
      });
```

See also: https://github.com/arose/ngl/blob/master/examples/scripts/representation/contact.js

**Comment by newzhongdan** [comment]
thanks you @RasmusFonseca , i used 
component.addRepresentation("distance", { atomPair: [["XX.X", "XX.X"]],  color: "magenta", labelVisible: false, scale: 0.5,}), result is decent.. but contact is better.. :D

**Comment by arose** [comment]
Yes, the 'contact' representation is the way to go, thanks @RasmusFonseca.

**Comment by sneshyba** [comment]
Glad to see this discussion -- but could I get some context for how to implement the above? I'm at a beginner's level, but the following works for me; I'd like to add H-bonds between the RNA and the solvent ... any pointers would be appreciated! 

uframe = mda.Universe(grofilename)
view = nv.show_mdanalysis(uframe)
view.add_representation('ball+stick',selection='RNA')
view.add_representation('licorice',selection='SOL',surfaceType='av')
view
