### ISSUE TITLE
Is it possible to get the corresponding representation when picking on an atom?

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#547]
Hi, is it currently possible?

**Comment by ppillot** [comment]
Each representation has a `repr.selection.test()` method that can take an AtomProxy as an argument.
To achieve your goal, you could loop through the current representations (with `stage.eachRepresentation` for example) and test if the atom picked belongs to its selection.
```javascript
//ap is the atomProxy for the picked atom
let r = 'none'
stage.eachRepresentation( representation => {
  if (representation.repr.selection.test(ap)) {
    r = representation.name
  }
})
console.log(`Atom is in representation: ${ r }`)
```

**Comment by giagitom** [comment]
Great! Thank you

**Comment by giagitom** [comment]
One thing, i tried the example but it gives back to me the wrong representation. Also i have found that the test seems to be positive for each representation. I tried something like this. Am I missing something?
```js
stage.mouseControls.add('clickPick+left', function(stage, pickingProxy){
		
	if (pickingProxy === undefined || pickingProxy.type !== 'atom' && pickingProxy.type !== 'bond') return
	else {	
		var atom = pickingProxy.atom || pickingProxy.closestBondAtom		

		var r = 'none'
		stage.eachRepresentation( function(representation) {
			if (representation.repr.selection.test(pickingProxy)) {
				r = representation.name
				console.log(`Atom is in representation: ${ r }`)
				return
				}

			})
		}
	})

```

**Comment by ppillot** [comment]
you probably should write `if (representation.repr.selection.test(atom))` instead of `if (representation.repr.selection.test(pickingProxy))`

**Comment by giagitom** [comment]
I tried, but the problem persists. I found that if i pick a representation and the correspondent atom proxy is common with any other representation, all representations with this atom are positive to the test.

**Comment by arose** [comment]
Sorry, there is no API to expose this

**Comment by giagitom** [comment]
Ok thanks
