### ISSUE TITLE
How to get the coordinates of a point moving in camera x, y or z direction?

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#548]
Hi, I have a point at some coordinates that i would like to move through camera x, y or z direction. How can i do this?

**Comment by arose** [comment]
Not sure I understand what you want to do exactly, but there are http://nglviewer.org/ngl/api/classes/viewercontrols.html which has a translate method.

**Comment by giagitom** [comment]
I am implementing a coloring method by proximity. In case of proximity respect to a point I would like the user to be able to easily move that point. To do so I would like the point to be moved always parallel to the view

**Comment by arose** [comment]
There is no API method but you should be able to do the math yourself following the example of the panAtom method here https://github.com/arose/ngl/blob/master/src/controls/trackball-controls.ts#L105-L117.

**Comment by giagitom** [comment]
Perfect! I figured out how to do it. Thank you!
