### ISSUE TITLE
filterSele and setSelection together fire warning THREE.Box3: .getSize() target is now required

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#549]
Hi, here a [pen](https://codepen.io/giagitom/pen/eKRGXK?editors=0010) that should define the problem.
Basically if i use filterSele with setSelection a warning is fired and from now on each time i use filterSele the surface needs to be rebuild and the same warning is fired in the console.

**Comment by arose** [comment]
thanks for reporting this, just fixed it in above commit

**Comment by giagitom** [comment]
Great! Thank you!
