### ISSUE TITLE
Opacity on cartoon representation has band artifacts with default side parameter

### ISSUE THREAD

**Issue by xrobin** [arose/ngl#551]
When I set the opacity of a representation to a value lower than 1, the cartoon representation has "zebra" style banding artifacts. [Example on CodePen](https://codepen.io/xrobin/pen/BVJbbN): you can more clearly see them if you zoom in a bit.

I had to set 

    side: "front"

in the  RepresentationParameters to get rid of them and have a smooth transparent cartoon. [Example](https://codepen.io/xrobin/pen/JZMzgm).

It took me a long time to find this setting, and I was quite lucky to find it at all. Is there a reason for 'front' not to be the default here? Otherwise I suggest to change the default value of side to "front".

**Comment by arose** [comment]
Same reason as #552.

Front is not the default because clipping cartoon would look strange then.
