### ISSUE TITLE
Setting opacity on a per-residue level?

### ISSUE THREAD

**Issue by xrobin** [arose/ngl#553]
I can set the opacity of a representation with something like `stage.compList[comp].reprList[repr].setParameters({"opacity": 0.5})`.

However I would like to set the opacity on only some residues of a protein chain. Here is[ an example on CodePen](https://codepen.io/xrobin/pen/aKqdWQ). I want a ligand and part of the protein to have full opacity, and the rest of the chain and ligands faded out.

At the moment I found that I can create a second representation and use a selection to show only parts of the protein chain: `repr2.setSelection("(18-23) and ligand")`. Then I set the opacity of the other representation, as in the previous example.

However this seems pretty inefficient with lots of duplication (now I need to keep track of color etc on two representations). Is it possible to set the opacity on only parts of a representation,
for instance using selections?

**Comment by ppillot** [comment]
As you've mentioned, settings are on a per representation basis, so the
option you talked about doesn't exist.
Clipping might be an option to consider as well and it can be applied to
the whole stage.

2018-06-19 13:23 GMT-04:00 Xavier Robin <notifications@github.com>:

**Comment by xrobin** [comment]
Thanks for the answer. So indeed I didn't miss anything obvious.
