### ISSUE TITLE
Dynamically change color of the hovered residue

### ISSUE THREAD

**Issue by xrobin** [arose/ngl#556]
I would like the hovered residue in a cartoon to be displayed in a different color, for instance red.

I though to use `stage.signals.hovered` to get a PickingProxy. From there I can get an atom, but I couldn't find a direct way to set the color on it.

So I created a color scheme with `NGL.ColormakerRegistry.addScheme(...)` and then called `setColor()` on the representation. However this has an effect only once and the next calls to `setColor` are ignored. 

Then I realized I can `removeRepresentation` and then `addRepresentation(...).setColor()`. It works!

However it isn't very efficient, especially with large structures; and isn't too convenient when I have multiple representations with various parameters set. Is there a better way to dynamically change colors, without re-creating the representation?

Ideally I would like to have a direct `setColor` method on `AtomProxy`.

**Comment by arose** [comment]
You are on the right track with `NGL.ColormakerRegistry.addScheme(...)` and `representation.setColor()`. However you need to call `representation.update({ color: true })` when the color in you scheme has changed.

**Comment by xrobin** [comment]
That's working, thanks! And sorry for the late answer.

**Comment by rsakai** [comment]
Hi @arose, I think I had the same question and tried to implement it as shown in the codepen below. Oddly, it seems it is working for some part of the structure, but not for the rest.  Somehow, the tooltip and highlighted residue do not match in parts.  Could you advise how I may resolve this issue?

https://codepen.io/rsakai/pen/WNNBPyx?editors=0010

**Comment by arose** [comment]
you want to use `atom.resno` not `atom.residueIndex`

**Comment by rsakai** [comment]
Thank you for the prompt response! That solved it.

**Comment by orangeSi** [comment]
> You are on the right track with `NGL.ColormakerRegistry.addScheme(...)` and `representation.setColor()`. However you need to call `representation.update({ color: true })` when the color in you scheme has changed.

@arose this work, but both will remove the raw color of all the rest residues( like below img ), so how to keep the raw color of all the rest residues except the hovered residue?  thanks~
![image](https://github.com/nglviewer/ngl/assets/12126846/dce6df86-ba69-43a8-b485-a7db75d6a102)
![image](https://github.com/nglviewer/ngl/assets/12126846/bff89ed1-804e-46e2-bbce-234e6a48a8a0)
