### ISSUE TITLE
TypeError: buffer.getMesh is not a function in detached window

### ISSUE THREAD

**Issue by xrobin** [arose/ngl#557]
It is not possible to add a shape in a detached window. We use detached windows in SWISS-MODEL to allow users to resize the separate window, possibly on a separate screen, while keeping the controls in the main page. So the user interacts with the main window but sees the effect in the popup. You can [see it in action here](https://swissmodel.expasy.org/templates/1blu.1).

The gist of it is: in the first or main window, we have a call to `window.open` which opens a detached, popup window. In this popup window we do:

    var stage = new NGL.Stage("viewport");
    window.opener.stage = this.stage;

So now the main window "sees" the stage of the detached window and interacts with it. From the main window we can do pretty much everything, such as adding representations (see addLigand in linked example below), adding new components (see add5MAS which loads a new file also in the example below), changing opacity and selections. However adding shapes doesn't work. Here is a minimal function:

    function addShape() {
    	var shape = new NGL.Shape("MyCylinder");
    	shape.addCylinder(
    		[28.426,13.549,-3.606],
    		[30.249,13.379,-4.862],
    		[1, 0, 0], 1);
    	var shapeComp = stage.addComponentFromObject( shape );
    	shapeComp.addRepresentation( "buffer" );
    }

This function works fine from the main window, but gives the following error in the javascript console of the main window:

    TypeError: buffer.getMesh is not a function

    addBuffer                viewer.js:404:21
    add                      viewer.js:375:8
    attach/<                 buffer-representation.js:70:12
    forEach                  self-hosted:261:13
    attach                   buffer-representation.js:69:8
    _make                    representation.js:352:16
    make                     representation.js:368:8
    build                    representation.js:322:8
    init                     buffer-representation.js:63:8
    BufferRepresentation     buffer-representation.js:59:8
    makeRepresentation       representation-utils.js:67:17
    _addRepresentation       component.js:215:21
    addRepresentation        shape-component.js:37:15
    addShape                 http://localhost/ngl/ngl.html:35:2
    onclick                  http://localhost/ngl/ngl.html:1:1

I could track it down to a call to `instanceof` in `makeRepresentation`:

	else if (object instanceof Shape$1) {

which is true in the main window, but false in a detached one. Apparently `instanceof` doesn't operate reliably across windows/frames.

I also [created a more minimal example](https://xavier.robin.name/files/ngl/ngl.html).
At the top you have a few buttons. You can see that addShape, addLigands and addComponent work fine in the main window. Then if you click on "detach", a new window open. You still operate the controls in the main window: addLigand and addComponent work fine, but not addShape.

Expected result: add shape displays the shape in the detached window.

**Comment by xrobin** [comment]
A workaround was to add:

    window.opener.NGL = NGL;

in the detached window. This ensures that the parent window operates on the same "NGL" as the one that created the stage.

**Comment by arose** [comment]
Thanks for sharing your solution! I have not worked with frames for a long time.
