### ISSUE TITLE
Question about how to zoom in IOS Safari

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#559]
Hi, I'm having some problem zooming on mobile IOS safari. I know it is possible becaue it works well at RCSB website, but I don't know how to do it. Is it all a matter of css or something else? My viewer container is in position:fixed

**Comment by arose** [comment]
you need some meta tag like `<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">`

**Comment by giagitom** [comment]
Thank you. Now it works

**Comment by newzhongdan** [comment]
in chrome/android work fine, but in safari for iPhone the zoom not work... its a safari problem or need other propery in the html?

**Comment by newzhongdan** [comment]
finnaly, work in safari, add this line code

`  document.getElementById('viewport').addEventListener('touchmove',function(e){e.preventDefault();});`

:)

**Comment by giagitom** [comment]
Good thanks!
