### ISSUE TITLE
Auto scrolling up and down

### ISSUE THREAD

**Issue by biharck** [arose/ngl#562]
Hey there. It looks like when I am scrolling down a page and then I click again into the div which contains de NGL, the page automatically scrolls up/down to the center of the figure.

Sometimes this behavior is annoying. Is there a way to disable it?

**Comment by biharck** [comment]
@arose I have created an example at https://codepen.io/pen?template=JNLMXb
In order to reproduce what I said, please scroll down until the footer, click there and then click in any black space. You should see the browser scrolling automatically trying to center the NGL view.

https://codepen.io/biharck/pen/bjOgPK

Could you please, help me?

Thanks a lot.

**Comment by ppillot** [comment]
This is something related to chrome only in my experience (does not happen in firefox). I am wondering if it is not a "feature" of this browser when a webGL context gets the focus.

**Comment by ppillot** [comment]
I have found a workaround: the HTML for the canvas ahas a tabindex set to -1 which should prevent the canvas to be focusable. But this is not efficient in Chrome and programatically removing the tabindex does the job: `stage.viewer.renderer.domElement.removeAttribute('tabindex')`

**Comment by arose** [comment]
thanks @ppillot!

**Comment by biharck** [comment]
Thank you @ppillot :)
