### ISSUE TITLE
Remove StructureComponent coordinates

### ISSUE THREAD

**Issue by stefdoerr** [arose/ngl#571]
Hi, I managed to do `addTrajectory` to my `StructureComponent` but when I do it there is always a frame -1 containing the original coordinates of the `StructureComponent`. How can I get rid of this -1 frame to only show the trajectory? I tried using `removeTrajectory` but it's apparently not considered a trajectory. I tried removing `structureComponent.structure.atomStore.x[y][z]` but then it didn't show anything. I'm a bit out of ideas.

**Comment by arose** [comment]
you can't, it is supposed to be a feature so you can always go back to the coordinates of the original structure
