### ISSUE TITLE
Is it possible to use from the command line / as a standalone application?

### ISSUE THREAD

**Issue by UnixJunkie** [arose/ngl#572]
Hello,
Sorry for the very probably stupid question, I know nothing about web technologies.
I have done
```
npm install ngl
```
Then, how do I run the stuff?
ngl protein.pdb?
firefox of something?

Thanks a lot,
Francois.

**Comment by ppillot** [comment]
Hello François,
if you npm install, you just get the JS library that you can use in your own programs.
If you want to display pdb files for example, the best way to go would be to run the nglviewer application. To install this application locally, you need to git clone the ngl repo and use a web server to point to the file examples/webapp.html (for example http://localhost:8080/ngl/examples/webapp.html, depending on your server config).
The easiest way is to use the webapp online http://nglviewer.org/ngl/

**Comment by UnixJunkie** [comment]
ok, thanks
