### ISSUE TITLE
Performances degradation with long string selections on chrome

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#576]
I am using ```atomSet.toSeleString() ``` in every representation. I noticed a big slow down generating the representation, when the selection string is very big, especially on Chrome. Firefox experiences much less performances degradation respect to chrome. I have made a [pen](https://codepen.io/giagitom/pen/vzZxqW?editors=0010#0).

**Comment by fredludlow** [comment]
I don't know why performance differs so much, but this relates to #269 (the idea being you could set selection directly from a Selection object, rather than converting to/from a selection string).

**Comment by giagitom** [comment]
This would be nice

**Comment by arose** [comment]
to be addressed by #269
