### ISSUE TITLE
Problems with API documentation

### ISSUE THREAD

**Issue by BernierCR** [arose/ngl#58]
Hello. I have found at least one spot where the documentation is wrong. I'm looking at this page, http://arose.github.io/ngl/doc/#API_reference/Object/ColorMakerRegistry

You have the following example, 

// color residues 1 to 100 in red, 101-200 in blue and the remaining in white
var mySelectionScheme = NGL.ColorMakerRegistry.addSelectionScheme( [
	[ "red": "1-100" ],
	[ "blue": "101-200" ],
	[ "white": "*" ]
] );
// apply colorscheme to an existing representation
repr.setParameters( { color: mySelectionScheme } );

In order to make this work, I had to change the : to , and change color to colorScheme, like this. 

// color residues 1 to 100 in red, 101-200 in blue and the remaining in white
		var mySelectionScheme = NGL.ColorMakerRegistry.addSelectionScheme( [
			[ "red", "1-100" ],
			[ "blue", "101-200" ],
			[ "white", "*" ]
		] );
		// apply colorscheme to an existing representation
		repr.setParameters( { colorScheme: mySelectionScheme } )

What did you intend? 

Chad

**Comment by arose** [comment]
Hi @BernierCR you are absolutely right. The documentation is wrong and you have done it the right way. I will fix the doc.

**Comment by arose** [comment]
fixed in https://github.com/arose/ngl/commit/8643a0cce3c739b6fb463c7860c75ec718514829
