### ISSUE TITLE
How to show contacts between two separate PDB files?

### ISSUE THREAD

**Issue by yekaizhou** [arose/ngl#583]
Hi Dr. Rose

I want to show the **contacts between 2 PDB files** instead of showing the inner bonds in each protein, how should I set the setting?

Thank you
Yekai

**Comment by fredludlow** [comment]
There's an example here: https://codepen.io/arose/pen/VQjBGq

You need to concat the two (or more) structures to make one component. NGL can only use atoms from a single component when creating a representation (component == PDB file in this case).

**Comment by arose** [comment]
Nice example, thanks @fredludlow!

**Comment by yekaizhou** [comment]
Many thanks @fredludlow ! 
But I am also wondering how to select specifically the the contacts between the two structures within the "concat" structure rather than all bonds in that structure. Should I set the "sele" attribute in it? And I saw the sele attribute in the example here is: `sele: "/0 or /2"`. What does /0 or /2 mean?

**Comment by fredludlow** [comment]
When you concat files like that they get added as separate models, so in the [example](https://codepen.io/arose/pen/VQjBGq) linked above the protein is model 0 and the various ligand poses in the sdf file are models 1 onwards. The `/n` simply specifies a model, so `/0 or /2` means calculate all contacts between all atoms in "model 0 or 2" (the full selection syntax is [here](http://nglviewer.org/ngl/api/manual/selection-language.html) 

You can then filter which contacts are displayed with `filterSele`. In that particular example if you add `filterSele: "/2"` to the contact parameters it will only display contacts that involve an atom in model 2.

This would still show intramolecular contacts in the ligand if they were present (I'm not sure there's a way to prevent that).

HTH!
