### ISSUE TITLE
How to control the visibility of one object?

### ISSUE THREAD

**Issue by yekaizhou** [arose/ngl#585]
Is there a built-in function in NGL to control whether a pdb file to be shown or not? I want to build a button to control the visibility of a specific protein within a single click.
Thanks.

**Comment by fredludlow** [comment]
Each representation has a `setVisibility` method, so you either need to keep a reference to representations as you create them, e.g.

```javascript
var myRepr = component.addRepresentation('ball+stick', {...})
// Then in e.g. a checkbox event handler with event 'e':
myRepr.setVisibility(e.target.checked)
```

or, if you set a name on your representation you can retrieve it like so:
```javascript
component.addRepresentation('ball+stick', {name: 'ligand', sele: 'ligand'})
// Then in handler:
stage.getRepresentationsByName('ligand').setVisibility(e.target.checked)
```

Have a look at some of the codepens linked from the [gallery](http://nglviewer.org/ngl/gallery/index.html) (look for ones with buttons/checkboxes). There's a fair bit of boilerplate setting up the UI, but if you look through the code for `setVisibility` and `setParameters` you can see what's going on.
