### ISSUE TITLE
Change opacity by chain

### ISSUE THREAD

**Issue by gbayarri** [arose/ngl#587]
I have a PDB structure with multiple chains and I would like to change opacity only for some chains (to highlight them). I have tried with setSelection but you can't do two setSelection at the same time, one for the highlighted chains and the other for the non-highlighted.

I've also tried the function eachChain but it returns 46 objects while my structure has 8 chains.

Can I change a parameter of a representation changing the selection? I mean change opacity only for ":A :B" and leave the rest.

What I'm missing? I think it sould be easy to do that without add new representations.

**Comment by ppillot** [comment]
I would make 2 different representations, one for the highlighted chains and an other for the non highlighted.

**Comment by gbayarri** [comment]
Yes, I've tried that, but I would like to know if it's possible in a single representation, because after highlighting the chains I have to do more changes on the representation and all these changes will be duplicated.

Thanks!

**Comment by arose** [comment]
No, NGL only support per-object transparency. @ppillot's workaround is the way to go.
