### ISSUE TITLE
Performance of NGL.ColorMakerRegistry.addSelectionScheme( selection_scheme )

### ISSUE THREAD

**Issue by BernierCR** [arose/ngl#59]
Hello. I got color changing to work. I am now dealing with performance issues. There are a lot of things I can do on my end to improve performance of my webapp. However, I need some insight into the NGL.ColorMakerRegistry.addSelectionScheme( selection_scheme ) function. 

I have noticed this function is O(N^2), where N is the number of selections in selection_scheme. I'm not sure why this is the case, but it may have something to do with the way jQuery works. For example, if N =130, NGL takes 968ms, but at N=2492, it takes 22571ms. My highest theoretical N so far is around 7000, although I may never see that in practice. That would take around 90,000ms to run. That's quite a bit too much for an interactive application. 

Can you think of a better faster way to do this? Would combining selections be faster? For example, which is faster? 

red, 10-50
red, 70-80

OR

red, 10-50 or 70-80

I know with Jmol and PyMOL, if I tried to put too many ORs together, it would crash. Please advise, 

Thank you

Chad

**Comment by arose** [comment]
Hi,

yeah `NGL.ColorMakerRegistry.addSelectionScheme` does not scale.

Here is my suggestion to do fast, flexible coloring per residue. Create an array with an entry for each residue, set the array index to the color (hex coded) you want.

```JavaScript
var residueHexColors = [ 0x00FF00, 0x00FF00, 0x00FF00 ];

var myScheme = NGL.ColorMakerRegistry.addScheme( function( params ){

	this.atomColor = function( atom ){
                // the residue index is zero-based, same order as in the loaded file
                return residueHexColors[ atom.residue.index ];
	};

} );
```

Note, I haven't tested the code. Please let me now if it work or if you further questions.

Also, the API for this is not particularly good. In the future I want to allow user data on the atom/group/chain/model level that can directly be used for selection and coloring. Stay tuned.

**Comment by BernierCR** [comment]
Wow, yes that works fast! Thank you. 

One issue though on my side. I don't keep track of all the residues and their original positions in the structure file. So far, this only works for the first molecule in my structure, 16S rRNA. My webapp usually just recolors the visible molecules. Since your code is very fast, I could probably get away with recoloring the entire thing even when only a little piece changes. I could figure out a way to create and manage such an array. You are sure there is no fast enough way to do this without keeping track of every single residue all the time in the same array? 

I'm keeping track of the selection, data, and colors on my end, but whatever you add would be awesome and much appreciated.

**Comment by arose** [comment]
> You are sure there is no fast enough way to do this without keeping track of every single residue all the time in the same array?

You don't strictly need an residue-index-based-array. It was just the fastest thing I could think of. But you can use anything you want in the `this.atomColor` method. How does the data structure you currently have looks like?

**Comment by BernierCR** [comment]
Hmm, you know, I think I can figure this out. Thanks, 

Till next time.

**Comment by arose** [comment]
> Hmm, you know, I think I can figure this out. Thanks,

Great! No problem.
