### ISSUE TITLE
code is not formatted in NGL's website

### ISSUE THREAD

**Issue by hainm** [arose/ngl#590]
hi, please see the screenshot.
http://nglviewer.org/ngl/api/classes/colormakerregistry.html

<img width="876" alt="screen shot 2018-10-27 at 12 12 23 pm" src="https://user-images.githubusercontent.com/4451957/47606432-a3932a80-d9e1-11e8-8e05-855eff2202e6.png">

**Comment by arose** [comment]
yeah, that is not supported by the doc generator
