### ISSUE TITLE
Hydrogens in nucleic acids not correctly identified as part of the backbone

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#593]
Hi,
I've tried a color scheme to distinguish between backbone and side-chains in DNA. The results show that hydrogen atoms are not identified as belonging to the backbone.
<img width="587" alt="dna by residue backbone" src="https://user-images.githubusercontent.com/3930632/47940537-4ad00000-dec1-11e8-8b2e-8493c844b6bb.png">

The culprit is here https://github.com/arose/ngl/blob/8194a88b176b16e5a9bbaf19196b95cbe514fec5/src/structure/structure-constants.ts#L1056
I was wondering if there was a concern for not adding those initially and if I could do a PR with the corresponding atoms?

**Comment by arose** [comment]
fixed in #596
