### ISSUE TITLE
Syntax error in minified blob when adding a surfacerepresentation

### ISSUE THREAD

**Issue by xrobin** [arose/ngl#594]
I have a clean checkout of the current `master` checkout, just pulled a few minutes ago.

```
git status
# On branch master
nothing to commit, working directory clean
```
The I build NGL with npm, and specifically the minified version:

    npm install
    npm run-script build-min

and then use  `dist/ngl.js`. When I create a surface representation:

     ngl_stage.compList[0].addRepresentation("surface")

I get no visible representation and the following error message in the browser javascript console:

    Object { stage: {…}, signals: {…}, parameters: {…}, uuid: "D3253E13-5F38-400A-9F03-7C48C5BFE0DC", parent: {…}, repr: {…} }
    Worker.onerror molsurf 
    error { target: Worker, isTrusted: true, message: "SyntaxError: function statement requires a name", filename: "blob:http://131.152.25.164:42342/53ef56ce-c48c-4929-8aa3-a9e0a7261fdb", lineno: 126, colno: 0, currentTarget: Worker, eventPhase: 2, bubbles: false, cancelable: true, … }
    ngl.js:1:691138
    SyntaxError: function statement requires a name
    53ef56ce-c48c-4929-8aa3-a9e0a7261fdb:126:8

Inspecting the blob, there indeed seems to be a syntax error. Here is an excerpt of the blob contents ([...] added for clarity):
```
[...]
function yS(C,I,c){var p=ty(I), [...]
function ym(t,e,i){t[0]=e[0]-i[0],t[1]=e[1]-i[1],t[2]=e[2]-i[2]}
function(C,I,L,R,t,e,i){var r=C.length,O=t[0],D=t[1],k=t[2],n=e[0][...]
self.func = function(t,e){var i=t.data.args,r=t.data.params;if(i&&r){var [...]
self.onmessage = function(t){var e=t.data.__name,i=t.data.__postId;void 0===e?console.error("message __name undefined"):void 0===self.func[...]
```
The third line is indeed missing the function name. This seems to be related with the minification process. If I use `build/js/ngl.dev.js` the surface representation is working properly.

One more note: if I checkout tag v2.0.0-dev.33 and run npm install && npm run-script build-min, surface representations work fine. Therefore this must be caused by a change since v2.0.0-dev.33.

**Comment by JohnMica** [comment]
hi guys, seems that there is a regression with latest dev release 37

as i am currently experiencing similar issue with the library as per the images attached

![Screenshot 2020-03-09 at 11 09 27](https://user-images.githubusercontent.com/7076631/76207991-baad7380-61f6-11ea-9f9b-b00f29c88198.png)

![Screenshot 2020-03-09 at 11 10 01](https://user-images.githubusercontent.com/7076631/76207993-bd0fcd80-61f6-11ea-856b-99fbb3bedccd.png)

**Comment by JohnMica** [comment]
nvm guys - it seems that it was a minification issue on nuxt build
