### ISSUE TITLE
makeImage with antialias: true leaves visible stitching lines

### ISSUE THREAD

**Issue by xrobin** [arose/ngl#595]
When I do:

```
ngl_stage.makeImage( {
                factor: 1,
                antialias: true,
                trim: false,
                transparent: false
            } ).then( function( blob ){
                NGL.download( blob, "example.png" );
            } );
```
The downloaded screenshot has visible transparent lines in it, as if the stitching didn't occur properly. Here is an example:

![3fh9 1](https://user-images.githubusercontent.com/1047170/48256057-c0caee80-e40e-11e8-9317-473f3cbf70be.png)

The image is created correctly if I set `antialias: false`. There are more lines if I increase the `factor`.

This is relatively new too, but was already broken in version `2.0.0-dev.33`. If necessary I can probably find out what version we were using before

**Comment by martingraham** [comment]
I had the opposite problem back in June (I got a grid of overplotted lines) and put in a fix --> https://github.com/arose/ngl/issues/523

I wonder if something else has changed which now means my fix breaks? I get the same effect you now see in your image that was previously ok.

**Comment by martingraham** [comment]
Had a look and I did this in the tiledRenderer to replace my earlier code, which was breaking as height was arriving as a non-integer which broke the % modulo test. Now I don't get gaps or overdrawn lines in my antialiased pngs.

if (this._antialias) {
        const w = Math.round((offsetX + width) / 2) - Math.round (offsetX / 2);
        const h = Math.round((offsetY + height) / 2) - Math.round (offsetY / 2);
      this._ctx.drawImage(
        viewer.renderer.domElement,
        Math.round(offsetX / 2),
        Math.round(offsetY / 2),
        w,
        h
      )
    }

I've submitted a pull request if that's easier

**Comment by martingraham** [comment]
Think this can be closed now

**Comment by fredludlow** [comment]
Okay, closing, feel free to reopen if it reappears
