### ISSUE TITLE
Constructing `stage` on hidden element give an empty view

### ISSUE THREAD

**Issue by lyskov** [arose/ngl#601]
If i try to construct `stage` on hidden element and then unhide it i am getting view with 1x1 size. Here is the minimal example to reproduce this (below). Note that uncommenting `stage.setSize(400, 300);` will fix the issue. Thanks,

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
</head>
<body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://unpkg.com/ngl"></script>

    <div id="parent" style="display: none;">
        NGL Viewer:
        <div id="viewport" style="width:400px; height:300px;"></div>
    </div>

    <button id="hide">Hide</button>
    <button id="show">Show</button>

<script>
    $(document).ready(function() {
        var stage = new NGL.Stage("viewport");
        stage.loadFile("rcsb://1crn", {defaultRepresentation: true});

        $("#hide").click(function(){
            $("#parent").hide();
        });
        $("#show").click(function(){
            $("#parent").show();
            // uncommenting this will fix the issue:
            //stage.setSize(400, 300);
        });
});
</script>

</body>
</html>
```

**Comment by arose** [comment]
try calling stage.handleResize()

**Comment by ppillot** [comment]
This is a limitation of the canvas element: it must be in the DOM to be drawn onto. Instead of using display none, you can use any combination of visible: hidden, margin: -9999px and if you use absolute positioning position it outside the boundaries of your page viewport, or with a z-index such as it appears under your other elements

**Comment by lyskov** [comment]
I see... - thank you for clarifying this @ppillot ! Unfortunately in my case i can not control init/delete of parents element because it done by JS framework. However i found a workaround: i can create new element and stage for each new hide/show cycle and it seems to work.
