### ISSUE TITLE
Choose default alt location for residue selection

### ISSUE THREAD

**Issue by jmiller656** [arose/ngl#620]
Hey, I was wondering if there was a way to do a selection for a residue in NGL where I can only select one of the alt locations for a residue rather than have all of them show up. For example, if I select 195:A for the protein 1SSX, I get two SER 195's. They are denoted by %A and %B in the viewer. I'd like to show only one of these

**Comment by fredludlow** [comment]
Yes, the syntax is `%A` for altloc A, you can use it in combination with a residue e.g. `195:A%A` or as part of a bigger expression. Docs are [here](https://github.com/arose/ngl/blob/master/doc/usage/selection-language.md).

You can also use a bare `%` to get atoms with no altloc specified. 

@arose - I wonder if there's a bug in the between-residue bonding e.g. if I load 1SSX and add a line repr with selection `(% or %B) and 193-196` the backbone is no longer connected - I've never had to use altloc selections so not sure if this is intended or not

**Comment by jmiller656** [comment]
Hey @fredludlow , thanks for the response. Does that mean if I use `195:A%`, then I should only show one serine residue?

Will this work in general with amino acids in proteins? 

For the project I'm working on, I'm trying to display certain amino acids in a protein. I know the residue number and the chain name to select from, but don't know beforehand if there will be alt locations that I have to deal with. I'm trying to show only one version of each amino acid, so I wasn't sure if I had to find some way of knowing that there were alt locations beforehand (is there a way to do this in ngl?) or if there was a way to ignore alt locations in general

**Comment by fredludlow** [comment]
If it's a file from the PDB then it should be [spec compliant](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM) and this would be true:

> If an atom is provided in more than one position, then a non-blank alternate location indicator must be used for each of the atomic positions.

So something like `195:A and (%A or %)` would likely display one position for each atom for most cases: If it has only one position the `%` catches it, if it has multiple positions then we're assuming that one of them is labelled A and caught by `%A`. 

This wouldn't work for an atom which only has altLoc B and C (this seems unlikely but you could have 3 states, one of which has a disordered section with no coordinates for some residues). This is probably a very rare situation - and you'd want to have a close look at what's going on in that case anyway.

If that's not enough you could use the NGL Structure object (`stage.compList[idx].structure`) - iterate over chains/atoms/whatever and figure out what's going on in that particular structure?

**Comment by jmiller656** [comment]
Thanks, this helped! I ended up finding that using just `%` gave me nothing because there was no version of SER195 that wasn't an alt location. Found another way to get alt location information and used that along with `%A` to display what I needed.
