### ISSUE TITLE
connection through a socket for manipulating primitives

### ISSUE THREAD

**Issue by Oeffner** [arose/ngl#624]
Dear all,

First of all a big thank you to the developers of NGL which seems to satisfy many of our needs at my work. Apart from using it for displaying molecules we would also like to use it for illustrating data which essentially are scatter plots on a grid. I'm a novice when it comes to JavaScript but have written a script for NGL that draws primitives such as spheres as a function of supplied xyz coordinates. The number of spheres can become rather large and it is not unusual for the javascript file to exceed 20-40 Mb. 

If I want to change just a few primitives rather than all of them my question is if it would be possible to manipulate the primitives in a quicker way than having to reload such large javascript file for any changes. Is it possible through a websocket from python to change properties of the primitives that are already defined in the javascript file? 

The code snippet below places a sphere at the origin and then when a connection is established to a websocket on localhost, port 7894 it then attempts to move the sphere to the position [1, -2, 3] as well as resizing it. The problem currently is that although the sphere is drawn at the new position the original sphere remains at the origin. 

Is what I'm doing too hacky for NGL or is there a better way to achieve what I want?

Many thanks,

Rob

``

var connection = new WebSocket('ws://127.0.0.1:7894/');
var a=[0,0,0];

window.addEventListener( 'resize', function( event ){
  stage.handleResize();
}, false );

var stage;
var shape;
var shapeComp;

       
var hklscene = function (b) {
  stage = new NGL.Stage('viewport', { backgroundColor: "grey" });
  shape = new NGL.Shape('shape');
  stage.setParameters( { cameraType: "orthographic" } );

  shape.addSphere(  b  , [ 1, 1, 1 ], 0.5, 'Origo');

  shapeComp = stage.addComponentFromObject(shape);
  shapeComp.addRepresentation('buffer');
  shapeComp.autoView();
}
     
document.addEventListener('DOMContentLoaded', function() { hklscene(a) }, false );
     
// receive messages from websocket server
connection.onmessage = function (e) {
  shapeComp.removeRepresentation('buffer');
  stage.removeComponent(shape);
  shape._primitiveData.sphereRadius[0] = 0.3
  shape._primitiveData.spherePosition[0] = 1
  shape._primitiveData.spherePosition[1] = -2
  shape._primitiveData.spherePosition[2] = 3
  shapeComp = stage.addComponentFromObject(shape);
  shapeComp.addRepresentation('buffer');
 
  shapeComp.autoView();
};

``

**Comment by fredludlow** [comment]
The problem is this line:
`shapeComp.removeRepresentation('buffer');`
You need to keep a reference to the representation and remove it (rather than using the String 'buffer')

I made a working example here:
https://codepen.io/fludlow/pen/moWRwe

**Comment by Oeffner** [comment]
Thanks @fredludlow for your help and sorry for the late reply.
