### ISSUE TITLE
Coloring each structure(more than 1) with differents color (unique stage) 

### ISSUE THREAD

**Issue by adriangarciarecio** [arose/ngl#625]
Hi, 

my name is Adrián and I post this question because I would want to color different pdb's (around 4) in the same stage with different colors (all of his atoms contained in the pdb). The result that I want is each structure be different compared the others.  I tried the next (but when I display the structures each of them are colored with rainbow colors not each structure wtih a different color):

for (i = 0; i < pdbs.length; i++) {
                    stage.loadFile(path_to_dir + pdbs + ".pdb", { backgroundColor: 'white' }).then(function (o) {
                        o.addRepresentation("cartoon", {
                            color: "random",
                            sele: "protein"
                        })
                    });

Best regards,
Adrián.

**Comment by fredludlow** [comment]
You want the "uniform" colorScheme and a list of colors to cycle through

```javascript
var colorList = ['red', 'orange', '#ff00ff']
var nColors = colorList.length
```
Then when adding your representation use something like this to cycle through them:

```javascript
for (i = 0; i < pdbs.length; i++) {
  stage.loadFile(path_to_dir + pdbs + ".pdb", { backgroundColor: 'white' }).then(function (o) {
    o.addRepresentation("cartoon", {
      colorScheme: "uniform",
      color: colorList[ i % nColors ],
      sele: "protein"
    })
  });
}

**Comment by adriangarciarecio** [comment]
Hi, 

first of all thank you for the answer. I tried to insert the code that you explain above but the result that I have is that all the structures were colored with the same color. I will do some tests to try discover how give to every structure his color. 

Thank you,
Adrián.

**Comment by fredludlow** [comment]
Oops, that's because the `i` variable is updated by the loop code. You need to capture its value in a function call or a closure, e.g.

```javascript
var structures = ["rcsb://1crn", "rcsb://1ajx", "rcsb://2vts", "rcsb://2vta"]

var colors = ["cyan", "red", "green", "blue"]

function createCartoon(path, color) {
  return stage.loadFile(structures[i]).then(function(o) {
    o.addRepresentation("cartoon", {
      colorScheme: "uniform",
      color: color,
      sele: "protein"
    })
    return o
  })  
}

for (var i = 0; i < structures.length; i++) {
    var color = colors[ i % colors.length ]
    createCartoon(structures[i], color)
}
```

NB: Those return statements in createCartoon mean you get back a promise that resolves to the component, in case you need to capture it and do anything else with it

**Comment by fredludlow** [comment]
https://codepen.io/fludlow/pen/PLpEOQ

**Comment by adriangarciarecio** [comment]
Oh perfect! Now works! 

Thank you so much!
