### ISSUE TITLE
Structures load in different order in Edge/Chrome

### ISSUE THREAD

**Issue by duerrsimon** [arose/ngl#627]
Hi, I am loading multiple structures. 
I have noticed that structures load in different speeds. 
Is this intentional or a bug in the way these requests are handled?

The DevTools output from Chrome:
 `
>ngl.js:1 STAGE LOG loading file 'model1.pdb'
>ngl.js:1 STAGE LOG loading file 'model2.pdb'
>ngl.js:1 STAGE LOG loading file 'model3.pdb'
>ngl.js:1 STAGE LOG loading file 'model4.pdb'
>ngl.js:1 STAGE LOG loaded 'model1.pdb'
>ngl.js:1 STAGE LOG loaded 'model3.pdb'
>ngl.js:1 STAGE LOG loaded 'model4.pdb
>ngl.js:1 STAGE LOG loaded 'model2.pdb'
``

**Comment by ppillot** [comment]
That's typical of asynchronous operations: requests are sent in order but they are then processed in the same order as the responses come in. It's the most efficient implementation given the single threaded nature of Javascript. That's also why NGL code for handling files loading is conveniently  wrapped into promises.
