### ISSUE TITLE
NGL viewer only shows one chain

### ISSUE THREAD

**Issue by Taoaoxiang** [arose/ngl#630]
Hello Dr. Rose,

I have found that sometimes NGL viewer only show one chain of a dimer. 
For example: 
1. In your webapp (http://nglviewer.org/ngl/), type in "3d90" in the "File-> PDB [    ]". It only shows Chain A. Even when I tried to put ":B" in the "filter selection", it still wouldn't show the structure of Chain B.
2. Then I downloaded that PDB (ID: 3d90) file and deleted everything else other than ATOM/HETATM/TER. and I used "File->Open..." to open the modified pdb file. It turned out that NGL viewer shows both chains. 
I know it's not a big deal, but I'm just curious what caused this minor issue.

Best regards,
Oliver

**Comment by arose** [comment]
By default, NGL shows the first assembly given in the PDB file (BU1). To see all depostited coordinates change it to AU.

![Screen Shot 2019-03-12 at 5 47 59 PM](https://user-images.githubusercontent.com/272250/54245674-04ce1d00-44ef-11e9-93e6-c2c3056bc875.png)

**Comment by Taoaoxiang** [comment]
Oh, I see. 
So by default, it shows the first assembly when import from PDB.
While it shows full assembly when load from local.
Just curious. Is there any reason you want to make them different? :wink:

**Comment by arose** [comment]
When loaded it locally, if I understand correctly, you removed everything but atom... records, which means also the information what constitutes an assembly. In that case NGL has no other choice but to show the given coordinates as there is no assembly info.

**Comment by Taoaoxiang** [comment]
I got it. Thank you, Dr. Rose!
