### ISSUE TITLE
removeAllComponents doesn't work if representations added with spurious extra arg

### ISSUE THREAD

**Issue by garyo** [arose/ngl#634]
You may or may not consider this significant, but it took me some time so here it is :-) 

If you add some representations with a spurious extra param to `addRepresentation`, then `stage.removeAllComponents` doesn't remove the component using them. (Yes, this is user error.)
Here's a codepen: https://codepen.io/oberbrunner/pen/aMqGGw
In that pen, each "reset" button should clear the stage and add its own molecule. It works fine if the representations are added without the extra param, but when that's defined (see `extraOpt` at the top), the old component doesn't get cleared -- you see both.

Also (probably a consequence of the same issue), if you run that codepen with the Chrome dev tools console open, you'll see errors there after clicking the reset. E.g.:
```
ngl.js:1 Uncaught TypeError: Cannot read property '12' of undefined
    at Yy.Zy.atomIndex1.get (ngl.js:1)
    at Yy.Zy.atom1.get (ngl.js:1)
    at Id.Rd.closestBondAtom.get (ngl.js:1)
    at Id.Rd.closeAtom.get (ngl.js:1)
    at Id.getLabel (ngl.js:1)
    at Object._v.tooltipPick [as callback] (ngl.js:1)
    at ngl.js:1
    at Array.forEach (<anonymous>)
    at Av.run (ngl.js:1)
    at Ev._onHover (ngl.js:1)
```
Presumably something's been deleted but something else is still referring to it.

I got into this because I somehow thought I should pass `{lazy: false}` as an extra arg to `addRepresentation` -- totally my error. But it caused this unexpected behavior.

**Comment by fredludlow** [comment]
Looking at the source for `StructureComponent.addRepresentation`, the 3rd parameter is `hidden` which basically means hidden from reprList. This is used for measurements (so the lines/spheres etc don't pollute `reprList`). The measurements get tidied up explicitly in `StructureComponent.dispose`

I think this is a bug, not sure whether it should be:
1) Impossible for user to create hidden representations (i.e. it's a private feature for measurements)
2) Possible, but they all get tracked and disposed of appropriately.

**Comment by arose** [comment]
I admit the design is not particularly user friendly but I would not say it is a bug. I suppose the third 'hidden' param could be hidden in a private method it someone wants to make a PR.

**Comment by fredludlow** [comment]
Okay, not an urgent fix but if we return to this my vote would be to track hidden representations in a separate array and dispose them all at the end (consistent with existing behaviour of measurements, but no unexpected dangling representations).
