### ISSUE TITLE
Zooming in/out simultaneously scrolls the browser (Chrome update)

### ISSUE THREAD

**Issue by j0kaso** [arose/ngl#636]
Hey!
new issue since the recent Chrome update:
When I want to zoom in & out (mouse wheel), the complete page is scrolled.
Reproduce e.g. on rcsb-pdb with Chrome (Version 73.0.3683.75 (Official Build) (64-bit Linux)).
No problems with other viewers (e.g. glmol) or with Firefox.

Please let me know how you plan to fix it (important for other embedded projects).
Cheers,
Johanna

**Comment by arose** [comment]
fixed, see https://www.chromestatus.com/features/6662647093133312 for background, will release soon
