### ISSUE TITLE
Get list of atoms of a residue

### ISSUE THREAD

**Issue by gbayarri** [arose/ngl#639]
Hi, is it possible to get a list with the atoms of a given residue? I mean every atom number of the residue.

For example I need all the atoms of the 62G / 201 residue:

...
TER    1066      GLU A 168                                                      
HETATM **1067**  N3  62G A 201      13.579  -4.702   0.217  1.00 10.91           N  
HETATM **1068**  C5  62G A 201      12.665  -6.469  -0.765  1.00 11.78           C  
HETATM **1069**  C6  62G A 201      11.648  -5.870  -0.059  1.00 11.43           C  
HETATM **1070**  C7  62G A 201      10.280  -6.366  -0.193  1.00 12.83           C  
HETATM **1071**  C8  62G A 201       9.429  -6.410   0.909  1.00 12.41           C  
HETATM **1072**  C10 62G A 201       7.735  -7.470  -0.416  1.00 12.09           C  
HETATM **1073**  C13 62G A 201      10.643  -6.857  -2.635  1.00 14.72           C  
HETATM **1074**  C15 62G A 201      12.642  -7.632  -1.651  1.00 11.72           C  
HETATM **1075**  C17 62G A 201      14.039  -8.052  -2.074  1.00 11.50           C  
HETATM **1076**  C21 62G A 201       9.890  -6.417  -3.822  1.00 14.13           C  
HETATM **1077**  C22 62G A 201       8.764  -5.653  -3.620  1.00 17.07           C  
HETATM 1093  O   HOH A 301       6.037  26.426   3.352  1.00 10.80           O
...

**Comment by fredludlow** [comment]
Assuming you've got the component as `myComponent`

```javascript
var view = myComponent.structure.getView(new NGL.Selection('201'))
view.eachAtom( a => { console.log(a.serial) } )
```
Should log the numbers you've got in bold above

**Comment by gbayarri** [comment]
Thanks, it's perfect!
