### ISSUE TITLE
 Totally clean the stage

### ISSUE THREAD

**Issue by gbayarri** [arose/ngl#640]
Hi, I'm loading a NGL in a modal window. After close / open the modal a few times I get the error "WARNING: Too many active WebGL contexts. Oldest context will be lost.". Is there any way to totally clean the stage after closing the modal? I tried redefining the variable where I store the stage and with removeAllComponents(), but it doesn't work.

Thanks.

**Comment by fredludlow** [comment]
Can you try the Stage.dispose() method? Also, is the canvas element removed from the DOM when the modal is closed? 

If that doesn't work could you make a minimal example? ([codepen](https://codepen.io/pen?template=JNLMXb) or other)

**Comment by gbayarri** [comment]
Hi, @fredludlow 

Here you have a codepen example that reproduces the behavior of my site:

https://codepen.io/anon/pen/QPVpbV

I show a viewport at the beginning and then, clicking at the button, two more in the modal window. In my computer, after opening and closing a few times (eight), the WARNING message appears and the first representation disappears (the one I name "stage0" in this example).

In this example I get some error related to the Stage.dispose() method, maybe I'm not using it properly. I also remove the canvas and the html content of the viewport layer (just in case).

For getting the warnings and errors, please use the Chrome / Firefox console. The codepen console doesn't show all the messages.

**Comment by fredludlow** [comment]
Thanks for that, that's really helpful. I've slightly refactored it to get rid of the error (your modal.bs.hidden listener was added multiple times and called stage1.dispose() multiple times)

https://codepen.io/fludlow/pen/GLXEBN

I have a feeling this could be a pain to fix properly - looking at the Chrome devtools memory tab (you can snapshot before and after opening/closing the modal and compare) there are canvas elements that don't get garbage collected. I suspect at least one reason is that event listeners are added and never removed. I'll try and have a dig...

In the meantime, you could possibly re-use the canvas and just remove all components on modal hide?

**Comment by gbayarri** [comment]
Thanks for your fast answer.

I'm not sure about how to re-use the canvas. In the example below I use Stage.removeAllComponents() but the problem persists. Maybe it happens because I create a new stage every time I launch the modal? I don't know how to create the stage just once and then use Stage.loadFile() every time the modal is launched. If I create the stage at the beginning, then the loadFile() shows nothing.

https://codepen.io/anon/pen/dLqZQY

**Comment by ppillot** [comment]
A canvas can not be instantiated if it is not in the DOM (otherwise it has no dimension and nothing can be drawn into it). You can add a check for the value undefined so that you are creating a stage only if it has not been created yet. And then, you should not remove it from the DOM by setting the container content to ''
Here are my modifications to your pen: https://codepen.io/anon/pen/oOPqzR

**Comment by gbayarri** [comment]
Thank you very much, @ppillot !

**Comment by fredludlow** [comment]
Thanks @ppillot
