### ISSUE TITLE
is it possible to get the protein accession of a picked atom?

### ISSUE THREAD

**Issue by gustavo-salazar** [arose/ngl#642]
Hey there,
I'm trying to get the accession of the protein of a clicked atom.
```javascript
    stage.signals.clicked.add(picked => {
      if (picked) {
        const residue = picked.atom;
        const chain = residue.chainid;
        console.log(chain);
        // protein accession?
      } 
    });
```
My motivation is to be able to deal with cases where a chain has more than one protein, for example, the structure [1ao7](https://www.ebi.ac.uk/pdbe/entry/pdb/1ao7/protein/4) in the chain D has 2 proteins, so I need to know if a clicked amino acid belong to one protein or the other.

Thanks,

Gustavo

**Comment by fredludlow** [comment]
The information is in the mmcif and PDB formats (possibly mmtf too?) but not parsed or stored by NGL so at the moment it's not possible without you keeping track of that information yourself. There is a minimal StructureHeader [class](https://github.com/arose/ngl/blob/b4a5eaafeb63dc9f190745af79c4f201b69f1b2c/src/structure/structure.ts#L111) that could be extended to include this data if you/somebody wants to make a PR to parse it from the header and populate the data.

**Comment by gustavo-salazar** [comment]
OK cool, thanks for letting me know!
