### ISSUE TITLE
Is it possible to rebuild only the changed portion of a representation?

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#643]
Hi, when i use `rep.setSelection(sele)` the representation is rebuilt as a whole. Is there a way to add/remove a portion of the mesh without having to completely rebuild the representation any time?

**Comment by fredludlow** [comment]
That's baked in to the way most representations work at the moment - have you got an example of what you want to do?

**Comment by giagitom** [comment]
When selections change frequently and a lot of atoms are selected building
representations becames time consuming. This implementation could increase
performances when a fiew atoms are added or removed from selection.


Il mar 16 apr 2019, 11:32 Fred Ludlow <notifications@github.com> ha scritto:

**Comment by arose** [comment]
Hi, this is not possible in NGL. However in Mol* (https://molstar.org) we handle representations on a per-chain level. So when you new selection does not change a whole chain the representation for that chain will get reused. Do you think that would be fast enough for your use case?

**Comment by giagitom** [comment]
Sure, this would be a big improvement I think.

**Comment by arose** [comment]
Good to hear.
