### ISSUE TITLE
Wrong guessed bonds for molecules/atoms separated by TER tag

### ISSUE THREAD

**Issue by GerardBCN** [arose/ngl#646]
Hi Alexander,

thanks for the great work you are putting into this project.

I am trying to depict a protein structure that has some "artifitial" atoms around them, which correspond to hotspots I am interested to plot as single VDW beads. 

I am separating these "extra" non-natural beads atoms with TER tags, which I would expect should tell to NGL that they are different molecules and therefore should not try to connect them with bonds. However, when one of these beads is very close to a protein atom, it guesses some bonds which should not be there.

Here's the type of structure I'm trying to plot:

```
[ protein goes here]

ATOM   1130  HG2 LYS    69      29.210  68.850  44.830  0.00  0.00      P0   H  
ATOM   1131  HG3 LYS    69      30.110  70.390  44.640  0.00  0.00      P0   H  
ATOM   1132  CD  LYS    69      30.980  68.550  43.830  0.00  0.10      P0   C  
ATOM   1133  HD2 LYS    69      30.460  68.430  42.870  0.00  0.00      P0   H  
ATOM   1134  HD3 LYS    69      31.850  69.180  43.640  0.00  0.00      P0   H  
ATOM   1135  CE  LYS    69      31.380  67.220  44.350  0.00  0.10      P0   C  
ATOM   1136  HE2 LYS    69      32.120  67.360  45.140  0.00  0.00      P0   H  
ATOM   1137  HE3 LYS    69      30.520  66.770  44.840  0.00  0.00      P0   H  
ATOM   1138  NZ  LYS    69      31.990  66.330  43.390  0.00  0.10      P0   N  
ATOM   1139  HZ1 LYS    69      31.340  65.680  42.980  0.00  0.00      P0   H  
ATOM   1140  HZ2 LYS    69      32.550  66.880  42.750  0.00  0.00      P0   H  
ATOM   1141  HZ3 LYS    69      32.590  65.710  43.920  0.00  0.00      P0   H  
ATOM   1142  C   LYS    69      31.910  71.070  47.760  0.00  0.10      P0   C  
ATOM   1143  O   LYS    69      31.600  72.180  47.350  0.00  0.10      P0   O  
TER
ATOM   1144      ENE Z   0      40.378  52.557  32.575 -1.00 71.54      Z0      
TER
ATOM   1145      ENE Z   1      49.044  63.391  40.575 -1.00 61.54      Z1      
TER
ATOM   1146      ENE Z   2      44.978  44.857  37.175 -1.00 60.78      Z2      
TER
ATOM   1147      ENE Z   3      38.378  55.057  50.242 -1.00 60.33      Z3      
TER
ATOM   1148      ENE Z   4      31.211  45.724  35.409 -1.00 58.20      Z4      
TER
ATOM   1149      ENE Z   5      39.378  65.057  41.575 -1.00 45.97      Z5      
TER
ATOM  1150      ENE Z   6      52.378  49.057  37.575 -1.00 44.09      Z6      
TER
ATOM   1151      ENE Z   7      39.378  44.057  46.575 -1.00 42.38      Z7      
TER
ATOM  1152      ENE Z   8      44.378  61.057  53.575 -1.00 35.71      Z8      

[ more "hotspot" beads here]

```

Here's how NGL depicts them:

![beads](https://user-images.githubusercontent.com/3877758/56658499-0caae080-669b-11e9-8c2e-af6c08925ba5.png)

Is there any way to inactivate automatic bonds guessing for certain atoms? should not the TER tag separate different molecules and therefore not trying to join them?

Thanks a lot Alex.

**Comment by arose** [comment]
There can be covalent bonds between a protein and a ligand, for instance the covalently bond retinal in rhodopsin or disulfide bonds. So TER records can't be used. However if you put your fake atoms in a separate MODELs then it should work as there is not bond detection between models.

**Comment by GerardBCN** [comment]
Thanks a lot Alex. The trick did its job! :)
