### ISSUE TITLE
Add graphical representation of the unitcell box

### ISSUE THREAD

**Issue by arose** [arose/ngl#65]
As a representation that can be added to a structure component.

**Comment by arose** [comment]
first version done ca3ebb2ec753b8fb5ced36e36929ba1969720938 adds a new representation called `unitcell`

![screenshot 37](https://cloud.githubusercontent.com/assets/272250/14943969/affc5156-0f9b-11e6-91c9-fda0df14f3d2.png)

**Comment by sbliven** [comment]
Looks good! It needs to be added to the representation docs.
