### ISSUE TITLE
LAT (lactose) in PDB files (e.g. 1JYN) wrongly typed as nucleic instead of saccharide

### ISSUE THREAD

**Issue by ppillot** [arose/ngl#650]
This issue does not happen with mmtf files as the residue detection can be based on the chemcomp type.
When this information is absent (in PDB files), saccharide detection in the `isSaccharide()` method relies on residues names. But `isRna()` detection relies on atoms identifiers and the combination O3', C4', O2' suffices to make a residue of RNA type (see https://github.com/arose/ngl/blob/91b32813c794e0fe7248021977d662638d303638/src/store/residue-type.ts#L209).
LAT has the pattern O2', O3', C4' in its [nomenclature](http://ligand-expo.rcsb.org/reports/L/LAT/index.html): isRna() returns true with this residue.
As isRna() is searched before isSaccharide() in the [getMoleculeType()](https://github.com/arose/ngl/blob/91b32813c794e0fe7248021977d662638d303638/src/store/residue-type.ts#L143) method, LAT is then incorrectly set to RNA.

I don't know what the best fix would be for this issue. Is the isRna() test stringent enough? Should the isSaccharide() test be moved before (as it requires testing against a long list of residues names for residues that are less frequent, it would make the structure building as a whole less efficient)?

**Comment by philippe-cosentino** [comment]
If I remove the quotation mark ' (replacing O3' C4' by O3 C4 etc.) LAT is detected as a saccharide.
