### ISSUE TITLE
makeImage with antialias: false leaves visible stitching lines 

### ISSUE THREAD

**Issue by hainm** [arose/ngl#652]
Hi, this is opposite to issue https://github.com/arose/ngl/issues/595
In this case, antialias=False will cause the stitching 

![image](https://user-images.githubusercontent.com/4451957/57710009-15f3f100-763a-11e9-8c36-9a38dfc3a2e8.png)

ngl version 0.35
Original issue from nglview: https://github.com/arose/nglview/issues/785#issuecomment-492083727

**Comment by arose** [comment]
can you try with the latest (v2.0.0-dev.36), there was another attempt to fix this (#637)

**Comment by hainm** [comment]
confirmed, thanks.
