### ISSUE TITLE
Surface calculation strategy

### ISSUE THREAD

**Issue by biharck** [arose/ngl#655]
Hello, guys. Good afternoon. Could you guys help me to understand which strategy NGL uses to calculate surface? Is it ASA (Accessible surface area), Connolly or something else?

Cheers,

**Comment by fredludlow** [comment]
Hi @biharck,

There are a 5 different surface calculation methods, chosen by the surfaceType parameter. There's a good definition of the types of surface you can calculate in the EDT paper: 
https://doi.org/10.1371/journal.pone.0008140 
The 'vws', 'sas', 'ms' and 'sas' all use the EDT algorithm 

I tend to use the 'av' type, which is a Connolly surface (also confusingly referred to as a molecular surface). This method was ported from AstexViewer and IMHO makes nicer surfaces. These surfaces also have the advantage that when you look at proteins and ligands interacting the surfaces tend to show the shape complementarity quite nicely, e.g:
http://nglviewer.org/ngl/?script=representation/molecularsurface-av
(turn on dark theme)
