### ISSUE TITLE
How to know when the model and representations are fully loaded?

### ISSUE THREAD

**Issue by garyo** [arose/ngl#657]
I'm embedding NGL. I'm loading a model like this (in an async typescript function):
```
  let obj = await stage.loadFile(name, { defaultRepresentation: false })
  obj.setDefaultAssembly('BU1') 
  representations.forEach((elt, idx) => {
    obj.addRepresentation(elt[0] as NGLViewer.StructureRepresentationType, elt[1])
  })
  obj.autoView()
```
but when I dump the Three.js scene (stage.viewer.scene) immediately after this, the graphics objects don't exist yet. I think they're getting created in the background. (Note that I'm using one or more "surface" representations which take more computation than some of the simpler ones that are computed inline.)

Is there any callback or hook so I can know when the world is fully loaded?

Looking at the source, in [representation.ts](https://github.com/arose/ngl/blob/17b06d7e1f1e85698462d016f87772dd227427bf/src/representation/representation.ts#L470) the function `representation.make()` takes an optional callback to call when it's done, but that doesn't get threaded up to any useful API. And `addRepresentation` doesn't have a callback the way `loadFile` does.

I suppose I could hook into the internal `tasks` Counter in the representation and call something when that goes to zero, but I presume that's not part of the public API. (?)

**Comment by ppillot** [comment]
loadFile returns a Promise, meaning that subsequent operations on the result of that promise are asynchronous.
If you add more code after that, it is executed synchronously, that is before your Promise has executed. In other words, when you dump the comment of the scene straight after the code you mentioned, the file has not been loaded yet. 
In your case, I would make the execution of the subsequent code inside the Promise returned by the loadFile method (I am not yet familiar with the await/async syntax to guide you there)
```javascript
stage.loadFile(name, { defaultRepresentation: false })
.then (obj => {
  obj.setDefaultAssembly('BU1') 
  representations.forEach((elt, idx) => {
    obj.addRepresentation(elt[0] as NGLViewer.StructureRepresentationType, elt[1])
  })
  obj.autoView()
.........add your code here........
})
```

Regarding your question, yes there is also a signal that is triggered whenever a representation is updated. You can bind a function call to its dispatch property.

**Comment by garyo** [comment]
I'm already `await`ing the loadFile, so I'm doing just what your code does. (`await` basically waits for the promise to resolve and returns the promise's value.)
It's not the loading that's causing me trouble, it's the surface representation.

As for the signal in question, please point me to it! I did find `component.signals.representationAdded`, but that is sent before the actual graphics objects are created ([here](http://nglviewer.org/ngl/api/file/src/component/component.js.html#lineNumber255)) because `makeRepresentation` kicks off bg tasks in its queue and doesn't wait for them. If there is a signal that is sent when it's updated (not just added), that might be just what I need.

**Comment by arose** [comment]
There is `stage.tasks` for example `stage.tasks.onZeroOnce(callback)`.

**Comment by garyo** [comment]
Aha, that's what I was looking for. That works perfectly, thank you @arose!
(I wasn't sure that the `.tasks` member was part of the public API.)
