### ISSUE TITLE
Coloring

### ISSUE THREAD

**Issue by ODIN987** [arose/ngl#659]
hello 

 i have an array of hexadecimal codes which i need to color my protein according to it 

so residue 1 will have the color denoted by array[0] and etc.

how can i do it in ngl viewer javascript. i need help as soon as possible

**Comment by fredludlow** [comment]
You're probably best creating a custom colormaker following the color/custom example:

https://codepen.io/fludlow/pen/qGzMoQ?&editable=true&editors=001

In your case the relevant bit would be something like:
```javascript
var myHexArray = [...]
var schemeId = NGL.ColormakerRegistry.addScheme(function (params) {
  this.atomColor = function (atom) {
  return myHexArray[atom.resno] // Or atom.resno - 1, See note below
  }
})
```

`atom.resno` is the residue number in the PDB file, also available is `atom.residueIndex` (that's the internal index of the residue, starting at 0).

**Comment by ODIN987** [comment]
hello @fredludlow 
so your code is actually mapping residue to hexdecimal color at position 0 in myhexArray and so on ?

**Comment by ODIN987** [comment]
hello @fredludlow
so your code is actually mapping residue 1 to hexdecimal color at position 0 in myhexArray and so on ?
saying i have 5 residues then the coloring would be as follow

res1 -> "#abcdefg"
res2 -> "#abddefg"
res3 -> "#bbcdefg"
res4 -> "adsasxxx"
fes5-> "3e3r2fw"
res6 -> "#redred"

**Comment by fredludlow** [comment]
So the code in my previous example:

```javascript
return myHexArray[atom.resno]
```

will use the value at myHexArray[1] for any atom belonging to residue 1. What is correct for you depends on the input array (bear in mind that not all structures start at residue 1, and some have gaps in their residue numbering).

If you use a custom colormaker, then when NGL is creating the representation it will call the `atomColor` function that you define for every atom in your structure. You can write whatever logic you like in that function and you have access to all the properties of the atom, residue, chain etc via the [AtomProxy](http://nglviewer.org/ngl/api/class/src/proxy/atom-proxy.js~AtomProxy.html) object that gets passed in.

**Comment by ODIN987** [comment]
Ok thanks for the help I got it @fredludlow
