### ISSUE TITLE
Please add to TODO how to run examples

### ISSUE THREAD

**Issue by yurivict** [arose/ngl#660]
Just running ```chrome webapp.html``` produces an empty screen.
So how to run them then?

**Comment by fredludlow** [comment]
Did you get this working? webapp.html needs to be hosted somewhere, minimal steps for this are:

```bash
git clone https://github.com/arose/ngl.git
cd ngl
npm install
npm run build
# If you have python, you can start a basic server like so:
python -m SimpleHTTPServer # python 2
python -m http.server # python3
```
And open localhost:8000/examples/webapp.html in your browser

If you're just including the viewer in your own project you can use the pre-built version from the dist folder: 
https://github.com/arose/ngl/blob/master/dist/ngl.js
