### ISSUE TITLE
zooming propagates into the scrolling of the page

### ISSUE THREAD

**Issue by gustavo-salazar** [arose/ngl#662]
Hey there, 

We are embedding NGL in our website, but we notice that the zooming events, either using a mouse or a mouse pad, are propagated as scrolling events for the page, so if you zoom, you might end up moving the structure viewer out of the view space.

I took one of the example in the page and adapt it to emulate my issue: https://codepen.io/gustavo-salazar/pen/dBPEWj

Is there any way that I can stop the propagation of the event?

Thanks,

Gustavo

**Comment by gustavo-salazar** [comment]
BTW, it seems that this is only happening in chrome. I tried Firefox and safari and it seems to work well there.

**Comment by hainm** [comment]
your example works fine (no issue) in my Chrome on Centos 7 machine.

**Comment by gustavo-salazar** [comment]
Wow that is then very specific then, I just check around and the problem happens in several chrome machines but all of them in Mac, and then I check on an Ubuntu machine and it doesn't happen there

**Comment by arose** [comment]
Hi @gustavo-salazar, are you using the latest version (dev-36)? It should be fixed by 4d6f0894c062b6bffb5aa29cdb8f6f2fdad44a33, see also #636.

**Comment by gustavo-salazar** [comment]
Thank you so much! I was using (dev-33) and just tested locally with (dev-36) and it solves the issue!

Sorry I didn't notice there was another issue about it.

**Comment by arose** [comment]
No problem, glad it worked
