### ISSUE TITLE
how to overcome "THREE.WebGLRenderer: Context Lost."?

### ISSUE THREAD

**Issue by hainm** [arose/ngl#666]
hi,

Saying I want to create 10 viewers to display 10 ligands and then create a grid of `2x5` to visualize 10 ligands at the same time.
However, only some of the viewers display and others are just broken. The JS console says "THREE.WebGLRenderer: Context Lost.".

Is there any way to overcome this issue or I have to live with it? 

I notice that the grid example in NGL works great: http://nglviewer.org/ngl/grid.html
Do you display static images because of above reason? 
thanks

**Comment by arose** [comment]
there is only a single ngl instance in the grid example that gets moved around, if the mouse is not over a cell it only shows an image

**Comment by hainm** [comment]
thanks, so my case is 10 instances. :D

**Comment by hainm** [comment]
uhm, my Chrome on my Mac can only display 7-8 stages at most:

<img width="1280" alt="Screen Shot 2019-06-22 at 12 53 46 AM" src="https://user-images.githubusercontent.com/4451957/59959571-63108180-9488-11e9-9d4e-ce3ffc216cb9.png">

**Comment by hainm** [comment]
The real application of multiple views is to compare multiple ligands with slight difference (e.g: having one extra atom in different positions).

**Comment by hainm** [comment]
Related issues:
- https://github.com/plotly/plotly.js/issues/2333

**Comment by ppillot** [comment]
You can use the trick of having only 2 WebGL contexts: one is not visible and is in charge of generating the static images, the other is visible when the mouse hovers an image and replaces it. When you mouse out, you need to store the orientation of your view to keep in sync the generated images with the 3D view. It's really tricky to get it right...

**Comment by hainm** [comment]
thanks @ppillot  for your suggestion. However, I am not sure if that applies to my case, where I want to sync the camera of, saying, 10 different ligands to examine them at the same times.
But I guess there's no way to overcome this, may be just limit to display only few at a time. cheers.
