### ISSUE TITLE
Animation callback?

### ISSUE THREAD

**Issue by garyo** [arose/ngl#672]
I'm integrating NGL with some other three.js code, and need to call an `update` function on each frame (this is for tweening to animate the camera or other scene objects). Is there any way to hook into the Viewer's `animate` or `render` method? If not, would a PR to add a `.setPreRenderCallback(cb)` call or something like that be appropriate? Or perhaps emit a signal, to permit multiple such callbacks?

**Comment by garyo** [comment]
Reading more of the source, perhaps there's a way to create a custom animation... Aha, and I think there is already a signal `viewer.signals.ticked`. If that's all I need, feel free to close this ticket.

**Comment by fredludlow** [comment]
The `ticked` signal gets fired every animationFrame (it's continuous as long as the page is active) and the `rendered` signal gets fired after each call to `viewer.render` (which ends up with a call to `WebGLRenderer.render()`). The `rendered` signal is only fired when something NGL knows about is updated (camera position, representations etc). Not sure if that helps?

**Comment by garyo** [comment]
It does, thanks! 

Just for posterity, it seems `ticked` is fired before the render, and you can use `viewer.requestRender()` when you've updated something.
`rendered` is fired _after_ the render. `ticked` seems to give smoother, more responsive animation.
