### ISSUE TITLE
support beta strand arrow?

### ISSUE THREAD

**Issue by hainm** [arose/ngl#677]
Hi,

this issue is originally from `nglview` but I think it's more about NGL. I think it's quite common to 
have this kind of representation. Just open a ticket here in case you know how or would like to support it (I am more Python guy). cheers and thanks.

--------------------
@mktonycho: https://github.com/arose/nglview/issues/785#issuecomment-511286961
Hi Nglview crew!
I really love Nglview. 
Now I just have one question.
I wonder what are some methods to draw beta-strand arrows. 
Beta-strands in protein indicates the direction such that more than two strands are either aligned in parallel or anti-parallel direction. 

For ex. in VMD, you can see something like this.
![image](https://user-images.githubusercontent.com/11916748/61198412-dcf8fb00-a714-11e9-8e9a-824234492f22.png)

It would be awesome to do something like this in Nglview as well.

Is adding an artificial arrow the only way to go for now like the code provided below?
shape.addArrow( [ 1, 2, 7 ], [ 30, 3, 3 ], [ 1, 0, 1 ], 1.0 );

Thank you very much for your hard work and lovely program.
Much appreciated.

Best regards,
Tony Cho

**Comment by hainm** [comment]
Example from [pv](http://biasmv.github.io/pv/demo.html)

![pv](https://user-images.githubusercontent.com/4451957/61237020-7caf8c80-a707-11e9-8888-b99cc19786d4.png)

**Comment by arose** [comment]
This is implemented in our new viewer Mol* (molstar.org), see below, and I don't intend to implement this myself in NGL

<img width="715" alt="Screen Shot 2019-07-16 at 1 30 13 PM" src="https://user-images.githubusercontent.com/272250/61287600-e6926980-a7cd-11e9-8a20-acd228ae5707.png">

**Comment by hainm** [comment]
@arose  is it a right time to try molstar in nglview yet?

**Comment by arose** [comment]
I would not try to do it in nglview but do a new project and think of a different architecture to sync the state between the js and py side.

**Comment by hainm** [comment]
yeah agree. would be interesting to try.

**Comment by hainm** [comment]
so, is this a right time to try molstar in notebook yet? If yes, can you please point me to where I should start
(I've had a quick look at molstar source code but I have no clue :D).
