### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Oeffner** [arose/ngl#681]
I'm trying to build NGL on Windows10 having followed the steps in https://github.com/arose/ngl/issues/660 
Unfortunately it fails during the build process with the error message below:

> 

build/js/src/ngl.js → build/js/ngl.dev.js, build/js/ngl.esm.js...
[!] Error: 'Signal' is not exported by q:\oeffner\NGL_HKLviewer\NGL\node_modules\signals\dist\signals.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
q:\oeffner\NGL_HKLviewer\NGL\build\js\src\selection\selection.js (6:9)
4:  * @private
5:  */
6: import { Signal } from 'signals';
            ^
7: import { parseSele } from './selection-parser';
8: import { makeAtomTest, makeResidueTest, makeChainTest, makeModelTest } from './selection-test';

> 

If anybody knows how to fix this that would be great. 

The reason why I'm interested in a recent build is that I want to display objects with NGL but where I can specify the exact position of clipping planes. In the released version of NGL it seems that clipping plane distances are computed relative to bounding box dimension which I have little control of. The amendments in https://github.com/arose/ngl/pull/656 seem to address this however.

**Comment by fredludlow** [comment]
Sorry for slow reply

Did you find a solution? Quite often I find deleting node_modules and doing a fresh npm install fixes bugs with building.

I've built a version with #674 and #656 merged (this is what I'm using at work and seems to be okay...). 

You can grab it from here:
https://www.fredludlow.com/ngl/merged-674/build/js/ngl.dev.js

Or minified:
https://www.fredludlow.com/ngl/merged-674/dist/ngl.js

**Comment by Oeffner** [comment]
Thank you for that. It's a couple of weeks ago I looked into that but end of the day I resorted to building NGL on Ubuntu. I had to make sure it was the correct version of npm I had installed though.
