### ISSUE TITLE
Is it possible to set the stage background color transparent?

### ISSUE THREAD

**Issue by lidaof** [arose/ngl#694]
Hi,

thanks for the nice library!!
Is it possible to set the stage background color transparent?

**Comment by hainm** [comment]
just curious: why do you need that?

**Comment by lidaof** [comment]
I put the stage in a div with background color.
I tried to change the stage background with
`this.stage.viewer.renderer.setClearColor( 0xffffff, 1);`
but it's not quite working as expected.

**Comment by hainm** [comment]
may be try this?

https://github.com/arose/ngl/blob/d35e0135eea6d603e3375b65a2a209fd8c9b47b1/src/stage/stage.ts#L161

or this
https://github.com/arose/ngl/blob/d35e0135eea6d603e3375b65a2a209fd8c9b47b1/src/stage/stage.ts#L251

**Comment by lidaof** [comment]
I used `setParameters ` it's working, thanks!

**Comment by evanbunnage** [comment]
Sorry to bump this old issue - @lidaof, how did you get this to work? I've tried using setParameters, but I'm not sure what the syntax is.

**Comment by lidaof** [comment]
Hi @evanbunnage sorry I have switched to a computer..cannot remember or find the details, sorry...i guess probably related to the code below, you can try play with it:

```
function setTheme (value) {
    var cssPath, bgColor
    if (value === 'light') {
      cssPath = NGL.cssDirectory + 'light.css'
      bgColor = 'white'
    } else {
      cssPath = NGL.cssDirectory + 'dark.css'
      bgColor = 'black'
    }
    cssLinkElement.href = cssPath
    stage.setParameters({ backgroundColor: bgColor })
  }
```
