### ISSUE TITLE
load mmCIF file error

### ISSUE THREAD

**Issue by lidaof** [arose/ngl#696]
Hi there,

I am trying to load a mmCIF format file using ngl from http://nglviewer.org/ngl/?script=showcase/ferredoxin, got error:
```
ngl.js:1 STAGE LOG error loading file: 'TypeError: Cannot read property 'charCodeAt' of undefined'
?script=showcase/ferredoxin:1 Uncaught (in promise) error loading file: 'TypeError: Cannot read property 'charCodeAt' of undefined'
```
My file is [here](https://wangftp.wustl.edu/~dli/tmp/GSM3271347_gm12878_01.impute3.round4.clean.3dg.cif). Same file can be load by [3dmol](http://3dmol.csb.pitt.edu/doc/index.html) or pymol2, not sure what  is the format error? Thanks!

**Comment by fredludlow** [comment]
First off - I'm really not familiar with the cif format (outside of the fairly standardised PDB version).

The cif-parser expects altloc to be one of your columns in the cif file.

`atomStore.altloc[idx] = altloc.charCodeAt(0);`

This is easy to fix (just check for undefined)

I started down this route here:
https://github.com/fredludlow/ngl/tree/696-cif

but there are other issues - this cif-parser expects certain names (eg `ptnr1_auth_seq_id`) but the example you've got calls it `ptnr1_label_seq_id`. Is there a definitive set of acceptable names somewhere? Do pymol and 3dmol parse the bonding section?

**Comment by lidaof** [comment]
Hi @fredludlow thank you for looking into this.
I am actually pretty new to this field, was trying to visualize this cif format using ngl. I used [dip-c](https://github.com/tanlongzhi/dip-c#interactive-visualization-of-3d-genomes) to generate the file. I will also look at the cif format specification. Thanks again.

**Comment by lidaof** [comment]
@fredludlow also  `ptnr1_label_seq_id` seems like a valid name as : http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_struct_conn.ptnr1_label_seq_id.html

**Comment by fredludlow** [comment]
I guess we need to figure out why NGL looks for `ptnr1_auth_seq_id` rather than `ptnr1_label_seq_id` and whether that's: just a bug; a better thing to do when it's available or the required behaviour for some other non-obvious reason :)

Is anyone with a good knowledge of mmcif format reading? :)

**Comment by arose** [comment]
Hi @lidaof, the file is a 3D genome, right, this is quite interesting. I would like to have a go at it. However not in NGL (as I stopped adding new features to it) but to Mol* (molstar.org). Also I would like to load the .3dg file directly and make use of Mol* support for coarse models (e.g. from pdb-dev.wwpdb.org). What do you think of that approach? Could you sent me a .3dg file via email?

**Comment by lidaof** [comment]
@fredludlow 3dmol seems have a fallback for this field: https://github.com/3dmol/3Dmol.js/blob/master/3Dmol/parsers.js#L1177

**Comment by arose** [comment]
> I guess we need to figure out why NGL looks for ptnr1_auth_seq_id rather than ptnr1_label_seq_id

`label_seq_id` is only defined for polymers and its main use is to link polymer 3d coordinates to the sequence.

**Comment by lidaof** [comment]
Sure, @arose i sent you an example file, thanks for looking into it.

**Comment by arose** [comment]
fixed in Mol* by reading .3dg files direclty
