### ISSUE TITLE
Cyclic cartoon ribbon not connected

### ISSUE THREAD

**Issue by bergwerf** [arose/ngl#704]
`1HVZ`, a defensin, has a kind of cyclic ribbon which is not connected nicely. I can imagine if this is not really a priority but I thought I'd report it anyway.

![image](https://user-images.githubusercontent.com/4458965/67897543-e771c000-fb5e-11e9-9519-81316702bc6a.png)

**Comment by arose** [comment]
yeah, fixed in Mol* :)

![1HVZ](https://user-images.githubusercontent.com/272250/67898161-08192600-fb1d-11e9-8486-a075de270788.png)
