### ISSUE TITLE
Issue with bonds between too distant atoms

### ISSUE THREAD

**Issue by giagitom** [arose/ngl#705]
Hi, 
Is there a way of not showing links between atoms too far apart? I would like to avoid this effect:
![Screenshot 2019-11-10 14:56:49](https://user-images.githubusercontent.com/20627977/68545177-dcbef280-03ca-11ea-930d-0329634c5e19.png)

**Comment by arose** [comment]
If this is a trajectory, there is an argument to handle periodic boundaries better but not getting rid of this effect in all cases. Bonds are only calculated once per type of molecule so adding a rule like you suggesting would require architectural changes.

**Comment by giagitom** [comment]
Ok thanks!
