### ISSUE TITLE
How to create a DOWNLOAD button?

### ISSUE THREAD

**Issue by yekaizhou** [arose/ngl#715]
I have tried in this way, but not working:

```
addElement(
  createElement("input", {type: "button", value: "pdb",
    onclick: function (e) {
      download(data = "./1aap.pdb", downloadName = "1aap.pdb")
    }
  })
)
```

<img width="208" alt="Screen Shot 2019-11-30 at 01 58 24" src="https://user-images.githubusercontent.com/39112978/69884991-04441380-1316-11ea-949c-d1d0950749f5.png">

I could click the pdb button that I created, but no download happens.

**Comment by garyo** [comment]
What does your `download` function do? (The event callback)

**Comment by yekaizhou** [comment]
Ahhhh solved. Change the `download` into `NGL.download`, which is an inner function in NGL.

**Comment by yekaizhou** [comment]
> What does your `download` function do? (The event callback) Also, do you see any errors in the Chrome dev tools console?

Thanks a lot. I solved it.
