### ISSUE TITLE
ngl cannot recognize two viewport in one page

### ISSUE THREAD

**Issue by CryoSky** [arose/ngl#717]
Hello, I need to put two viewports in one HTML page, the first port shows a static structure and the second port shows a trajectory.
However, when I put the two viewports in the page, the structure that loaded on the second viewport goes to the first viewport and ngl cannot recognize it. You can check https://awsem.rice.edu/check_job/9a7518f6-163c-4613-8937-064a29a819d3 for an example of a bug. Could anyone tell me how to fix this? Many thanks in advance.
The script I use:
This is for the first viewport

    <div id="viewport" style="width:100%; height:400px;margin:0 auto"></div>
  
<script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.0/js/ion.rangeSlider.min.js"></script>

<script>

NGL.mainScriptFilePath = "https://unpkg.com/ngl";
NGL.DatasourceRegistry.add("data", new NGL.StaticDatasource("../../static/jobs/9a7518f6-163c-4613-8937-064a29a819d3/"));
var stage;
document.addEventListener("DOMContentLoaded", function () {
      stage = new NGL.Stage("viewport",{
        backgroundColor: "#FFF"
      });
      stage.loadFile("data://best_1_1.pdb", {defaultRepresentation: true});

    });

</script>

This is the script of the second viewport
<div id="viewport2" style="width:100%; height:400px;"></div>
    <input type="text" class="js-range-slider" name="my_range" value="" />
<input type="button" id="Play" class="off btn btn-secondary" value="play" onclick="PlayPause(); toggleText(this.id);" />

<script>

NGL.mainScriptFilePath = "https://unpkg.com/ngl";
NGL.DatasourceRegistry.add("data", new NGL.StaticDatasource("../../static/jobs/9a7518f6-163c-4613-8937-064a29a819d3/"));
var stage;

document.addEventListener("DOMContentLoaded",
    function() { // ########### MAIN FUNCTION ###########
      var stage2 = new NGL.Stage("viewport2", {
        backgroundColor: "#FFF111"
      });
      stage.mouseControls.remove("hoverPick");

      loadStructure("data://trajectory_1.pdb") // File, color, view, Z

    });

play_button_id = document.getElementById("Play");
console.log(play_button_id);

function loadStructure(input) {
    let frame_range = $(".js-range-slider").data("ionRangeSlider");

    console.log("Loading Structure");
    stage.removeAllComponents();
    isRunning = false;
    console.log(isRunning);
    toggleText(play_button_id.id);
    return stage.loadFile(input, {
      defaultRepresentation: true,
      asTrajectory: true
    }).then(function(o) {

      o.autoView(2000)
      traj = o.trajList[0];
      player = new NGL.TrajectoryPlayer(traj.trajectory, {
        step: 1,
        timeout: 100,
        start: 0,
        mode: "loop",
        end: traj.trajectory.frameCount,
      });
      console.log("Frames");
      frame_range.update({
        max: traj.trajectory.frameCount,
      });
      console.log(frame_range);
    });

      console.log("Frames");
   
  }

var isRunning = false;

  function toggleText(play_button_id) {
    var text = document.getElementById(play_button_id);
    text.value = isRunning == false ? "Play" : "Pause";

  }
  // play/pause function
  var playcount = 0;

  function PlayPause() {

    let frame_range = $(".js-range-slider").data("ionRangeSlider");

    
    if (!isRunning) {
      player.play();
      isRunning = true;
      playcount += 1;
      traj.signals.frameChanged.add(function() {

        var fnum = traj.trajectory.currentFrame;
        frame_range.update({
          from: fnum
        });

      });
    } else {
      isRunning = false;
      player.pause();
    }
  }

// range slider paramteres
  $(".js-range-slider").ionRangeSlider({
    skin: "big",
    min: 0,
    from: 0,
    grid: true, // default false (enable grid)
    grid_num: 2, // default 4 (set number of grid cells)
    grid_snap: false,
    onChange: function(data) {
      traj.setFrame(data.from);
    },

  });
</script>
Best,

**Comment by hainm** [comment]
I think you need to use different id 
```id="viewport"
```

**Comment by CryoSky** [comment]
Thanks, I already fixed the bug by passing the variable to the function of loadstructure.
