### ISSUE TITLE
Orient only selection along Principal Axes

### ISSUE THREAD

**Issue by gauravdiwan89** [arose/ngl#722]
I am trying to select just one chain from a protein and would like to orient just this chain along its Principal Axes. Currently, NGL viewer orients it along the principle axes of the whole structure and not the selection.

Is it possible to do it just for a chain/selection?

**Comment by fredludlow** [comment]
Adapting the example in the interaction-controls [document](https://github.com/arose/ngl/blob/e8713514cfa7100a8313b3ff34a3c94b4125ced4/doc/usage/interaction-controls.md), you can do something like:
```
stage.loadFile("rcsb://1blu").then(function (o) {
  o.addRepresentation("ball+stick", { color: "atomindex" })
  
  // For whole structure
  //  var pa = o.structure.getPrincipalAxes(); 
  
  // For residues 1-10:
  var pa = o.structure.getView(new NGL.Selection('1-10')).getPrincipalAxes();
  stage.animationControls.rotate(pa.getRotationQuaternion(), 1500);
})
```
