### ISSUE TITLE
How can I save the html view (my own pdb) ? 

### ISSUE THREAD

**Issue by yanyuna** [arose/ngl#723]
How can I save the html view (my own 3D structure) ,so that when I open the html, it's my own 3D html.

**Comment by fredludlow** [comment]
A couple of options:

1) NGL is typically embedded within another project or webpage, see the examples/embedded.html file for an example. The code pen examples are also helpful for seeing example of what you can do quickly (go through the [gallery](http://nglviewer.org/ngl/gallery/index.html) and click "edit" it'll take you to the codepen with the JS loaded)

2) If you want the nice GUI of the webapp example, you can host your own copy of it and add a script to the examples/scripts directory (for this to work you'll need to have an NPM environment setup and rebuild whenever you add new scripts - see [buliding](https://github.com/arose/ngl/blob/master/DEVELOPMENT.md) instructions). For example, the script in 'examples/scripts/color/bfactor.js' can be loaded at startup by adding ?script=color/bfactor to the webapp URL, i.e. http://nglviewer.org/ngl/?script=color/bfactor

Not sure if that answers the question?

**Comment by yanyuna** [comment]
Thank you for your reply.

I make the "build" fold and run  "npm run-script build" and "npm run-script doc". when I open "examples/webapp.html" ,there is no drop-down list in the “Examples”. How can I use webapp.html locally?

**Comment by yanyuna** [comment]
Thank you for your reply.

I make the "build" fold and run "npm run-script build" and "npm run-script doc". when I open "examples/webapp.html" ,there is no drop-down list in the “Examples”. How can I use webapp.html locally?

**Comment by fredludlow** [comment]
Closing, but feel free to reopen
