### ISSUE TITLE
load js script including stage parameters into embedded html

### ISSUE THREAD

**Issue by j0kaso** [arose/ngl#729]
Hey,

I define structures and representations within a js script. I want now to load this into an embedded HTML and manipulate/use the named representations, e.g. hide show whenever sb clicks on a button.

The first problem I run into: how do I correctly load the js script? I can't just `<script src="ngl.js"></script>` as the stage object was not defined yet.

As an example, I would like to load https://github.com/arose/ngl/blob/master/examples/scripts/representation/label.js into my HTML page (very simple, following: http://nglviewer.org/ngl/api/manual/usage/embedding.html). And then add the function to view/hide the surface as a click function outside of the .js file (in the HTML file).

Thanks for your help!
Cheers,
Johanna

**Comment by fredludlow** [comment]
As you've found - the code in https://github.com/arose/ngl/blob/master/examples/scripts/representation/label.js
is intended to be run once the NGL stage has been created, so the simplest thing to do is to wrap that in a function and only call it once the page is ready (you can use the DOMContentLoaded event as shown in embedding.html).

There are many ways to do this but a very simple example (if you just want to setup a single page with a fixed set of components, representations and buttons) would be something like

Main html page
```
...
<script src="ngl.js"></script>  <!-- This is the built NGL thing from github/wherever -->
<script src="myCode.js"></script> <!-- Your own code in this file -->
...

<input type="button" id="licoriceBtn">Toggle Licorice</input>
<input type="button" id="surfaceBtn">Toggle Surface</input>
...
```

Then inside `myCode.js` have a "DOMContentLoaded" listener, load the components, representations and define some functions for your buttons:

```javascript

var reprs = {}

document.addEventListener("DOMContentLoaded", function () {
    var stage = new NGL.Stage("viewport");
    stage.loadFile("rcsb://1crn").then( function(c) {
       reprs.licorice = c.addRepresentation('licorice', {})
       reprs.surface = c.addRepresentation('surface', {})
       // Etc...
    })
});

document.getElementById('licoriceBtn').addEventListener('click', function() {
  reprs.licorice.setVisible(!reprs.licorice.getVisible())
})

document.getElementById('surfaceBtn').addEventListener('click', function() {
  reprs.surface.setVisible(!reprs.surface.getVisible())
```

When you find yourself repeating yourself a lot you can abstract out helper functions, or pickup a framework of your choice (react/vue/whatever) but for a minimal simple page something like the above would work fine.

**Comment by j0kaso** [comment]
Thanks for the really detailed answer - that helps!
