### ISSUE TITLE
Show selections from multiple structures and arrange them

### ISSUE THREAD

**Issue by gauravdiwan89** [arose/ngl#731]
I would like to

1) display selections from multiple structures, 

2) rotate them along their principal axis and 

3) arrange them equally spaced in the viewer along the x-axis with their centres in the same y-z plane.

Can someone please help me with this?

Here are some examples that I would like to display together: Chain A of PDB code 6CHG, Chain D of PDB code 3K8P and Chain A of PDB code 4GWM

**Comment by fredludlow** [comment]
This is a limitation of NGL (selections only apply to a single structure) - however, there's a bit of a hack you can do using concatenate:
http://nglviewer.org/ngl/?script=test/concat
(You can click through the example in the gallery to see the code in codepen:
http://nglviewer.org/ngl/gallery/index.html)

**Comment by gauravdiwan89** [comment]
I have a code example that sort of already does what I'm talking about. Here is the code:

```
// function to show the structure
function showStructure (stage, stageObj, chain, residues, color, pos_arr) {
  console.log(chain)
  const selection = new NGL.Selection(':' + chain + ' and ' + residues)
  const struc = stageObj.structure.getView(selection)
  const pa = struc.getPrincipalAxes()
  const comp = stage.addComponentFromObject(struc)
  
  comp.addRepresentation( "cartoon", {
        sele: ":"+ chain + ' and ' + residues,
        color: color
  })
  comp.addRepresentation( "axes", {
        sele: ":"+ chain + ' and ' + residues,
        showBox: true
  })
  comp.setRotation(pa.getRotationQuaternion())
  
  // translate by x angstrom along chosen axis
  comp.setPosition(pos_arr)
};

function loadStructure (pdb_id, chain, residues, color, xOffset) {
  const url = "rcsb://"+pdb_id+".pdb"
  stage.loadFile(url).then(stageObj => {
    this.showStructure(stage, stageObj, chain, residues, color, xOffset)
    stage.autoView();
  });
};

this.loadStructure("6CHG","A","1-350","red",[0,0,0])
this.loadStructure("3K8P","D","1-650","blue",[-200,0,0])
this.loadStructure("4GWM","A","1-100","green",[-400,0,0])

```

However, if you run this code, you can see that there are 3 structures. However they are not along a single straight line even though the y and z offsets are set to 0. 

Is it possible to align the centres of these selections?
