### ISSUE TITLE
Reversing b-factor color-scale

### ISSUE THREAD

**Issue by ryin222** [arose/ngl#743]
Hi Alex! I was wondering if there is a way I can reverse the color-scale of color by b-factor?

The reason I asked this is that I was trying to get a b-factor color scale showing the lowest temperature as blue, and highest as red. It seems that currently, the NGL's color by the b-factor function generates a color scale reverse of that(i.e. lowest temperature in red and highest in blue). 

I have attache two pictures of 5yy5 color by b-factor, one with NGL one with another viewer (e.g. PyMol)
![Screen Shot 2020-05-05 at 11 16 42 PM](https://user-images.githubusercontent.com/57362463/81135563-b667b300-8f26-11ea-877e-a35584476ba7.png)
![Screen Shot 2020-05-05 at 11 15 58 PM](https://user-images.githubusercontent.com/57362463/81135566-b798e000-8f26-11ea-9a71-ee102bc64044.png)

Thank you!

**Comment by arose** [comment]
there is a `colorReverse` option

**Comment by ryin222** [comment]
Thank you, Alex!!! That solves my problem :D 
I hope you have a great one!

**Comment by arose** [comment]
You're welcome. Be sure to also check out NGL's successor project Mol* (https://molstar.org).

**Comment by ryin222** [comment]
Will do! Thank you guy so much for developing such wonderful programs! It's very impressive!
