### ISSUE TITLE
selection language, ligands by name, mostly works, fails with 2VO in pdb 4our

### ISSUE THREAD

**Issue by paul-shannon** [arose/ngl#744]
@arose, As always, I am grateful for all the capabilities of ngl.js.

Working with pdb 4our (arabidopis phytochrome) I am trying to learn relevant parts of ngl's selection language.  My goal is to toggle display on and off as I explore the structure.  To do this, I experiment in the javascript console with a loaded model.

The following commands work fine from the javascript console.  I picked the ligand names out of the tooltips where they appear in [brackets], seen when I mouse over a structure of interest, for instance 

```
atom:[GOL]701:B.03 (4our)
```

The random colorScheme and spacefill representation make it  easy to see when the selection works:

```
s = stage.getComponentsByName("4our")
s.addRepresentation("spacefill", {sele: "GOL", colorScheme: "random"})
s.addRepresentation("spacefill", {sele: "PGE", colorScheme: "random"})
s.addRepresentation("spacefill", {sele: "SO4", colorScheme: "random"})
```
but this fails:
```
s.addRepresentation("spacefill", {sele: "2VO", colorScheme: "random"})
```
Though the function call (addRepresentation) returns a non-null value.

Any suggestions?

**Comment by ppillot** [comment]
You should use brackets for residues name `[2V0]` (mandatory when the include digits)
I would also advise you to use the NGL web application to test your selection strings interactively.

**Comment by paul-shannon** [comment]
@ppillot, Thank you!   This works perfectly.
