### ISSUE TITLE
Question about automatically collapsing filter selection in html

### ISSUE THREAD

**Issue by noeliaferruz** [arose/ngl#745]
Hi,
I am rendering on a web a protein and a ligand, with the residues around the ligand as well. 
This is the code to select the residues around the ligand:

```
var selection = new NGL.Selection( "not protein and not water");
var radius = 4;
var atomSet = obj[1].structure.getAtomSetWithinSelection( selection, radius );
 // expand selection to complete groups
var atomSet2 = obj[1].structure.getAtomSetWithinGroup( atomSet );
var residues2 = obj[1].addRepresentation("licorice",{
sele: atomSet2.toSeleString(),
})
```
The selection looks too large in the web though. The users can of course collapse it by hand, but I was wondering if there's a way to automatically collapse it upon loading? Something like, collapse=True (this didn't work)?

Thanks

**Comment by fredludlow** [comment]
Do you mean go from a list of atom IDs to something like ":A and 1-4 or 7 or 10". I don't know of a way to do this at the moment but it would certainly be a nice addition. I guess you could fairly easily create a naive implementation (walk through models, chains, residues, atoms and build a big nested and/or statement). For a more thorough job, a quick google suggests the relevant term might be [rewriting](https://en.wikipedia.org/wiki/Rewriting) but it's not an area I have any knowledge of...

**Comment by noeliaferruz** [comment]
Hey thank you, eventually found a workaround!

**Comment by gph82** [comment]
a bit late to the party, but, what was the workaround? I have the same question...

**Comment by noeliaferruz** [comment]
HI Guillermo!

I actually don't remember. Shortly after I translated the project to mol*.

**Comment by gph82** [comment]
We're on our way of doing that also, but for the moment it's easier to build on existing nfg scripts.
Thanks for the quick reply!


Sent from my Galaxy



-------- Original message --------
