### ISSUE TITLE
Camera rig: why is camera always on -Z?

### ISSUE THREAD

**Issue by garyo** [arose/ngl#747]
I'm working on exporting some NGL scenes, and the way NGL handles the camera is a bit unusual. I wonder why it's done that way.
According to `src/controls/viewer-controls.ts`, the camera is always on the -Z axis, and zooming moves it in and out (so it's really dolly). Rotating the camera is actually done by rotating the scene the other way, using `rotationGroup`, and similarly for translation. 
Is there a reason to constrain the camera to -Z rather than orbiting it around the objects in the more usual way?

**Comment by arose** [comment]
> Is there a reason to constrain the camera to -Z rather than orbiting it around the objects in the more usual way?

Not really except that I found the math easier at the time... Changing it to the more usual way would help making use of other cameras, e.g. for VR.

**Comment by garyo** [comment]
OK, thanks!
