### ISSUE TITLE
Possible to display subsequence only?

### ISSUE THREAD

**Issue by jessevig** [arose/ngl#749]
First of all, thank you for this wonderful tool!

Can you tell me if it might be possible to display a subsection of a protein/chain within a residue index range, e.g. from residue 10 through 50?

Thanks very much in advance!

**Comment by ppillot** [comment]
You can make a selection string such as `:A and 10-30` to select residues from 10 to 30 on chain A

**Comment by jessevig** [comment]
Works perfectly, thanks!
