### ISSUE TITLE
NGL as a local volume/structure viewer?

### ISSUE THREAD

**Issue by pconesa** [arose/ngl#751]
Hi @arose , is it possible, I guess so, to have http://nglviewer.org/ngl/ as a local viewer for local volumes/structures? 

I mean this: http://nglviewer.org/ngl/, maybe without examples and being able to preload it...probably based on url param?

I'm not asking you to implement it, just to help us do it. Give us some pointers?

Thanks once more, it's good to see how it grows. 

By the way, we have 2 resources using NGL : 
http://3dbionotes.cnb.csic.es/webserver
http://scipion.cnb.csic.es/m/services/

**Comment by arose** [comment]
Hi @pconesa,

what is running at http://nglviewer.org/ngl/ is just https://github.com/arose/ngl/blob/master/examples/webapp.html. If you look at the html you will find some pointers to 'examples' and loading files or 'scripts' (the examples are all scripts).

Also, have you seen our new project molstar.org? If you start something new you might want to consider using that :)

**Comment by pconesa** [comment]
Hi @arose , thanks, I'll check molstar....is there something equivalent to webapp.html

**Comment by arose** [comment]
> is there something equivalent to webapp.html

the viewer app has something, you can find it build in the published package, e.g. on https://unpkg.com/browse/molstar@0.7.1-dev.11/build/viewer/

**Comment by pconesa** [comment]
Thanks, I think I've got the pointers. Many thanks!
