### ISSUE TITLE
Add new mesh from convexhull

### ISSUE THREAD

**Issue by tubiana** [arose/ngl#754]
Hi :-) 

I would like to add a new shape based on a convexhull calculation, but I am a bit confused with the example from the api documentation: 
```
shape.addMesh(
    [ 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1 ],
    [ 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0 ],
    undefined, undefined, "My mesh"
);
```
What I have from my hull object is this: the index of each points forming the vertices (I can have the coordinates easilly.  They do not seems to fully ordored, example : 
```
array([[  8,  39,  16],
       [  8,  39, 499],
       [323, 625, 324],
       [939, 940,  16],
       [939, 940, 936],
       [939,  39,  16],
       [939,  39, 936],
       ......
 ```
Is there any transformation to do or can still create this mesh with my data structure? I tried to find more example or other documentation but I didn't found anything :/

Note that I use nglviewer, but since my question is on the mesh's coordonate system I prefer to ask it here.

Thank you for your help :)

**Comment by tubiana** [comment]
Ok I managed to get the hull!

with this code:
```
hull = ConvexHull(positions)

                mesh = []
                for triangles in hull.simplices:
                    vertices = []
                    for vertex in triangles:
                        vertices.extend(positions[vertex])
                    mesh.append(vertices)
                mesh = np.asarray(mesh).flatten().tolist()
                color = [[0, 0, 1]] * len(mesh)  # RGB, for now let's fix it to blue
                color = np.asarray(color).flatten().tolist()
                shape = self.displayMol.shape
                # shape.add_mesh(mesh,color)

                shape.add_mesh(
                    mesh,
                    color,
                )
```

But When I add some transparency, it seems that the normals are not always good... Any advices ?
![screenshot (1)](https://user-images.githubusercontent.com/8037224/82832515-9d19ad00-9ebb-11ea-8f5f-dd46dda64c85.png)

I must assume that I have to calculate the normals, I tried, but when I specify the normals, it doesn't work. Do I have to specify the ìndex` as well? and if so, what should be the length of each vector?

Thank you so much :)

**Comment by arose** [comment]
This looks like an issue with overlapping transparency, try rendering with `side: 'front'`

**Comment by tubiana** [comment]
Thank you for your answer :) 

But unfortunately, it's worst with `side:'front'`...
![screenshot (2)](https://user-images.githubusercontent.com/8037224/82840918-951a3700-9ed4-11ea-91d1-3056ddde0090.png)

**Comment by arose** [comment]
> But unfortunately, it's worst with side:'front'

It looks worse but it shows that the triangle winding order is no homogeneous. It should be CCW (counter clockwise). If you adjust you mesh to be CCW it will look better.

**Comment by tubiana** [comment]
Ok thank you for the tip, I will check that :-)
