### ISSUE TITLE
Selections for negative residue numbers don't work

### ISSUE THREAD

**Issue by josemduarte** [arose/ngl#77]
Some residue numbers can be negative and the selections don't work for those.

See for instance 1hek (the n-terminal tail of chain A has a few negative residue numbers). Selecting `-5:A` results in a wrongly selected residue

**Comment by arose** [comment]
done f946abef871a58249fb9cd18c7037fab9f4d4263

"-5:A" for resno -5 in chain A

"-12--8" for residues with resno -12 to -8

"-12-0" for residues with resno -12 to 0
