### ISSUE TITLE
Undocumented overwritePreferences parameter for Stage

### ISSUE THREAD

**Issue by hermanbergwerf** [arose/ngl#84]
I found that this property blocked me from applying different settings to a new Stage in the constructor. Adding `overwritePreferences: true` to the input `params` solved this problem. See: https://github.com/arose/ngl/blob/aa88b3846addd0d1aea757ba350f7e45a5a8b4df/js/ngl/stage.js#L20.

I could not find this parameter in the documentation at http://arose.github.io/ngl/doc/#API_reference/Core/Stage. What is this parameter used for? (it doesn't seem very useful).

**Comment by arose** [comment]
It is missing from the docs. I will be switch to jsdoc based API docs #85.

A `stage` has a preferences object that stores user preferences in localStorage. It is probably a good idea have `overwritePreferences: true` as the default. It seemed to me a good idea prefer user preferences by default.

**Comment by arose** [comment]
I removed whole preferences stuff from `Stage` and moved it to the GUI code, `overwritePreferences: true` is no longer necessary, see #119.
