### ISSUE TITLE
Add NGL.Stage.loadData method

### ISSUE THREAD

**Issue by hermanbergwerf** [arose/ngl#86]
Currently you can only load data via `.loadFile`. It would be useful if you can load a data String using a method such as `.loadData`.

**Comment by hermanbergwerf** [comment]
Wait, I just found you can pass a `Blob` to `path` in `.loadFile`. Perhaps it would be nice to have a more explicit method for that. Sorry.

**Comment by arose** [comment]
> Wait, I just found you can pass a Blob to path in .loadFile. Perhaps it would be nice to have a more explicit method for that.

Maybe, I don't want to clutter the API with so many methods. A `Blob` is very similar to a `File` I would say.

**Comment by hainm** [comment]
I agree that loadFile is sufficient. API should be simple and easy to remember.

**Comment by arose** [comment]
my plan is to document how to load string data

**Comment by arose** [comment]
added examples to new api docs 3c7ecad1522979458bf459495aa7ea6d2704c4ce
