### ISSUE TITLE
Clipping surfaces to pocket

### ISSUE THREAD

**Issue by fredludlow** [arose/ngl#87]
Firstly - this is a fantastic project, many thanks to @arose for releasing it!

And now the feature request :) I was wondering if it would be possible to clip surfaces to particular residues of a protein like the attached image? i.e. - calculate the surface as though for the whole protein but only display parts that are within e.g. 8A of a ligand:

![clipped_surface](https://cloud.githubusercontent.com/assets/900535/14820269/d1902a9a-0bbd-11e6-84b5-c55a72fe688b.png)

The above is from AstexViewer and requires you to specify both the full molecule you're generating surface for and the subset of atoms you actually want it displayed on.

**Comment by arose** [comment]
Thanks @fredludlow!

Distance-based selections are currently not available, see #91. Definitely on the todo list!

**Comment by fredludlow** [comment]
Great! Is it possible at the moment to display the surface for a specific selection (e.g. "1-10") but not show the bits corresponding to intramolecular contacts - i.e. get a fragment of the "overall" surface?

**Comment by arose** [comment]
> get a fragment of the "overall" surface?

Yes, with the `filterSele` parameter:

```JavaScript
stage.loadFile( "rcsb://3pqr.pdb" ).then( function( o ){
    o.addRepresentation( "cartoon", { sele: "*" } );
    o.addRepresentation( "surface", { sele: "*", filterSele: ":A" } );
    o.centerView();
} );
```

![screenshot 98](https://cloud.githubusercontent.com/assets/272250/14890684/76c9fa12-0d18-11e6-89ba-e8ed2291c9c4.png)

**Comment by fredludlow** [comment]
Ahh, I'd missed the filterSele parameter - nice... I'll close this for now as #76 and #91 cover the other part of the question. Thanks again!
