### ISSUE TITLE
exportImage

### ISSUE THREAD

**Issue by hainm** [arose/ngl#94]
Hi,

I tried to call "exportImage" from Python (NGLView) but nothing happens. Any idea why?

```python
args = ['4x', True, False, False, True]
view._remote_call('exportImage',
                  target='Stage',
                  args=args)
```

Note: below works

```python
args = ['dark',]

view._remote_call('setTheme',
                  target='Stage',
                  args=args)
```

**Comment by arose** [comment]
try with 

```Python
args = [4, True, False, False, True]
```

the first argument has to be an integer, not a string

**Comment by hainm** [comment]
thanks. works for me.

But if using `4`, my computer is freezing. Need to reduce to `2`. 

Any improvement with NGL-dev? or any tip?

**Comment by hainm** [comment]
PS: it's damn fast in http://arose.github.io/ngl/

**Comment by arose** [comment]
Yeah, there was a bug fixed a while ago. Will update nglview next week.

**Comment by hainm** [comment]
Cool. I will add export_image or nglview too. The rendered image look nice.
