### ISSUE TITLE
loadFile from disk?

### ISSUE THREAD

**Issue by hainm** [arose/ngl#95]
is there any way to loadFile from disk with absolute path?

Currently I have only two options

- Use data in the same path
```python
stage.loadFile('./test.pdb')
```

- make Blob

**Comment by arose** [comment]
The browser does not have direct access to the file system for security reasons. It has to go either through a web server or be initiated by the user selecting a file through a file open dialog. Note that there are workarounds for development using command line flags when starting the browser, but these disable said security features.

**Comment by hainm** [comment]
ok I see. So just let nglview users to use relative path. For text file, could use Blob

```python
blob = open('test.txt').read()
view._remote_call("loadFile", target='Stage', 
       args=["type": "blob", 'data': blob])
