### ISSUE TITLE
exportImage: add option to specify filename

### ISSUE THREAD

**Issue by hainm** [arose/ngl#98]
currently the downloaded image's name is 'screenshot.png'. If I do the screenshot several times, Chrome adds 'screenshot(2).png' . So I need to rename it.

**Comment by arose** [comment]
I refactored the image generation (5ca95ef6577da48a2b9aa40c968eb6e37e4f068a) and `stage.makeImage` now returns a `Blob` via a Promise. So you can trigger download with whatever name you like. You can also send the Blob-bytes to the Python kernel in nglview.

```JavaScript
stage.makeImage( {
    factor: 1,
    antialias: true,
    trim: false,
    transparent: false
} ).then( function( blob ){
    NGL.download( blob, "screenshot.png" );
} );
```

**Comment by hainm** [comment]
that's perfect. Can't wait to have new NGL in NGLView.
